<?php $form = $this->form;?>

    <div class="animatedParent">
            <div class="row">
                
                <div class="col-lg-3"></div>
                <div class="col-xs-12 col-md-4 col-sm-12 col-lg-6">
                    <div class="blue-line sm normal"></div>
                    <div class="signup-box">
                    <?php if($this->errorMessage) { ?>
                    <div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px !important;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?php  echo $this->errorMessage;   ?>                                               
                    </div>
                    <?php } ?>
                    <?php if ($this->messages): ?>
                    <br clear="all">
                    <div class="alert alert-success alert-dismissable">
                    <?php foreach ($this->messages as $message): ?>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
                    <?php endforeach ?>
                    </div>
                    <?php endif ?>
                        <div class="logo"><img src="/img/sterlite-logo.png" alt="" style="width: 195px; height: 28px;"></div>
                        <p class="text-center" style="font-size: 12px;">"Empowering Humanity by Addressing the toughest challenges of Energy Delivery"</p>
                        <h4 class="text-center"> Forgot your password?</h4>
                        <p class="text-center">Not to worry. To reset your password, enter the email address you use to login.</p>
                        <form action="/index/forgotpassword" method="post" >
                            
                            <div class="form-group">
                                 <i class="fa fa-user" aria-hidden="true"></i>
                                <?php echo $form->email;?>
                               <div class="forgot"><a href="/admin">Login</a></div>
                            </div>
                            <div class="text-right mar-bot"><button type="submit" class="btn btn-success">Reset Password</button></div>
                        </form>
                    </div>
                    
                    <div class="blue-line lg normal"></div>
                </div>
                 <div class="col-lg-3"></div>
            </div>
        </div>