<?php
    $params = $this->params;
    $getUserRecord = $this->getUserRecord;
?>
<div class="right-aside view-port-height">
<!-- Content Header (Page header) -->
        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i>  My Profile</h4>
                </div>
              
            </div>
        </div>

        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <div class="alert_data">
                <?php echo $message ?>.
                </div>
                <?php endforeach ?>
                </div>
            <?php endif ?>
            <div class="row">
                <div class="col-12">
               
                   <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                                   <p style="float: left; margin: 0px;">My Profile</p> <a href="/index/edit-profile"  style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">Edit Profile</a>
                                    </div>
                                <div class="card-block ">
                                    
                                    <div class="row m-t-10">
                                        <div class="col-lg-12">
                                            <table class="profile2_userprofile">
                                                <tbody>
                                                <tr>
                                                    <td>Name </td>
                                                    <td>: <?php echo $getUserRecord['name'];?></td>
                                                </tr>
                                                <tr>
                                                    <td>Email </td>
                                                    <td>: <?php echo $getUserRecord['email_id'];?></td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                </div>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>