<script type="text/javascript">
    function validateUser(){ 
            if(document.getElementById("newPassword").value==""){
            alert("Please Enter New Password.");
            document.getElementById("newPassword").focus();
            return false;
            }

            if(document.getElementById("confirmPassword").value==""){
            alert("Please Enter Confirm Password.");
            document.getElementById("confirmPassword").focus();
            return false;
            }

            if(document.getElementById("newPassword").value!=document.getElementById("confirmPassword").value){
            alert("Password do not match, please enter valid password");
            document.getElementById("confirmPassword").focus();
            return false;
            }

            if(document.getElementById("confirmotp").value==""){
            alert("Enter OTP");
            document.getElementById("confirmotp").focus();
            return false;
            }
    }         
</script>
    <div class="animatedParent">
            <div class="row">
                
                <div class="col-lg-3"></div>
                <div class="col-xs-12 col-md-4 col-sm-12 col-lg-6">
                    
                    <div class="blue-line sm normal"></div>
                    
                    <div class="signup-box">
                    <?php if($this->errorMessage) { ?>
                    <div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px !important;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?php  echo $this->errorMessage;   ?>                                               
                    </div>
                    <?php } ?>
                    <?php if ($this->messages): ?>
                    <br clear="all">
                    <div class="alert alert-success alert-dismissable">
                    <?php foreach ($this->messages as $message): ?>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
                    <?php endforeach ?>
                    </div>
                    <?php endif ?>
                        <div class="logo"><img src="/img/sterlite-logo.png" alt="" style="width: 195px; height: 28px;"></div>
                        <p class="text-center" style="font-size: 12px;">"Empowering Humanity by Addressing the toughest challenges of Energy Delivery"</p>
                        <h4 class="text-center"> Reset your password</h4>
                         <form name="resetPassword" method="post" onsubmit="return validateUser();"  action="/index/reset-password"  >
                            <input type="hidden" name="token" value="<?php echo $this->params['token']?>"> 
                             <div class="form-group">
                                    <i class="sli-power icons" aria-hidden="true"></i>
                                        <input type="password" value="" class="form-control" name="newPassword" id="newPassword" placeholder="New Password">
                                    
                                </div>   

                                <div class="form-group">
                                    <i class="sli-power icons" aria-hidden="true"></i>
                                        <input type="password" value="" class="form-control" name="confirmPassword" id="confirmPassword" placeholder="Confirm Password">
                                    
                                </div>

                                <div class="form-group">
                                    <i class="sli-power icons" aria-hidden="true"></i>
                                        <input type="text" value="" class="form-control" name="confirmotp" id="confirmotp" placeholder="Enter OTP">
                                </div> 
                            <div class="text-right mar-bot"><button type="submit" class="btn btn-success">Update</button></div>
                        </form>
                    </div>
                    
                    <div class="blue-line lg normal"></div>
                </div>
                 <div class="col-lg-3"></div>
            </div>
        </div>