<style>
	.fa {
		font-size: 20px;
	}
</style>
<link rel="stylesheet" href="/assets/css/select2.min.css">
<link rel="stylesheet" href="/assets/css/jquery.datetimepicker.min.css">
<script src="/assets/js/select2.min.js"></script>
<script src="/assets/js/jquery.datetimepicker.full.min.js"></script>

<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>User Attendance
					<div class="pull-right">
						<a href="javascript:void(0)" data-target="#markAttendanceModal" data-toggle="modal" class="btn btn-success">Mark Attendance</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="user-list">
						<table class="display" width="100%" id="userListTable">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Start Date</th>
									<th>End Date</th>
								</tr>
							</thead>
							<tbody>
								<?php if($this->userAttendance){ 
									$i = 1;
									foreach($this->userAttendance as $user) { ?>
										<tr>
											<td><?php echo $i;?>.</td>
											<td><?php echo ucwords(strtolower($user['name'])); ?></td>
											<td><?php echo $user['start_date'] ? date('d/m/Y H:i:s', strtotime($user['start_date'])):"-"; ?></td>
											<td><?php echo $user['end_date'] ? date('d/m/Y H:i:s', strtotime($user['end_date'])):"-"; ?></td>
										</tr>
										<?php  $i++; } } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Bootstrap Modal: User Profile Details -->
			<div class="modal fade" id="markAttendanceModal">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3 class="modal-title">Mark Attendance</h3>
						</div>
						<div class="modal-body">
							<form id="attendanceForm">
								<div class="row">
									<div class="table-responsive">
										<table class="table table-condensed">
											<thead>
												<tr>
													<th>Employee Name</th>
													<th>Start Time</th>
													<th>End Time</th>
												</tr>
											</thead>
											<tbody id="user_list">
												<?php if ($this->userList): ?>
													<tr>
														<td>
															<select class="form-control select2" name="employee_id[]" id="employee_id" style="width: 100%;">
																<?php foreach ($this->userList as $user): ?>
																	<option value="<?php echo $user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
																<?php endforeach ?>
															</select>
														</td>
														<td>
															<input type="text" class="form-control datetimepicker" name="start_time[]" id="start_time">
														</td>
														<td>
															<input type="text" class="form-control datetimepicker" name="end_time[]" id="end_time">
														</td>
													</tr>
												<?php endif ?>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="3">
														<input type="button" class="btn btn-success" value="Add Row" onclick="addRow()">
													</td>
												</tr>
											</tfoot>
										</table>
									</div>
								</div>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
								<button type="button" class="btn btn-primary" id="saveAttendance">Save</button>
							</div>
						</form>
					</div>
				</div>
			</div>

			<script>
				$(document).ready(function() {
					$('.datetimepicker').datetimepicker({
						format: 'd/m/Y H:i'
					});
					$("#userListTable").DataTable();
					$(".select2").select2();
					$("#saveAttendance").click(function(e) {
						e.preventDefault();
						$("#loading-bg").show();
						$.ajax({
							url: '/backend/mark-attendance',
							type: 'POST',
							data: $('#attendanceForm').serialize(),
							success:function(data){
								$("#loading-bg").hide();
								var data = JSON.parse(data);
								console.log(data);
								if (data.flag) {
									swal({
										title : data.title,
										text  : data.message,
										icon  : "success"
									}).then(function(){
										window.location.reload();
									});
								} else {
									swal({
										title : data.title,
										text  : data.message,
										icon  : "error"
									});
									return false;
								}
							}
						});
						
					});
				});
				function addRow() {
					var newRow = `<tr>
					<td>
					<select class="form-control select2" name="employee_id[]" id="employee_id" style="width: 100%;">
					<?php foreach ($this->userList as $user): ?>
						<option value="<?php echo $user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
					<?php endforeach ?>
					</select>
					</td>
					<td>
					<input type="text" class="form-control datetimepicker" name="start_time[]" id="start_time">
					</td>
					<td>
					<input type="text" class="form-control datetimepicker" name="end_time[]" id="end_time">
					</td>
					</tr>`;
					$('#user_list').append(newRow);
					$('.select2').select2();
					$('.datetimepicker').datetimepicker({
						format: 'd/m/Y H:i'
					});
				}
			</script>