<form action="/invoice/generated-invoice-view" method="POST" role="form" enctype="multipart/form-data" onsubmit="return validateInputData()">
	<div class="row">
		<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
		</div>
	</div>
	<br clear="all">
	<div class="row">
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="state_id">State For<span id="mandatory">*</span> :</label>
			<select class="form-control select2" name="state_id" id="state_id" onchange="getClientMasterList()">
				<option value="">Select State</option>
				<?php foreach ($this->stateList as $state): ?>
					<option value="<?php echo $state['id']; ?>"><?php echo $state['state_name']; ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="client_id">Client Name<span id="mandatory">*</span> :</label>
			<select class="form-control select2" name="client_id" id="client_id" onchange="getClientDetails()">
				<option value="">Select Client</option>
			</select>
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="invoice_date">Invoice Date<span id="mandatory">*</span> :</label>
			<input type="text" class="form-control datepicker" name="invoice_date" id="invoice_date" placeholder="Select Invoice Date" readonly="" value="<?php echo date('d/m/Y'); ?>">
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="invoice_number">Invoice Number<span id="mandatory">*</span> :</label>
			<input type="text" class="form-control" name="invoice_number" id="invoice_number" placeholder="Enter Invoice Number">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="po_number">PO Number :</label>
			<select class="form-control select2" name="po_number" id="po_number" onchange="getSitesByPoNumber()">
				<option value="">Select PO Number</option>
				<?php foreach ($this->poNumber as $po): ?>
					<option value="<?php echo $po['po_number']; ?>"><?php echo $po['po_number']; ?></option>
				<?php endforeach ?>
			</select>
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="site_id">Site ID :</label>
			<select class="form-control select2" name="site_id" id="site_id">
				<option value="">Select Site ID</option>
			</select>
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="infratel_id">Infratel ID :</label>
			<input type="text" class="form-control" name="infratel_id" id="infratel_id" readonly="">
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
			<label for="so_number">SO Number :</label>
			<input type="text" class="form-control" name="so_number" id="so_number" readonly="">
		</div>
	</div>
	<div class="row">
		<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<label for="">Tax is payble under reverse charge (Yes/No) : </label>
			<input type="radio" name="reverseChargeTax" id="radioTure" value="Yes"> <b>Yes</b> &nbsp;
			<input type="radio" name="reverseChargeTax" id="radioFalse" value="No"> <b>No</b>
		</div>
		<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<label for="">Is IGST Applicable (Yes/No) : </label>
			<input type="radio" name="isIgst" id="radioTure" value="Yes"> <b>Yes</b> &nbsp;
			<input type="radio" name="isIgst" id="radioFalse" value="No"> <b>No</b>
		</div>
	</div>
	<br>
	<h3 align="center"><u>Billing And Shipping Details</u></h3>
	<br>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<table class="table-bordered" width="100%">
				<thead>
					<tr>
						<th colspan="2" width="50%" style="text-align: center;">Bill To Party</th>
						<th colspan="2"  width="50%" style="text-align: center;">Ship To Party</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td colspan="2"  width="50%" style="padding: 10px 10px 10px 10px;">
							<label for="bill_client_id">Client Name<span id="mandatory">*</span> :</label>
							<span id="bill_client_name"></span>
						</td>
						<td id="ship_client_id_td" colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
							<label for="ship_client_id">Client Name<span id="mandatory">*</span> :</label>
							<span id="ship_client_name"></span>
						</td>
					</tr>
					<tr>
						<td colspan="2" width="50%"style="padding: 10px 10px 10px 10px;">
							<label for="">Address :</label>
							<span id="client_address_bill" ></span>
						</td>
						<td colspan="2" width="50%"style="padding: 10px 10px 10px 10px;">
							<label for="">Address :</label>
							<span  id="client_address_ship"></span>
						</td>
					</tr>
					<tr>
						<td colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
							<label for="">GSTIN :</label>
							<span id="client_gst_bill" ></span>
						</td>
						<td colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
							<label for="">GSTIN :</label>
							<span id="client_gst_ship" ></span>
						</td>
					</tr>
					<tr>
						<td style="padding: 10px 10px 10px 10px;">
							<label for="">State : </label>
							<span id="client_state_name_bill"></span>
						</td>
						<td style="padding: 10px 10px 10px 10px;">
							<label for="">State Code : </label>
							<span id="client_state_code_bill"></span>
						</td>
						<td style="padding: 10px 10px 10px 10px;">
							<label for="">State : </label>
							<span id="client_state_name_ship"></span>
						</td>
						<td style="padding: 10px 10px 10px 10px;">
							<label for="">State Code : </label>
							<span id="client_state_code_ship"></span>
						</td>
					</tr>
				</tbody>
			</table>
		</div>	
	</div>
	<br clear="all">
	<div class="row" id="productsServicesDiv" style="overflow: auto; padding: 8px 15px;">
		<table class="table table-bordered" id="productsServicesTable">
			<thead>
				<tr>
					<th style="text-align: center;">Name of Product/Service</th>
					<th style="text-align: center;">HSN/SAC Code</th>
					<th style="text-align: center;">UOM</th>
					<th style="text-align: center;">Rate</th>
					<th style="text-align: center;">Quantity</th>
					<th style="text-align: center;">Taxable Value</th>
					<th style="text-align: center;">Action</th>
				</tr>
			</thead>
			<tbody>
				<tr id="row_2">
					<td width="25%">
						<select name="service_product_id[]" id="service_product_id_2" class="form-control mandatorySelect select2" onchange="getServiceProductDetails(2)">
							<option value="">Please Select</option>
							<?php foreach ($this->serviceProductList as $serviceProducts): ?>
								<option value="<?php echo $serviceProducts['id']; ?>"><?php echo $serviceProducts['name_of_service']; ?></option>
							<?php endforeach ?>
						</select>
					</td>
					<td>
						<input type="text" name="hsn_sac_code[]" id="hsn_sac_code_2" class="form-control" readonly="">
					</td>
					<td>
						<input type="text" class="form-control" name="unit_of_measurement[]" id="unit_of_measurement_2" readonly="">
					</td>
					<td>
						<input type="text" class="form-control" name="rate[]" id="rate_2" readonly="">
					</td>
					<td>
						<input type="text" class="form-control" name="quantity[]" id="quantity_2" onkeyup="getTaxableValue(2)">
					</td>
					<td>
						<input type="text" class="form-control" name="taxable_value[]" id="taxable_value_2" readonly>
					</td>
					<td></td>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Product/Service</button>
			</div>
		</div>
	</div>
	<br clear="all">
	<div class="row">
		<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<button type="submit" class="btn btn-primary pull-right">Generate Invoice</button>
		</div>
	</div>
</form>