<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	
	<script src="https://use.fontawesome.com/e2d16502eb.js"></script>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	<style>
		#page-wrap { width: 297mm; height:210mm; margin: 0 auto; }
		td {
			font-size:12px;
		}
		@media all {
			.page-break	{ display: none; }
		}
		@media print {
			.page-break	{ display: block; page-break-before: always; }
		}
		body{
			font-family: 'Droid Sans', sans-serif;
		}
	</style>
	<link href="https://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet"> 
</head>
<body>
	<div id="page-wrap" >
		<table width="100%" style="border:1px solid;" cellspacing="0" cellpadding="0">
			<tr>
				<td style="border-bottom:1px solid; padding-left: 5px;" valign="top">
					<b>Vendor Name and Address :</b> LOGIMETRIX TECHSOLUTIONS PVT. LTD., 3/204, II Floor, Vikas Khand, Gomti Nagar, Lucknow(UP) - 226010	
				</td>
			</tr>
			<tr>
				<td style="border-bottom:1px solid; padding-left: 5px;" valign="top">
					<b>GST NO. :</b> 09AACCL3704H1ZO 
				</td>
			</tr>
			<tr>
				<td style="border-bottom:1px solid; padding-left: 5px;" valign="top">
					<b>PAN NO. :</b> AACCL3704H <span class="pull-right" style="padding-right: 5px;"><i>Original for Recipient</i></span>	
				</td>
			</tr>
			<tr>
				<td style="border-bottom:1px solid; padding-left: 5px; text-align: center;" valign="top">
					<span style="font-size: 15px;"><b>Tax Invoice</b></span>
				</td>
			</tr>
			<tr>
				<td valign="top">
					<table width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td width="50%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Invoice No :</b> &nbsp; <?php echo $this->params['invoiceNumber']; ?></span>
							</td>
							<td width="25%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>PO No :</b> &nbsp; <?php echo $this->params['po_number']; ?></span>
							</td>
							<td width="25%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>PO Date :</b> &nbsp; <?php echo $this->params['poDate']; ?></span>
							</td>
						</tr>
						<tr>
							<td style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Invoice Date :</b> &nbsp; <?php echo $this->params['invoice_date']; ?></span>
							</td>
							<td style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<?php if (isset($this->params['infratel_id'])): ?>
									<span><b>Infratel ID :</b> &nbsp; <?php echo $this->params['infratel_id']; ?></span>
								<?php endif ?>
							</td>
							<td style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<?php if (isset($this->params['so_number'])): ?>
									<span><b>SO No :</b> &nbsp; <?php echo $this->params['so_number']; ?></span>
								<?php endif ?>
							</td>
						</tr>
						<tr>
							<td style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Tax is payble under reverse charge (YES/NO) :</b> &nbsp; <?php echo $this->params['reverseChargeTax']; ?></span>
							</td>
							<td style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Site ID :</b> &nbsp; <?php echo $this->params['site_id']; ?></span>
							</td>
							<td style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>Work Completion Date :</b> &nbsp; <?php echo $this->params['work_completion_date']; ?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			
			<tr>
				<td width="100%">
					<table width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td width="25%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<p><b>State :</b> &nbsp; <?php echo $this->params['stateName']; ?></p>
							</td>
							<td width="25%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<p><b>State Code :</b> &nbsp; <?php echo $this->params['stateCode'] >= '10' ? $this->params['stateCode']:"0".$this->params['stateCode']; ?></p>
							</td>
							<td width="50%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<p><b>Place of Supply/Services :</b> &nbsp; <?php echo $this->params['stateName']; ?></p>
							</td>
						</tr>
					</table>
				</td>
			</tr>

			<tr>
				<td width="100%">
					<table width="100%" cellspacing="0" cellpadding="0">
						<tr>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid; text-align: center;" valign="top">
								<b>Bill to Party</b>
							</td>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px; text-align: center;" valign="top">
								<b>Ship to Party</b>
							</td>
						</tr>
						<tr>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Name :</b> &nbsp; <?php echo $this->params['bill_client_name']; ?></span>
							</td>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>Name :</b> &nbsp; <?php echo $this->params['ship_client_name']; ?></span>
							</td>
						</tr>
						<tr>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Address :</b> &nbsp; <?php echo $this->params['client_address_bill']; ?></span>
							</td>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>Address :</b> &nbsp; <?php echo $this->params['client_address_ship']; ?></span>
							</td>
						</tr>
						<tr>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>Customer GSTIN :</b> &nbsp; <?php echo $this->params['client_gst_bill']; ?></span>
							</td>
							<td colspan="2" width="50%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>Customer GSTIN :</b> &nbsp; <?php echo $this->params['client_gst_ship']; ?></span>
							</td>
						</tr>
						<tr>
							<td width="31%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>State :</b> &nbsp; <?php echo $this->params['client_state_name_bill']; ?></span>
							</td>
							<td width="19%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>State Code :</b> &nbsp; <?php echo $this->params['client_state_code_bill']; ?></span>
							</td>
							<td width="31%" style="border-bottom:1px solid; padding-left: 5px; border-right: 1px solid;" valign="top">
								<span><b>State :</b> &nbsp; <?php echo $this->params['client_state_name_ship']; ?></span>
							</td>
							<td width="19%" style="border-bottom:1px solid; padding-left: 5px;" valign="top">
								<span><b>State Code :</b> &nbsp; <?php echo $this->params['client_state_code_ship']; ?></span>
							</td>
						</tr>
					</table>
				</td>
			</tr>

			<tr>
				<td width="100%">
					<table cellspacing="0" cellpadding="0" width="100%">
						<tr>
							<td rowspan="2" width="4%" style="border-right:1px solid; height:20px; text-align:center;">
								Sr. No.
							</td>
							<td rowspan="2" width="20%" style="border-right:1px solid; text-align:center;">
								Name of Product/Service
							</td>
							<td rowspan="2" width="7%" style="border-right:1px solid; text-align:center;">
								HSN/SAC Code
							</td>
							<td rowspan="2" width="8%" style="border-right:1px solid; text-align:center;">
								UOM
							</td>
							<td rowspan="2" width="5%" style="border-right:1px solid; text-align:center;">
								Qty
							</td>
							<td rowspan="2" width="6%" style="border-right:1px solid; text-align:center;">
								Rate
							</td>
							<td rowspan="2" width="7%" style="border-right:1px solid; text-align:center;">
								Taxable Value
							</td>
							<td colspan="2" width="11%" style="border-right:1px solid; text-align:center;">
								IGST
							</td>
							<td colspan="2" width="11%" style="border-right:1px solid; text-align:center;">
								CGST
							</td>
							<td colspan="2" width="11%" style="border-right:1px solid; text-align:center;">
								SGST
							</td>
							<td rowspan="2" width="10%" style="text-align:center; height:20px;">
								Total
							</td>
						</tr>

						<tr>
							<td width="5%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Rate</td>
							<td width="6%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Amount</td>
							<td width="5%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Rate</td>
							<td width="6%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Amount</td>
							<td width="5%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Rate</td>
							<td width="6%" style="border-top: 1px solid; border-right:1px solid; text-align:center;">Amount</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td width="100%">
					<table cellspacing="0" cellpadding="0" width="100%">
						<?php 
						$i = 0;
						foreach ($this->params['productDetails'] as $productServiceDetails): ?>
							<tr>
								<td style="border-top:1px solid; border-right:1px solid; height:30px; text-align:center;" width="4%"><?php echo $i+1; ?>
							</td>
							<td width="20%" style="border-top:1px solid; border-right:1px solid; text-align:left; height:30px; padding-left: 5px; padding-right: 5px; white-space: normal;"><?php echo $productServiceDetails['serviceName']; ?>
						</td>
						<td width="7%" style="border-top:1px solid; border-right:1px solid; text-align:center;"><?php echo $this->params['hsn_sac_code'][$i]; ?>
					</td>
					<td width="8%" style="border-top:1px solid; border-right:1px solid; text-align:center;">
						<?php echo $this->params['unit_of_measurement'][$i]; ?> 
					</td>
					<td width="5%" style="border-top:1px solid; border-right:1px solid; text-align:center;">
						<?php echo $this->params['quantity'][$i]; ?> 
					</td>
					<td width="6%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
						<?php echo $this->params['rate'][$i]; ?>
					</td>
					<td width="7%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
						<b><?php echo $this->params['taxable_value'][$i]; ?></b>
					</td>
					<td width="5%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
						<?php if (isset($productServiceDetails['igstRate'])) { echo $productServiceDetails['igstRate'].'%';
					} else { echo '0'; } ; ?>
				</td>
				<td width="6%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
					<?php if (isset($productServiceDetails['igstAmount'])) { echo $productServiceDetails['igstAmount'];
				} else { echo '0'; } ; ?>
			</td>
			<td width="5%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
				<?php if (isset($productServiceDetails['cgstRate'])) { echo $productServiceDetails['cgstRate'].'%';
			} else { echo '0'; } ; ?>
		</td>
		<td width="6%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
			<?php if (isset($productServiceDetails['cgstAmount'])) { echo $productServiceDetails['cgstAmount'];
		} else { echo '0'; } ; ?>
	</td>
	<td width="5%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
		<?php if (isset($productServiceDetails['sgstRate'])) { echo $productServiceDetails['sgstRate'].'%';
	} else { echo '0'; } ; ?>
</td>
<td width="6%" style="border-top:1px solid; text-align:center; border-right:1px solid;">
	<?php if (isset($productServiceDetails['sgstAmount'])) { echo $productServiceDetails['sgstAmount'];
} else { echo '0'; } ; ?>
</td>
<td width="10%" style="border-top:1px solid; text-align:center;">
	<b><?php echo $productServiceDetails['total']; ?></b>
</td>
</tr>
<?php $i++;
endforeach ?>


<tr>
	<td colspan="6" style="border-top:1px solid; border-right:1px solid; text-align:center;"><b>Total</b>
	</td>
	<td style="border-top:1px solid; border-right:1px solid; text-align:center;">
		<b><?php echo $this->params['total_taxable_value']; ?></b>
	</td>
	<td style="border-top:1px solid; border-right:1px solid; text-align:center;">
	</td>
	<td style="border-top:1px solid; border-right:1px solid; text-align:center;">
		<?php echo $this->params['total_igst']?$this->params['total_igst']:"0.00"; ?>
	</td>
	<td style="border-top:1px solid; border-right:1px solid; text-align:center;">
	</td>
	<td style="border-top:1px solid; text-align:center; border-right:1px solid;">
		<?php echo $this->params['total_cgst']?$this->params['total_cgst']:"0.00"; ?>
	</td>
	<td style="border-top:1px solid; text-align:center; border-right:1px solid;">
	</td>
	<td style="border-top:1px solid; text-align:center; border-right:1px solid;">
		<?php echo $this->params['total_sgst']?$this->params['total_sgst']:"0.00"; ?>
	</td>
	<td style="border-top:1px solid; text-align:center;">
		<b><?php echo $this->params['total_invoice_amount']; ?></b>
	</td>
</tr>
</table>
</td>
</tr>

<tr>
	<td width="100%">
		<table cellspacing="0" cellpadding="0" width="100%">
			<tr>
				<td rowspan="2" style="border-top:1px solid; border-right: 1px solid; padding: 5px; text-align: center;" width="57%">Total Invoice Amount in words :
				</td>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;" width="33%">Total Amount before Tax</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;" width="10%">
					<?php echo $this->params['total_taxable_value']; ?>
				</td>

			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;">
					Add : CGST @ <?php echo $this->params['productDetails'][0]['cgstRate'].'%'; ?>
				</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;">
					<?php echo $this->params['total_cgst']; ?>
				</td>
			</tr>
			<tr>
				<td rowspan="4" style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; padding: 5px; text-align: center;">
					<strong>INR <?php echo ucwords(strtolower($this->params['total_invoice_amount_in_words'])); ?> Only</strong>
				</td>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;">
					Add : SGST @ <?php echo $this->params['productDetails'][0]['sgstRate'].'%'; ?>
				</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;">
					<?php echo $this->params['total_sgst']; ?>
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;">
					Add : IGST @ <?php echo $this->params['productDetails'][0]['igstRate'].'%'; ?>
				</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;">
					<?php echo $this->params['total_igst']; ?>
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;">Total Tax Amount
				</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;">
					<?php echo $this->params['total_tax_amount']; ?>
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; margin-right: 3px; text-align:left;">
					Total Amount after Tax
				</td>
				<td style="border-top:1px solid; padding-left: 5px; margin-right: 3px; text-align:center;">
					<?php echo $this->params['total_invoice_amount']; ?>
				</td>
			</tr>
		</table>
	</td>
</tr>

<tr>
	<td width="100%">
		<table cellspacing="0" cellpadding="0" width="100%">
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right:1px solid; text-align:left;" width="50%">Bank Details : <b> </b>
				</td>
				<td rowspan="4" style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; text-align:left;" width="7%">

				</td>
				<td style="border-top:1px solid; padding-left: 5px; border-right: 1px solid; text-align:left;" width="33%">
					GST on Reverse Charge
				</td>
				<td style="border-top:1px solid; padding-left: 5px; text-align:center;" width="10%">0
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right:1px solid; text-align:left;" width="50%">Bank A/C : <b> </b>
				</td>
				<td colspan="2" style="border-top:1px solid; padding-left: 5px; text-align:left;" width="35%" >
					Certified that the particulars given abouve are true and correct
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right:1px solid; text-align:left;" width="50%">Bank IFSC : <b> </b>
				</td>
				<td colspan="2" rowspan="2" style="border-top: 1px solid; text-align: center;" width="50%">
					For Company Name
					<br />
					<br />
					<br />
					<br />
					Authorised Signatory
				</td>
			</tr>
			<tr>
				<td style="border-top:1px solid; padding-left: 5px; border-right:1px solid; text-align:left;" width="50%">
					Terms & conditions
					<br>
					1. Payments through DD/At Par Cheque only & payble at ............
					<br />
					2. Payments as per contract/agreement.
					<br />
					3. Disputes, if any, subject to .............. jurisdiction only.
				</td>


			</tr>
		</table>
	</td>
</tr>
			<!-- <tr>
				<td width="100%">
					<table cellspacing="0" cellpadding="0" width="100%">
						<tr>
							<td style="border-top:1px solid; border-right:1px solid;  height:70px; padding-left:10px;" width="50%">Declaration : 
								<br />
								<br />
								We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.
							</td>
							<td width="50%" style="border-top:1px solid; text-align:right; height:70px; padding:10px 10px 10px 10px;">
								<b>for </b>
								<br />
								<br />
								<br />
								<br />
								Authorised Signatory
							</td>
						</tr>
					</table> 
				</td>
			</tr> -->
		</table>

	</div>
</body>
</html>
