<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 16px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
	.hidden {
		display: none;
	}
</style>
<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params['error'])): ?>
			<?php if ($this->params['error']) { ?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Invoice Generation Form</h3>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<!-- <a href="/invoice/invoice-report" class="btn btn-success pull-right">View Generated Invoices</a> -->
					</div>
				</div>
			</div>
			<div class="panel panel-body">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
					<form action="/invoice/generated-invoice-view" method="POST" role="form" enctype="multipart/form-data" onsubmit="return validateInputData()">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
							</div>
						</div>
						<br clear="all">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="state_id">State For<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="state_id" id="state_id" onchange="getClientMasterList()">
									<option value="">Select State</option>
									<?php foreach ($this->stateList as $state): ?>
										<option value="<?php echo $state['id']; ?>"><?php echo $state['state_name']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="client_id">Client Name<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="client_id" id="client_id" onchange="getClientDetails()">
									<option value="">Select Client</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_number">PO Number<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="po_number" id="po_number" onchange="getSitesByPoNumber()">
									<option value="">Select PO Number</option>
									
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="site_id">Site ID<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="site_id" id="site_id">
									<option value="">Select Site ID</option>
								</select>
							</div>
						</div>

						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="invoice_date">Invoice Date<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control datepicker" name="invoice_date" id="invoice_date" placeholder="Select Invoice Date" readonly="" value="<?php echo date('d/m/Y'); ?>">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="">Tax is payble under reverse charge :</label>
								<select class="form-control select2" name="reverseChargeTax" id="reverseChargeTax">
									<option value="">Please Select</option>
									<option value="Yes">Yes</option>
									<option value="No">No</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="">Is IGST applicable<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="isIgstApplicable" id="isIgstApplicable">
									<option value="">Please Select</option>
									<option value="Yes">Yes</option>
									<option value="No">No</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="work_completion_date">Work Completion Date<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control datepicker" name="work_completion_date" id="work_completion_date" placeholder="Work Completion Date" readonly="" value="<?php echo date('d/m/Y'); ?>">
							</div>
							<!-- <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="invoice_number">Invoice Number<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="invoice_number" id="invoice_number" placeholder="Enter Invoice Number">
							</div> -->
							<!-- <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="infratel_id">Infratel ID :</label>
								<input type="text" class="form-control" name="infratel_id" id="infratel_id" readonly="">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="so_number">SO Number :</label>
								<input type="text" class="form-control" name="so_number" id="so_number" readonly="">
							</div> -->
						</div>
						<div class="row">
							
						</div>
						<br>
						<h3 align="center"><u>Billing And Shipping Details</u></h3>
						<br>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<table class="table-bordered" width="100%">
									<thead>
										<tr>
											<th colspan="2" width="50%" style="text-align: center;">Bill To Party</th>
											<th colspan="2"  width="50%" style="text-align: center;">Ship To Party</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="2"  width="50%" style="padding: 10px 10px 10px 10px;">
												<label for="bill_client_id">Client Name<span id="mandatory">*</span> :</label>
												<span id="bill_client_name"></span>
												<input type="hidden" name="bill_client_name">
											</td>
											<td id="ship_client_id_td" colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
												<label for="ship_client_id">Client Name<span id="mandatory">*</span> :</label>
												<span id="ship_client_name"></span>
												<input type="hidden" name="ship_client_name">
											</td>
										</tr>
										<tr>
											<td colspan="2" width="50%"style="padding: 10px 10px 10px 10px;">
												<label for="">Address :</label>
												<span id="client_address_bill" ></span>
												<input type="hidden" name="client_address_bill">
											</td>
											<td colspan="2" width="50%"style="padding: 10px 10px 10px 10px;">
												<label for="">Address :</label>
												<span id="client_address_ship"></span>
												<input type="hidden" name="client_address_ship">
											</td>
										</tr>
										<tr>
											<td colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
												<label for="">GSTIN :</label>
												<span id="client_gst_bill" ></span>
												<input type="hidden" name="client_gst_bill">
											</td>
											<td colspan="2" width="50%" style="padding: 10px 10px 10px 10px;">
												<label for="">GSTIN :</label>
												<span id="client_gst_ship" ></span>
												<input type="hidden" name="client_gst_ship">
											</td>
										</tr>
										<tr>
											<td style="padding: 10px 10px 10px 10px;">
												<label for="">State : </label>
												<span id="client_state_name_bill"></span>
												<input type="hidden" name="client_state_name_bill">
											</td>
											<td style="padding: 10px 10px 10px 10px;">
												<label for="">State Code : </label>
												<span id="client_state_code_bill"></span>
												<input type="hidden" name="client_state_code_bill">
											</td>
											<td style="padding: 10px 10px 10px 10px;">
												<label for="">State : </label>
												<span id="client_state_name_ship"></span>
												<input type="hidden" name="client_state_name_ship">
											</td>
											<td style="padding: 10px 10px 10px 10px;">
												<label for="">State Code : </label>
												<span id="client_state_code_ship"></span>
												<input type="hidden" name="client_state_code_ship">
											</td>
										</tr>
									</tbody>
								</table>
							</div>	
						</div>
						<br clear="all">
						<div class="row" id="productsServicesDiv" style="overflow: auto; padding: 8px 15px;">
							<table class="table table-bordered" id="productsServicesTable">
								<thead>
									<tr>
										<th style="text-align: center;">Name of Product/Service</th>
										<th style="text-align: center;">HSN/SAC Code</th>
										<th style="text-align: center;">UOM</th>
										<th style="text-align: center;">Rate</th>
										<th style="text-align: center;">Quantity</th>
										<th style="text-align: center;">Taxable Value</th>
										<th style="text-align: center;">Action</th>
									</tr>
								</thead>
								<tbody>
									<tr id="row_2">
										<td width="25%">
											<select name="service_product_id[]" id="service_product_id_2" class="form-control mandatorySelect select2" onchange="getServiceProductDetails(2)">
												<option value="">Please Select</option>
												<?php foreach ($this->serviceProductList as $serviceProducts): ?>
													<option value="<?php echo $serviceProducts['id']; ?>"><?php echo $serviceProducts['name_of_service']; ?></option>
												<?php endforeach ?>
											</select>
										</td>
										<td>
											<input type="text" name="hsn_sac_code[]" id="hsn_sac_code_2" class="form-control">
										</td>
										<td>
											<input type="text" class="form-control" name="unit_of_measurement[]" id="unit_of_measurement_2" readonly="">
										</td>
										<td>
											<input type="text" class="form-control" name="rate[]" id="rate_2" onkeyup="clearQuantity(2)">
										</td>
										<td>
											<input type="text" class="form-control" name="quantity[]" id="quantity_2" onkeyup="getTaxableValue(2)">
										</td>
										<td>
											<input type="text" class="form-control" name="taxable_value[]" id="taxable_value_2" readonly>
										</td>
										<td></td>
									</tr>
								</tbody>
							</table>
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Product/Service</button>
								</div>
							</div>
						</div>
						<br clear="all">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<button type="submit" class="btn btn-primary pull-right">Generate Invoice</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
	});
	function clearQuantity(count) {
		$("#quantity_"+count).val('');
		$("#taxable_value_"+count).val('');
	}
	function getClientMasterList() {
		var state_id = $("#state_id").val();
		if (state_id == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/master/get-client-details',
				type: 'POST',
				data: {state_id: state_id},
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						$.each(data.clientDetails, function(index, val) {
							$("#client_id").append('<option value="'+val.id+'">'+val.client_name+'</option>');	
						});
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						$("#client_id").empty();	
						$("#client_id").append('<option value="">Select Client</option>');	
					}
				}
			});

		}
	}
	function getSitesByPoNumber() {
		var po_number = $("#po_number").val();
		if (po_number != "") {
			$("#loading-bg").show();
			$("#site_id").empty();
			$.ajax({
				url: '/siteallocation/get-allocated-sites-by-po-number',
				type: 'POST',
				data: {po_number: po_number},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					if (data.flag) {
						$("#site_id").html(data.allocated_sites);
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : 'error'
						});
					}
				}
			});
		} else {
			$("#site_id").html("<option>Select Site ID</option>");
		}
	}
	function getClientDetails() {
		var client_id = $("#client_id").val();
		if (client_id == "") {
			swal({
				title : "Client Missing!",
				text  : "Please select client name.",
				icon  : "error"
			}).then(function(){
				$("#client_id").select2('open');
			});
			// $("#shipAndBillDuplicateCheckbox").attr('checked', false);
			$("#bill_client_name").text('');
			$("input[name='bill_client_name']").val('');
			$("#client_address_ship").text('');
			$("input[name='client_address_ship']").val('');
			$("#client_gst_ship").text('');
			$("input[name='client_gst_ship']").val('');
			$("#client_state_name_ship").text('');
			$("input[name='client_state_name_ship']").val('');
			$("#client_state_code_ship").text('');
			$("input[name='client_state_code_ship']").val('');
			$("#ship_client_name").text('');
			$("input[name='ship_client_name']").val('');
			$("#client_address_bill").text('');
			$("input[name='client_address_bill']").val('');
			$("#client_gst_bill").text('');
			$("input[name='client_gst_bill']").val('');
			$("#client_state_name_bill").text('');
			$("input[name='client_state_name_bill']").val('');
			$("#client_state_code_bill").text('');
			$("input[name='client_state_code_bill']").val('');
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/master/get-client-details',
				type: 'POST',
				data: {client_id: client_id},
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						if (data.clientDetails.state_code < 10) {
							data.clientDetails.state_code = '0'+data.clientDetails.state_code;
						}
						$("#bill_client_name").text(data.clientDetails.client_name);
						$("input[name='bill_client_name']").val(data.clientDetails.client_name);
						$("#ship_client_name").text(data.clientDetails.client_name);
						$("input[name='ship_client_name']").val(data.clientDetails.client_name);
						$("#client_address_bill").text(data.clientDetails.client_billing_address);
						$("input[name='client_address_bill']").val(data.clientDetails.client_billing_address);
						$("#client_address_ship").text(data.clientDetails.client_shipping_address);
						$("input[name='client_address_ship']").val(data.clientDetails.client_shipping_address);
						$("#client_gst_bill").text(data.clientDetails.client_gst);
						$("input[name='client_gst_bill']").val(data.clientDetails.client_gst);
						$("#client_gst_ship").text(data.clientDetails.client_gst);
						$("input[name='client_gst_ship']").val(data.clientDetails.client_gst);
						$("#client_state_name_bill").text(data.clientDetails.state_name);
						$("input[name='client_state_name_bill']").val(data.clientDetails.state_name);
						$("#client_state_name_ship").text(data.clientDetails.state_name);
						$("input[name='client_state_name_ship']").val(data.clientDetails.state_name);
						$("#client_state_code_bill").text(data.clientDetails.state_code);
						$("input[name='client_state_code_bill']").val(data.clientDetails.state_code);
						$("#client_state_code_ship").text(data.clientDetails.state_code);
						$("input[name='client_state_code_ship']").val(data.clientDetails.state_code);
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
					}
				}
			});
		}
		var state_id = $("#state_id").val();
		var client_id = $("#client_id").val();
		if (state_id == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
			return false;
		} else if (client_id == "") {
			swal({
				title : "Client Missing!",
				text  : "Please select client name.",
				icon  : "error"
			}).then(function(){
				$("#client_id").select2('open');
			});
			return false;
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/manage-po-site/get-po-list-by-state-and-client',
				type: 'POST',
				data: {state_id: state_id, client_id: client_id},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					if (data.flag) {
						$("#po_number").empty();
						$("#po_number").append("<option value=''>Select PO Number</option>");
						$("#po_number").append(data.poList);
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						return false;
					}
				}
			});
		}
	}
	function duplicateDataToShipping() {
		if($("#shipAndBillDuplicateCheckbox").prop("checked") == true) {
			var bill_client_id 			= $("#bill_client_id").val();
			$("#ship_client_id").val(bill_client_id).trigger('change');
		} else {
			$("#ship_client_id").val('').trigger('change');
			$("#client_address_ship").text('');
			$("#client_gst_ship").text('');
			$("#client_state_name_ship").text('');
			$("#client_state_code_ship").text('');
		}
	}
	function addMoreRow() {
		var length = $("#productsServicesTable tr").length;
		var row_count = parseInt(length) + 1;
		var row_html = `<tr id="row_`+row_count+`">
		<td width="25%">
		<select name="service_product_id[]" id="service_product_id_`+row_count+`" class="form-control mandatorySelect select2" onchange="getServiceProductDetails(`+row_count+`)">
		<option value="">Please Select</option>
		<?php foreach ($this->serviceProductList as $serviceProducts): ?>
			<option value="<?php echo $serviceProducts['id']; ?>"><?php echo $serviceProducts['name_of_service']; ?></option>
		<?php endforeach ?>
		</select>
		</td>
		<td>
		<input type="text" name="hsn_sac_code[]" id="hsn_sac_code_`+row_count+`" class="form-control">
		</td>
		<td>
		<input type="text" class="form-control" name="unit_of_measurement[]" id="unit_of_measurement_`+row_count+`" readonly="">
		</td>
		<td>
		<input type="text" class="form-control" name="rate[]" id="rate_`+row_count+`" onkeyup="clearQuantity(`+row_count+`)">
		</td>
		<td>
		<input type="text" class="form-control" name="quantity[]" id="quantity_`+row_count+`" onkeyup="getTaxableValue(`+row_count+`)">
		</td>
		<td>
		<input type="text" class="form-control" name="taxable_value[]" id="taxable_value_`+row_count+`" readonly >
		</td>
		<td><a href="javascript:void(0)" title="Delete Row" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color: red;"></i></a></td>
		</tr>`;
		$("#productsServicesTable").append(row_html);
		$(".select2").select2();
	}
	function deleteRow(count) {
		$("#row_"+count).remove();
	}
	function getServiceProductDetails(count) {
		var service_id = $("#service_product_id_"+count).val();
		if (service_id == "") {
			swal({
				title : "Service/Product Missing!",
				text  : "Please select service/product.",
				icon  : "error"
			}).then(function(){
				$("#service_product_id_"+count).select2('open');
			});
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/invoice/get-service-product-details',
				type: 'POST',
				data: {service_product_id: service_id},
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						$("#hsn_sac_code_"+count).val(data.serviceProduceDetail.hsn_sac_code);
						$("#unit_of_measurement_"+count).val(data.serviceProduceDetail.unit_of_measurement);
						if (data.serviceProduceDetail.service_rate > 0) {
							$("#rate_"+count).val(data.serviceProduceDetail.service_rate);
							
						} else {
							$("#rate_"+count).attr('readonly',false);
						}
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
					}
				}
			});

		}
	}
	function getTaxableValue(count) {
		var rate = $("#rate_"+count).val();
		var quantity = $("#quantity_"+count).val();
		if (quantity == "") {
			$("#taxable_value_"+count).val('');
		} else {
			var taxableValue = parseFloat(rate) * parseFloat(quantity);
			$("#taxable_value_"+count).val(taxableValue.toFixed(2));
		}
	}
</script>
