
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Monthly Invoice Report
					<div class="pull-right">
						<a  href="javascript:void(0)" style="float: right;"  id="leave-details" data-toggle="modal" data-target="#con-close-modal" class="btn btn-success" onclick="addMontlyInvoice();" title="add Invoice">Add Monthly Invoice</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="row">
						<form action="/invoice/monthly-invoice" method="post">
							<div class="col-md-2">
								<select class="form-control" name="month" id="month">
								    <option value="">Select Month</option>
									<option value="01" <?php echo $this->month == "01"?"selected":""; ?>>January</option>
									<option value="02" <?php echo $this->month == "02"?"selected":""; ?>>February</option>
									<option value="03" <?php echo $this->month == "03"?"selected":""; ?>>March</option>
									<option value="04" <?php echo $this->month == "04"?"selected":""; ?>>April</option>
									<option value="05" <?php echo $this->month == "05"?"selected":""; ?>>May</option>
									<option value="06" <?php echo $this->month == "06"?"selected":""; ?>>June</option>
									<option value="07" <?php echo $this->month == "07"?"selected":""; ?>>July </option>
									<option value="08" <?php echo $this->month == "08"?"selected":""; ?>>August</option>
									<option value="09" <?php echo $this->month == "09"?"selected":""; ?>>September</option>
									<option value="10" <?php echo $this->month == "10"?"selected":""; ?>>October</option>
									<option value="11" <?php echo $this->month == "11"?"selected":""; ?>>November</option>
									<option value="12" <?php echo $this->month == "12"?"selected":""; ?>>December</option>
								</select>
							</div>
							<div class="col-md-2">
								<select class="form-control" name="year" id="year">
								    <option value="">Select Year</option>
									<?php $years = array_combine(range(date("Y"), 1910), range(date("Y"), 1910));
									
									foreach($years as $year) {  ?>
										<option value="<?php echo $year;?>" <?php echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>
									<?php } ?>
								</select>
							</div>
							<div class="col-md-5">
								<button type="submit" class="btn btn-primary">Show</button>
							</div>
						</form>
					</div>
					<br clear="all">
					<div class="table-responsive" id="state-list">
						<table class="display" width="100%" id="systemListTable">
							<thead>
								<th>#</th>
								<th>State</th>
								<th>Client</th>
								<th>Po Value</th>
								<th>Month</th>
								<th>Year</th>
								<th>Invoice amount </th>
								<th>LTS Invoice amount </th>
								<th>LTS Invoice Percent </th>
								<th>Vendor Data </th>
								<th>Profit </th>
								<th>Total Expense</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php if($this->monthly_report){
									$i = 1;
									foreach ($this->monthly_report as $data) { ?>
										<tr>
											<td> <?php echo $i; ?></td>
											<td><?php echo $data['state_name']; ?></td>
											<td><?php echo $data['client_name']; ?></td>
											<td><?php echo $data['po_amount']; ?></td>
											<td><?php echo date("F", mktime(0, 0, 0,$data['month'], 10));?></td>
											<td><?php echo $data['year']; ?></td>
											<td><?php echo $data['invoice_value']; ?></td>
											<td><?php echo $data['lts_invoice_amount']; ?></td>
											<td><?php echo $data['lts_invoice_percent']; ?></td>
											<td><?php
											foreach ($data['vendor_details'] as $key => $value) {?>
												<table class="display">
													<tr>
														<td><?php echo $value['vendor_name']?></td>
														<td>Rs.<?php echo $value['vendor_amount']?></td>
													</tr>
												</table>
											<?php }
											?></td>
											<td><?php echo $data['profit']; ?></td>
											<td><?php echo $data['total']; ?></td>
											<td>
												<a href="javascript:void(0)" onclick="viewVendors('<?php echo $data['id'];?>')" title="View Vendors"><span class="fa fa-eye"></span>
												</a>
												<a href="javascript:void(0)" onclick="deleteInvoice('<?php echo $data['id'];?>')" title="Delete System"><span class="fa fa-trash" style="color: red;"></span>
													
												</td>

											</tr>
											<?php $i++; } } ?>
										</tbody>
										<tfoot>
											<tr>
												<td></td>
												<td></td>
												<td></td>
												<td class="bagde"><?php echo  $this->total_amount['po_amount'];?></td>
												<td></td>
												<td></td>
												<td><?php echo  $this->total_amount['lts_invoice_amount'];?></td>
												<td><?php echo  $this->total_amount['Invoice_amount'];?></td>

											</tr>
										</tfoot>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="custom-width-modalLabel" aria-hidden="true" style="display: none;">
					<div class="modal-dialog" style="max-height:85%;  margin-top: 50px; margin-bottom:50px; width: 90%">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
								<h3 class="modal-title" id="custom-width-modalLabel">Add Montly Invoice</h3>
							</div>
							<div class="modal-body">

							</div>

						</div><!-- /.modal-content -->
					</div><!-- /.modal-dialog -->
				</div>
				<!-- View System Assets Modal : Start -->
				<div class="modal fade" id="viewSystemAssetsModal"></div>


				<script type="text/javascript">
					$(document).ready(function() {
						$("#systemListTable").DataTable();
					});
					function addMontlyInvoice(){
						$.ajax({
							url: "/invoice/add-monthly-invoice",
							context: document.body,
							success: function(responseText) {
								$(".modal-body").html(responseText);
								$(".modal-body").find("script").each(function(i) {
								});
							}
						});
					}

					function deleteInvoice(id) {
						swal({
							title : "Are you sure?",
							text  : "Do you want to delete clicked Invoice ?",
							icon  : "warning",
							buttons : [true, "Yes,Delete "],
							dangerMode : true
						}).then(function(isConfirm){
							if (!isConfirm) {
								return false;
							} else {
								$.ajax({
									url: '/invoice/delete-invoice',
									type: 'POST',
									data:{id:id},
									success:function(data){
										var data = JSON.parse(data);
										console.log(data);
										if (data.flag) {
											swal({
												title : data.title,
												text  : data.message,
												icon  : "success",
											}).then(function(){
												location.reload("/invoice/monthly-invoice");
											});
										} else {
											swal({
												title : "Failed !",
												text  : data.message,
												icon  : "error"
											});           
										}
									}
								});

							}
						});
					}

					function viewVendors(id){
						$.ajax({
							url: "/invoice/view-monthly-invoice/id/"+id,
							context: document.body,
							success: function(responseText) {
								$("#viewSystemAssetsModal").html(responseText);
								$("#viewSystemAssetsModal").modal('toggle');
							}
						});
					}

				</script>