<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
  .mandatory{
    color: red;
    font-size: 20px;
  }
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Services/Products List
          <div class="pull-right">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#addServiceModal" class="btn btn-success">Add Service/Product</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="service-list">
            <table class="display" width="100%" id="serviceListTable">
             <thead>
              <th>#</th>
              <th style="white-space: nowrap;">State Name</th>
              <th style="white-space: nowrap;">Client Name</th>
              <th style="white-space: nowrap;">Service/Product Name</th>
              <th>HSN/SAC Code</th>
              <th>UOM</th>
              <th>GST Slab</th>
              <th>IGST</th>
              <th>CGST</th>
              <th>SGST</th>
              <th>Service Rate</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->invoiceServiceList){
                $i = 1;
                foreach ($this->invoiceServiceList as $service) { ?>
                 <tr id="row_<?php echo $i;?>">
                  <td><?php echo $i; ?></td>
                  <td style="white-space: nowrap;"><?php echo $service['state_name']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $service['client_name']; ?></td>
                  <td><?php echo $service['name_of_service']; ?></td>
                  <td><?php echo $service['hsn_sac_code']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $service['unit_of_measurement']; ?></td>
                  <td><?php echo $service['gst_slab']; ?></td>
                  <td><?php echo $service['igst_percentage']; ?></td>
                  <td><?php echo $service['cgst_percentage']; ?></td>
                  <td><?php echo $service['sgst_percentage']; ?></td>
                  <td><?php echo $service['service_rate'] ? $service['service_rate']:"-"; ?></td>
                  <td><?php echo $service['is_active']?"Active":"Deactive"; ?></td>
                  <td style="white-space: nowrap;">
                    <?php if ($service['is_active'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="editRowData(<?php echo $service['id']; ?>, <?php echo $i;?>)" title="Edit Data"><span class="fa fa-pencil fa-2x" style="color: green;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteServiceProduct(<?php echo $service['id']; ?>,'deactivate')" title="Deactivate Service/Product"><span class="fa fa-ban fa-2x" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Service/Product" onclick="deactivateActivateDeleteServiceProduct(<?php echo $service['id']; ?>,'activate')"><span class="fa fa-sign-in fa-2x" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteServiceProduct(<?php echo $service['id']; ?>,'delete')" title="Delete Service/Product"><span class="fa fa-trash fa-2x" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Transporter Modal : START -->
  <div class="modal fade" id="addServiceModal">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Service/Product</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form method="" role="form" id="addServiceProductForm">
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="state_id">State Name<span class="mandatory">*</span></label>
                <select class="form-control select2" name="state_id" id="state_id" style="width: 100%" onchange="getClientMasterList()">
                  <option value="">Select State</option>
                  <?php foreach ($this->stateList as $state): ?>
                    <option value="<?php echo $state['id']; ?>"><?php echo $state['state_name']; ?></option>
                  <?php endforeach ?>
                </select>
              </div> 
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="client_id">Client Name<span class="mandatory">*</span></label>
                <select class="form-control select2" name="client_id" id="client_id" style="width: 100%">
                  <option value="">Select Client</option>

                </select>
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="service_name">Name of Service/Product <span class="mandatory">*</span></label>
                <input type="text" class="form-control" name="service_name" id="service_name" placeholder="Name of Service/Product">
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="hsn_sac_code">HSN/SAC Code <span class="mandatory">*</span></label>
                <input type="text" class="form-control" name="hsn_sac_code" id="hsn_sac_code" placeholder="HSN/SAC Code" oninput="this.value = this.value.replace(/[^0-9]/g,'')">
              </div> 
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="unit_of_measurement">Unit of Measurement (UOM)<span class="mandatory">*</span></label>
                <input type="text" class="form-control" name="unit_of_measurement" id="unit_of_measurement" placeholder="Unit of Measurement">
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="gst_slab">GST Slab <span class="mandatory">*</span></label>
                <input type="text" class="form-control" name="gst_slab" id="gst_slab" placeholder="GST Slab">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="igst_percentage">IGST</label>
                <input type="text" class="form-control" name="igst_percentage" id="igst_percentage" placeholder="IGST">
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="cgst_percentage">CGST</label>
                <input type="text" class="form-control" name="cgst_percentage" id="cgst_percentage" placeholder="CGST">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="sgst_percentage">SGST</label>
                <input type="text" class="form-control" name="sgst_percentage" id="sgst_percentage" placeholder="SGST">
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="service_price">Rate/Price of Service</label>
                <input type="text" class="form-control" name="service_price" id="service_price" placeholder="Rate/Price of Service">
              </div>
              <div class="clearfix"></div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button class="btn btn-primary pull-right" id="saveServiceProduct">Submit</button>
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  <!-- Add Transporter Modal : END -->
  <script>
    $(document).ready(function() {
      $(".select2").select2();
      $("#serviceListTable").DataTable();
      $("#saveServiceProduct").click(function(event) {
        event.preventDefault();
        var state_id      = $("#state_id").val();
        var client_id     = $("#client_id").val();
        var service_name  = $("#service_name").val();
        var hsn_code      = $("#hsn_sac_code").val();
        var unit_of_measurement = $("#unit_of_measurement").val();
        var gst_slab = $("#gst_slab").val();
        if (state_id == "") {
          swal({
            title : "State Missing!",
            text  : "Please select state name.",
            icon  : "error"
          }).then(function(){
            $("#state_id").select2('open');
          });
          return false;
        } else if (client_id == "") {
         swal({
          title : "Client Missing!",
          text  : "Please select client name.",
          icon  : "error"
        }).then(function(){
          $("#client_id").select2('open');
        });
        return false;
      } else if (service_name == "") {
        swal({
          title : "Service/Product Missing!",
          text  : "Please enter service/product name.",
          icon  : "error"
        }).then(function(){
          $("#service_name").focus();
        });
        return false;
      } else if (hsn_code == "") {
        swal({
          title : "HSN/SAC Code Missing!",
          text  : "Please enter HSN/SAC code.",
          icon  : "error"
        }).then(function(){
          $("#hsn_sac_code").focus();
        });
        return false;
      } else if (unit_of_measurement == "") {
       swal({
        title : "UOM Missing!",
        text  : "Please enter unit of measurement.",
        icon  : "error"
      }).then(function(){
        $("#unit_of_measurement").focus();
      });
      return false;
    } else if (gst_slab == "") {
     swal({
      title : "GST Slab Missing!",
      text  : "Please enter GST slab.",
      icon  : "error"
    }).then(function(){
      $("#gst_slab").focus();
    });
    return false;
  } else {
    $("#addServiceModal").modal('toggle');
    $("#loading-bg").show();
    $.ajax({
      url: '/invoice/add-invoice-service-product',
      type: 'POST',
      data: $("#addServiceProductForm").serialize(),
      success:function(data){
        $("#loading-bg").hide();
        var data = JSON.parse(data);
        console.log(data);
        if (data.flag) {
          swal({
            title : data.title,
            text  : data.message,
            icon  : "success"
          }).then(function(){
            window.location.reload();
          });
        } else {
          swal({
            title : data.title,
            text  : data.message,
            icon  : "error"
          }).then(function(){
            $("#addServiceModal").modal('toggle');
          });
          return false;
        }
      }
    });
  }
});
    });
    function editRowData(service_id, row_id) {
      if (service_id == "") {

      } else {
        $("#loading-bg").show();
        $.ajax({
          url: '/invoice/get-invoice-service-product-details',
          type: 'POST',
          data: {service_id: service_id},
          success:function(data){
            var data = JSON.parse(data);
            $("#loading-bg").hide();
            console.log(data);
            if (data.flag) {
              var html_data = `<td>`+row_id+`</td>
              <td id="state_name_`+row_id+`">`+data.serviceDetails.state_name+`</td>
              <td id="client_name_`+row_id+`">`+data.serviceDetails.client_name+`</td>
              <td><input type="text" class="form-control" id="name_of_service_`+row_id+`" value="`+data.serviceDetails.name_of_service+`"/></td>
              <td><input type="text" class="form-control" id="hsn_sac_code_`+row_id+`" value="`+data.serviceDetails.hsn_sac_code+`" /></td>
              <td><input type="text" class="form-control" id="unit_of_measurement_`+row_id+`" value="`+data.serviceDetails.unit_of_measurement+`" /></td>
              <td><input type="text" class="form-control" id="gst_slab_`+row_id+`" value="`+data.serviceDetails.gst_slab+`" /></td>
              <td><input type="text" class="form-control" id="igst_percentage_`+row_id+`" value="`+data.serviceDetails.igst_percentage+`" /></td>
              <td><input type="text" class="form-control" id="cgst_percentage_`+row_id+`" value="`+data.serviceDetails.cgst_percentage+`" /></td>
              <td><input type="text" class="form-control" id="sgst_percentage_`+row_id+`" value="`+data.serviceDetails.sgst_percentage+`" /></td>
              <td><input type="text" class="form-control" id="service_rate_`+row_id+`" value="`+data.serviceDetails.service_rate+`" /></td>
              <td></td>
              <td> <a href="javascript:void(0)" onclick="updateRowData(`+data.serviceDetails.id+`,`+row_id+`)" title="Update Data"><span class="fa fa-refresh fa-2x" style="color: #1DAA29;"></span></a></td>`;
              $("#row_"+row_id).html(html_data);
              $('.select2').select2();
            } else {
              swal({
                title : data.titel,
                text  : data.message,
                icon  : "error"
              });
              return false;
            }
          }
        });
        
      }
    }
    function updateRowData(service_id, row_id) {
      var state = $("#state_name_"+row_id).text();
      var client= $("#client_name_"+row_id).text();
      var nos   = $("#name_of_service_"+row_id).val();
      var hsn   = $("#hsn_sac_code_"+row_id).val();
      var uom   = $("#unit_of_measurement_"+row_id).val();
      var gst   = $("#gst_slab_"+row_id).val();
      var igst  = $("#igst_percentage_"+row_id).val();
      var cgst  = $("#cgst_percentage_"+row_id).val();
      var sgst  = $("#sgst_percentage_"+row_id).val();
      var rate  = $("#service_rate_"+row_id).val();
      if (service_id == "") {

      } else {
        $("#loading-bg").show();
        $.ajax({
          url: '/invoice/update-invoice-product-service',
          type: 'POST',
          data: {nos:nos, hsn:hsn, uom:uom, gst:gst, igst:igst, cgst:cgst, sgst:sgst, rate:rate, service_id:service_id},
          success:function(data){
            var data = JSON.parse(data);
            $("#loading-bg").hide();
            console.log(data);
            if (data.flag) {
              swal({
                title : data.title,
                text  : data.message,
                icon  : 'success'
              }).then(function(){
                var html_data = `<td>`+row_id+`</td>
                <td>`+state+`</td>
                <td>`+client+`</td>
                <td>`+data.serviceDetails.nos+`</td>
                <td>`+data.serviceDetails.hsn+`</td>
                <td>`+data.serviceDetails.uom+`</td>
                <td>`+data.serviceDetails.gst+`</td>
                <td>`+data.serviceDetails.igst+`</td>
                <td>`+data.serviceDetails.cgst+`</td>
                <td>`+data.serviceDetails.sgst+`</td>
                <td>`+data.serviceDetails.rate+`</td>
                <td>Active</td>
                <td><a href="javascript:void(0)" onclick="editRowData(`+data.serviceDetails.service_id+`,`+row_id+`)" title="Edit Data"><span class="fa fa-pencil fa-2x" style="color: green;"></span></a>
                &nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="deactivateActivateDeleteServiceProduct(`+data.serviceDetails.service_id+`,'deactivate')" title="Deactivate Service/Product"><span class="fa fa-ban fa-2x" style="color: #D66F00;"></span></a>
                </td>`;
                $("#row_"+row_id).html(html_data);
              });
            } else {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "error"
              });
              return false;
            }
          }
        });

      }
    }
    function getClientMasterList() {
      var state_id = $("#state_id").val();
      if (state_id == "") {
        swal({
          title : "State Missing!",
          text  : "Please select state name.",
          icon  : "error"
        }).then(function(){
          $("#client_id").empty();
          $("#client_id").html('<option value="">Select Client</option>');
          $("#state_id").select2('open');
        });
      } else {
        $("#loading-bg").show();
        $.ajax({
          url: '/master/get-client-details',
          type: 'POST',
          data: {state_id: state_id},
          success:function(data){
            var data = JSON.parse(data);
            $("#loading-bg").hide();
            console.log(data);
            if (data.flag) {
              $.each(data.clientDetails, function(index, val) {
                $("#client_id").append('<option value="'+val.id+'">'+val.client_name+'</option>');  
              });
            } else {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "error"
              });
              $("#client_id").empty();  
              $("#client_id").append('<option value="">Select Client</option>');  
            }
          }
        });

      }
    }
    function deactivateActivateDeleteServiceProduct(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" clicked service/product?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $("#loading-bg").show();
          $.ajax({
            url  : '/invoice/activate-deactivate-delete-service',
            type : 'POST',
            data : {type:type, service_id:id},
            success:function(data){
              var data = JSON.parse(data);
              $("#loading-bg").hide();
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/invoice/service-product-for-invoice");
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });
        }
      });
    }
  </script>

