<style>
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 16px;
	}
	.error_box{
		border: 1px solid red;
		border-radius: 5px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
	.hidden {
		display: none;
	}
</style>
<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params['error'])): ?>
			<?php if ($this->params['error']) { ?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Add New PO</h3>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<!-- <a href="/invoice/invoice-report" class="btn btn-success pull-right">View Generated Invoices</a> -->
					</div>
				</div>
			</div>
			<div class="panel panel-body">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
					<form action="/manage-po-site/add-po-sites" method="POST" role="form" id="addPoAndSitesForm">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
							</div>
						</div>
						<br clear="all">
						<?php ?>
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po">PO<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="po" id="po" >
									<option value="">Select PO</option>
									<?php foreach ($this->po_list as $po): ?>
										<option value="<?php echo $po['po_no']; ?>"><?php echo $po['po_no']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<br>
						<h3 align="center"><u>Site Details</u></h3>
						<br>

						<div class="row" id="productsServicesDiv" style="overflow: auto; padding: 8px 15px;">
							<table class="table table-bordered" id="siteDetailsTable">
								<thead>
									<tr>
										<th style="text-align: center;">Site ID <span id="mandatory">*</span></th>
										<th style="text-align: center;">Site Name</th>
										<th style="text-align: center;">SO Number</th>
										<th style="text-align: center;">Infratel ID</th>
										<th style="text-align: center;">Location <span id="mandatory">*</span></th>
										<th style="text-align: center;">Latitude</th>
										<th style="text-align: center;">Longitude</th>
										<th style="text-align: center;">Work Type <span id="mandatory">*</span></th>
										<th style="text-align: center;">Site Type <span id="mandatory">*</span></th>
										<th style="text-align: center;">Action</th>
									</tr>
								</thead>
								<tbody>
									<tr id="row_2">
										<td width="10%">
											<input type="text" name="site_id[]" id="site_id_2" class="form-control" onkeyup="getInfratelId(2,this.value)">
										</td>

										<td>
											<input type="text" name="site_name[]" id="site_name_2" class="form-control">
										</td>

										<td>
											<input type="text" name="so_number[]" id="so_number_2" class="form-control">
										</td>
										<td>
											<input type="text" class="form-control" name="infratel_id[]" id="infratel_id_2">
										</td>
										<td>
											<input type="text" class="form-control" name="location[]" id="location_2">
										</td>
										<td>
											<input type="text" class="form-control" name="latitude[]" id="latitude_2">
										</td>
										<td>
											<input type="text" class="form-control" name="longitude[]" id="longitude_2">
										</td>
										<td width="15%">
											<input type="text" class="form-control" name="work_type[]" id="work_type_2" >
										</td>
										<td width="10%">
											<select class="form-control select2" name="site_type[]" id="site_type_2" >
									<option value="">Select Site Type</option>
										<option value="RTT">RTT</option>
										<option value="GBT">GBT</option>
										<option value="Upgradation ">Upgradation</option>
								</select>
										</td>
										<td></td>
									</tr>
								</tbody>
							</table>
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Sites</button>
								</div>
							</div>
						</div>
						<br clear="all">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<button type="submit" class="btn btn-primary pull-right" id="addPoAndSitesButton">Add Sites</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
		$("#addPoAndSitesButton").click(function(event) {
			event.preventDefault();
			$("#loading-bg").show();
			$.ajax({
				url: $("#addPoAndSitesForm").attr('action'),
				type: 'POST',
				data: $("#addPoAndSitesForm").serialize(),
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "success"
						}).then(function(){
							window.location.href = "/manage-po-site/po-details";
						});
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						return false;
					}
				}
			});
			
		});
	});

	function addMoreRow() {
		var length = $("#siteDetailsTable tr").length;
		var row_count = parseInt(length) + 1;
		var row_html = `<tr id="row_`+row_count+`">
		<td>
		<input type="text" name="site_id[]" id="site_id_`+row_count+`" class="form-control" onkeyup="getInfratelId(`+row_count+`,this.value)">
		</td>
		<td>
		<input type="text" name="site_name[]" id="site_name_`+row_count+`" class="form-control">
		</td>
		<td>
		<input type="text" name="so_number[]" id="so_number_`+row_count+`" class="form-control">
		</td>
		<td>
		<input type="text" class="form-control" name="infratel_id[]" id="infratel_id_`+row_count+`">
		</td>
		<td>
		<input type="text" class="form-control" name="location[]" id="location_`+row_count+`">
		</td>
		<td>
		<input type="text" class="form-control" name="latitude[]" id="latitude_`+row_count+`">
		</td>
		<td>
		<input type="text" class="form-control" name="longitude[]" id="longitude_`+row_count+`">
		</td>
		<td>
		<input type="text" class="form-control" name="work_type[]" id="work_type_`+row_count+`" >
		</td>
		<td>
		<select class="form-control select2" name="site_type[]" id="site_type_`+row_count+`" >
			<option value="">Select Site Type</option>
				<option value="RTT">RTT</option>
				<option value="GBT">GBT</option>
				<option value="Upgradation ">Upgradation</option>
		</select>
		</td>
		<td><a href="javascript:void(0)" title="Delete Row" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color: red;"></i></a></td>
		</tr>`;
		$("#siteDetailsTable").append(row_html);
	}
	function deleteRow(count) {
		$("#row_"+count).remove();
	}
	

	function getInfratelId(count,site_id){
		if(site_id != ""){
			$.ajax({
				url: '/manage-po-site/get-site-matrix-data/site_id/'+site_id,
				type: 'GET',
				success:function(data){
					console.log(data);
					if(data){
						var data = JSON.parse(data);
						$('#infratel_id_'+count).val(data.infratel_id);
						$('#site_name_'+count).val(data.zone);
						$('#location_'+count).val(data.zone);
					}
				}
			});
		}
		

	}
</script>
