<style>
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 16px;
	}
	.error_box{
		border: 1px solid red;
		border-radius: 5px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
	.hidden {
		display: none;
	}
</style>
<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params['error'])): ?>
			<?php if ($this->params['error']) { ?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Edit PO</h3>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
					</div>
				</div>
			</div>
			<div class="panel panel-body">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
					<form action="/manage-po-site/edit-po-and-sites/po/<?php echo $this->po['id']; ?>" method="POST" role="form" id="editPoAndSitesForm">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
							</div>
						</div>
						<br clear="all">
						<div class="row">
							<input type="hidden" name="po_no" value="<?php echo $this->po['po_no']; ?>">
							<input type="hidden" name="po_id" value="<?php echo $this->po['id']; ?>">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="state_id">State<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="state_id" id="state_id" onchange="getClientMasterList()">
									<option value="">Select State</option>
									<?php foreach ($this->stateList as $state): ?>
										<option value="<?php echo $state['id']; ?>" <?php echo $state['id'] == $this->po['state_id'] ? "selected":""; ?>><?php echo $state['state_name']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="client_id">Client Name<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="client_id" id="client_id">
									<option value="<?php echo $this->po['client_id']; ?>"><?php echo $this->po['client_name']; ?></option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_type">PO Type<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="po_type" id="po_type">
									<option value="">Select PO Type</option>
									<option value="Standard PO" <?php echo "Standard PO" == $this->po['document_type'] ? "selected":""; ?>>Standard PO</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_amount">PO Amount<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="po_amount" id="po_amount" value="<?php echo $this->po['po_amount']; ?>" oninput="this.value = this.value.replace(/[^\0-9\.]/g,'')" required>
							</div>

							<!-- <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="operationg_unit">Operating Unit<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="operating_unit" id="operating_unit" value="<?php echo $this->po['operating_unit']; ?>" oninput="this.value = this.value.replace(/[^A-Z a-z]/g,'')" >
							</div> -->
							
						</div>

						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_number">PO Number<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="po_number" value="<?php echo $this->po['po_no']; ?>" id="po_number" oninput="this.value = this.value.replace(/[^A-Z / a-z 0-9]/g,'')">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_date">PO Date<span id="mandatory">*</span> :</label>
								<input type="text" value="<?php echo date('d/m/Y',strtotime($this->po['order_date'])); ?>" class="form-control datepicker" name="po_date" id="po_date" readonly="">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="revision">Revision :</label>
								<input type="text" class="form-control" value="<?php echo $this->po['rev']; ?>" name="revision" id="revision" oninput="this.value = this.value.replace(/[^0-9]/g,'')">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="site_type">Site Type :</label>
								<select class="form-control select2" name="site_type" id="site_type" >
                    			    <option value="">Select Site Type</option>
                    				<option value="RTT">RTT</option>
                    				<option value="GBT">GBT</option>
                    				<option value="Upgrade">Upgrade</option>
                    		</select>
							</div>
						</div>
						<br>
						<h3 align="center"><u>Site Details</u></h3>
						<br>

						<div class="row" id="productsServicesDiv" style="overflow: auto; padding: 8px 15px;">
							<table class="table table-bordered" id="siteDetailsTable">
								<thead>
									<tr>
										<th style="text-align: center;">Site ID <span id="mandatory">*</span></th>
										<th style="text-align: center;">Site Name</th>
										<th style="text-align: center;">SO Number</th>
										<th style="text-align: center;">Infratel ID</th>
										<th style="text-align: center;">Location <span id="mandatory">*</span></th>
										<th style="text-align: center;">Latitude</th>
										<th style="text-align: center;">Longitude</th>
										<th style="text-align: center;">Work Type <span id="mandatory">*</span></th>
										<th style="text-align: center;">Action</th>
									</tr>
								</thead>
								<tbody>
									<?php if(!$this->po_sites){ ?>

										<tr id="row_2">
											<input type="hidden" name="new_site[]" class="new" value="1">
											<td width="10%">
												<input type="text" name="site_id[]" id="site_id_2" class="form-control site_id" >
											</td>
											<td>
												<input type="text" name="site_name[]" id="site_name_2" class="form-control">
											</td>
											<td>
												<input type="text" name="so_number[]" id="so_number_2" class="form-control">
											</td>
											<td>
												<input type="text" class="form-control" name="infratel_id[]" id="infratel_id_2">
											</td>
											<td>
												<input type="text" class="form-control" name="location[]" id="location_2">
											</td>
											<td>
												<input type="text" class="form-control" name="latitude[]" id="latitude_2">
											</td>
											<td>
												<input type="text" class="form-control" name="longitude[]" id="longitude_2">
											</td>
											<td width="25%">
												<input type="text" class="form-control" name="work_type[]" id="work_type_2" >
											</td>
								<!--			<td width="10%">-->
												<!--<input type="text" class="form-control" name="site_type[]" id="site_type_2" >-->
								<!--<select class="form-control select2" name="site_type[]" id="site_type_2" >-->
								<!--	<option value="">Select Site Type</option>-->
								<!--		<option value="RTT">RTT</option>-->
								<!--		<option value="GBT">GBT</option>-->
								<!--		<option value="Upgradation ">Upgradation</option>-->
								<!--</select>-->
								<!--			</td>-->
											<td></td>
										</tr>
										
									<?php }else{
										$y = 2;
										foreach ($this->po_sites as $po_site) {

											$deployment = $this->controller->getDeploymentData($po_site['site_id'],$po_site['po_no']);
											$location = $this->controller->getLocationData($deployment['infratel_site_id']);
											 
											?>

											<tr id="row_<?php echo $y; ?>">
												<input type="hidden" name="po_site_id[]" value="<?php echo $po_site['id']; ?>">
												<input type="hidden" name="po_site_deployment_id[]" value="<?php echo $deployment['id']; ?>">
												<input type="hidden" name="po_site_location[]" value="<?php echo $po_site_location['id']; ?>">
												<td width="10%">
													<input type="text" name="site_id[]" id="site_id_<?php echo $y; ?>" class="form-control site_id" value="<?php echo $po_site['site_id']; ?>" >
												</td>
												<td>
													<input type="text" name="site_name[]" id="site_name_<?php echo $y; ?>" class="form-control" value="<?php echo $po_site['site_name']; ?>" >
												</td>
												<td>
													<input type="text" name="so_number[]" id="so_number_<?php echo $y; ?>" class="form-control" value="<?php echo $deployment['so_no']; ?>" >
												</td>
												<td>
													<input type="text" class="form-control" name="infratel_id[]" id="infratel_id_<?php echo $y; ?>" value="<?php echo $deployment['infratel_id']; ?>" >
												</td>
												<td>
													<input type="text" class="form-control" name="location[]" id="location_<?php echo $y; ?>" value="<?php echo $deployment['location']; ?>" >
												</td>
												<td>
													<input type="text" class="form-control" name="latitude[]" id="latitude_<?php echo $y; ?>" value="<?php echo $location['latitude']; ?>" >
												</td>
												<td>
													<input type="text" class="form-control" name="longitude[]" id="longitude_<?php echo $y; ?>" value="<?php echo $location['longitude']; ?>" >
												</td>
												<td width="25%">
													<input type="text" class="form-control" name="work_type[]" id="work_type_<?php echo $y; ?>" value="<?php echo $deployment['work_type']; ?>" >
												</td>
								<!--		        <td width="25%">-->
								<!--<select class="form-control select2" name="site_type[]" id="site_type_<?php echo $y; ?>" >-->
								<!--	<option value="">Select Site Type</option>-->
								<!--		<option value="RTT">RTT</option>-->
								<!--		<option value="GBT">GBT</option>-->
								<!--		<option value="Upgradation ">Upgradation</option>-->
								<!--</select>-->
								<!--				</td>-->
												<td>
													<a href="javascript:void(0)" title="Delete Row" onclick="deleteRow(<?php echo $po_site['site_id']?>)"><i class="fa fa-trash fa-2x" style="color: red;"></i></a>
												</td>
											</tr>


											<?php $y++; } } ?>

										</tbody>
									</table>
									<!-- <div class="row">
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Sites</button>
										</div>
									</div> -->
								</div>
								<br clear="all">
								<div class="row">
									<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
										<button type="submit" class="btn btn-primary pull-right" id="addPoAndSitesButton">Add Sites</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>

		<script type="text/javascript">
			$(document).ready(function() {
				$(".select2").select2();
				$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
$("#addPoAndSitesButton").click(function(event){

    event.preventDefault();

    if(!checkInputData()){
        return false;
    }

    $("#loading-bg").show();

    $.ajax({
        url: $("#editPoAndSitesForm").attr('action'),
        type: 'POST',
        data: $("#editPoAndSitesForm").serialize(),
        dataType: 'json',   // important
        success:function(response){

            $("#loading-bg").hide();
            console.log(response);

            if (response.flag) {
                swal({
                    title : response.title,
                    text  : response.message,
                    icon  : "success"
                }).then(function(){
                    window.location.href = "/manage-po-site/po-details";
                });
            } else {
                swal({
                    title : response.title,
                    text  : response.message,
                    icon  : "error"
                });
            }
        },
        error:function(xhr){
            $("#loading-bg").hide();
            console.log(xhr.responseText);
            alert("Server Error Occurred");
        }
    });
});
			});

			function addMoreRow() {
				var length = $("#siteDetailsTable tr").length;
				var new_site_length = $(".new").length;
				var new_site_length = new_site_length + 1;
				var row_count = parseInt(length) + 1;
				var row_html = `<tr id="row_`+row_count+`">
				<td>
				<input type="hidden" name="new_site[]" class="new" value="`+new_site_length+`">

				<input type="text" name="site_id[]" id="site_id_`+row_count+`" class="form-control site_id" onkeyup="getInfratelId(`+row_count+`,this.value)">
				</td>
				<td>
				<input type="text" name="site_name[]" id="site_name_`+row_count+`" class="form-control">
				</td>
				<td>
				<input type="text" name="so_number[]" id="so_number_`+row_count+`" class="form-control">
				</td>
				<td>
				<input type="text" class="form-control" name="infratel_id[]" id="infratel_id_`+row_count+`">
				</td>
				<td>
				<input type="text" class="form-control" name="location[]" id="location_`+row_count+`">
				</td>
				<td>
				<input type="text" class="form-control" name="latitude[]" id="latitude_`+row_count+`">
				</td>
				<td>
				<input type="text" class="form-control" name="longitude[]" id="longitude_`+row_count+`">
				</td>
				<td>
				<input type="text" class="form-control" name="work_type[]" id="work_type_`+row_count+`" >
				</td>
				<td><a href="javascript:void(0)" title="Delete Row" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color: red;"></i></a></td>
				</tr>`;
				$("#siteDetailsTable").append(row_html);
			}
			function deleteRow(count) {
			 
				$.ajax({
					url: "/manage-po-site/delete-sites/site_id/" + count,
					method: "POST",
					context: document.body,
					success: function () {
						swal({
							title: "Deleted", 
							text: "Site has been deleted successfully.", 
							type: "success"
						}, function() {
							if(count){
								window.location.href = "/manage-po-site/po-details";
							}
						});
					}
				});
			}

			function getInfratelId(count,site_id){
				if(site_id != ""){
					$.ajax({
						url: '/manage-po-site/get-site-matrix-data/site_id/'+site_id,
						type: 'GET',
						success:function(data){
							console.log(data);
							if(data){
								var data = JSON.parse(data);
								$('#infratel_id_'+count).val(data.infratel_id);
								$('#location_'+count).val(data.zone);
							}
						}
					});
				}
				

			}

			function checkInputData() {
				if ($("#state_id").val() == "") {
					swal({
						title : "State Missing!",
						text  : "Please select state name.",
						icon  : "error"
					}).then(function(){
						$("#state_id").select2('open');
					});
					return false;
				} else if ($("#client_id").val() == "") {
					swal({
						title : "Client Missing!",
						text  : "Please select client name.",
						icon  : "error"
					}).then(function(){
						$("#client_id").select2('open');
					});
					return false;
				} else if ($("#po_type").val() == "") {
					swal({
						title : "PO Type Missing!",
						text  : "Please select PO type.",
						icon  : "error"
					}).then(function(){
						$("#po_type").select2('open');
					});
					return false;
				} else if ($("#po_amount").val() == "") {
					swal({
						title : "PO Amount Missing!",
						text  : "Please enter PO Amount.",
						icon  : "error"
					}).then(function(){
						$("#po_amount").focus();
					});
					return false;
				} else if ($("#po_number").val() == "") {
					swal({
						title : "PO Number Missing!",
						text  : "Please enter PO number.",
						icon  : "error"
					}).then(function(){
						$("#po_number").focus();
					});
					return false;
				} else if ($("#po_date").val() == "") {
					swal({
						title : "PO Date Missing!",
						text  : "Please select PO date.",
						icon  : "error"
					}).then(function(){
						$("#po_date").focus();
					});
					return false;
				} else if ($(".site_id").val() == "") {
        			swal({
        				title : "Site id Missing!",
        				text  : "Please enter Site Id.",
        				icon  : "error"
        			}).then(function(){
        				$(".site_id").focus();
        			});
    			return false;
				} 

				else {
					return true;
				}
			}
		</script>
