<style>
	#siteTable > tbody {
		display:block;
		max-height:250px;
		overflow-y:scroll;
	}
	#siteTable > thead > tr, #siteTable > tbody > tr {
		display:table;
		width:100%;
		table-layout:fixed;
	}
</style> 
<div class="modal-dialog" style="width: 70%;">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">PO Number: <?php echo $this->params['po_number']; ?> Site(s) List</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="table-responsive">
						<table class="table table-striped" id="siteTable">
							<thead>
								<tr>
									<th>#</th>
									<th>Site Id</th>
									<th>Site Allocated</th>
									<th>Allocation Date</th>
									<th>Site Expense</th>
									<th>Site Due Date</th>
								</tr>
							</thead>
							<tbody>
								<?php if ($this->poSiteDetails){ ?>
									<?php $i = 1;
									foreach ($this->poSiteDetails as $siteDetails): ?>
										<tr>
											<td><?php echo $i; ?></td>
											<td><?php echo $siteDetails['site_id']; ?></td>
											<td><?php if ($siteDetails['site_allocation_id'] != "") { echo 'Yes'; } else echo 'No'; ?></td>
											<td><?php if ($siteDetails['site_allocation_date'] != "") { echo date('d/m/Y', strtotime($siteDetails['site_allocation_date']));
										} else { echo "-"; } ?></td>
										<td><?php if ($siteDetails['total_site_expense'] != "") {
											echo $siteDetails['total_site_expense'];
										} else { echo "-"; } ?></td>
										<td><?php if ($siteDetails['site_due_date'] != "") {
											echo date('d/m/Y', strtotime($siteDetails['site_due_date']));
										} else { echo "-"; } ?></td>
									</tr>
									<?php $i++; endforeach ?>
									<?php } else { ?><tr>
										<td colspan="6" style="color: red; text-align: center;">Site(s) Not Found!</td>
									</tr>
								<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
		</div>
	</div>
</div>