<style>
  #mandatory {
    color: red;
    font-size: 20px;
  }
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']): ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success</strong> <?php echo $message['success']; ?>
          </div>
        <?php endif ?>
      <?php endforeach ?>
    <?php endif ?>
    <?php if (isset($this->params)): ?>
      <?php if ($this->params['error']) { ?>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
        </div>
      <?php } ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Import PO
        </h3>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <form name="importPoForm" action="/manage-po-site/import-po" method="POST" role="form" enctype="multipart/form-data">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <label for="uploaded_excel">Upload Excel File <span id="mandatory">*</span></label>
                <input type="file" class="form-control" name="uploaded_excel" id="uploaded_excel">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <button type="submit" class="btn btn-success" style="margin-top: 27px;">Import</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>


