 <link rel="stylesheet" href="/assets/css/select2.min.css">
 <script src="/assets/js/select2.min.js"></script>
 <div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']): ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success</strong> <?php echo $message['success']; ?>
          </div>
        <?php endif ?>
      <?php endforeach ?>
    <?php endif ?>
    <?php if (isset($this->params)): ?>
      <?php if ($this->params['error']) { ?>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
        </div>
      <?php } ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Import Site Data
          <div class="pull-right">
           <!--  <a href="/excel/location.xlsx" type="button" class="btn btn-success" style="float: right; margin-left: 10px;">
              <i class="fa fa-file-excel-o" style="font-size: 14px;"></i> Location Sheet
            </a> -->
            <a href="/excel/matrix.xls" type="button" class="btn btn-success" style="float: right; margin-left: 10px;">
              <i class="fa fa-file-excel-o" style="font-size: 14px;"></i> Matrix Sheet
            </a>
           <!--  <a href="/excel/deployment.xlsx" type="button" class="btn btn-success" style="float: right; margin-left: 10px;">
              <i class="fa fa-file-excel-o" style="font-size: 14px;"></i> Deployment Sheet 
          </a> -->
          </div>
        </h3>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <form name="importPoForm" action="/manage-po-site/import-site-data" method="POST" role="form" enctype="multipart/form-data">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="type_of_sheet">Type of Sheet <span id="mandatory">*</span></label>
                <select name="type_of_sheet" id="type_of_sheet" style="height: 35px;"  value="" class="form-control select2">
                  <option value="">Please Select</option>
                  <!-- <option value="Deployment"<?php echo $this->params['type_of_sheet'] == "Deployment" ? "selected":""; ?>>Deployment Sheet</option> -->
                  <option value="Matrix"<?php echo $this->params['type_of_sheet'] == "Matrix" ? "selected":""; ?>>Matrix Sheet</option>
                  <!-- <option value="Location"<?php echo $this->params['type_of_sheet'] == "Location" ? "selected":""; ?>>Location Sheet</option> -->
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="uploaded_excel">Upload Excel File <span id="mandatory">*</span></label>
                <input type="file" class="form-control" name="uploaded_excel" id="uploaded_excel">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <button type="submit" class="btn btn-success" style="margin-top: 22px;">Import</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

<script>
  $(document).ready(function() {
    $("#officeExpenseDetailsTable").DataTable();
    $('.select2').select2();
  });
</script>

