<div class="panel panel-body">
  <form action="/manage-po-site/save-report-new-incident/type/<?php echo $this->incident_type;?>" method="POST" id="incidentReportForm">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_date">Date of Incident<span id="mandatory">*</span></label>
          <input type="text" class="form-control datepicker" name="incident_date" id="incident_date" readonly="" value="<?php echo date('d/m/Y'); ?>">
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="employee_id">Employee<span id="mandatory">*</span></label>
          <select class="form-control mandatorySelect select2" multiple="" name="employee_id[]" id="employee_id">
            <?php foreach ($this->userList as $user): ?>
              <option value="<?php echo $user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
            <?php endforeach ?>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_report">Incident Report<span id="mandatory">*</span></label>
          <textarea class="form-control" name="incident_report" id="incident_report" cols="40" rows="3"></textarea>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_effect">Incident Consequence</label>
          <textarea class="form-control" name="incident_effect" id="incident_effect" cols="40" rows="3"></textarea>
        </div>
      </div>
      <div class="row" id="saveButtonDiv">
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
          <button type="button" class="btn btn-success" style="float: right;" id="saveIncidentReport">Save Report</button>
        </div>
      </div>
    </div>
  </form>
</div>

<script>
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true, maxDate:0 });
    $("#saveIncidentReport").click(function(event) {
      event.preventDefault();
      var incident_date     = $("#incident_date").val();
      var employee_id       = $("#employee_id").val();
      var incicdent_report  = $("#incicdent_report").val();
      if (incident_date == "") {
        swal({
          title : "Incident Date Missing!",
          text  : "Please select incident date.",
          icon  : "error"
        }).then(function(){
          $("#incident_date").focus();
        });
        return false;
      } else if (incident_report == "") {
       swal({
        title : "Incident Report Missing!",
        text  : "Please enter incident report.",
        icon  : "error"
      }).then(function(){
        $("#incident_report").focus();
      });
      return false;
    } else {
      $("#loading-bg").show();
      $.ajax({
        url: $("#incidentReportForm").attr('action'),
        type: 'POST',
        data: $("#incidentReportForm").serialize(),
        success:function(data){
          $("#loading-bg").hide();
          var data = JSON.parse(data);
          if (data.flag) {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "success"
            }).then(function(){
              window.location.href = "/manage-po-site/site-incidents-report";
            });
          } else {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "error"
            });
            return false;
          }
        }
      });
      
    }
  });
  }); 

</script>