 
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>PO Status
          <div class="pull-right">
            <a href="/manage-po/po-details" class="btn btn-success">PO Details</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <h2>Page is under construction....</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>

  <script>
    $(document).ready(function() {
      $("#officeExpenseDetailsTable").DataTable();
    });
  </script>

