<div class="panel panel-body">
  <form action="/manage-po-site/save-report-new-incident/type/<?php echo $this->incident_type;?>" method="POST" id="incidentReportForm">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_date">Date of Incident<span id="mandatory">*</span></label>
          <input type="text" class="form-control datepicker" name="incident_date" id="incident_date" readonly="" value="<?php echo date('d/m/Y'); ?>">
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="po_no">PO Number <span id="mandatory">*</span></label>
          <select name="po_no" id="po_no" class="form-control select2" onchange="getSitesByPoNumber()">
            <option value="">Select PO Number</option>
            <?php foreach ($this->poNumbers as $poNumber): ?>
              <option value="<?php echo $poNumber['po_no']; ?>"><?php echo $poNumber['po_no']; ?></option>
            <?php endforeach ?>
          </select>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="site_id">Site ID<span id="mandatory">*</span></label>
          <select name="site_id" id="site_id" class="form-control select2">
            <option value="">Select Site ID</option>
          </select>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="employee_id">Employee<span id="mandatory">*</span></label>
          <select class="form-control mandatorySelect select2" multiple="" name="employee_id[]" id="employee_id">
            <?php foreach ($this->userList as $user): ?>
              <option value="<?php echo $user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
            <?php endforeach ?>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="vendor_id">Vendor</label>
          <select class="form-control mandatorySelect transferTo select2" name="vendor_id[]" id="vendor_id">
            <option value="">Please Select</option>
            <?php foreach ($this->vendorList as $vendor): ?>
              <option value="<?php echo $vendor['id']; ?>"><?php echo $vendor['vendor_name']." (".$vendor['contact_person'].")"; ?></option>
            <?php endforeach ?>
          </select>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_report">Incident Report<span id="mandatory">*</span></label>
          <textarea class="form-control" name="incident_report" id="incident_report" cols="40" rows="3"></textarea>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <label for="incident_effect">Incident Consequence</label>
          <textarea class="form-control" name="incident_effect" id="incident_effect" cols="40" rows="3"></textarea>
        </div>
      </div>
      <div class="row" id="saveButtonDiv">
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
          <button type="button" class="btn btn-success" style="float: right;" id="saveIncidentReport">Save Report</button>
        </div>
      </div>
    </div>
  </form>
</div>

<script>
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true, maxDate:0 });
    $("#saveIncidentReport").click(function(event) {
      event.preventDefault();
      var incident_date     = $("#incident_date").val();
      var po_no             = $("#po_no").val();
      var site_id           = $("#site_id").val();
      var employee_id       = $("#employee_id").val();
      var incicdent_report  = $("#incicdent_report").val();
      if (incident_date == "") {
        swal({
          title : "Incident Date Missing!",
          text  : "Please select incident date.",
          icon  : "error"
        }).then(function(){
          $("#incident_date").focus();
        });
        return false;
      } else if (po_no == "") {
        swal({
          title : "PO Number Missing!",
          text  : "Please select PO number.",
          icon  : "error"
        }).then(function(){
          $("#po_no").focus();
        });
        return false;
      } else if (site_id == "") {
        swal({
          title : "Site ID Missing!",
          text  : "Please select site ID.",
          icon  : "error"
        }).then(function(){
          $("#site_id").focus();
        });
        return false;
      } else if (incident_report == "") {
       swal({
        title : "Incident Report Missing!",
        text  : "Please enter incident report.",
        icon  : "error"
      }).then(function(){
        $("#incident_report").focus();
      });
      return false;
    } else {
      $("#loading-bg").show();
      $.ajax({
        url: $("#incidentReportForm").attr('action'),
        type: 'POST',
        data: $("#incidentReportForm").serialize(),
        success:function(data){
          $("#loading-bg").hide();
          var data = JSON.parse(data);
          if (data.flag) {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "success"
            }).then(function(){
              window.location.href = "/manage-po-site/site-incidents-report";
            });
          } else {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "error"
            });
            return false;
          }
        }
      });
      
    }
  });
  }); 


  function getSitesByPoNumber() {
    var po_number = $("#po_no").val();
    if (po_number != "") {
      $.ajax({
        url: '/siteallocation/get-allocated-sites-by-po-number',
        type: 'POST',
        data: {po_number: po_number},
        success:function(data){
          var data = JSON.parse(data);
          console.log(data);
          if (data.flag) {
            $("#site_id").html(data.allocated_sites);
          } else {
            swal({
              title : data.title,
              text  : data.message,
              icon  : 'error'
            });
          }
        }
      });
    } else {
      $("#siteId").html("<option>Select Site ID</option>");
    }
  }


</script>