
<style type="text/css">

  #map_canvas {
    width: 100%;
    height: 100%;
  }

  .img-circle{
    border-radius: 50%;
    height: 120px;
    width: 120px;
  }
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    text-align: center;
    background-color: #444;
    color: white;
  }
</style>
<link href="/assets/plugins/bootstrap/bootstrap.css" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="/assets/plugins/lib/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="/assets/plugins/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    // Asynchronously Load the map API 
    var script = document.createElement('script');
    script.src = "https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyCNCcTQduJoNRebWEf7zgqlpe1YJibSuGI&callback=initialize";
    document.body.appendChild(script);
  });

  function initMap() {
  // The location of Uluru
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
    document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
</script>
<!-- Popup Div-->

<!-- loader start -->
<div class="loading-bg" style="display: none;">  
  <div class="loader"></div>
</div>
<!-- loader end -->
<div class="row">
  <div class="col-sm-12">
    <div id="map" class="mapping"></div>
  </div>
</div>


<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
