<?php ?>

<div class="view-port-height">

        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-list"></i>  Expense</h4>
                </div>
            </div>
        </div>


        <div class="content">

            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <div class="alert_data">
                <?php echo $message ?>.
                </div>
                <?php endforeach ?>
                </div>
            <?php endif ?>

            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                    <p style="float: left; margin: 3px;">Expense</p> 
                                   <!--<a href="/user/create-user" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px">
                                        <i class="ti-user"></i> Create New User
                                        </a>-->
                        </div>

                        <div class="card-block">
                           
               
                        </div>

                    </div>
                </div>
            </div>

        </div> <!-- end of content -->

    </div>
