<?php 
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$this->WebLoginID   = $authStorage->read()->WebLoginID;
$this->id           = $authStorage->read()->id;
$this->Role         = $authStorage->read()->Role; 
$this->access_token = $authStorage->read()->access_token;
?>

<!--<script type="text/javascript" src="/js/jquery.min.js" ></script>-->
<script type="text/javascript">
$(document).ready(function() {
$("#zone").select2();
});  
</script>

<script type="text/javascript">
function showDateWiseSiteAndAmount(){
var date1 = $('#date1').val();
var date2 = $('#date2').val();

var newdate1 = date1.split("/").reverse().join("-");
var newdate2 = date2.split("/").reverse().join("-");
if( (new Date(newdate2).getTime() < new Date(newdate1).getTime()) ){
$('#show-error').html('<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>Invalid Date Range..! Try Again.</div>');
}
else{
var id   = "show-date-wise-record";
$("#"+id).html('<div class="loading">Loading&#8230;</div>');
$.ajax({
type: 'POST',
url:  '/expense/show-date-wise-site-and-amount-ajax/',
data: { date1:date1 , date2:date2 },
cache: false,
success: function(responseText){
$("#show-date-wise-record").html(responseText);
$('#show-error').html('');
   },
});
}
}


function showZoneWiseSiteAndAmount(zone){
var id   = "show-zone-wise-record";
$("#"+id).html('<div class="loading">Loading&#8230;</div>');
$.ajax({
type: 'POST',
url:  '/expense/show-zone-wise-site-and-amount-ajax/',
data: { zone:zone },
cache: false,
//contentType : false,
//processData : false,
success: function(responseText){
  //alert(responseText);
$("#show-zone-wise-record").html(responseText);
$('#show-error').html('');
jQuery('html,body').animate({scrollTop:jQuery('#show-zone-wise-record').offset().top}, 'slow');
   },
});
}
</script>

<script type="text/javascript" src="/vendors/amcharts/amcharts.js"></script>
<script type="text/javascript" src="/vendors/amcharts/pie.js"></script>
<script type="text/javascript" src="/vendors/amcharts/themes/light.js"></script>
<script type="text/javascript" src="/vendors/amcharts/serial.js" ></script>

<style>
#chartDivZone {
 width  : 100%;
 height  : 348px;
 font-size : 12px;
}                
</style>
<style>
#chartDivNew {
 width  : 100%;
 height  : 348px;
 font-size : 12px;
}                
</style>
<style>
#chartdiv {
 width  : 100%;
 height  : 338px;
 font-size : 12px;
}                
</style>
<style>
#chartdiv2 {
 width  : 100%;
 height  : 338px;
 font-size : 12px;
}                
</style>
<style>
#chartdiv3 {
 width  : 100%;
 height  : 338px;
 font-size : 12px;
}                
</style>
<style>
#chartdiv4 {
 width  : 100%;
 height  : 338px;
 font-size : 12px;
}                
</style>
<style>
#pie1 {
 width  : 100%;
 height  : 338px;
 font-size : 12px;
}                
</style>
<script type="text/javascript">
      AmCharts.makeChart("chartDivZone", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 60
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->zonewisereport) > 0 ){ ?>
           <?php foreach ($this->zonewisereport as $keyzone) { ?>
            {
              "category": "<?php echo $keyzone['zone']; ?>",
              "column-1": <?php echo $keyzone['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
  </script>

<script type="text/javascript">
      AmCharts.makeChart("chartDivNew", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 60
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->datewisesiteamount) > 0 ){ ?>
           <?php foreach ($this->datewisesiteamount as $keysite) { ?>
            {
              "category": "<?php echo $keysite['site_id']; ?>",
              "column-1": <?php echo $keysite['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
  </script>

<script type="text/javascript">
      AmCharts.makeChart("chartdiv", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 60
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->currentdateamount) > 0 ){ ?>
           <?php foreach ($this->currentdateamount as $key_site) { ?>
            {
              "category": "<?php echo $key_site['site_id']; ?>",
              "column-1": <?php echo $key_site['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
    </script>

    <script type="text/javascript">
      AmCharts.makeChart("chartdiv2", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 50
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->currentweekamount) > 0 ){ ?>
           <?php foreach ($this->currentweekamount as $keyone_site) { ?>
            {
              "category": "<?php echo $keyone_site['week']; ?>",
              "column-1": <?php echo $keyone_site['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
    </script>

     <script type="text/javascript">
      AmCharts.makeChart("chartdiv4", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 50
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->monthwiseamount) > 0 ){ ?>
           <?php foreach ($this->monthwiseamount as $keythree_site) { ?>
            {
              "category": "<?php echo $keythree_site['month']; ?>",
              "column-1": <?php echo $keythree_site['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
    </script>
<script type="text/javascript">
      AmCharts.makeChart("pie1",
        {
          "type": "pie",
          "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
          "innerRadius": "50%",
          "labelText": "",
          "colors": [
            "#990000",
            "#fcb410",
            "#5aca82"
          ],
          "titleField": "category",
          "valueField": "column-1",
          "allLabels": [],
          "balloon": {},
          "legend": {
            "enabled": true,
            "align": "center",
            "markerType": "circle"
          },
          "titles": [],
          "dataProvider": [
            {
              "category": "Total PO",
              "column-1": <?php echo $this->total_po_no; ?>
            },
            {
              "category": "Total SITES",
              "column-1": <?php echo $this->total_sites; ?>
            }
          ]
        }
      );
    </script>
<div class="view-port-height">

        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <!--<h4><i class="fa fa-line-chart"></i>   Expense Dashboard</h4>-->
                </div>
            </div>
        </div>


        <div class="content">

            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <!--<div class="card-header card-info text-white">
                    <p style="float: left; margin: 3px;"><i class="fa fa-line-chart"></i>  Expense Dashboard</p> 
                    </div>-->

                        <div class="card-block">
                           
                         <div class="row m-t-10">
                           <div class="col-lg-12">

                            <div class="form-group row">

                              <div class="col-lg-4" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Current Day Report (<?php echo date("d/m/Y"); ?>)</h6>
                              <div id="chartdiv"></div>
                              </div>

                              <div class="col-lg-4" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Ongoing Month Weekly Report (<?php echo date('F'); ?>)</h6>
                              <div id="chartdiv2"></div>
                              </div>

                              <div class="col-lg-4" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Monthly Wise Report</h6>
                              <div id="chartdiv4"></div>
                              </div>

                            </div>


                                </div>
                                    </div>
               
                        </div> <!--card-block-->


                    </div>
                </div>
            </div>

        </div> <!-- end of content -->



        <div class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">

                           <div class="card-block">
                             <div class="row m-t-10">
                           <div class="col-lg-12">

                            <div class="form-group row">

                            
                              <div class="col-lg-8" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Date Wise Report</h6>
                              <div id="show-error"></div>
                              <div class="row">
                              <div class="col-lg-2"><b> From Date :</b></div>  
                              <div class="col-lg-3">
                              <input type="text" id="date1" name="date1" value="<?php echo date('d/m/Y'); ?>" 
                              class="form-control datepick datePickStart" onchange="showDateWiseSiteAndAmount()"
                              data-date-format="dd/mm/yyyy" data-grp="1" readonly="" placeholder="Select Date" />
                              </div>
                              <div class="col-lg-2"><b> To Date :</b></div>  
                              <div class="col-lg-3">
                              <input type="text" id="date2" name="date2" value="<?php echo date('d/m/Y'); ?>" 
                              class="form-control datepick datePickEnd" onchange="showDateWiseSiteAndAmount()"
                              data-date-format="dd/mm/yyyy" data-grp="1" readonly="" placeholder="Select Date" />
                              </div>
                              </div>

                              <div id="show-date-wise-record">
                              <div id="chartDivNew"></div>
                              </div>

                              </div>

                              <div class="col-lg-4" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Total PO No. / Sites </h6>
                              <div id="pie1"></div>
                              </div>

                            </div>


                                </div>
                                    </div>

                           </div>


                    </div>
                </div>
            </div>

        </div> <!-- end of content -->



            <div class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">

                           <div class="card-block">
                             <div class="row m-t-10">
                           <div class="col-lg-12">

                            <div class="form-group row">

                            
                              <div class="col-lg-8" style="text-align:center;">
                              <h6><i class="fa fa-list"></i> Zone Wise Site Expenses Report</h6>
                              <div id="show-error"></div>
                              <div class="row">
                              <div class="col-lg-2"><b> Select Zone :</b></div>  
                              <div class="col-lg-3">
                         <div class="input-group">
                           <select name="zone" id="zone" value="" style="width:100%; height:30px;" 
                           class="form-control" onchange="showZoneWiseSiteAndAmount(this.value)">
                            <option value="">---Select Zone---</option>
                              <?php foreach ($this->zone_list as $value) { ?>
                                 <option value="<?php echo $value['operating_unit']; ?>"><?php echo $value['zone']; ?></option>
                                     <?php } ?>
                                        </select>
                                           </div>  
                              </div>
                              </div>

                              <div id="show-zone-wise-record">
                              <div id="chartDivZone"></div>
                              </div>

                              </div>

                              <div class="col-lg-4" style="text-align:center;">
                              </div>

                            </div>


                                </div>
                                    </div>

                           </div>


                    </div>
                </div>
            </div>

        </div> <!-- end of content -->



    </div>
