<?php 
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$this->WebLoginID   = $authStorage->read()->WebLoginID;
$this->id           = $authStorage->read()->id;
$this->Role         = $authStorage->read()->Role; 
$this->access_token = $authStorage->read()->access_token;
?>

<script type="text/javascript">
function validateFile(){
var filename  = $('#import_file').get(0).files[0].name;
var filesize  = $('#import_file').get(0).files[0].size;
var fileext   = $('#import_file').get(0).files[0].name.split('.').pop().toLowerCase(); 
var extArryay = new Array('xls' , 'XLS' , 'xlsx' , 'XLSX');             
var isValidFileExt = $.inArray(fileext, extArryay);  
if (isValidFileExt == -1) {
swal('Invalid File Extension , Upload Only .xls or .xlsx File');
$('#import_file').replaceWith($('#import_file').val('').clone(true));
} else {
if (filesize > 4000000) { 
swal('Invalid File Size , Size Should be below 4Mb');
$('#import_file').replaceWith($('#import_file').val('').clone(true));
 } else { 
//swal('Valid File , You Can Proceed');
 }  
   }
      }    

function validateUser(){
if(document.getElementById("import_file").value==""){
swal('Please Select a File.!');
$('#import_file').css('border-color', 'red');
document.getElementById("import_file").focus();
return false;
} else {
 $('#import_file').css('border-color', 'green');
 }
   }
</script>

<div class="view-port-height">

        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-list"></i> Expense Module</h4>
                </div>
            </div>
        </div>


        <div class="content">

            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                    <p style="float: left; margin: 3px;">Import Expense</p> 
                    <a href="/expense/" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px"> Back </a>
                        </div>

                        <div class="card-block">

                         <div class="row m-t-10"> 
                          <div class="col-lg-12">  


                   
            <?php if ($this->messages): ?>
            <div class="alert alert-success alert-dismissable">
            <?php foreach ($this->messages as $message): ?>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
            <?php endforeach ?>
            </div>

            <?php endif ?>
            <?php if($this->errorMessage) { ?>
            <br clear="all">
            <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php  echo $this->errorMessage;   ?>                                             
            </div>
            <?php } ?>



                        <form action="/expense/import-expense/" name="importForm" id="importForm" method="post" 
                        enctype="multipart/form-data" onsubmit="return validateUser();" >

                         <div class="form-group row">

                            <div class="col-lg-2">
                             <label for="import_file"  style="color:black; font-weight:bold;" class="col-form-label"> 
                            Select File To Import * </label>   
                            </div>

                            <div class="col-lg-4">
                            <input type="file" name="import_file" id="import_file" class="form-control" 
                            onchange="validateFile()"/>
                            </div>

                            <div class="col-lg-3">
                             <button type="submit" name="submit" class="btn btn-responsive layout_btn_prevent btn-info">Submit</button>   
                            </div>

                            <div class="col-lg-3"></div>

                         </div>  <!-- end of form-group row-->


                        </form>

                   </div> <!-- end of row m-t-10-->
                    </div> <!-- col-lg-12 -->
                           
               
                        </div>

                    </div>
                </div>
            </div>

        </div> <!-- end of content -->

    </div>
