  <?php
    $record = $this->paginator; 
    $totalrec = $this->totalrec;

?>  
<style type="text/css"> 
#scroll-id {
    width: 600px;
    overflow-x: scroll;
}
</style>
      <div class="table-responsive mt-1" id="expense-list">

              <div id="leftpag">

              Total Expense : <b><?php echo $this->sum_amount; ?></b>

                <?php if($totalrec > $this->perPage) { 
                  echo $this->paginationControl($this->paginator, 'Sliding', 'expense-pagination.phtml'); 
                    } ?>  
                     </div>

                      <div id="divchallan">

                    <table class="table table-bordered table2excel" border="1" id="scroll-id">
                                         <thead>
                                            <tr>
                                                <th style=" white-space:nowrap;">
                                                # <a href="javascript:void(0)" 
        onclick="getPage('<?php echo $this->totalnum; ?>',
        '<?php if($this->id_order){ echo $this->id_order; }else{ echo 'desc';} ?>','id')" class="noprint" >
      <?php if($this->id_order == 'desc' && $this->params['type'] == 'id'){ ?>
      <img src="/img/asc.png" style="height:20px;" /><?php }
      elseif($this->id_order == 'asc' && $this->params['type'] == 'id'){ ?>
      <img src="/img/desc.png" style="height:20px;" /><?php }
        else{?><img src="/img/desc.png" style="height:20px;" /><?php }?>
      </a></th>
                                                <th style=" white-space:nowrap;">Transfer For</th>
                                                <th style=" white-space:nowrap;">State For</th>
                                                <th style=" white-space:nowrap;">Amount</th>
                                                <th style=" white-space:nowrap;">Transfer Date</th>
                                                <th style=" white-space:nowrap;">Transfered To</th>
                                                <th style=" white-space:nowrap;">Remark</th>
                                                <!--<th style=" white-space:nowrap;">Attachment</th>-->
                                                <!--<th style=" white-space:nowrap;">Status</th>-->
                                            </tr>
                                            </thead>

                                            <tbody>
                                            <?php 
                                            if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10;
                                            $i=$istart;
                                            foreach($record as $expense){ ?>
                                            <tr>
                                            <td style=" white-space:nowrap;"><?php echo $i+1;?>.</td>
                                            <td style=" white-space:nowrap;"><?php echo $expense['transferfor']; ?></td>
                                            <td style=" white-space:nowrap;"><?php echo $expense['statefor']; ?></td> 
                                            <td style=" white-space:nowrap;"><?php echo $expense['ofc_amount']; ?></td>
                                            <td style=" white-space:nowrap;">
                                            <?php if($expense['ofc_transfer_date']){ 
                                            echo date('d/m/Y' , strtotime($expense['ofc_transfer_date']));
                                            } ?>
                                            </td>
                                            <td style=" white-space:nowrap;"><?php echo $expense['name']; ?></td>
                                            <td style=" white-space:nowrap;">
                                            <?php if($expense['ofc_remark']){ echo $expense['ofc_remark']; }else{ echo "-"; } ?>
                                            </td>
                                            <!--<td style=" white-space:nowrap;">
                                            <?php if($expense['ofc_attachment']){ echo $expense['ofc_attachment']; }else{ echo "-"; } ?>
                                            </td>-->
                                            <?php  $i++;} } else{  ?>
                                            <tr><td colspan="7">
                                            <p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                            <?php } ?>
                                            </tbody>
                                      </table>

                                  </div>

                      <div id="leftpag">
                        <?php if($totalrec > $this->perPage) { 
                          echo $this->paginationControl($this->paginator, 'Sliding', 'expense-pagination.phtml'); 
                           } ?>  
                            </div>


                                  </div>