<?php 
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$this->WebLoginID   = $authStorage->read()->WebLoginID;
$this->id           = $authStorage->read()->id;
$this->Role         = $authStorage->read()->Role; 
$this->access_token = $authStorage->read()->access_token;
?>


<style>
#chartdiv4 {
 width  : 100%;
 height  : 348px;
 font-size : 12px;
}                
</style>

 <script type="text/javascript">
      AmCharts.makeChart("chartdiv4", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 50
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->monthwiseamount) > 0 ){ ?>
           <?php foreach ($this->monthwiseamount as $keythree_site) { ?>
            {
              "category": "<?php echo $keythree_site['month']; ?>",
              "column-1": <?php echo $keythree_site['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
    </script>

    <div id="chartdiv4"></div>