<?php 
$front = Zend_Controller_Front::getInstance();
$params= $front->getRequest()->getParams();
$controller = $front->getRequest()->getControllerName(); 
$action = $front->getRequest()->getActionName(); 

$user_search = $_GET['user_search'];
$search = $_GET['search'];

$arrpre = array('page' => $this->previous);
$arrnext = array('page' => $this->next);
if($user_search)
{
  $arrpre['user_search'] = $user_search;
  $arrnext['user_search'] = $user_search;
}
if($search)
{
  $arrpre['search'] = $search;
  $arrnext['search'] = $search;
}
// echo "<pre>";
         // print_r($attendance_report);exit;
?>


<ul class="pagination pagination-sm float-right">
    <?php if (isset($this->previous)): ?>

        <li class="page-item previous" aria-controls="datatable-editable" tabindex="0" id="datatable-editable_previous"><a class="page-link" href="javascript:void(0)" onclick="getPage1('<?php echo $this->previous; ?>', 'attendence','<?php echo $params['date_from'] ; ?>','<?php echo $params['date_to']; ?>');"> < Prev</a> </li>

          <?php else: ?>

           <li class="page-item previous" ><a class="page-link" herf="javascript:void(0);" class="disable">< Prev</a> </li>

           <?php endif; ?>

       
            <?php foreach ($this->pagesInRange as $page): ?>

            <?php 
      $arrpage = array('page' => $page);
      if($user_search)
      {
        $arrpage['user_search'] = $user_search;
      }
      if($search)
      {
        $arrpage['search'] = $search;
      }
      
      
      if ($page != $this->current): ?>

         <li class="page-item" aria-controls="datatable-editable" tabindex="0"><a class="page-link" href="javascript:void(0)" onclick="getPage1('<?php echo $page; ?>', 'attendence','<?php echo $params['date_from'] ; ?>','<?php echo $params['date_to']; ?>');" ><?= $page; ?></a> </li>

         <?php else: ?>

        <li class="page-item active" aria-controls="datatable-editable" tabindex="0"> <a class="page-link" href="javascript:void(0);" class="pagenumactive"><?= $page; ?></a> </li>

      
      <?php endif; ?>

        <?php endforeach; ?>

         <?php  if (isset($this->next)): ?>

       <li class="page-item next" aria-controls="datatable-editable" tabindex="0" id="datatable-editable_next"> <a  class="page-link" href="javascript:void(0)" onclick="getPage1('<?php echo $this->next; ?>', 'attendence','<?php echo $params['date_from'] ; ?>','<?php echo $params['date_to']; ?>');">Next ></a> </li>

        <?php else: ?>

         <li class="page-item next"><a class="page-link" herf="javascript:void(0);" class="disable">Next ></a> </li>

         <?php endif; ?>
     
</ul>

