<?php 
$front = Zend_Controller_Front::getInstance();
$params= $front->getRequest()->getParams();
$controller = $front->getRequest()->getControllerName(); 
$action = $front->getRequest()->getActionName(); 

$user_search = $_GET['user_search'];
$search = $_GET['search'];

$arrpre = array('page' => $this->previous);
$arrnext = array('page' => $this->next);
if($user_search)
{
	$arrpre['user_search'] = $user_search;
	$arrnext['user_search'] = $user_search;
}
if($search)
{
	$arrpre['search'] = $search;
	$arrnext['search'] = $search;
}
if($params['dueDate_from']){
    $date_from  = date('d/m/Y', strtotime($params['dueDate_from']));
    $date_to    = date('d/m/Y', strtotime($params['dueDate_to']));
    $due_date  = $date_from.' - '.$date_to;
}else{
    $due_date  = '';
}

if($params['createdDate_from']){
    $createdDate_from  = date('d/m/Y', strtotime($params['createdDate_from']));
    $createdDate_to    = date('d/m/Y', strtotime($params['createdDate_to']));
    $created_date  = $createdDate_from.' - '.$createdDate_to;
}else{
    $created_date  = '';
}
?>

<ul class="pagination pagination-sm float-right">
		<?php if (isset($this->previous)): ?>

        <li class="page-item previous" aria-controls="datatable-editable" tabindex="0" id="datatable-editable_previous"><a class="page-link" href="javascript:void(0)" onclick="getPage('<?php echo $this->previous; ?>', '<?php echo $params['task_id']?>','<?php echo $params['task_type']; ?>','<?php echo $params['assign_to']; ?>','<?php echo $due_date; ?>','<?php echo $created_date; ?>','<?php echo $params['reminder']; ?>','<?php echo $params['priority']; ?>','<?php echo $params['status']; ?>','<?php echo $params['order']; ?>','<?php echo $params['key']; ?>');"> < Prev</a> </li>

          <?php else: ?>

           <li class="page-item previous" ><a class="page-link" herf="javascript:void(0);" class="disable">< Prev</a> </li>

           <?php endif; ?>

		   
            <?php foreach ($this->pagesInRange as $page): ?>

            <?php 
			$arrpage = array('page' => $page);
			if($user_search)
			{
				$arrpage['user_search'] = $user_search;
			}
			if($search)
			{
				$arrpage['search'] = $search;
			}
			
			
			if ($page != $this->current): ?>

         <li class="page-item" aria-controls="datatable-editable" tabindex="0"><a class="page-link" href="javascript:void(0)" onclick="getPage('<?php echo $page; ?>', '<?php echo $params['task_id']?>','<?php echo $params['task_type']; ?>','<?php echo $params['assign_to']; ?>','<?php echo $due_date; ?>','<?php echo $created_date; ?>','<?php echo $params['reminder']; ?>','<?php echo $params['priority']; ?>','<?php echo $params['status']; ?>','<?php echo $params['order']; ?>','<?php echo $params['key']; ?>');" ><?php echo $page; ?></a> </li>

         <?php else: ?>

        <li class="page-item active" aria-controls="datatable-editable" tabindex="0"> <a class="page-link" href="javascript:void(0);" class="pagenumactive"><?php echo $page; ?></a> </li>

      
      <?php endif; ?>

        <?php endforeach; ?>

         <?php  if (isset($this->next)): ?>

       <li class="page-item next" aria-controls="datatable-editable" tabindex="0" id="datatable-editable_next"> <a  class="page-link" href="javascript:void(0)" onclick="getPage('<?php echo $this->next; ?>', '<?php echo $params['task_id']?>','<?php echo $params['task_type']; ?>','<?php echo $params['assign_to']; ?>','<?php echo $due_date; ?>','<?php echo $created_date; ?>','<?php echo $params['reminder']; ?>','<?php echo $params['priority']; ?>','<?php echo $params['status']; ?>','<?php echo $params['order']; ?>','<?php echo $params['key']; ?>');" >Next ></a> </li>

        <?php else: ?>

         <li class="page-item next"><a class="page-link" herf="javascript:void(0);" class="disable">Next ></a> </li>

         <?php endif; ?>
		 
</ul>

