<style>
.fa {
	font-size: 20px;
}
</style>
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if (isset($message['success'])){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if (isset($message['error'])) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Deactive User's List
					<div class="pull-right">
						<a href="/user" class="btn btn-success">Active Users</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="user-list">
						<table class="display" width="100%" id="deactiveUserListTable">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Phone</th>
									<th>Email</th>
									<th>Department</th>
									<th>Date of Joining</th>
									<th>Date of Deactivation</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<?php if($this->deactiveUsers){ 
									$i = 1;
									foreach($this->deactiveUsers as $deactiveUser) { ?>
										<tr>
											<td><?php echo $i;?>.</td>
											<td><?php echo ucwords(strtolower($deactiveUser['name'])); ?></td>
											<td><?php echo $deactiveUser['contact_no']; ?></td>
											<td><?php echo $deactiveUser['email_id']; ?></td>
											<td><?php echo $deactiveUser['department']; ?></td>
											<td><?php echo date("d/m/Y", strtotime($deactiveUser['date_of_joining'])); ?></td>
											<td><?php echo date("d/m/Y", strtotime($deactiveUser['updated'])); ?></td>
											<td>
												<a href="javascript:void()" title="Activate User" onclick="activateUserProfile('<?php echo md5($deactiveUser['id']); ?>','<?php echo $deactiveUser['name']; ?>')"><i class="fa fa-sign-in" style="color: #11CC00"></i></a>
												&nbsp;&nbsp;
												<a href="javascript:void(0)" class="tododelete redcolor" onclick="permanentDeleteUser('<?php echo md5($deactiveUser['id']);?>', '<?php echo ucwords(strtolower($deactiveUser['name'])); ?>')" title="Permanent Delete"><i class="fa fa-trash" style="color: red;"></i></a></td>
											</tr>
											<?php  $i++; } } ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<script>
					$(document).ready(function() {
						$("#deactiveUserListTable").DataTable();
					});

					function activateUserProfile(userId, name) {
						if (userId == "") {
							swal("User Missing !","User ID is missing. Please try again.","error");
							return false;
						}
						swal({
							title:"Are You Sure !",
							text:"Do you want to activate "+name,
							icon:"warning",
							buttons:[true, "Yes, Activate"],
							dangerMode:true
						}).then(function(isConfirm){
							if (!isConfirm) {
								return false;
							} else {
								$.ajax({
									url: '/user/activate-user-profile/user_id/'+userId+'/name/'+name,
									type: 'GET',
									success:function (data) {
										var data = JSON.parse(data);
										if (data.flag == true) {
											swal({
												title:"Activated Successfully",
												text:data.message,
												icon:"success"
											}).then(function(){
												window.location.reload();
											});
										} else {
											swal("Something Went Wrong",data.message,"error");
										}
									}
								});
							}
						});
					}

					function permanentDeleteUser(userId, name) {
						if (userId == "") {
							swal("User Missing !","User ID is missing. Please try again.","error");
							return false;
						}
						swal({
							title:"Are You Sure !",
							text:"Do you want to delete "+name+" permanently.",
							icon:"warning",
							buttons:[true, "Yes, Delete"],
							dangerMode:true
						}).then(function(isConfirm){
							if (!isConfirm) {
								return false;
							} else {
								$.ajax({
									url: '/user/delete-user-profile/user_id/'+userId+'/name/'+name,
									type: 'GET',
									success:function (data) {
										var data = JSON.parse(data);
										if (data.flag == true) {
											swal({
												title:"Deleted Successfully",
												text:data.message,
												icon:"success"
											}).then(function(){
												window.location.reload();
											});
										} else {
											swal("Something Went Wrong",data.message,"error");
										}
									}
								});
							}
						});
					}
				</script>