<style>
	.fa {
		font-size: 20px;
	}
</style>
<script type="text/javascript">
	function deleteMappedUserRole(userId) {
		swal({
			title: "Are you sure?",
			text: "You want to Delete this ",
			type: "warning",
			showCancelButton: true,
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "Yes, Delete this role mapping!",
			closeOnConfirm: false
		}, function (isConfirm) {
			if (!isConfirm) return;
			$.ajax({
				url: "/user/delete-user/id/"+userId,
				context: document.body,
				success: function () {
					swal({
						title: "Deleted", 
						text: "Status has been successfully changed", 
						type: "success"
					},function() {
						window.location.href="/user";
					});
				},
				error: function (xhr, ajaxOptions, thrownError) {
					swal("Error "+status+"!", "Please try again", "error");
				}
			});
		});
	};
	function getPage(page){
		var url   = '/user/user-list/page/'+page;
		var id    = 'user-list';
		$("#"+id).html('<div class="loading">Loading&#8230;</div>');
		$.ajax({
			url: url,
			context: document.body,
			success: function(responseText) {
				$("#"+id).html(responseText);
				$("#"+id).find("script").each(function(i) {
					eval($(this).text());
				});
			}
		});
	};
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('th').attr("nowrap","nowrap");
		$('td').attr("nowrap","nowrap");
	});
</script>
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>User List
					<div class="pull-right">
						<a href="/user/create-user" class="btn btn-success">Create User</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="user-list">
						<table class="display" width="100%" id="userListTable">
							<thead>
								<tr>
									<th>#</th>
									<th>Name</th>
									<th>Phone</th>
									<th>Email</th>
									<th>Department</th>
									<th>Date of Joining</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<?php if($this->user_list){ 
									$i = 1;
									foreach($this->user_list as $user) { ?>
										<tr>
											<td><?php echo $i;?>.</td>
											<td><?php echo ucwords(strtolower($user['name'])); ?></td>
											<td><?php echo $user['contact_no']; ?></td>
											<td><?php echo $user['email_id']; ?></td>
											<td><?php echo $user['department']; ?></td>
											<td><?php echo date("d/m/Y", strtotime($user['date_of_joining'])); ?></td>
											<td>
												<a href="javascript:void(0)" title="View Profile" onclick="viewUserDetails('<?php echo md5($user['id']); ?>')"><i class="fa fa-info-circle" style="color: #187CC9"></i></a>
												&nbsp;&nbsp;
												<a href="/user/edit-user-info/id/<?php echo md5($user['id']);?>"title="Edit Profile"><i class="fa fa-pencil"></i></a>
												&nbsp;&nbsp;
												<a href="javascript:void(0)" title="Clear Device ID" onclick="clearUserDeviceId('<?php echo md5($user['id']); ?>','<?php echo $user['name']; ?>')"><i class="fa fa-mobile" style="color: #11CC00"></i></a>
												&nbsp;&nbsp;
												<a href="javascript:void(0)" class="tododelete redcolor" onclick="deactivateUserProfile('<?php echo md5($user['id']);?>', '<?php echo ucwords(strtolower($user['name'])); ?>')" title="Deactivate Profile"><i class="fa fa-ban" style="color: red;"></i></a></td>
											</tr>
											<?php  $i++; } } ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- Bootstrap Modal: User Profile Details -->
				<div class="modal fade" id="userProfileDetailsModal">
					
				</div>
				<script>
					$(document).ready(function() {
						$("#userListTable").DataTable();
					});
					function viewUserDetails(userId) {
						$.ajax({
							url: '/user/view-user-profile/user_id/'+userId,
							type: 'GET',
							success:function(data){
								$("#userProfileDetailsModal").html(data);
								$("#userProfileDetailsModal").modal("toggle");
							}
						});
					}
					function deactivateUserProfile(userId, name) {
						if (userId == "") {
							swal("User Missing !","User ID is missing. Please try again.","error");
							return false;
						}
						swal({
							title:"Are You Sure !",
							text:"Do you want to deactivate "+name,
							icon:"warning",
							buttons:[true, "Yes, Deactivate"],
							dangerMode:true
						}).then(function(isConfirm){
							if (!isConfirm) {
								return false;
							} else {
								$.ajax({
									url: '/user/deactivate-user-profile/user_id/'+userId+'/name/'+name,
									type: 'GET',
									success:function (data) {
										var data = JSON.parse(data);
										if (data.flag == true) {
											swal({
												title:"Deactivated Successfully",
												text:data.message,
												icon:"success"
											}).then(function(){
												window.location.reload();
											});
										} else {
											swal("Something Went Wrong",data.message,"error");
										}
									}
								});
							}
						});
					}

					function clearUserDeviceId(userId, name) {
						if (userId == "") {
							swal("User Missing !","User ID is missing. Please try again.","error");
							return false;
						}
						swal({
							title:"Are You Sure !",
							text:"Do you want to clear "+name+"'s device ID.",
							icon:"warning",
							buttons:[true, "Yes, Clear"],
							dangerMode:true
						}).then(function(isConfirm){
							if (!isConfirm) {
								return false;
							} else {
								$("#loading-bg").show();
								$.ajax({
									url: '/user/clear-user-device-id',
									type: 'POST',
									data :{user_id:userId, name:name},
									success:function (data) {
										var data = JSON.parse(data);
										$("#loading-bg").hide();
										if (data.flag) {
											swal({
												title:data.title,
												text:data.message,
												icon:"success"
											}).then(function(){
												window.location.reload();
											});
										} else {
											swal({
												title : data.title,
												text  : data.message,
												icon  : "error"
											});
											return false;
										}
									}
								});
							}
						});
					}
				</script>