<?php
    $user_list = $this->user_list;
    $record = $this->paginator; 
    $totalrec = $this->totalrec;
?>
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Department</th>
        <th>Location</th>
        <th>SBU</th>
        <th>Role</th>
    </tr>
    </thead>
    <tbody>
    <?php 
    if($totalrec){ 
    $totalnum = $this->totalnum?$this->totalnum:1;
    $istart = ($totalnum-1) * 10;
    $i=$istart;
    foreach($record as $user)
    { ?>
    <tr>
        <td><?php echo $i+1;?>.</td>
        <td><?php echo $user['name']; ?></td>
        <td><?php echo $user['contact_no']; ?></td>
        <td><?php echo $user['email_id']; ?></td>
        <td><?php echo $user['department_name']; ?></td>
        <td><?php echo $user['location_name']; ?></td>
        <td><?php echo $user['sbu']; ?></td>
        <td><?php echo $user['role']; ?></td>
    </tr>
    <?php  $i++;} } else{  ?>
                    <tr><td colspan="7"><p style="color:red; font-size:16px;">No User Found !</p></td></tr>
        <?php  } ?>
    </tbody>
</table>
<?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'task-pagination.phtml'); } ?>