<style>
.fb-profile img.fb-image-lg{
	z-index: 0;
	width: 100%;  
	/*margin-bottom: 10px;*/
	height: 200px;
	border-radius: 4px;
}
.fb-image-profile
{
	margin: -125px 10px 0px 20px;
	z-index: 9;
	width: 20%; 
	border-radius: 25%;
}
@media (max-width:768px)
{

	.fb-profile-text>h1{
		font-weight: 700;
		font-size:16px;
	}

	.fb-image-profile
	{
		margin: -125px 10px 0px 0px;
		z-index: 9;
		width: 20%; 
		border-radius: 25%;

	}


}
.tabbable-line{font-family: 'Montserrat', sans-serif;}
.tabbable-line ul{border:none}
.tabbable-line li a,.tabbable-line li a:hover{background:#6c98df;margin-right:5px;border-radius:10px 10px 0 0;border:0;color:#fff;font-size:16px;position: relative;}
.tabbable-line li.active a{background: #f2f2f2;color:#2c2c2c;border:solid 1px #ccc; border-bottom:0;z-index: 99;left:0px;}
</style>

<div class="modal-dialog" role="document" style="width: 70%">
	<div class="modal-content">
		<div class="" >
			<div class="panel-body">
				<div class="row" style="margin-right: -30px !important;margin-left: -30px !important;margin-top: -10px !important;">
					<div class="col-sm-12">
						<div class="fb-profile">
							<img align="left" class="fb-image-lg" src="/img/infra background.jpg" alt="Profile image"/>
							<?php if($this->userDetails['profile_path']){ ?>
								<img align="left" class="fb-image-profile thumbnail" src="<?php echo $this->userDetails['profile_path']; ?>" alt="Profile image"/>
							<?php }else{ ?>
								<img align="left" class="fb-image-profile thumbnail" src="/img/user default.png" alt="Profile image "/>
							<?php } ?> 
							<div class="fb-profile-text">
								<h1><?php echo $this->userDetails['name']?>  
								<a href="/user/edit-user-info/id/<?php echo md5($this->userDetails['id']);?>" class="btn btn-success"><i class="fa fa-edit"></i></a> 
							</h1>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<table class="table table-hover">
						<tr>
							<th>Mobile Number :</th><td><?php echo $this->userDetails['contact_no']; ?></td>
							<th>Alternate Mobile Number :</th><td><?php echo $this->userDetails['alternate_mobile']; ?></td>
						</tr>
						<tr>
							<th>Email ID :</th><td><?php echo $this->userDetails['email_id']; ?></td>
							<th>Date of Joining :</th><td><?php echo date("d/m/Y", strtotime($this->userDetails['date_of_joining'])); ?></td>
						</tr>
						<tr>
							<th>Current Address :</th><td><?php echo $this->userDetails['current_address']; ?></td>
							<th>Permanent Address :</th><td><?php echo $this->userDetails['permanent_address']; ?></td>
						</tr>
						<tr>
							<th>Department :</th><td><?php echo $this->userDetails['department']; ?></td>
							<th>Role Type :</th><td><?php echo $this->userDetails['role_type']; ?></td>
						</tr>
						<tr>
							<th>Role :</th><td><?php echo $this->userDetails['role']; ?></td>
							<!-- <th>Permanent Address :</th><td><?php echo $this->userDetails['permanent_address']; ?></td> -->
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
</div>


