


<script type="text/javascript">
	$(document).ready(function() {
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
		
	});
	function getClientMasterList() {
		var state_id = $("#state_id").val();
		if (state_id == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
			$("#client_id").empty();
			$("#client_id").append('<option value="">Select Client</option>');
			return false;
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/master/get-client-details',
				type: 'POST',
				data: {state_id: state_id},
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						$("#client_id").empty();	
						$("#client_id").append('<option value="">Select Client</option>');	
						$.each(data.clientDetails, function(index, val) {
							$("#client_id").append('<option value="'+val.id+'">'+val.client_name+'</option>');	
						});
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						$("#client_id").empty();	
						$("#client_id").append('<option value="">Select Client</option>');	
					}
				}
			});

		}
	}

	function getInfratelId(count,site_id){
		if(site_id != ""){
			$.ajax({
				url: '/manage-po-site/get-site-matrix-data/site_id/'+site_id,
				type: 'GET',
				success:function(data){
					console.log(data);
					if(data){
						var data = JSON.parse(data);
						$('#infratel_id_'+count).val(data.infratel_id);
						$('#site_name_'+count).val(data.zone);
						$('#location_'+count).val(data.zone);
					}
				}
			});
		}
		

	}

	function checkInputData() {
		if ($("#state_id").val() == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
			return false;
		} else if ($("#client_id").val() == "") {
			swal({
				title : "Client Missing!",
				text  : "Please select client name.",
				icon  : "error"
			}).then(function(){
				$("#client_id").select2('open');
			});
			return false;
		} else if ($("#po_type").val() == "") {
			swal({
				title : "PO Type Missing!",
				text  : "Please select PO type.",
				icon  : "error"
			}).then(function(){
				$("#po_type").select2('open');
			});
			return false;
		}  else if ($("#po_amount").val() == "") {
			swal({
				title : "PO Amount Missing!",
				text  : "Please enter PO Amount.",
				icon  : "error"
			}).then(function(){
				$("#po_amount").focus();
			});
			return false;
		} else if ($("#po_number").val() == "") {
			swal({
				title : "PO Number Missing!",
				text  : "Please enter PO number.",
				icon  : "error"
			}).then(function(){
				$("#po_number").focus();
			});
			return false;
		} else if ($("#po_date").val() == "") {
			swal({
				title : "PO Date Missing!",
				text  : "Please select PO date.",
				icon  : "error"
			}).then(function(){
				$("#po_date").focus();
			});
			return false;
		} 
		
		else {
			return true;
		}
	}
</script>