
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
	.select2.select2-container {
		width: 100% !important;
	}
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
		padding: 10px 15px 10px 15px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 18px;
	}  
	.formDiv {
		border: 5px solid #b0d5ea;
		border-radius: 5px;
		padding: 10px 10px 10px 10px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
	.error_box{
		border: 1px solid red;
		border-radius: 4px;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params)): ?>
			<?php if (isset($this->params['success'])){ ?>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Success !</strong>&nbsp; <?php echo $this->params["success"]; ?>
				</div>
			<?php } else if (isset($this->params['error'])) { ?>
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Create New Expense</h3>
					</div>

					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<a <?php if (isset($this->params['expenseType']) && $this->params['expenseType'] == "Office Expense") { ?>
							href="/expense/office-expenses" <?php } else { ?>href="/expense" <?php } ?> class="btn btn-success pull-right">Back</a>
						</div>
					</div>
				</div>
				<div class="panel panel-body">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
							</div>
						</div>
						<div class="row">

							

							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="expenseTypeSelect">Expense Type<span id="mandatory">*</span></label>
								<select id="expenseTypeSelect" class="form-control select2">
									<option value="">Please Select</option>
									<?php foreach ($this->expenseTypeList as $expenseType): ?>
										<option value="<?php echo $expenseType['id']; ?>"><?php echo $expenseType['expense_type']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 formDiv" style="display: none;">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script>
		$(function() {
		    $("body").delegate(".datepicker", "focusin", function(){
		        $(this).datepicker({ dateFormat: "yy-mm-dd", changeYear:true, changeMonth:true, maxDate:0});		    
			});
		});


		$(document).ready(function() {
			$(".select2").select2();
			$("#expenseTypeSelect").change(function(event) {
				event.preventDefault();
				var expenseType = $("#expenseTypeSelect").val();
				var expenseTypeTextValue = $("#expenseTypeSelect option:selected").text();
				if (expenseType != "") {
					if (expenseTypeTextValue == "Site Expense") {
						$.ajax({
							url: '/expense/site-expense-form/expense_type/'+expenseType,
							type: 'GET',
							success:function (data) {
								$(".formDiv").html(data);
								$("#expenseType").val(expenseType);
							}
						});
						$(".formDiv").show();
					} else if (expenseTypeTextValue == "Office Expense") {
						$.ajax({
							url: '/expense/office-expense-form/expense_type/'+expenseType,
							type: 'GET',
							success:function (data) {
								$(".formDiv").html(data);
								$("#expenseType").val(expenseType);
							}
						});
						$(".formDiv").show();
					} 
				} else {
					$(".formDiv").hide();
				}
			});
		}); 
		function addMoreRow() {
			var siteId = $('#siteId').val();
			var row_count = $('#expenseDetailsTable tr').length;
			var expenseType = $("#expenseTypeSelect").val();
			var result1, result2;
			$.when(
				$.ajax({
					url: '/expense/get-expense-in-list/expense_type_id/'+expenseType,
					type: 'GET',
					success:function(data){
						var data = JSON.parse(data);
						console.log(data);
						if (data.flag) {
							result1 = data.expenseOption;
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
						}
					}
				}),
				$.ajax({
					url: '/expense/get-site-document-for-list',
					type: 'GET',
					success:function(data){
						var data = JSON.parse(data);
						console.log(data);
						if (data.flag) {
							result_1 = data.option;
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
						}
					}
				}),
				$.ajax({
					url: '/siteallocation/get-site-allocated-to-details',
					type: 'POST',
					data: {site_id: siteId},
					success:function(data){
						var data = JSON.parse(data);
						console.log(data);
						if (data.flag) {
							result2 = data.material_supplier_list;
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
						}
					}
				})
				).then(function(){
					$("#expense_in_id_"+row_count).html(result1);
					$("#expense_remark_"+row_count).html(result_1);
					$("#amountTransferTo_"+row_count).html(result2);
				});
				var html_content = `<tr id="row_`+row_count+`">
				<td width="25%">
				<select name="expense_in_id[]" id="expense_in_id_`+row_count+`" class="form-control mandatorySelect select2" onchange="showExpenseForList(`+row_count+`)">
				<option value="">Please Select</option>
				</select>
				</td>
				<td>
				<select name="expense_for_id[]" id="expense_for_id_`+row_count+`"class="form-control mandatorySelect select2">
				<option value="">Please Select</option>
				</select>
				</td>
				<td>
				<input type="text" class="form-control mandatoryField"  name="spentAmount[]" id="spentAmount_`+row_count+`">
				</td>
				<td>
				<input type="text" class="form-control mandatoryField" name="spentRemark[]" id="spentRemark_`+row_count+`">
				</td>
				<td>
				<select id="expense_remark_`+row_count+`" name="expense_remark[]" class="form-control select2 mandatorySelect " required="required" onchange="checkRequired(this.value,`+row_count+`)"><option value="">Select</option>
				</select></td>
				<input type="hidden" id="is_required_`+row_count+`" class="is_require">

				<td> 
				<input type="file" class="form-control" name="bill_attachment[]" id="bill_attachment_`+row_count+`">
				</td>
				<td> 
				<input type="text" class="form-control datepicker mandatoryField" readonly="" name="date[]" id="date_`+row_count+`">
				</td>
				<td><a href="javascript:void(0)" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color:red;"></i></a></td>
				</tr>`;
				$("#expenseDetailsTable").append(html_content);
				$(".select2").select2();
			} 
			function addMoreRowInOfficeExpenseForm() {
				var row_count = $('#expenseDetailsTable tr').length;
				var expenseType = $("#expenseTypeSelect").val();
				$.ajax({
					url: '/expense/get-expense-in-list/expense_type_id/'+expenseType,
					type: 'GET',
					success:function(data){
						var data = JSON.parse(data);
						console.log(data);
						if (data.flag) {
							$("#expense_in_id_"+row_count).html(data.expenseOption);
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
						}
					}
				});
				var html_content = `<tr id="row_`+row_count+`">
				<td>
				<select name="expense_in_id[]" id="expense_in_id_`+row_count+`" class="form-control mandatorySelect select2" onchange="showExpenseForList(`+row_count+`)">
				<option value="">Please Select</option>
				</select>
				</td>
				<td>
				<select name="expense_for_id[]" id="expense_for_id_`+row_count+`" class="form-control select2">
				<option value="">Please Select</option>
				</select>
				</td>
				<td>
				<input type="text" class="form-control" name="spentAmount[]" id="spentAmount_`+row_count+`" required="">
				</td>
				<td><input type="text" class="form-control" name="spentRemark[]" id="spentRemark_`+row_count+`"></td>
				<td><a href="javascript:void(0)" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color:red;"></i></a></td>
				</tr>`;
				$("#expenseDetailsTable").append(html_content);
				$(".select2").select2();
			}
			function deleteRow(count) {
				$("#row_"+count).remove();
			} 
			function showExpenseForList(row_number) {
				var expenseInId = $("#expense_in_id_"+row_number).val();
				if (expenseInId != "") {
					$.ajax({
						url: '/expense/get-expense-for-by-expense-in/expense_in_id/'+expenseInId,
						type: 'GET',
						success:function(data) {
							var data = JSON.parse(data);
							console.log(data);
							if (data.flag) {
								$("#expense_for_id_"+row_number).html(data.option);
								$("#is_required_"+row_number).val(data.is_required);
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : "error"
								}).then(function(){
									$("#expense_for_id_"+row_number).html('<option value="">Please Select</option>');
								});
							} 
						}
					}); 
				} else {
					swal({
						title : "Expense In Missing!",
						text  : "Please try again after refreshing the page.",
						icon  : "error"
					});
				}
			}
			function showDocumentList(row_number){
				var expense_remark = $('#expense_remark_'+row_number).val();
				if (expense_remark != "") {
					$.ajax({
						url: '/expense/get-site-documents/expense_remark/'+expense_remark,
						type: 'GET',
						success:function(data) {
							var data = JSON.parse(data);
							console.log(data);
							if (data.flag) {
								$("#expense_remark_"+row_number).html(data.option);
								$("#is_required_"+row_number).html(data.is_required);
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : "error"
								}).then(function(){
									$("#expense_remark_"+row_number).html('<option value="">Please Select</option>');
								});
							} 
						}
					}); 
				} else {
					swal({
						title : "Site Document Type is  Missing!",
						text  : "Please try again after refreshing the page.",
						icon  : "error"
					});
				}
			}
			function getSitesByPoNumber() {
				var po_number = $("#poNumber").val();
				if (po_number != "") {
					$.ajax({
						url: '/siteallocation/get-allocated-sites-by-po-number',
						type: 'POST',
						data: {po_number: po_number},
						success:function(data){
							var data = JSON.parse(data);
							console.log(data);
							if (data.flag) {
								$("#siteId").html(data.allocated_sites);
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : 'error'
								});
							}
						}
					});
				} else {
					$("#siteId").html("<option>Select Site ID</option>");
				}
			}
			function getAllocatedNatureOfWork() {
				var supervisorId = $("#siteAllocatedTo").val();
				if (supervisorId != "") {
					$.ajax({
						url: '/siteallocation/get-allocated-work-by-allocated-to-id',
						type: 'POST',
						data: {allocated_to_id: supervisorId},
						success:function(data){
							var data = JSON.parse(data);
							console.log(data);
							if (data.flag) {
								$("#nature_of_work").html(data.allocated_work_list);
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : "error"
								});
							}
						}
					});

				} else {
					swal({
						title : "Allocated To Missing!",
						text  : "Please select site allocated to.",
						icon  : "error"
					}).then(function(){
						$("#siteAllocatedTo").focus();
						$("#nature_of_work").html('<option value="">Please Select</option>');
					});
				}
			}
			function validateSiteExpenseInputData() {
				var company_id     = $("#company_id option:selected").val();
				var siteExpenseDate     = $("#siteExpenseDateOfTransfer").val();
				var poNumber            = $("#poNumber").val();
				var siteId              = $("#siteId").val();
				var siteExpenseAmount   = $("#siteExpenseTransferAmount").val();
				var siteExpenseTo       = $("#siteExpenseTransferTo").val();
				// var billNumber          = $("#billAttachmentNumber").val();
				if (company_id == "") {
					swal({
						title : "Company Missing !",
						text  : "Please Select Company.",
						icon  : "error"
					}).then(function() {
						$("#siteExpenseDateOfTransfer").focus();
					});
					return false;
				}else if (siteExpenseDate == "") {
					swal({
						title : "Transfer Date Missing !",
						text  : "Please Select Date of Transfer.",
						icon  : "error"
					}).then(function() {
						$("#siteExpenseDateOfTransfer").focus();
					});
					return false;
				} else if (poNumber == "") {
					swal({
						title : "PO Number Missing !",
						text  : "Please Select PO Number.",
						icon  : "error"
					}).then(function() {
						$("#poNumber").focus();
					});
					return false;
				} else if (siteId == "") {
					swal({
						title : "Site Missing !",
						text  : "Please Select Site ID.",
						icon  : "error"
					}).then(function() {
						$("#siteId").focus();
					});
					return false;
				} else if (siteExpenseAmount == "") {
					swal({
						title : "Expense Amount Missing !",
						text  : "Please Enter Transfer Amount.",
						icon  : "error"
					}).then(function() {
						$("#siteExpenseTransferAmount").focus();
					});
					return false;
				} else {
					var error_count = validateRowData();
    		// alert(error_count);
    		if (error_count > 0) {
    			return false;
    		}
    	}
    }
    function validateRowData() {
    	var error_count = 0;
    	var require_error_count_1 = 0;
    	$('.mandatorySelect').each(function(e) {
    		if ($(this).val() == "") {
    			$(this).siblings(".select2-container").addClass('error_box');
    			error_count += 1;
    		} else {
    			$(this).siblings(".select2-container").removeClass('error_box');
    		}
    	});
    	$('.mandatoryField').each(function(e) {
    		if ($(this).val() == "") {
    			$(this).addClass('error_box');
    			error_count += 1;
    		} else {
    			$(this).removeClass('error_box');
    		}
    	});
    	require_error_count_1 =validateUploads();
    	//alert(require_error_count_1);
    	return error_count+require_error_count_1;
    }
    function validateOfficeExpenseInputData() {
    	var company_id   = $("#company_id option:selected").val();
    	var officeExpenseDate   = $("#officeExpenseDateOfTransfer").val();
    	var officeExpenseFor    = $("#officeExpenseTransferFor").val();
    	var officeExpenseTo     = $("#officeExpenseTransferTo").val();
    	var officeExpenseAmount = $("#officeExpenseTransferAmount").val();
    	var officeExpenseRemark = $("#officeExpenseTansferRemark").val();
    	if (company_id == "") {
    		swal({
    			title : "Company Missing !",
    			text  : "Please Select Company.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseDateOfTransfer").focus();
    		});
    		return false;
    	} else if (officeExpenseDate == "") {
    		swal({
    			title : "Transfer Date Missing !",
    			text  : "Please Select Date of Transfer.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseDateOfTransfer").focus();
    		});
    		return false;
    	} else if (officeExpenseFor == "") {
    		swal({
    			title : "Transfer For Missing !",
    			text  : "Please Select Expense Transfer For.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseTransferFor").focus();
    		});
    		return false;
    	} else if (officeExpenseTo == "") {
    		swal({
    			title : "Transfer To Missing !",
    			text  : "Please Select Expense Transfer To.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseTransferTo").focus();
    		});
    		return false;
    	} else if (officeExpenseAmount == "") {
    		swal({
    			title : "Transfer Amount Missing !",
    			text  : "Please Enter Transfer Amount.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseTransferAmount").focus();
    		});
    		return false;
    	}else if(officeExpenseRemark == ""){
    		swal({
    			title : "Remark is Missing !",
    			text  : "Please Enter Remark.",
    			icon  : "error"
    		}).then(function() {
    			$("#officeExpenseTansferRemark").focus();
    		});
    		return false;
    	}
    }
    // function validateSiteExpenseInputData() {
    // 	var company_id     = $("#company_id option:selected").val();
    // 	var siteExpenseDate     = $("#siteExpenseDateOfTransfer").val();
    // 	var poNumber            = $("#poNumber").val();
    // 	var siteId              = $("#siteId").val();
    // 	var siteExpenseAmount   = $("#siteExpenseTransferAmount").val();
    // 	var siteExpenseTo       = $("#siteExpenseTransferTo").val();
    // 	var billNumber          = $("#billAttachmentNumber").val();
    // 	if (company_id == "") {
    // 		swal({
    // 			title : "Company Missing !",
    // 			text  : "Please Select Company.",
    // 			icon  : "error"
    // 		}).then(function() {
    // 			$("#siteExpenseDateOfTransfer").focus();
    // 		});
    // 		return false;
    // 	}else if (siteExpenseDate == "") {
    // 		swal({
    // 			title : "Transfer Date Missing !",
    // 			text  : "Please Select Date of Transfer.",
    // 			icon  : "error"
    // 		}).then(function() {
    // 			$("#siteExpenseDateOfTransfer").focus();
    // 		});
    // 		return false;
    // 	} else if (poNumber == "") {
    // 		swal({
    // 			title : "PO Number Missing !",
    // 			text  : "Please Select PO Number.",
    // 			icon  : "error"
    // 		}).then(function() {
    // 			$("#poNumber").focus();
    // 		});
    // 		return false;
    // 	} else if (siteId == "") {
    // 		swal({
    // 			title : "Site Missing !",
    // 			text  : "Please Select Site ID.",
    // 			icon  : "error"
    // 		}).then(function() {
    // 			$("#siteId").focus();
    // 		});
    // 		return false;
    // 	} else if (siteExpenseAmount == "") {
    // 		swal({
    // 			title : "Expense Amount Missing !",
    // 			text  : "Please Enter Transfer Amount.",
    // 			icon  : "error"
    // 		}).then(function() {
    // 			$("#siteExpenseTransferAmount").focus();
    // 		});
    // 		return false;
    // 	} else {
    // 		var error_count = validateRowData();
    // 		if (error_count > 0) {
    // 			return false;
    // 		}
    // 	}
    // }
    function validateUploads(){
    	var error_count = 0;
    	$('.is_require').each(function(e) {
    		if ($(this).val() == 1) {
    			var element_id = $(this).attr('id');
    			tempArr = element_id.split('_');
    			count = tempArr[2];
    			//alert(count);
    			if($('#bill_attachment_'+count).val() == ""){
    				swal({
    					title : "Attachment Required !",
    					text  : "Please Select File Attachment.",
    					icon  : "error"
    				}).then(function() {
    					$("bill_attachment_"+count).focus();
    				});
    				$('#bill_attachment_'+count).css('background-color','red');
    				error_count += 1;
    			}
    		} 
    	});
    	return error_count;
    }
    function checkRequired(value,row){
    	var tempArr = value.split('-');
    	$('#is_required_'+row).val(tempArr[1]);
    }
</script>