<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/kelly.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/dataviz.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/material.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/dark.js"></script>
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>


<!-- Chart code -->


<script>
	am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("officediv", am4charts.XYChart3D);

chart.data = [
<?php foreach ($this->yearlyOfficeExpense as $office_expense) { ?>
	{
		"country": "<?php echo $office_expense[0]; ?>",
		"visits": <?php echo $office_expense[1];?>
	},
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#FFFFFF");

columnTemplate.adapter.add("fill", function(fill, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

columnTemplate.adapter.add("stroke", function(stroke, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineY.strokeOpacity = 0;

}); // end am4core.ready()
</script>

<!-- Resources -->
<script>
	am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("siteexpence", am4charts.XYChart3D);

// Add data
chart.data = [
<?php foreach ($this->yearlySiteExpense as $site_expense) { ?>
	{
		"country": "<?php echo $site_expense[0]; ?>",
		"visits": <?php echo $site_expense[1];?>
	},
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

series.columns.template.fill ="#0f0";

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#0f0");

columnTemplate.adapter.add("fill", function(fill, target) {
	return chart.colors.getIndex(target.dataItem.index);
})
columnTemplate.adapter.add("stroke", function(stroke, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineX.fill = 0;


}); // end am4core.ready()
</script>

<!-- Chart code -->
<script>
	am4core.ready(function() {

// Themes begin
// am4core.useTheme(am4themes_animated);
am4core.useTheme(am4themes_kelly);
// am4core.useTheme(am4themes_dataviz);
// am4core.useTheme(am4themes_material);
// am4core.useTheme(am4themes_dark);

am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("chartdiv", am4charts.XYChart3D);
chart.data = [
<?php foreach ($this->profit_loss as $data) { ?>
	{
		"country": "<?php echo $data[2];?>",
		"year2017": <?php echo $data[1];?>,
		"year2018": <?php echo $data[0];?>
	},
<?php }?>
];
console.log(chart.data);
// Create axes
var categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.grid.template.location = 0;
categoryAxis.renderer.minGridDistance = 30;

var valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.renderer.labels.template.adapter.add("text", function(text) {
	return text ;
});

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "year2017";
series.dataFields.categoryX = "country";
series.name = "Year 2017";
series.clustered = false;
series.columns.template.tooltipText = "Expense in {category}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = 0.9;
series.columns.template.fill = am4core.color("#ADFF2F");

var series2 = chart.series.push(new am4charts.ColumnSeries3D());
series2.dataFields.valueY = "year2018";
series2.dataFields.categoryX = "country";
series2.name = "Year 2018";
series2.clustered = false;
series2.columns.template.tooltipText = "Invoice in {category}: [bold]{valueY}[/]";
series2.columns.template.fill = am4core.color("#DC143C");


}); // end am4core.ready()
</script>

<!-- HTML -->
<style type="text/css">
	#siteexpence {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	#officediv {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	#chartdiv {
		width: 100%;
		height: 500px;
	}
</style>
<div id="page-wrapper">
	<div class="main-page">
		<!-- Main content -->
		<?php if ($this->messages): ?>
			<div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
				<?php foreach ($this->messages as $message): ?>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<div class="alert_data">
						<?php echo $message ?>.
					</div>
				<?php endforeach ?>
			</div>
		<?php endif ?>
		<div class="row">
			<div class="col-lg-12"><br>
				<div class="widget-header">
					<h4 align="center"><b>Site Expense</b>
					</h4><br>
					<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
					<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
					<div class="card" id="siteexpence"></div>
				</div>
				
			</div>
			<div class="col-lg-12"><br>
				<div class="widget-header">
					<h4 align="center"><b>Office Expense</b>
					</h4><br>
					<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
					<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
					<div class="card" id="officediv"></div>
				</div>
			</div>
			<div class="col-lg-12"><br>
				<div class="widget-header">
					<h4 align="center"><b>Invoice Vs Expense</b>
					</h4><br>
					<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
					<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
					<div class="card" id="chartdiv"></div>
				</div>
				<div class="col-sm-8" style="margin-left: 35%">
					<div class="col-sm-1" style="background-color:#DC143C;height: 20px;height: 20px;"></div>
					<div class="col-sm-2">Invoice</div>
					<div class="col-sm-1" style="background-color:#ADFF2F;height: 20px;height: 20px;"></div>
					<div class="col-sm-2">Expense</div></br></br>
				</div>
			</div>
		</div>