  <?php
  $user_list = $this->user_list;
  $record = $this->paginator; 
  $totalrec = $this->totalrec;

  ?>  
  <style type="text/css"> 
  #scroll-id {
    width: 600px;
    overflow-x: scroll;
  }

  #submit {
    background-color: lightgreen;
    border-radius: 5px;
    font-family: cambria;
    font-weight: bold;
    font-size: 15px;
  }

  #close {
    background-color: red;
    border-radius: 5px;
    font-family: cambria;
    font-weight: bold;
    font-size: 15px;
  }

  #fa_plus {
    cursor: pointer;
    margin-left: 20%;
    font-size: 20px;
  }

  #fa_update {
    cursor: pointer;
    margin-left: 20%;
    font-size: 1.3em;
  }
</style>
<div class="table-responsive mt-1" id="expense-list">
  <?php $user = new Application_Model_User();  ?> 

  <b>Total Site Expenses : <?php echo number_format($this->sum); ?></b>

  <div id="leftpag">
    <?php if($totalrec > $this->perPage) { 
      echo $this->paginationControl($this->paginator, 'Sliding', 'expense-pagination.phtml'); 
    } ?>  
  </div>

  <table class="table table-bordered table2excel" id="scroll-id">
   <thead>
    <tr>
      <th style=" white-space:nowrap;">
        # <a href="javascript:void(0)" 
        onclick="getPage('<?php echo $this->totalnum; ?>',
        '<?php if($this->id_order){ echo $this->id_order; }else{ echo 'desc';} ?>','id')" >
        <?php if($this->id_order == 'desc' && $this->params['type'] == 'id'){ ?>
          <img src="/img/asc.png" style="height:20px;" /><?php }
          elseif($this->id_order == 'asc' && $this->params['type'] == 'id'){ ?>
            <img src="/img/desc.png" style="height:20px;" /><?php }
            else{?><img src="/img/desc.png" style="height:20px;" /><?php }?>
          </a></th>
          <th style=" white-space:nowrap;">PO</th>
          <!--<th style=" white-space:nowrap;">Description</th>-->
          <th style=" white-space:nowrap;">Order Date</th>
          <th style=" white-space:nowrap;">Amount</th>
          <th style=" white-space:nowrap;">Inclusive Tax</th>
          <th style=" white-space:nowrap;">Exclusive Tax</th>
          <th style=" white-space:nowrap;">Tax Amount</th>
          <th style=" white-space:nowrap;">Revision</th>
          <th style=" white-space:nowrap;">Status</th>

          <th style=" white-space:nowrap;">Site ID</th>
          <th style=" white-space:nowrap;">Last Fund Transferred Date</th>
          <th style=" white-space:nowrap;">Expenses</th>
          <th style=" white-space:nowrap;">Assigned To</th>
          <th style=" white-space:nowrap;">Invoice No.</th>
          <th style=" white-space:nowrap;">Invoice Value</th>
          <th style=" white-space:nowrap;">Margin</th>
          <th style=" white-space:nowrap;">Action</th>
        </tr>
      </thead>

      <tbody>
        <?php 
        if($totalrec){ 
          $totalnum = $this->totalnum?$this->totalnum:1;
          $istart = ($totalnum-1) * 10;
          $i=$istart;
          foreach($record as $expense){ ?>
            <tr>
              <td style=" white-space:nowrap;"><?php echo $i+1;?>.</td>
              <td style=" white-space:nowrap;"><?php echo $expense['po_number']; ?></td>
              <!--<td style=" min-width:220px;"><?php echo $expense['description']; ?></td>-->
              <td style=" white-space:nowrap;"><?php echo $expense['order_date']; ?></td> 
              <td style=" white-space:nowrap;"><?php echo $expense['amount']; ?>ttt</td>
              <td style=" white-space:nowrap;"><?php echo $expense['inclusive_tax']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $expense['exclusive_tax']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $expense['tax_amount']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $expense['rev']; ?></td>
              <td style=" min-width:110px;"><?php echo $expense['status']; ?></td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;"> 
                    <?php echo $value; ?>
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;"> 
                    <?php if($user->getLastFundDate($expense['po_number'],$value) != ''){ ?>
                      <?php echo date('d/m/Y', strtotime( $user->getLastFundDate($expense['po_number'],$value) ) ); ?>
                    <?php }else { echo "-"; } ?>
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;">
                    <?php if( $user->getExpensesByPoSite($expense['po_number'],$value) !='' ){ ?>
                      <a href="javascript:void(0)" id="<php echo $i+1; ?>" 
                        onClick="showDetailedExpenseList('<?php echo $expense['po_number']; ?>','<?php echo $value; ?>')">
                        <?php echo $user->getExpensesByPoSite($expense['po_number'],$value); ?>
                      </a>
                    <?php }else echo "-"; ?> 
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;">
                    <?php if( $user->assignedTo($expense['po_number'],$value) !='' ){ ?>
                      <?php echo $user->assignedTo($expense['po_number'],$value); ?>
                    <?php }else echo "-"; ?> 
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;"> 
                    <?php if ($user->getInvoiceNumberByPoSite($expense['po_number'],$value) != '') {?>
                      <?php echo $user->getInvoiceNumberByPoSite($expense['po_number'],$value);?>
                    <?php } else  echo "-"; ?>
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;">
                    <?php if ($user->getInvoiceValueByPoSite($expense['po_number'],$value) != '') { ?>
                      <?php echo $user->getInvoiceValueByPoSite($expense['po_number'],$value);?>
                    <?php } else  echo "-"; ?> 
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;">
                    <?php if ($user->getMarginByPoSite($expense['po_number'],$value) != '') {?>
                      <?php echo $user->getMarginByPoSite($expense['po_number'],$value);?>
                    <?php } else  echo "-"; ?> 
                  </div>
                <?php } ?>
              </td>

              <td style=" white-space:nowrap;">
                <?php foreach ($expense['site_ids'] as $key => $value) { ?>
                  <div class="col-md-12" style="border-bottom:1px solid grey; height:28.5px;">
                    <?php if( $user->getExpensesByPoSite($expense['po_number'],$value) !='' && $user->getInvoiceValueByPoSite($expense['po_number'],$value) ==''  && $user->getInvoiceNumberByPoSite($expense['po_number'],$value) == '') { ?>

                      <i class="fa fa-plus fa-2x" id="fa_plus" title="Add Invoice Details" onclick="showAddForm('<?php echo $expense['po_number']; ?>', '<?php echo $value ?>', '<?php echo $user->getExpensesByPoSite($expense['po_number'],$value); ?>', '<?php echo $this->totalnum;?>', '<?php echo $ponumber;?>', '<?php echo $siteid;?>', '<?php echo $order;?>', '1')"></i>
                    <?php } else if ($user->getExpensesByPoSite($expense['po_number'],$value) !='' && $user->getInvoiceValueByPoSite($expense['po_number'],$value) !=''  && $user->getInvoiceNumberByPoSite($expense['po_number'],$value) != '') {?>

                      <i class="fa fa-edit fa-2x" id="fa_update" title="Update Invoice Details" onclick="showUpdateForm('<?php echo $expense['po_number']; ?>', '<?php echo $value ?>', '<?php echo $user->getExpensesByPoSite($expense['po_number'],$value); ?>', '<?php echo $user->getInvoiceNumberByPoSite($expense['po_number'],$value);?>', '<?php echo $user->getInvoiceValueByPoSite($expense['po_number'],$value);?>', '<?php echo $this->totalnum;?>', '<?php echo $ponumber;?>', '<?php echo $siteid;?>', '<?php echo $order;?>', '2')"></i>
                    <?php } else echo '-'; ?>
                  </div>
                <?php } ?>
              </td>

            </tr>
            <?php  $i++;} } else{  ?>
              <tr><td colspan="7">
                <p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
              <?php } ?>
            </tbody>
          </table>

          <div id="leftpag">
            <?php if($totalrec > $this->perPage) { 
              echo $this->paginationControl($this->paginator, 'Sliding', 'expense-pagination.phtml'); 
            } ?>  
          </div>
        </div>


        
        <!-- <div id="invoiceModal" class="modal fade" role="dialog">
          <div class="modal-dialog modal-lg animated rollIn" style="max-width: 400px;">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="title"></h4>
              </div>
              <div class="modal-body">
                <form action="" enctype="multipart/form-data" id="invoiceForm">
                  <input type="hidden" name="expense_po_number" id="expense_po_number">
                  <input type="hidden" name="expense_site_id" id="expense_site_id">
                  <input type="hidden" name="total_expense" id="total_expense">
                  <input type="hidden" name="page" id="page">
                  <input type="hidden" name="ponumber" id="ponumber">
                  <input type="hidden" name="siteid" id="siteid">
                  <input type="hidden" name="order" id="order">
                  <input type="hidden" name="type" id="type">

                  <div class="form-group">
                    <label for="">Invoice Number:<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" name="invoice_number" id="invoice_number" placeholder="Enter Invoice Number" required=""><span class="error" id="error_invoice" style="color: red; display: none;">Field is mandatory</span>
                  </div>

                  <div class="form-group">
                    <label for="">Invoice Value:<span style="color: red;">*</span></label>
                    <input type="text" class="form-control" name="invoice_value" id="invoice_value" placeholder="Enter Invoice Value" required=""><span class="error" id="error_value" style="color: red; display: none;">Field is mandatory</span>
                  </div>

                  <div class="form-group">
                    <label for="">Invoice Document:<span style="color: red;">*</span></label>
                    <input type="file" class="form-control" name="invoice_document" id="invoice_document" required=""><span class="error" id="error_invoice_doc" style="color: red; display: none;">Field is mandatory</span>
                  </div>

                  <div class="form-group">
                    <label for="">Bill Document:<span style="color: red;">*</span></label>
                    <input type="file" class="form-control" name="bill_document" id="bill_document" required=""><span class="error" id="error_bill_doc" style="color: red; display: none;">Field is mandatory</span>
                  </div>

                  <div class="form-group">
                    <button class="btn btn-default" data-dismiss="modal" id="submit">Submit</button>
                  </div>
                </form>
              </div> 
            </div>
          </div> 
        </div> 

        <script type="text/javascript">

          function showAddForm(po_nmber, site_id, expense, page, ponumber, siteid, order, type) {
            var title = "ADD INVOICE DETAILS";
            $('.error').hide();
            $('#title').text(title);
            $('#total_expense').val(expense);
            $('#expense_po_number').val(po_nmber);
            $('#expense_site_id').val(site_id);
            $('#page').val(page);
            $('#ponumber').val(ponumber);
            $('#siteid').val(siteid);
            $('#order').val(order);
            $('#type').val(type);
            $('#invoiceModal').modal('toggle');
          }

          function showUpdateForm(po_nmber, site_id, expense, invoice_no, invoice_value, page, ponumber, siteid, order, type) {
            var title = "UPDATE INVOICE DETAILS";
            $('.error').hide();
            $('#title').text(title);
            $('#total_expense').val(expense);
            $('#expense_po_number').val(po_nmber);
            $('#expense_site_id').val(site_id);
            $('#invoice_number').val(invoice_no);
            $('#invoice_value').val(invoice_value);
            $('#page').val(page);
            $('#ponumber').val(ponumber);
            $('#siteid').val(siteid);
            $('#order').val(order);
            $('#type').val(type);
            $('#invoiceModal').modal('toggle');
          }


          $(document).ready(function() {
            $(document).on('click', '#submit', function(event) {
              event.preventDefault();
              var invoice_document = $('#invoice_document').prop('files')[0];   
              var bill_document = $('#bill_document').prop('files')[0]; 
              var form_data = new FormData();                  
              form_data.append('expense', $("#total_expense").val());
              form_data.append('po_no', $("#expense_po_number").val());
              form_data.append('site_id', $("#expense_site_id").val());
              form_data.append('invoice_no', $("#invoice_number").val());
              form_data.append('invoice_val', $("#invoice_value").val());
              form_data.append('page', $("#page").val());
              form_data.append('ponumber', $("#ponumber").val());
              form_data.append('siteid', $("#siteid").val());
              form_data.append('order', $("#order").val());
              form_data.append('type', $("#type").val());
              form_data.append('invoice_document', invoice_document);
              form_data.append('bill_document', bill_document);
              console.log(form_data);
              var id    = 'expense-list';
              $("#"+id).html('<div class="loading">Loading&#8230;</div>');
              $.ajax({
                url: '/expense/expense-list', 
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,                         
                type: 'post',
                success: function(responseText) {
                  alert("Invoice Details has been added successfully.");
                  $("#"+id).html(responseText);
                  $("#"+id).find("script").each(function(i) {
                    eval($(this).text());

                  });
                }
              });

            });
          });
        </script> -->
