
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
	.select2.select2-container {
		width: 100% !important;
	}
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
		padding: 10px 15px 10px 15px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 18px;
	}  
	.formDiv {
		border: 5px solid #b0d5ea;
		border-radius: 5px;
		padding: 10px 10px 10px 10px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
	.error_box{
		border: 1px solid red;
		border-radius: 4px;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params)): ?>
			<?php if (isset($this->params['success'])){ ?>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Success !</strong>&nbsp; <?php echo $this->params["success"]; ?>
				</div>
			<?php } else if (isset($this->params['error'])) { ?>
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Fund Transfers Details</h3>
					</div>

					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<a <?php if (isset($this->params['expenseType']) && $this->params['expenseType'] == "Office Expense") { ?>
							href="/expense/office-expenses" <?php } else { ?>href="/expense" <?php } ?> class="btn btn-success pull-right">Back</a>
						</div>
					</div>
				</div>
				<div class="panel panel-body">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
							</div>
						</div>
						<div class="row">

							

							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="transferTypeSelect">Transfer Type<span id="mandatory">*</span></label>
								<select id="transferTypeSelect" class="form-control select2">
									<option value="">Please Select</option>
									<option value="2">Site Fund Transfers</option>
									<option value="1">Office Fund Transfers</option>
								</select>
							</div>
						</div>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 formDiv" style="display: none;">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
		<div class="modal-dialog" style="width: 80%">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 class="modal-title">Add New PO</h3>
				</div>
				<div class="modal-body">
					<form id="addPoAndSitesForm">
						<div class="row">

							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="state_id">State<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="state_id" id="state_id" onchange="getClientMasterList()">
									<option value="">Select State</option>
									<?php foreach ($this->stateList as $state): ?>
										<option value="<?php echo $state['id']; ?>"><?php echo $state['state_name']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="client_id">Client Name<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="client_id" id="client_id">
									<option value="">Select Client</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_type">PO Type<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="po_type" id="po_type">
									<option value="">Select PO Type</option>
									<option value="Standard PO">Standard PO</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_amount">PO Amount<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="po_amount" id="po_amount" oninput="this.value = this.value.replace(/[^0-9]/g,'')" required="">
							</div>


						</div>
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_number">PO Number<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="po_number" id="po_number" oninput="this.value = this.value.replace(/[^A-Z / a-z 0-9]/g,'')">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_date">PO Date<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control datepicker" name="po_date" id="po_date" readonly="">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="revision">Revision :</label>
								<input type="text" class="form-control" name="revision" id="revision" oninput="this.value = this.value.replace(/[^0-9]/g,'')">
							</div>
						</div>
						<br>
						<h3 align="center"><u>Site Details</u></h3>
						<br>

						<div class="row" id="productsServicesDiv" style="overflow: auto; padding: 8px 15px;">
							<table class="table table-bordered" id="siteDetailsTable">
								<thead>
									<tr>
										<th style="text-align: center;">Site ID <span id="mandatory">*</span></th>
										<th style="text-align: center;">Site Name</th>
										<th style="text-align: center;">SO Number</th>
										<th style="text-align: center;">Infratel ID</th>
										<th style="text-align: center;">Location <span id="mandatory">*</span></th>
										<th style="text-align: center;">Latitude</th>
										<th style="text-align: center;">Longitude</th>
										<th style="text-align: center;">Work Type <span id="mandatory">*</span></th>
										<th style="text-align: center;">Action</th>
									</tr>
								</thead>
								<tbody>
									<tr id="row_2">
										<td width="10%">
											<input type="text" name="site_id" id="site_id_2" class="form-control" onkeyup="getInfratelId(2,this.value)">
										</td>

										<td>
											<input type="text" name="site_name" id="site_name_2" class="form-control">
										</td>

										<td>
											<input type="text" name="so_number" id="so_number_2" class="form-control">
										</td>
										<td>
											<input type="text" class="form-control" name="infratel_id" id="infratel_id_2">
										</td>
										<td>
											<input type="text" class="form-control" name="location" id="location_2">
										</td>
										<td>
											<input type="text" class="form-control" name="latitude" id="latitude_2">
										</td>
										<td>
											<input type="text" class="form-control" name="longitude" id="longitude_2">
										</td>
										<td width="25%">
											<input type="text" class="form-control" name="work_type" id="work_type_2" >
										</td>
										<td></td>
									</tr>
								</tbody>
							</table>

						</div>
						<br clear="all">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<button  class="btn btn-primary pull-right" id="addPoAndSitesButton">Add Sites</button>
							</div>
						</div>
					</form>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>
	<div class="modal modal-success fade" id="myUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
		<div class="modal-dialog" style="width: 60%">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h3 class="modal-title">Add New Payee</h3>
				</div>
				<div class="modal-body">
					<form id="addPayeeForm">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="name">Name<span id="mandatory">*</span> :</label>
								<input type="text" class="form-control" name="name" id="name" required="">
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="mobile">Mobile No. :</label>
								<input type="text" class="form-control" name="mobile" id="mobile" >
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="mobile">Address. :</label>
								<input type="text" class="form-control" name="address" id="address" >							
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3" style="margin-top: 20px;">
								<button  class="btn btn-primary" id="addPayee">Add Payee</button>
							</div>
						</div>
					</form>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>
	<script>
		$(document).ready(function() {
			$(".select2").select2();
			$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
			$("#transferTypeSelect").change(function(event) {
				event.preventDefault();
				var transferType = $("#transferTypeSelect").val();
				var transferTypeTextValue = $("#transferTypeSelect option:selected").text();
				if (transferType != "") {
					if (transferTypeTextValue == "Site Fund Transfers") {
						$.ajax({
							url: '/expense/site-fund-form/transfer_type/'+transferType,
							type: 'GET',
							success:function (data) {
								$(".formDiv").html(data);
							}
						});
						$(".formDiv").show();
					} else if (transferTypeTextValue == "Office Fund Transfers") {
						$.ajax({
							url: '/expense/office-fund-form/transfer_type/'+transferType,
							type: 'GET',
							success:function (data) {
								$(".formDiv").html(data);
							}
						});
						$(".formDiv").show();
					} 
				} else {
					$(".formDiv").hide();
				}
			});
		}); 

		function getSitesByPoNumber() {
			var po_number = $("#poNumber").val();
			if (po_number != "") {
				if(po_number == "new"){
					$.ajax({
						url: '/expense/add-new-po',
						type: 'GET',
						success:function(){
							$("#myModal").show();
							$("#myModal").modal('toggle');
						}
					});

				}else{
					$.ajax({
						url: '/siteallocation/get-allocated-sites-by-po-number',
						type: 'POST',
						data: {po_number: po_number},
						success:function(data){
							var data = JSON.parse(data);
							console.log(data);
							if (data.flag) {
								$("#siteId").html(data.allocated_sites);
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : 'error'
								});
							}
						}
					});
				}
			} else {
				$("#siteId").html("<option>Select Site ID</option>");
			}
		}
		function getAllocatedNatureOfWork() {
			var supervisorId = $("#siteAllocatedTo").val();
			if (supervisorId != "") {
				$.ajax({
					url: '/siteallocation/get-allocated-work-by-allocated-to-id',
					type: 'POST',
					data: {allocated_to_id: supervisorId},
					success:function(data){
						var data = JSON.parse(data);
						console.log(data);
						if (data.flag) {
							$("#nature_of_work").html(data.allocated_work_list);
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
						}
					}
				});

			} else {
				swal({
					title : "Allocated To Missing!",
					text  : "Please select site allocated to.",
					icon  : "error"
				}).then(function(){
					$("#siteAllocatedTo").focus();
					$("#nature_of_work").html('<option value="">Please Select</option>');
				});
			}
		}
		function validateSiteExpenseInputData() {
			var company_id     = $("#company_id option:selected").val();
			var siteExpenseDate     = $("#siteExpenseDateOfTransfer").val();
			var poNumber            = $("#poNumber").val();
			var siteId              = $("#siteId").val();
			var siteExpenseAmount   = $("#siteExpenseTransferAmount").val();
			var siteExpenseTo       = $("#siteExpenseTransferTo").val();
			var billNumber          = $("#billAttachmentNumber").val();
			if (company_id == "") {
				swal({
					title : "Company Missing !",
					text  : "Please Select Company.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseDateOfTransfer").focus();
				});
				return false;
			}else if (siteExpenseDate == "") {
				swal({
					title : "Transfer Date Missing !",
					text  : "Please Select Date of Transfer.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseDateOfTransfer").focus();
				});
				return false;
			} else if (poNumber == "") {
				swal({
					title : "PO Number Missing !",
					text  : "Please Select PO Number.",
					icon  : "error"
				}).then(function() {
					$("#poNumber").focus();
				});
				return false;
			} else if (siteId == "") {
				swal({
					title : "Site Missing !",
					text  : "Please Select Site ID.",
					icon  : "error"
				}).then(function() {
					$("#siteId").focus();
				});
				return false;
			} else if (siteExpenseAmount == "") {
				swal({
					title : "Expense Amount Missing !",
					text  : "Please Enter Transfer Amount.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseTransferAmount").focus();
				});
				return false;
			} 
		}
		function getClientMasterList() {
			var state_id = $("#state_id").val();
			if (state_id == "") {
				swal({
					title : "State Missing!",
					text  : "Please select state name.",
					icon  : "error"
				}).then(function(){
					$("#state_id").select2('open');
				});
				$("#client_id").empty();
				$("#client_id").append('<option value="">Select Client</option>');
				return false;
			} else {
				$("#loading-bg").show();
				$.ajax({
					url: '/master/get-client-details',
					type: 'POST',
					data: {state_id: state_id},
					success:function(data){
						var data = JSON.parse(data);
						$("#loading-bg").hide();
						console.log(data);
						if (data.flag) {
							$("#client_id").empty();	
							$("#client_id").append('<option value="">Select Client</option>');	
							$.each(data.clientDetails, function(index, val) {
								$("#client_id").append('<option value="'+val.id+'">'+val.client_name+'</option>');	
							});
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
							$("#client_id").empty();	
							$("#client_id").append('<option value="">Select Client</option>');	
						}
					}
				});

			}
		}
		function getInfratelId(count,site_id){
			if(site_id != ""){
				$.ajax({
					url: '/manage-po-site/get-site-matrix-data/site_id/'+site_id,
					type: 'GET',
					success:function(data){
						console.log(data);
						if(data){
							var data = JSON.parse(data);
							$('#infratel_id_'+count).val(data.infratel_id);
							$('#site_name_'+count).val(data.zone);
							$('#location_'+count).val(data.zone);
						}
					}
				});
			}
		}

		function checkInputData() {
			if ($("#state_id").val() == "") {
				swal({
					title : "State Missing!",
					text  : "Please select state name.",
					icon  : "error"
				}).then(function(){
					$("#state_id").select2('open');
				});
				return false;
			} else if ($("#client_id").val() == "") {
				swal({
					title : "Client Missing!",
					text  : "Please select client name.",
					icon  : "error"
				}).then(function(){
					$("#client_id").select2('open');
				});
				return false;
			} else if ($("#po_type").val() == "") {
				swal({
					title : "PO Type Missing!",
					text  : "Please select PO type.",
					icon  : "error"
				}).then(function(){
					$("#po_type").select2('open');
				});
				return false;
			}  else if ($("#po_amount").val() == "") {
				swal({
					title : "PO Amount Missing!",
					text  : "Please enter PO Amount.",
					icon  : "error"
				}).then(function(){
					$("#po_amount").focus();
				});
				return false;
			} else if ($("#po_number").val() == "") {
				swal({
					title : "PO Number Missing!",
					text  : "Please enter PO number.",
					icon  : "error"
				}).then(function(){
					$("#po_number").focus();
				});
				return false;
			} else if ($("#po_date").val() == "") {
				swal({
					title : "PO Date Missing!",
					text  : "Please select PO date.",
					icon  : "error"
				}).then(function(){
					$("#po_date").focus();
				});
				return false;
			} 

			else {
				return true;
			}
		}
		$("#addPoAndSitesButton").click(function(event) {
			event.preventDefault();
			if(!checkInputData()){
				return false;
			} else {
				$("#loading-bg").show();
				$.ajax({
					url: '/expense/add-new-po',
					type: 'POST',
					data: $("#addPoAndSitesForm").serialize(),
					success:function(data){
						var data = JSON.parse(data);
						$("#loading-bg").hide();
						console.log(data.options);
						if (data.flag) {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "success"
							}).then(function(){
								$("#myModal").modal('toggle');
								result_1 = data.options;
								result_2 = data.sites;
								$("#poNumber").html(result_1);
								$("#siteId").html(result_2);

							});
						} else {
							swal({
								title : data.title,
								text  : data.message,
								icon  : "error"
							});
							return false;
						}
					}
				});
			}
		});
		$("#addPayee").click(function(event) {
			event.preventDefault();
			$("#loading-bg").show();
			$.ajax({
				url: '/expense/add-new-payee',
				type: 'POST',
				data: $("#addPayeeForm").serialize(),
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data.options);
					if (data.flag) {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "success"
						}).then(function(){
							$("#myUserModal").modal('toggle');
							result_3 = data.options;
							$("#amountTransferTo").html(result_3);
						});
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						return false;
					}
				}
			});
			
		});
		function validateSiteExpenseInputData() {
			var company_id     = $("#company_id option:selected").val();
			var siteExpenseDate     = $("#siteExpenseDateOfTransfer").val();
			var poNumber            = $("#poNumber").val();
			var siteId              = $("#siteId").val();
			var siteExpenseAmount   = $("#siteExpenseTransferAmount").val();
			var siteExpenseTo       = $("#siteExpenseTransferTo").val();
			var billNumber          = $("#billAttachmentNumber").val();
			if (company_id == "") {
				swal({
					title : "Company Missing !",
					text  : "Please Select Company.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseDateOfTransfer").focus();
				});
				return false;
			}else if (siteExpenseDate == "") {
				swal({
					title : "Transfer Date Missing !",
					text  : "Please Select Date of Transfer.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseDateOfTransfer").focus();
				});
				return false;
			} else if (poNumber == "") {
				swal({
					title : "PO Number Missing !",
					text  : "Please Select PO Number.",
					icon  : "error"
				}).then(function() {
					$("#poNumber").focus();
				});
				return false;
			} else if (siteId == "") {
				swal({
					title : "Site Missing !",
					text  : "Please Select Site ID.",
					icon  : "error"
				}).then(function() {
					$("#siteId").focus();
				});
				return false;
			} else if (siteExpenseAmount == "") {
				swal({
					title : "Expense Amount Missing !",
					text  : "Please Enter Transfer Amount.",
					icon  : "error"
				}).then(function() {
					$("#siteExpenseTransferAmount").focus();
				});
				return false;
			} else {
				var error_count = validateRowData();
				if (error_count > 0) {
					return false;
				}
			}
		}

		function otherPayeeForm(){
			var payee = $('#amountTransferTo').val();
			if(payee == 'payee'){
				$.ajax({
					url: '/expense/add-new-payee',
					type: 'GET',
					success:function(){
						$("#myUserModal").show();
						$("#myUserModal").modal('toggle');
					}
				});

			}
		}
	</script>