<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$user               = new Application_Model_User;
?>

<style type="text/css">
	.table th ,   .table td , .table div{
		padding: 3px;
		text-align: left;
	} 
	#scroll-id {
		width: 600px;
	}
	@media print{
		.noprint {display:none !important; }
	}
	a:hover {
		text-decoration: underline !important;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Fund Transfer Report&nbsp;<span class="badge" style="font-size: 20px;"> <i class="fa fa-rupee"></i> <?php echo $this->total_amount['total_amount']; ?></span>
					<div class="pull-right">
						<a href="/expense/fund-transfer" class="btn btn-success">Add Fund Transfer</a>
						
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="row">
						<form action="" method="" role="form" >

						</form>
					</div>
					<div class="row">
						<form action="" method="POST" role="form" onsubmit="return validateForm()">
							<div class="col-md-2">
								<div class="form-group">
									<!-- <label for="">From date</label> -->
									<input type="text" class="form-control datepicker " name="from_date" id="from_date" placeholder="From Date" readonly="" value="<?php if(isset($this->from_date)){ echo $this->from_date;} ?>" >
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<!-- <label for="">To date</label> -->
									<input type="text" class="form-control datepicker " name="to_date" id="to_date" placeholder="To Date" readonly="" value="<?php if(isset($this->to_date)){ echo $this->to_date; } ?>">
								</div>
							</div>

							<div class="col-md-1" style="padding: 0px;margin: 0px;">
								<div class="form-group" style="padding: 0px;margin: 0px;">
									<button type="submit" class="btn btn-primary">Submit</button>
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<a href="/expense/office-expenses" class="btn btn-info">Reset</a>
								</div>
							</div>
						</form>
						
					</div>

					<div class="table-responsive" id="user-list">
						<table class="display" width="100%" id="officeExpenseDetailsTable">
							<thead>
								<th>#</th>
								<th style="white-space: nowrap;">Company</th>
								<th style="white-space: nowrap;">Transfer Date</th>
								<th style="white-space: nowrap;">Transfered To</th>
								<th style="white-space: nowrap;">Amount</th>
								<th style="white-space: nowrap;">Remark</th>
								<th style="white-space: nowrap;">PO Number</th>
								<th style="white-space: nowrap;">Site Id</th>
								<th>Bank Account</th>
								<th>Payment Mode</th>
								<th style="white-space: nowrap;">Recommended By</th>
								<th style="white-space: nowrap;">Approved By</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php if($this->fundDetailsResult){ 
									$i = 1; 
									foreach($this->fundDetailsResult as $fundDetailsResult){ ?>
										<tr>
											<td style="white-space: nowrap;"><?php echo $i; ?></td>
											<td style="white-space: nowrap;">
												<?php echo ucwords(strtolower($fundDetailsResult['company']));?>
											</td>
											<td style="white-space: nowrap;">
												<?php echo date('d/m/Y', strtotime($fundDetailsResult['transfer_date'])); ?>
											</td>
											<td style="white-space: nowrap;">
												<a href="javascript:void(0)" title="View Details" onclick="showTransferDetails(<?php echo $fundDetailsResult['transfer_to']; ?>,'<?php echo $fundDetailsResult['allocation_type']?>')"><?php echo ucwords(strtolower($fundDetailsResult['transfer_name']));?></a>
											</td>
											<td style="white-space: nowrap;">
												<?php echo $fundDetailsResult['amount'];?>
											</td>
											<td style="white-space: nowrap;">
												<?php if ($fundDetailsResult['remark']) { echo $fundDetailsResult['remark']; } else { echo "-"; } ?>
											</td>
											<td style="white-space: nowrap;"><?php  echo $fundDetailsResult['po_no']?></td>
											<td style="white-space: nowrap;"><?php  echo $fundDetailsResult['site_id']?></td>
											<td><?php echo $fundDetailsResult['bank_name']; ?><br><?php echo $fundDetailsResult['bank_account_number']; ?></td>
											<td><?php echo $fundDetailsResult['payment_mode']; ?></td>
											<td style="white-space: nowrap;">
												<?php echo $fundDetailsResult['recommended_name'];?>
											</td>
											<td style="white-space: nowrap;">
												<?php echo $fundDetailsResult['approved_by'];?>
											</td>
											<td style="white-space: nowrap;">
												<a href="javascript:void(0)" class="fa fa-pencil" title="View Details" onclick="showExpenseAmountDetails(<?php echo $fundDetailsResult['id']; ?>)"></a>
											</td>
										</tr>
										<?php $i++; }}?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	</div>

	<script>
		$(document).ready(function() {

			$(".datepicker").datepicker({ 
				dateFormat: "dd/mm/yy", 
				changeYear:true, 
				changeMonth:true 
			});
			$("#officeExpenseDetailsTable").DataTable({
				dom: 'Bfrtip',
				buttons: [
				'excelHtml5'
				]	
			});
		});

		function showExpenseAmountDetails(transfer_id) {
			if (transfer_id == "") {
				swal({
					title : "Expense ID Missing!",
					text  : "Please try after refreshing the page.",
					icon  : "error"
				});
			} else {
				$.ajax({
					url: '/expense/get-fund-amount-details',
					type: 'POST',
					data: {transfer_id: transfer_id},
					success:function(data){
						$("#myModal").html(data);
						$("#myModal").modal('toggle');
					}
				});
			}
		}

		function validateForm() {
			if ($('#from_date').val() == "") {
				swal({
					title : "From Date Missing!",
					text  : "Click from date input box and select date",
					icon  : "error"
				});
				return false
			}else if ($('#to_date').val() == "") {
				swal({
					title : "To Date Missing!",
					text  : "Click to date input box and select date",
					icon  : "error"
				});
				return false
			}  else {
				return true;
			}
		}

		function viewAttachments(po_no){
			$.ajax({
				url: '/expense/get-attach-documents-details',
				type: 'POST',
				data: {po_no: po_no},
				success:function(data){
					$('#myModal').html(data);
					$('#myModal').modal('toggle');
				}
			});
		}
		function showTransferDetails(transfer_to, transfer_to_type){
			$.ajax({
				url: '/expense/get-user-fund-transfer-details',
				type: 'POST',
				data: {transfer_to: transfer_to,transfer_to_type:transfer_to_type},
				success:function(data){
					$('#myModal').html(data);
					$('#myModal').modal('toggle');
				}
			});
		} 
	</script>

