	<div class="modal-dialog" style="width: 60%; max-height: 60%;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Expense Details</h3>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>#</th>
										<th>Expense In</th>
										<th>Expense For</th>
										<th>Amount</th>
										<th>Remark</th>
										<th>Expense Date</th>
										<th>Attachment</th>
									</tr>
								</thead>
								<tbody>
									<?php if ($this->expenseDetails): ?>
										<?php $i = 1;
										foreach ($this->expenseDetails as $expense): ?>
											<tr>
												<td><?php echo $i; ?></td>
												<td><?php echo $expense['expense_in']; ?></td>
												<td><?php echo $expense['expense_for']; ?></td>
												<td><?php echo $expense['spent_amount']; ?></td>
												<td><?php echo $expense['spent_remark']; ?></td>
												<td><?php echo date('d/m/Y', strtotime($expense['expense_date']));  ?></td>
												<td><?php if ($expense['attachment_path'] != "" || $expense['attachment_path'] != NULL): ?>
												<a href="<?php echo $expense['attachment_path']; ?>" target="_blank"><i class="fa fa-eye"></i></a><?php endif ?></td>
											</tr>
											<?php $i++; endforeach ?>
										<?php endif ?>
										<tr>
										<td></td>		
										<td></td>		
										<td rowspan="3">Total :</td>		
										<td><span style="color:red;"><b><?php echo $this->expenseTotal ?></b></span></td>		
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>