


<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">Fund Amount Details</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="table-responsive">
						<table class="table table-bordered" style="width: 100%;" id="dtBasicExample">
							<thead>
								<tr>
									<th>Name</th>
									<th>Credit</th>
									<th>Debit</th>
									<th>Balance</th>
									<th>Transfer Date</th>
								</tr>
							</thead>
							<tbody>
								<?php if ($this->UserFunds): ?>
									<?php foreach ($this->UserFunds as $UserFunds): ?>
										<tr>
											<td><?php echo $UserFunds['user_name']; ?></td>
											<td><?php echo $UserFunds['credit']; ?></td>
											<td><?php echo $UserFunds['debit']; ?></td>
											<td><?php echo $UserFunds['balance']; ?></td>
											<td><?php echo date('d-m-Y',strtotime($UserFunds['created']));?></td>
										</tr>
									<?php endforeach ?>
								<?php endif ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$('#dtBasicExample').DataTable();
		$('.dataTables_length').addClass('bs-select');
	});
</script>