
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">Fund Amount Details</h3>
		</div>
		<div class="modal-body">
			<form action="/expense/fund-transfer-reports" method="post" role="form">
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for="">Transfer Date :</label>
					<input type="text" class="form-control datepicker" name="transfer_date" id="transfer_date"  value="<?php  echo date('d-m-Y',strtotime($this->expenseDetails['transfer_date'])); ?>">
					<input type="hidden" name="id" id="id"  value="<?php  echo $this->expenseDetails['id']; ?>">
				</div>
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for="">Transfered Amount:</label>
					<input type="text" class="form-control"name="amount" value="<?php echo $this->expenseDetails['amount']; ?>" >
				</div>
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for=""></label><br>
					<input type="submit" class="btn btn-primary">
				</div>

			</form>
		</div>
		<div class="modal-footer">
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true, maxDate:0 });
	});
</script>