
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">Expense Amount Details</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for="">Transfer Date :</label>
					<input type="text" class="form-control" value="<?php echo date('d/m/Y', strtotime($this->expenseDetails['transfer_date'])); ?>" readonly>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for="">Transfered To :</label>
					<input type="text" class="form-control" value="<?php echo ucwords(strtolower($this->expenseDetails['name'])); ?>" readonly>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
					<label for="">Transfered Amount:</label>
					<input type="text" class="form-control" value="<?php echo $this->expenseDetails['amount']; ?>" readonly>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="table-responsive">
						<table class="table table-bordered" style="width: 100%;">
							<thead>
								<tr>
									<th>Expense In</th>
									<th>Expense For</th>
									<th>Spent Amount</th>
									<th>Spent Remarks</th>
								</tr>
							</thead>
							<tbody>
								<?php if ($this->expenseAmountDetails): ?>
									<?php foreach ($this->expenseAmountDetails as $expenseDetails): ?>
										<tr>
											<td><?php echo $expenseDetails['expense_in_type']; ?></td>
											<td><?php echo $expenseDetails['expense_transfer_for']; ?></td>
											<td><?php echo $expenseDetails['spent_amount']; ?></td>
											<td><?php echo $expenseDetails['spent_remark']; ?></td>
										</tr>
									<?php endforeach ?>
								<?php endif ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
		</div>
	</div>
</div>