	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title">Document Details</h3>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="table table-responsive">
							<table class="table-striped" width="100%">
								<thead>
									<th>#</th>
									<th></th>
									<th>Document</th>
									<th>Attachment</th>
									
								</thead>
								<tbody>
									<?php if ($this->siteexpenseDocuments) { ?>
										<?php $i = 1; 
										foreach ($this->DocumentsDetails as $documents): ?>
											<tr>
												<td><?php echo $i; ?></td>
												<td><input type="checkbox" name="" disabled
													<?php foreach ($this->siteexpenseDocuments as $key => $value) {
														if(($value['required_doc_type'] == $documents['id']) && $value['attachment_path']!=""){?>
															checked
														<?php	}}?>
														></td>
														<td><?php echo $documents['document_name']; ?></td>	<td>											
															<?php foreach($this->siteexpenseDocuments as $key => $site_document){
																if(($site_document['required_doc_type'] == $documents['id']) && $site_document['attachment_path']!=""){?>
																	<a href="<?php echo $site_document['attachment_path']?>" class="fa fa-eye"></a>
																<?php }}?>
															</td>
														</tr>
														<?php $i++;
													endforeach ?>
												<?php } else { ?>
													<tr><td colspan="7" style="text-align: center; color: red; font-weight: bold;">No Data Found!</td></tr>
												<?php } ?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
						</div>
					</div>
				</div>
			</div>