<?php 
$record = $this->paginator; 
$totalrec = $this->totalrec;
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$user               = new Application_Model_User;
?>

<style type="text/css">
	.table th ,   .table td , .table div{
		padding: 3px;
		text-align: left;
	} 
	#scroll-id {
		width: 600px;
	}
	@media print{
		.noprint {display:none !important; }
	}
	a:hover {
		text-decoration: underline !important;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Site Expense Report&nbsp;<span class="badge" style="font-size: 20px;"> <i class="fa fa-rupee"></i> <?php echo number_format((float)$this->total_amount['total_amount'], 2, '.', '') ; ?></span>
					<!--<div class="pull-right">-->
					<!--	<a href="/expense/" class="btn btn-success">Add Site Expense</a>-->
						
					<!--</div>-->
					</h3>
				</div>
				<div class="panel panel-body">

					<div class="row">
						<form action="" method="POST" role="form" >  
						<!--onsubmit="return validateForm()"-->
							<div class="col-md-2">
								<div class="form-group">
									<label for="">From date</label>
									<input type="text" class="form-control datepicker " name="from_date" id="from_date" placeholder="From Date" readonly="" value="<?php if(isset($this->from_date)){ echo $this->from_date;} ?>" >
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<label for="">To date</label>
									<input type="text" class="form-control datepicker " name="to_date" id="to_date" placeholder="To Date" readonly="" value="<?php if(isset($this->to_date)){ echo $this->to_date; } ?>">
								</div>
							</div>
							
							<div class="col-md-2">
							    <div class="form-group">
									<label for="session">Select Session</label>
								    <select id="session" class="form-control select2">
								        <option value="">Select Session</option>
								        <option value="2022-2023">2022-2023</option>
								        <option value="2023-2024" selected>2023-2024</option>
								    </select>
								</div>
							</div>
							<div class="col-md-2">
							    <div class="form-group">
									<label for="quarter">Select Quarter</label>
								    <select id="quarter" class="form-control select2">
								        <option value="">Select Quarter</option>
								        <option value="1">Quarter I</option>
								        <option value="2">Quarter II</option>
								        <option value="3">Quarter III</option>
								        <option value="3">Quarter IV</option>
								    </select>
								</div>
							</div>

							<div class="col-md-2">
								<div class="form-group">
									<button type="submit" class="btn btn-primary" style="margin-bottom:-50px;">Submit</button>
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<a href="/expense/office-expenses" class="btn btn-info" style="margin-bottom:-50px;">Reset</a>
								</div>
							</div>
						</form>
						<a href="expense/export-site-expense  ?>" class="btn btn-info"  type="submit"   title="file-excel" style="margin-top: -15px;float:right;margin-right: 20px;"><i class="glyphicon glyphicon-circle-arrow-down" ></i></a> 
					</div>

					<div class="table-responsive" id="user-list">
						<table class="display" width="100%" id="siteExpenseDetailsTable">
							<thead>
								<tr>
									<th>#</th>
									<th>PO Number</th>
									<th>PO Date</th>
									<th>Site ID</th>
									<th>Site Name</th>
									<th>Transferred Amount</th>
									<th>Reported Amount</th>
                                    <th>Not Reported Amount</th>
									<th>Last Fund Transferred Date</th>
									<th>Last Expense Added By</th>
									<th>Last Expense Added Date</th>
									<th>Attached Documents</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								if($this->siteDetails){ 
									$i = 0;
									foreach($this->siteDetails as $siteDetails){ ?>
										<tr>
											<td><?php echo $i+1;?>.</td>
											<td><?php echo $siteDetails['po_no']; ?></td>
											<td><span style="display: none;"><?php echo date('d/m/Y', strtotime($siteDetails['order_date'])); ?></span>
											<?php 
											    if($siteDetails['order_date'] != 0) {
                                                    echo date('d/m/Y', strtotime($siteDetails['order_date']));											            
											    } else {
											        echo '';
											    }
											 ?></td>
											<td><a href="javascript:void(0)" title="View Allocated Details" onclick="showAllocatedDetails('<?php echo $siteDetails['po_no']; ?>','<?php echo $siteDetails['site_id']; ?>')"><?php echo $siteDetails['site_id']; ?></a></td>
										<td><?php echo $siteDetails['site_name']; ?></td>
										<td><b><a href="/expense/site-expense-details/po-number/<?php echo md5($siteDetails['po_no']); ?>/site-id/<?php echo md5($siteDetails['site_id']); ?>" title="View Details"><?php echo number_format((float)$siteDetails['total_expense'], 2, '.', '') ; ?></a></b></td>
										<td><span style="color:#337ab7;" ><b><?php echo number_format((float)$siteDetails['balance_amount'], 2, '.', '') ; ?></b></span></td>
											<td>
                                              <?php if($siteDetails['total_expense']-$siteDetails['balance_amount'] > 0) { ?>
                                        <span style="color:red;" ><b><?php echo $siteDetails['total_expense']-$siteDetails['balance_amount']; ?></b></span>
                                              <?php } else if($siteDetails['total_expense']-$siteDetails['balance_amount'] < 0){ ?>
                                                <span style="color:green;" ><b><?php echo $siteDetails['total_expense']-$siteDetails['balance_amount']; ?></b></span>
                                              <?php } else if($siteDetails['total_expense']-$siteDetails['balance_amount'] == 0){ ?>
                                              <span style="color:#337ab7;" ><b><?php echo $siteDetails['total_expense']-$siteDetails['balance_amount']; ?></b></span>
                                              <?php }?>
                                              </td>
										<td><?php if (($siteDetails['last_fund_transfer_date']) && ($siteDetails['last_fund_transfer_date'] != '0000-00-00')) {
												echo date("d/m/Y", strtotime($siteDetails['last_fund_transfer_date']));
											} else {
												echo '00/00/0000';
											} ?></td>
										<td><?php echo $siteDetails['last_expense_added_by']; ?></td>
										<td><?php echo $siteDetails['last_expense_added_date']; ?></td>
										<td><a href="javascript:void(0)" title="Delete Expense" onclick="viewAttachments(<?php echo $siteDetails['po_no']; ?>,'site_expense')"><i class="fa fa-file-text-o" style="color: red;"></i></a>
										</td>
										</tr>
										<?php  $i++;} } ?>
										
									</tbody>
									<tfoot>
										<tr>
											<td colspan = "8" style="text-align: center;"><h3>Total :<span class="badge" style="font-size: 20px;"> <i class="fa fa-rupee"></i> <?php echo number_format((float)$this->total_amount['total_amount'], 2, '.', '') ; ?></span></h3>
											</td>
										</tr>
									</tfoot>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			</div>

			<script>
				$(document).ready(function() {
					$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });

					var t =$("#siteExpenseDetailsTable").DataTable({
						// "order": [[ 6, "desc" ]],
						 // columnDefs: [
					  //      { type: 'date-mmm-yyyy', targets: 6 }
					  //    ]
					} );

					t.on( 'order.dt search.dt', function () {
						t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
							cell.innerHTML = i+1;
						} );
					} ).draw();
				});
				function showAllocatedDetails(po_no, site_id) {
					$.ajax({
						url: '/siteallocation/get-site-allocation-details',
						type: 'POST',
						data: {poNumber: po_no, siteId: site_id},
						success:function(data){
							$('#myModal').html(data);
							$('#myModal').modal('toggle');
						}
					});

				}


				function validateForm() {
					if ($('#from_date').val() == "") {
						swal({
							title : "From Date Missing!",
							text  : "Click from date input box and select date",
							icon  : "error"
						});
						return false
					}else if ($('#to_date').val() == "") {
						swal({
							title : "To Date Missing!",
							text  : "Click to date input box and select date",
							icon  : "error"
						});
						return false
					}  else {
						return true;
					}
				}

				function viewAttachments(po_no){
					$.ajax({
						url: '/expense/get-attach-documents-details',
						type: 'POST',
						data: {po_no: po_no},
						success:function(data){
							$('#myModal').html(data);
							$('#myModal').modal('toggle');
						}
					});
				}
			</script>

