<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
  #mandatory {
    color: red;
    font-size: 16px;
  }
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Invoice(s) Details
          <div class="pull-right">
            <a href="/expense/punch-invoice" class="btn btn-success">Punch Invoice</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="expenseInTypeListTable">
             <thead>
              <th>#</th>
              <th style="white-space: nowrap;">Client Name</th>
              <th style="white-space: nowrap;">PO Number</th>
              <th style="white-space: nowrap;">Site ID</th>
              <th style="white-space: nowrap;">State Name</th>
              <th style="white-space: nowrap;">Invoice Number</th>
              <th style="white-space: nowrap;">Invoice Date</th>
              <th style="white-space: nowrap;">Invoice Amount</th>
              <th style="white-space: nowrap;">Invoice Remark</th>
              <th style="white-space: nowrap;">Received Date</th>
              <th style="white-space: nowrap;">Received Amount</th>
              <?php if ($this->role_type == 1) { ?>
                <th>Review</th>
              <?php } ?>
            </thead>
            <tbody>
              <?php if($this->invoiceReports){
                $i = 1;
                foreach ($this->invoiceReports as $invoice) { ?>
                 <tr>
                  <td style="white-space: nowrap;"><?php echo $i; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['client_name']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['po_no']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['site_id']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['state_name']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['invoice_no']; ?></td>
                  <td style="white-space: nowrap;"><?php echo date('d/m/Y', strtotime($invoice['invoice_date'])); ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['invoice_value']; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['invoice_remark'] ? $invoice['invoice_remark']:"-"; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['amount_received_date'] ? date('d/m/Y', strtotime($invoice['amount_received_date'])):"-"; ?></td>
                  <td style="white-space: nowrap;"><?php echo $invoice['received_amount'] ? $invoice['received_amount']:"-"; ?></td>
                  <?php if ($this->role_type == 1) { ?>
                    <td style="white-space: nowrap;">
                      <?php if ($invoice['marked_for_review'] == "0") { ?>
                        <a href="javascript:void(0)" onclick="changeViewStatusUpdateAndDeleteInvoice(<?php echo $invoice['id']; ?>,'unmark')" title="Mark For Review"><span class="fa fa-eye" style="color: #10B22D;"></span></a>
                        &nbsp;&nbsp;
                        <a href="javascript:void(0)" onclick="changeViewStatusUpdateAndDeleteInvoice(<?php echo $invoice['id']; ?>,'update','<?php echo $invoice['invoice_no']; ?>')" title="Update Invoice"><span class="fa fa-pencil" style="color: #10B22D;"></span></a>
                        &nbsp;&nbsp;
                        <a href="javascript:void(0)" onclick="changeViewStatusUpdateAndDeleteInvoice(<?php echo $invoice['id']; ?>,'delete')" title="Delete Invoice"><span class="fa fa-trash" style="color: #E61919;"></span></a>
                      <?php } else { ?>
                        <a href="javascript:void(0)" onclick="changeViewStatusUpdateAndDeleteInvoice(<?php echo $invoice['id']; ?>,'mark')" title="Mark As Viewed"><span class="fa fa-eye-slash" style="color: #AD0000;"></span></a>
                        &nbsp;&nbsp;
                        <a href="javascript:void(0)" onclick="changeViewStatusUpdateAndDeleteInvoice(<?php echo $invoice['id']; ?>,'update','<?php echo $invoice['invoice_no']; ?>')" title="Update Invoice"><span class="fa fa-pencil" style="color: #10B22D;"></span></a>
                      <?php } ?> 
                    </td>
                  <?php } ?>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="updateInvoiceDetailsModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Update Invoice Details</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form">
              <input type="hidden" name="invoice_id" id="invoice_id">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="invoice_num">Invoice Number :</label>
                <input type="text" class="form-control" name="invoice_num" id="invoice_num" readonly="">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="update_received_amount">Received Amount <span id="mandatory">*</span>:</label>
                <input type="text" class="form-control" name="update_received_amount" id="update_received_amount" placeholder="Enter Received Amount">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="update_received_amount_date">Received Date <span id="mandatory">*</span> :</label>
                <input type="text" class="form-control datepicker" name="update_received_amount_date" id="update_received_amount_date" placeholder="Select Date" readonly="">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="updateInvoiceDetails" value="Update">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseInTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#expenseInTypeListTable").DataTable();
      $(".select2").select2();
      $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
      $("#updateInvoiceDetails").click(function(event) {
        event.preventDefault();
        var received_amount   = $("#update_received_amount").val();
        var received_date     = $("#update_received_amount_date").val();
        var invoice_number    = $("#invoice_num").val();
        var invoice_id        = $("#invoice_id").val();
        if (received_date == "") {
          swal({
            title : "Received Date Missing!",
            text  : "Please select amount received date.",
            icon  : "error",
          }).then(function(){
            $("#update_received_amount_date").focus();
          });
        } else if (received_amount == "") {
          swal({
            title : "Received Amount Missing!",
            text  : "Please enter received amount.",
            icon  : "error",
          }).then(function(){
            $("#update_received_amount").focus();
          });
        } else {
          $("#updateInvoiceDetailsModal").modal("toggle");
          $.ajax({
            url: '/expense/change-view-status-and-update-invoice',
            type: 'POST',
            data: {received_date: received_date, received_amount:received_amount, invoice_num:invoice_number, type:'update', invoice_id:invoice_id},
            success:function(data){
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success"
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                }).then(function(){
                  $("#updateInvoiceDetailsModal").modal("toggle");
                });
              }
            }
          });
        }
      });
    });
    function changeViewStatusUpdateAndDeleteInvoice(id, type, invoice_num = null) {
      if (type == "") {
        swal({
          title : "Request Type Missing!",
          text  : "Please try agian after refreshing the page.",
          icon  : "error"
        });
      } else if (id == "") {
        swal({
          title : "Invoice ID Missing!",
          text  : "Please try agian after refreshing the page.",
          icon  : "error"
        });
      } else if (type == 'update') {
        $("#invoice_num").val(invoice_num);
        $("#invoice_id").val(id);
        $("#updateInvoiceDetailsModal").modal('toggle');
      } else {
        var text;
        if (type == "delete") {
          text = "Do you want to delete invoice details?";
        } else {
          text = "Do you want to "+type+" as viewed?";
        }
        swal({
          title : "Are you sure?",
          text  : text,
          icon  : "warning",
          buttons : [true, "Yes, "+type],
          dangerMode : true
        }).then(function(isConfirm){
          if (!isConfirm) {
            return false;
          } else {
            $("#loading-bg").show();
            $.ajax({
              url  : '/expense/change-view-status-and-update-invoice',
              type : 'POST',
              data : {type:type, invoice_id:id},
              success:function(data){
                $("#loading-bg").hide();
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "success",
                  }).then(function(){
                    location.reload("/expense/invoice-report");
                  });
                } else {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "error"
                  });           
                }
              }
            });

          }
        });
      }
    }
    function submitUpdateExpenseInTypeForm(id) {
      var expenseTypeId = $("#updatedExpenseTypeId").val();
      var expenseInType = $("#updatedExpenseInType").val();
      if (expenseTypeId == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please select expense type.",
          icon  : "error",
        });
      } else if (expenseInType == "") {
        swal({
          title : "Expense In Type Missing!",
          text  : "Please enter expense in type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseInTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-in-type',
          type: 'POST',
          data: {expenseInTypeId:id, expenseTypeId: expenseTypeId, expenseInType:expenseInType},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseInTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

