
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
.select2.select2-container {
  width: 100% !important;
}
.mainDiv {
  background-color: #DCF2FE;
  border-radius: 5px;
  padding: 10px 15px 10px 15px;
}
form {
  padding: 5px;
}
#mandatory {
  color: red;
  font-size: 18px;
}  
.formDiv {
  border: 5px solid #b0d5ea;
  border-radius: 5px;
  padding: 10px 10px 10px 10px;
}
.table-bordered {
  border: 2px solid #1b1a1a !important;
}
.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
  border: 1px solid #1b1a1a !important;
}
</style>

<div id="page-wrapper">
  <div class="main-page">
    <?php if (isset($this->params)): ?>
      <?php if (isset($this->params['success'])){ ?>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Success !</strong>&nbsp; <?php echo $this->params["success"]; ?>
        </div>
      <?php } else if (isset($this->params['error'])) { ?>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
        </div>
      <?php } ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h3>Create New Expense</h3>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a <?php if (isset($this->params['expenseType']) && $this->params['expenseType'] == "Office Expense") { ?>
              href="/expense/office-expenses" <?php } else { ?>href="/expense" <?php } ?> class="btn btn-success pull-right">Back</a>
            </div>
          </div>
        </div>
        <div class="panel panel-body">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
              </div>
            </div>
            <link rel="stylesheet" href="/assets/css/select2.min.css">
            <script src="/assets/js/select2.min.js"></script>

            <div class="officeExpenseDiv">
              <form action="/expense/create-new-expense" method="POST" enctype="multipart/form-data" onsubmit="return validateOfficeExpenseInputData()">
                <input type="hidden" name="expenseType" id="expenseType" value="1">
                <input type="hidden" name="expenseTypeName" id="expenseTypeName" value="Office Expense">
                <div class="row">
                  <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h2 align="center" style="text-decoration: underline;">Office Expense Formhfghgfhgf</h2>
                  </div>
                </div>
                <br clear="all">
                <div class="row">

                  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <label for="company_id">Company<span id="mandatory">*</span></label>
                    <select id="company_id" name="company_id" class="form-control select2" required="required">
                      <option value="">Please Company</option>
                      <?php foreach ($this->companies as $company): ?>
                        <option value="<?php echo $company['id']; ?>"><?php echo $company['name']; ?></option>
                      <?php endforeach ?>
                    </select>
                  </div>


                  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                   <label for="officeExpenseDateOfTransfer">Date of Transfer<span id="mandatory">*</span></label>
                   <input type="text" class="form-control datepicker" name="officeExpenseDateOfTransfer" id="officeExpenseDateOfTransfer" readonly="" value="<?php if (isset($this->params['officeExpenseDateOfTransfer'])) { echo $this->params['officeExpenseDateOfTransfer']; } else { echo date('d/m/Y'); } ?>">
                 </div>
                 <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <label for="officeExpenseTransferTo">Transfer To <span id="mandatory">*</span></label>
                  <select name="officeExpenseTransferTo" id="officeExpenseTransferTo" class="form-control select2">
                    <option value="">Please Select</option>
                    <?php foreach ($this->userList as $user): ?>
                      <option value="<?php echo $user['id']; ?>"<?php if (isset($this->params['officeExpenseTransferTo'])) { echo $this->params['officeExpenseTransferTo'] == $user['id']?"selected":""; } ?>><?php echo ucwords(strtolower($user['name'])); ?></option>
                    <?php endforeach ?>
                  </select>
                </div>
                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <label for="officeExpenseTransferAmount">Transfer Amount<span id="mandatory">*</span></label>
                  <input type="text" class="form-control" name="officeExpenseTransferAmount" id="officeExpenseTransferAmount" oninput="this.value = this.value.replace(/[^0-9.]/g, '');" value="<?php if (isset($this->params['officeExpenseTransferAmount'])) { echo $this->params['officeExpenseTransferAmount']; } ?>">
                </div>


                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <label for="officeExpenseBillNumber">Attachment/Bill Number <span id="mandatory">*</span></label>
                  <input type="text" class="form-control" name="officeExpenseBillNumber" id="officeExpenseBillNumber" value="<?php if (isset($this->params['officeExpenseBillNumber'])) { echo $this->params['officeExpenseBillNumber']; } ?>" required>
                </div>
                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <label for="officeExpenseAttachment">Upload Attachment</label>
                  <input type="file" class="form-control" name="officeExpenseAttachment" id="officeExpenseAttachment">
                </div>


                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                  <label for="officeExpenseTansferRemark">Remarks (if any)</label>
                  <input type="text" class="form-control" name="officeExpenseTansferRemark" id="officeExpenseTansferRemark" value="<?php if (isset($this->params['officeExpenseTansferRemark'])) { echo $this->params['officeExpenseTansferRemark']; } ?>">
                </div>

                <div class="clearfix"></div>
                <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                  <label for="bank_account_id">Bank Account<span id="mandatory">*</span></label>
                  <select name="bank_account_id" id="bank_account_id" class="form-control select2" required="required">
                    <option value="">Select Bank Account</option>
                    <?php foreach ($this->bank_accounts as $bank_account): ?>
                      <option value="<?php echo $bank_account['id']; ?>"><?php echo $bank_account['bank_name']."(".$bank_account['bank_account_number'].")"; ?></option>
                    <?php endforeach ?>
                  </select>
                </div>

                <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                  <label for="payment_mode_id">Payment Mode <span id="mandatory">*</span></label>
                  <select name="payment_mode_id" id="payment_mode_id" class="form-control select2" required="required">
                    <option value="">Select Payment Mode</option>
                    <?php foreach ($this->payment_modes as $payment_mode): ?>
                      <option value="<?php echo $payment_mode['id']; ?>"><?php echo $payment_mode['payment_mode']; ?></option>
                    <?php endforeach ?>
                  </select>
                </div>
                <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <label for="debit_account_id">Debit Account <span id="mandatory">*</span></label>
      <select name="debit_account_id" id="debit_account_id" class="form-control select2" required="required">
        <option value="">Select Debit Account</option>
        <?php foreach ($this->debitAccount as $debit): ?>
          <option value="<?php echo $debit['id']; ?>"><?php echo $debit['debit_account']; ?></option>
        <?php endforeach ?>
      </select>
    </div>

              </div>

              <br clear="all">
              <div class="row" id="expenseDetailsDiv" style="overflow: auto; padding: 8px 15px;">
                <table class="table table-bordered" id="expenseDetailsTable">
                  <thead>
                    <th>Expense In</th>
                    <th>Expense For</th>
                    <th>Spent Amount</th>
                    <th>Expense Remark</th>
                    <th>Action</th>
                  </thead>
                  <tbody>
                    <tr id="row_1">
                      <td>
                        <select name="expense_in_id[]" id="expense_in_id_1" class="form-control select2" onchange="showExpenseForList(1)">
                          <option value="">Please Select</option>
                          <?php foreach ($this->expenseInMasterList as $expenseInList): ?>
                            <option value="<?php echo $expenseInList['id']; ?>"><?php echo $expenseInList['expense_in_type']; ?></option>
                          <?php endforeach ?>
                        </select>
                      </td>
                      <td>
                        <select name="expense_for_id[]" id="expense_for_id_1" class="form-control select2">
                          <option value="">Please Select</option>
                        </select>
                      </td>
                      <td>
                        <input type="text" class="form-control" name="spentAmount[]" id="spentAmount_1" required="">
                      </td>
                      <td><input type="text" class="form-control" name="spentRemark[]" id="spentRemark_1"></td>
                      <td></td>
                    </tr>
                  </tbody>
                </table>
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRowInOfficeExpenseForm();">Add More Row</button>
                  </div>
                </div>
              </div>
              <div class="row" id="saveButtonDiv">
                <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
                  <button type="submit" class="btn btn-success" style="float: right;">Save Expense</button>
                </div>
              </div>
            </form>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
  }); 
  function addMoreRowInOfficeExpenseForm() {
    var row_count = $('#expenseDetailsTable tr').length;
    var expenseType = $("#expenseTypeSelect").val();
    $.ajax({
      url: '/expense/get-expense-in-list/expense_type_id/1',
      type: 'GET',
      success:function(data){
        var data = JSON.parse(data);
        console.log(data);
        if (data.flag) {
          $("#expense_in_id_"+row_count).html(data.expenseOption);
        } else {
          swal({
            title : data.title,
            text  : data.message,
            icon  : "error"
          });
        }
      }
    });
    var html_content = `<tr id="row_`+row_count+`">
    <td>
    <select name="expense_in_id[]" id="expense_in_id_`+row_count+`" class="form-control select2" onchange="showExpenseForList(`+row_count+`)">
    <option value="">Please Select</option>
    </select>
    </td>
    <td>
    <select name="expense_for_id[]" id="expense_for_id_`+row_count+`"class="form-control select2">
    <option value="">Please Select</option>
    </select>
    </td>
    <td>
    <input type="text" class="form-control" name="spentAmount[]" id="spentAmount" required="">
    </td>
    <td><input type="text" class="form-control" name="spentRemark[]" id="spentRemark" required=""></td>
    <td><a href="javascript:void(0)" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color:red;"></i></a></td>
    </tr>`;
    $("#expenseDetailsTable").append(html_content);
    $(".select2").select2();
  } 
  function deleteRow(count) {
   $("#row_"+count).remove();
 } 
 function showExpenseForList(row_number) {
  var expenseInId = $("#expense_in_id_"+row_number).val();
  if (expenseInId != "") {
    $.ajax({
      url: '/expense/get-expense-for-by-expense-in/expense_in_id/'+expenseInId,
      type: 'GET',
      success:function(data) {
       var data = JSON.parse(data);
       console.log(data);
       if (data.flag) {
        $("#expense_for_id_"+row_number).html(data.option);
      } else {
        swal({
          title : data.title,
          text  : data.message,
          icon  : "error"
        }).then(function(){
          $("#expense_for_id_"+row_number).html('<option value="">Please Select</option>');
        });
      } 
    }
  });
  } else {
    swal({
      title : "Expense In Missing!",
      text  : "Please try again after refreshing the page.",
      icon  : "error"
    });
  }
}
function getSitesByPoNumber() {
  var po_number = $("#poNumber").val();
  if (po_number != "") {
    $.ajax({
      url: '/siteallocation/get-sites-by-po-number',
      type: 'POST',
      data: {po_number: po_number},
      success:function(data){
        var data = JSON.parse(data);
        console.log(data);
        var option = "<option value=''>Select Site ID</option>";
        if (data.flag) {
          $.each(data.sites, function(index, site_id) {
            option += "<option value='"+site_id.site_id+"'>"+site_id.site_id+"</option>";
          });
        } else {
          option += "<option>"+data.message+"</option>";
        }
        $("#siteId").html(option);
      }
    });
  } else {
    $("#siteId").html("<option>Select Site ID</option>");
  }
}
function validateSiteExpenseInputData() {
  var siteExpenseDate     = $("#siteExpenseDateOfTransfer").val();
  var poNumber            = $("#poNumber").val();
  var siteId              = $("#siteId").val();
  var siteExpenseAmount   = $("#siteExpenseTransferAmount").val();
  var siteExpenseFor      = $("#siteExpenseTransferFor").val();
  var siteExpenseTo       = $("#siteExpenseTransferTo").val();
    // alert(siteExpenseAmount);
    // return false;
    if (siteExpenseDate == "") {
      swal({
        title : "Transfer Date Missing !",
        text  : "Please Select Date of Transfer.",
        icon  : "error"
      }).then(function() {
        $("#siteExpenseDateOfTransfer").focus();
      });
      return false;
    } else if (poNumber == "") {
      swal({
        title : "PO Number Missing !",
        text  : "Please Select PO Number.",
        icon  : "error"
      }).then(function() {
        $("#poNumber").focus();
      });
      return false;
    } else if (siteId == "") {
      swal({
        title : "Site Missing !",
        text  : "Please Select Site ID.",
        icon  : "error"
      }).then(function() {
        $("#siteId").focus();
      });
      return false;
    } else if (siteExpenseAmount == "") {
      swal({
        title : "Expense Amount Missing !",
        text  : "Please Enter Transfer Amount.",
        icon  : "error"
      }).then(function() {
        $("#siteExpenseTransferAmount").focus();
      });
      return false;
    } else if (siteExpenseFor == "") {
      swal({
        title : "Transfer For Missing !",
        text  : "Please Select Transfer For.",
        icon  : "error"
      }).then(function() {
        $("#siteExpenseTransferFor").focus();
      });
      return false;
    } else if (siteExpenseTo == "") {
      swal({
        title : "Transfer To Missing !",
        text  : "Please Select Transfer To.",
        icon  : "error"
      }).then(function() {
        $("#siteExpenseTransferTo").focus();
      });
      return false;
    }
  }
  function validateOfficeExpenseInputData() {
    var officeExpenseDate   = $("#officeExpenseDateOfTransfer").val();
    var officeExpenseFor    = $("#officeExpenseTransferFor").val();
    var officeExpenseTo     = $("#officeExpenseTransferTo").val();
    var officeExpenseAmount = $("#officeExpenseTransferAmount").val();
    if (officeExpenseDate == "") {
      swal({
        title : "Transfer Date Missing !",
        text  : "Please Select Date of Transfer.",
        icon  : "error"
      }).then(function() {
        $("#officeExpenseDateOfTransfer").focus();
      });
      return false;
    } else if (officeExpenseFor == "") {
      swal({
        title : "Transfer For Missing !",
        text  : "Please Select Expense Transfer For.",
        icon  : "error"
      }).then(function() {
        $("#officeExpenseTransferFor").focus();
      });
      return false;
    } else if (officeExpenseTo == "") {
      swal({
        title : "Transfer To Missing !",
        text  : "Please Select Expense Transfer To.",
        icon  : "error"
      }).then(function() {
        $("#officeExpenseTransferTo").focus();
      });
      return false;
    } else if (officeExpenseAmount == "") {
      swal({
        title : "Transfer Amount Missing !",
        text  : "Please Enter Transfer Amount.",
        icon  : "error"
      }).then(function() {
        $("#officeExpenseTransferAmount").focus();
      });
      return false;
    }
  }
</script>