<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>

<div class="officeExpenseDiv">
  <form action="/expense/create-new-expense" method="POST" enctype="multipart/form-data" onsubmit="return validateOfficeExpenseInputData()">
    <input type="hidden" name="expenseType" id="expenseType">
    <input type="hidden" name="expenseTypeName" id="expenseTypeName" value="Office Expense">
    <div class="row">
      <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2 align="center" style="text-decoration: underline;">Office Expense Form</h2>
      </div>
    </div>
    <br clear="all">
    <div class="row">

      <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
        <label for="company_id">Company<span id="mandatory">*</span></label>
        <select id="company_id" name="company_id" class="form-control select2" required="required">
          <option value="">Please Company</option>
          <?php foreach ($this->companies as $company): ?>
            <option value="<?php echo $company['id']; ?>"><?php echo $company['name']; ?></option>
          <?php endforeach ?>
        </select>
      </div>


      <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
       <label for="officeExpenseDateOfTransfer">Date of Transfer<span id="mandatory">*</span></label>
       <input type="text" class="form-control datepicker" name="officeExpenseDateOfTransfer" id="officeExpenseDateOfTransfer" readonly="" value="<?php if (isset($this->params['officeExpenseDateOfTransfer'])) { echo $this->params['officeExpenseDateOfTransfer']; } else { echo date('d/m/Y'); } ?>">
     </div>
     <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="officeExpenseTransferTo">Transfer To <span id="mandatory">*</span></label>
      <select name="officeExpenseTransferTo" id="officeExpenseTransferTo" class="form-control select2">
        <option value="">Please Select</option>
        <?php foreach ($this->userList as $user): ?>
          <option value="<?php echo $user['id']; ?>"<?php if (isset($this->params['officeExpenseTransferTo'])) { echo $this->params['officeExpenseTransferTo'] == $user['id']?"selected":""; } ?>><?php echo ucwords(strtolower($user['name'])); ?></option>
        <?php endforeach ?>
      </select>
    </div>
    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="officeExpenseTransferAmount">Transfer Amount<span id="mandatory">*</span></label>
      <input type="text" class="form-control" name="officeExpenseTransferAmount" id="officeExpenseTransferAmount" oninput="this.value = this.value.replace(/[^0-9.]/g, '');" value="<?php if (isset($this->params['officeExpenseTransferAmount'])) { echo $this->params['officeExpenseTransferAmount']; } ?>">
    </div>


    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="officeExpenseBillNumber">Attachment/Bill Number <span id="mandatory">*</span></label>
      <input type="text" class="form-control" name="officeExpenseBillNumber" id="officeExpenseBillNumber" value="<?php if (isset($this->params['officeExpenseBillNumber'])) { echo $this->params['officeExpenseBillNumber']; } ?>" required>
    </div>
    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="officeExpenseAttachment">Upload Attachment</label>
      <input type="file" class="form-control" name="officeExpenseAttachment" id="officeExpenseAttachment">
    </div>


    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="officeExpenseTansferRemark">Remarks<span id="mandatory">*</span></label>
      <input type="text" class="form-control" name="officeExpenseTansferRemark" id="officeExpenseTansferRemark" value="<?php if (isset($this->params['officeExpenseTansferRemark'])) { echo $this->params['officeExpenseTansferRemark']; } ?>">
    </div>

    <div class="clearfix"></div>
    <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <label for="bank_account_id">Bank Account<span id="mandatory">*</span></label>
      <select name="bank_account_id" id="bank_account_id" class="form-control select2" required="required">
        <option value="">Select Bank Account</option>
        <?php foreach ($this->bank_accounts as $bank_account): ?>
          <option value="<?php echo $bank_account['id']; ?>"><?php echo $bank_account['bank_name']."(".$bank_account['bank_account_number'].")"; ?></option>
        <?php endforeach ?>
      </select>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <label for="payment_mode_id">Payment Mode <span id="mandatory">*</span></label>
      <select name="payment_mode_id" id="payment_mode_id" class="form-control select2" required="required">
        <option value="">Select Payment Mode</option>
        <?php foreach ($this->payment_modes as $payment_mode): ?>
          <option value="<?php echo $payment_mode['id']; ?>"><?php echo $payment_mode['payment_mode']; ?></option>
        <?php endforeach ?>
      </select>
    </div>

    <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <label for="debit_account_id">Debit Account <span id="mandatory">*</span></label>
      <select name="debit_account_id" id="debit_account_id" class="form-control select2" required="required">
        <option value="">Select Debit Account</option>
        <?php foreach ($this->debitAccount as $debit): ?>
          <option value="<?php echo $debit['id']; ?>"><?php echo $debit['debit_account']; ?></option>
        <?php endforeach ?>
      </select>
    </div>

  </div>

  <br clear="all">
  <div class="row" id="expenseDetailsDiv" style="overflow: auto; padding: 8px 15px;">
    <table class="table table-bordered" id="expenseDetailsTable">
      <thead>
        <th>Expense In</th>
        <th>Expense For</th>
        <th>Spent Amount</th>
        <th>Expense Remark</th>
        <th>Action</th>
      </thead>
      <tbody>
        <tr id="row_1">
          <td>
            <select name="expense_in_id[]" id="expense_in_id_1" class="form-control select2" onchange="showExpenseForList(1)">
              <option value="">Please Select</option>
              <?php foreach ($this->expenseInMasterList as $expenseInList): ?>
                <option value="<?php echo $expenseInList['id']; ?>"><?php echo $expenseInList['expense_in_type']; ?></option>
              <?php endforeach ?>
            </select>
          </td>
          <td>
            <select name="expense_for_id[]" id="expense_for_id_1" class="form-control select2">
              <option value="">Please Select</option>
            </select>
          </td>
          <td>
            <input type="text" class="form-control" name="spentAmount[]" id="spentAmount_1" required="">
          </td>
          <td><input type="text" class="form-control" name="spentRemark[]" id="spentRemark_1"></td>
          <td></td>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRowInOfficeExpenseForm();">Add More Row</button>
      </div>
    </div>
  </div>
  <div class="row" id="saveButtonDiv">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
      <button type="submit" class="btn btn-success" style="float: right;">Save Expense</button>
    </div>
  </div>
</form>
</div>

<script>
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
  });
</script>