
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>


    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Office Expense Report <span class="badge" style="font-size: 20px;"> <i class="fa fa-rupee"></i> <?php echo number_format((float)$this->total_amount['total_amount'], 2, '.', '') ; ?></span>

          <div class="pull-right">
            <a href="/expense/new-expense/expense_type/1" class="btn btn-success">Add New Expense</a>
          </div>
        </h3>
      </div>
      <div class="panel panel-body">

        <div class="row">
          <form action="" method="POST" role="form" onsubmit="return validateForm()">
            <div class="col-md-2">
              <div class="form-group">
                <label for="">From date</label>
                <input type="text" class="form-control datepicker " name="from_date" id="from_date" placeholder="From Date" readonly="" value="<?php if(isset($this->from_date)){ echo $this->from_date;} ?>" >
              </div>
            </div>
            <div class="col-md-2">
              <div class="form-group">
                <label for="">To date</label>
                <input type="text" class="form-control datepicker " name="to_date" id="to_date" placeholder="To Date" readonly="" value="<?php if(isset($this->to_date)){ echo $this->to_date; } ?>">
              </div>
            </div>

            <div class="col-md-3">
              <div class="form-group">
                <label for="">Company </label>
                <select id="company_id" name="company_id" class="form-control select2" required="required">
                  <option value="">Please Company</option>
                  <?php foreach ($this->companies as $company): ?>
                    <option value="<?php echo $company['id']; ?>" <?php if(isset($this->company_id)){ echo $this->company_id == $company['id']?"selected":""; } ?>><?php echo $company['name']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div>
            <div class="col-md-2">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <div class="col-md-2">
              <a href="/expense/office-expenses" class="btn btn-info">Reset</a>
            </div>
          </form>
          <a href="/expense/export-office-expense"class="btn btn-info"  type="submit" style="margin-bottom: 5px;float:right;margin-right: 15px;" title="file-excel"><i class="glyphicon glyphicon-circle-arrow-down" ></i></a>
        </div>

        <div class="table-responsive" id="user-list">
          <table class="display" width="100%" id="officeExpenseDetailsTable">
            <thead>
              <th>#</th>
              <th style="white-space: nowrap;">Company</th>
              <th style="white-space: nowrap;">Transfer Date</th>
              <th style="white-space: nowrap;">Transfered To</th>
              <th style="white-space: nowrap;">Amount</th>
              <th style="white-space: nowrap;">Remark</th>
              <th>Bank Account</th>
              <th>Payment Mode</th>
              <th style="white-space: nowrap;">Bill/Attachment Number</th>
              <th style="white-space: nowrap;">Bill/Attachment</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->officeExpenseDetails){ 
                $i = 1; 
                foreach($this->officeExpenseDetails as $officeExpense){ ?>
                  <tr>
                    <td style="white-space: nowrap;"><?php echo $i; ?></td>
                    <td style="white-space: nowrap;">
                      <?php echo ucwords(strtolower($officeExpense['company']));?>
                    </td>
                    <td style="white-space: nowrap;">
                      <?php echo date('d/m/Y', strtotime($officeExpense['transfer_date'])); ?>
                    </td>
                    <td style="white-space: nowrap;">
                      <?php echo ucwords(strtolower($officeExpense['name']));?>
                    </td>
                    <td style="white-space: nowrap;">
                      <a href="javascript:void(0)" title="View Details" onclick="showExpenseAmountDetails(<?php echo $officeExpense['id']; ?>)"><?php echo $officeExpense['amount'];?></a>
                    </td>
                    <td style="white-space: nowrap;">
                      <?php if ($officeExpense['remark']) { echo $officeExpense['remark']; } else { echo "-"; } ?>
                    </td>
                    <td><?php echo $officeExpense['bank_name']; ?><br><?php echo $officeExpense['bank_account_number']; ?></td>
                    <td><?php echo $officeExpense['payment_mode']; ?></td>
                    <td style="white-space: nowrap;">
                      <?php echo $officeExpense['bill_number'];?>
                    </td>
                    <td style="white-space: nowrap;">
                      <?php if ($officeExpense['attachment']) { ?>
                        <a href="<?php echo $officeExpense['attachment']; ?>" target="_blank"><i class="fa fa-eye"></i></a>
                      <?php } else { echo "-"; } ?>
                    </td>
                    <td style="white-space: nowrap;">
                      <?php if ($this->role_type == 1 || $this->role_type == 4){ ?>
                        <a href="javascript:void(0)" title="Delete Expense" onclick="deleteExpense(<?php echo $officeExpense['id']; ?>,'office_expense')"><i class="fa fa-trash" style="color: red;"></i></a>
                        <a href="/expense/print-expense/id/<?php echo $officeExpense['id']?>" title="Delete Expense"><i class="fa fa-print" style="color: blue;"></i></a>
                        <?php if($officeExpense['approved'] == 0){?>
                          <a href="javascript:void(0)" title="Approve Expense" onclick="approveExpense(<?php echo $officeExpense['id']; ?>,<?php echo $officeExpense['approved']?>,<?php echo $officeExpense['created_by']?>)" class="btn btn-danger">Approve</a>
                        <?php }else{?>
                          <a href="javascript:void(0)" title="Approve Expense" onclick="approveExpense(<?php echo $officeExpense['id']; ?>,<?php echo $officeExpense['approved']?>,<?php echo $officeExpense['created_by']?>)" class="btn btn-success">Approve</a>
                        <?php }} else { ?>
                          <a href="javascript:void(0)" title="Make Request" onclick="makeRequestTo()"><i class="fa fa-comments" aria-hidden="true"></i></a>
                        <?php } ?>
                      </td>
                    </tr>
                    <?php $i++; }}?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      </div>

      <script>
        $(document).ready(function() {

          $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
          $("#officeExpenseDetailsTable").DataTable();
        });


        function validateForm() {
          if ($('#from_date').val() == "") {
            swal({
              title : "From Date Missing!",
              text  : "Click from date input box and select date",
              icon  : "error"
            });
            return false
          }else if ($('#to_date').val() == "") {
            swal({
              title : "To Date Missing!",
              text  : "Click to date input box and select date",
              icon  : "error"
            });
            return false
          }  else {
           return true;
         }
       }

       function showExpenseAmountDetails(expense_id) {
        if (expense_id == "") {
          swal({
            title : "Expense ID Missing!",
            text  : "Please try after refreshing the page.",
            icon  : "error"
          });
        } else {
          $.ajax({
            url: '/expense/get-expense-amount-details',
            type: 'POST',
            data: {expense_id: expense_id},
            success:function(data){
              $("#myModal").html(data);
              $("#myModal").modal('toggle');
            }
          });
        }
      }
      function deleteExpense(expense_id,type) {
        if (expense_id == '') {
          swal({
            title : "ID Not Found!",
            text  : "Please try again after refreshing the page.",
            icon  : "error"
          });
          return false;
        } else {
          swal({
            title : "Are you sure?",
            text  : "Do you want to delete clicked expense?",
            icon  : "warning",
            buttons : [true, "Yes, Delete"],
            dangerMode : true
          }).then(function(isConfirm){
            if (!isConfirm) {
              return false;
            } else {
             $("#loading-bg").show();
             $.ajax({
              url: '/expense/delete-expense',
              type: 'POST',
              data: {expense_id: expense_id,type:type},
              success:function(data){
                $("#loading-bg").hide();
                console.log(data);
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : 'success'
                  }).then(function(){
                   window.location.reload('/expense/office-expenses');
                 });
                } else {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : 'error'
                  });
                }
              }
            });
           }
         }); 
        }
      }
      var count =0;
      function approveExpense(id,approved,createdby) {
        count++;
        if (id == '') {
          swal({
            title : "ID Not Found!",
            text  : "Please try again after refreshing the page.",
            icon  : "error"
          });
          return false;
        } else {
          swal({
            title : "Are you sure?",
            text  : "Do you want to approve clicked expense?",
            icon  : "warning",
            buttons : [true, "Yes, Approve"],
            dangerMode : true
          }).then(function(isConfirm){
            if (!isConfirm) {
              return false;
            } else {
             // $("#loading-bg").show();
             $.ajax({
              url: '/expense/approve-expense',
              type: 'POST',
              data: {expense_id: id,approve : approved,createdby :createdby},
              success:function(data){
                // $("#loading-bg").hide();
                console.log(data);
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : 'success'
                  }).then(function(){
                   window.location.reload('/expense/office-expenses');
                 });
                } else {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : 'error'
                  });
                }
              }
            });
           }
         }); 
        }
      }
    </script>

