<script type="text/javascript">
      AmCharts.makeChart("chartDivNew2", {
          "type": "serial",
          "categoryField": "category",
          "colors": [
            "#990000",
            "#B0DE09",
            "#0D8ECF",
            "#2A0CD0",
            "#CD0D74",
            "#CC0000",
            "#00CC00",
            "#0000CC",
            "#DDDDDD",
            "#999999",
            "#333333",
            "#990000"
          ],
          "startDuration": 1,
          "handDrawThickness": 3,
          "theme": "default",
          "categoryAxis": {
            "gridPosition": "start" ,
            "labelRotation": 60
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true
          },
          "trendLines": [],
          "graphs": [
            {
              "fillAlphas": 1,
              "id": "AmGraph-1",
              "title": "graph 1",
              "type": "column",
              "valueField": "column-1"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1",
              "title": ""
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [
            {
              "id": "Title-1",
              "size": 12,
              "text": ""
            }
          ],

          "dataProvider": [
           <?php if( sizeof($this->datewiseofficeamount) > 0 ){ ?>
           <?php foreach ($this->datewiseofficeamount as $keyoffice) { 
            $total_chars = strlen(trim($keyoffice['transfer_for']));
            if($total_chars > 20 ){
            $transfer_for = wordwrap($keyoffice['transfer_for'],15,"<br>");
            }else { $transfer_for = $keyoffice['transfer_for']; }
            ?>
            {
              "category": "<?php echo $transfer_for."<br>"."(".$keyoffice['transfer_date'].")"; ?>",
              "column-1": <?php echo $keyoffice['sum']; ?>
            }, 
            <?php } ?>
            <?php } else { ?>
              {
              "category": "",
              "column-1": ""
            },
            <?php } ?>
           ]
        }
      );
</script>
<div id="chartDivNew2"></div>