<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>

<div class="siteExpenseDiv">
  <form action="/expense/fund-transfer" method="POST" enctype="multipart/form-data" onsubmit="return validateSiteExpenseInputData()">
   <input type="hidden" name="transferType" id="transferType" value="2">
   <input type="hidden" name="transferTypeName" id="transferTypeName" value="Site fund">
   <div class="row">
    <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h2 align="center" style="text-decoration: underline;">Site Fund Transfer Form</h2>
    </div>
  </div>
  <br clear="all">
  <div class="row">

    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <label for="company_id">Company<span id="mandatory">*</span></label>
      <select id="company_id" name="company_id" class="form-control select2" required="required">
        <option value="">Please Company</option>
        <?php foreach ($this->companies as $company): ?>
          <option value="<?php echo $company['id']; ?>"><?php echo $company['name']; ?></option>
        <?php endforeach ?>
      </select>
    </div>



    <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
     <label for="siteExpenseDateOfTransfer">Date of Transfer<span id="mandatory">*</span></label>
     <input type="text" class="form-control datepicker" name="siteExpenseDateOfTransfer" id="siteExpenseDateOfTransfer" readonly="" value="<?php if(isset($this->params['siteExpenseDateOfTransfer'])){ echo $this->params['siteExpenseDateOfTransfer']; } else { echo date('d/m/Y'); } ?>">
   </div>
   <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <label for="poNumber">PO Number <span id="mandatory">*</span></label>
    <select name="poNumber" id="poNumber" class="form-control select2" onchange="getSitesByPoNumber()">
      <option value="">Select PO Number</option>
      <option value="new">Add New PO</option>
      <?php foreach ($this->poNumbers as $poNumber): ?>
        <option value="<?php echo $poNumber['po_no']; ?>"<?php if(isset($this->params['poNumber'])) { echo $this->params['poNumber'] == $poNumber['po_no']?"selected":"";} ?>><?php echo $poNumber['po_no']; ?></option>
      <?php endforeach ?>
    </select>
  </div>
  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <label for="siteId">Site ID<span id="mandatory">*</span></label>
    <select name="siteId" id="siteId" class="form-control select2">
      <option value="">Select Site ID</option>
    </select>
  </div>
  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <label for="siteExpenseTransferAmount">Transfer Amount<span id="mandatory">*</span></label>
    <input type="text" class="form-control" name="siteExpenseTransferAmount" id="siteExpenseTransferAmount" oninput="this.value = this.value.replace(/[^0-9.]/g, '');" value="<?php if(isset($this->params['siteExpenseTransferAmount'])){ echo $this->params['siteExpenseTransferAmount']; } ?>">
  </div>

  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <label for="siteExpenseTransferRemark">Transfer To <span id="mandatory">*</span></label>
    <select class="form-control mandatorySelect transferTo select2" name="amountTransferTo" id="amountTransferTo" onchange="otherPayeeForm()">
      <option value="">Please Select</option>
      <option value="payee">Other Payee</option>
      <optgroup label="Users">
        <?php foreach ($this->userList as $user): ?>
          <option value="<?php echo $user['name'].'-user-'.$user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
        <?php endforeach ?>
      </optgroup>
      <optgroup label="Payee">
        <?php foreach ($this->Payees as $payee): ?>
          <option value="<?php echo $payee['payee_name'].'-payee-'.$payee['id']; ?>"><?php echo ucwords(strtolower($payee['payee_name'])); ?></option>
        <?php endforeach ?>
      </optgroup>
      <optgroup label="Vendors">
        <?php foreach ($this->vendorList as $vendor): ?>
          <option value="<?php echo $vendor['vendor_name'].'-vendor-'.$vendor['id']; ?>"><?php echo $vendor['vendor_name']." (".$vendor['contact_person'].")"; ?></option>
        <?php endforeach ?>
      </optgroup>
      <?php if ($this->transporterList): ?>
        <optgroup label="Transporters">
          <?php foreach ($this->transporterList as $transporter): ?>
            <option value="<?php echo $transporter['transporter_name'].'-transporter-'.$transporter['id']; ?>"><?php echo $transporter['transporter_name']; ?></option>
          <?php endforeach ?>
        </optgroup>
      <?php endif ?>
      <optgroup label="Material Suppliers">
        <?php foreach ($this->materialSupplierList as $materialSupplier): ?>
          <option value="<?php echo $materialSupplier['supplier_name'].'-supplier-'.$materialSupplier['id']; ?>"><?php echo $materialSupplier['supplier_name']; ?></option>
        <?php endforeach ?>
      </optgroup>
    </select>
  </div>
  <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
    <label for="siteExpenseTransferRemark">Remarks (if any)</label>
    <input type="text" class="form-control" name="siteExpenseTransferRemark" id="siteExpenseTransferRemark" value="<?php if(isset($this->params['siteExpenseTransferRemark'])){ echo $this->params['siteExpenseTransferRemark']; } ?>">
  </div>

  <div class="clearfix"></div>
  <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <label for="bank_account_id">Bank Account<span id="mandatory">*</span></label>
    <select name="bank_account_id" id="bank_account_id" class="form-control select2" required="required">
      <option value="">Select Bank Account</option>
      <?php foreach ($this->bank_accounts as $bank_account): ?>
        <option value="<?php echo $bank_account['id']; ?>"><?php echo $bank_account['bank_name']."(".$bank_account['bank_account_number'].")"; ?></option>
      <?php endforeach ?>
    </select>
  </div>

  <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <label for="payment_mode_id">Payment Mode <span id="mandatory">*</span></label>
    <select name="payment_mode_id" id="payment_mode_id" class="form-control select2" required="required">
      <option value="">Select Payment Mode</option>
      <?php foreach ($this->payment_modes as $payment_mode): ?>
        <option value="<?php echo $payment_mode['id']; ?>"><?php echo $payment_mode['payment_mode']; ?></option>
      <?php endforeach ?>
    </select>
  </div>
  <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <label for="recommended_by">Recommended By <span id="mandatory">*</span></label>
    <select name="recommended_by" id="recommended_by" class="form-control select2" required="required">
      <option>Select</option>
      <?php foreach ($this->userList as $user): ?>
        <option value="<?php echo $user['name'].'-user-'.$user['id']; ?>"><?php echo ucwords(strtolower($user['name'])); ?></option>
      <?php endforeach ?>
    </select>
  </div>
  <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <label for="approved_by">Approved By <span id="mandatory">*</span></label>
    <select name="approved_by" id="approved_by" class="form-control select2" required="required">
      <option>Select</option>
      <option value="Shantanu_Rai">Shantanu Rai</option>
      <option value="Vipul_Rai">Vipul Rai</option>
      <option value="Richa_Rai">Richa Rai</option>
    </select>
  </div>

</div>

<br clear="all">

<div class="row" id="saveButtonDiv">
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
    <button type="submit" class="btn btn-success" style="float: right;">Save Fund Data</button>
  </div>
</div>
</form>
</div>
<script>
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true, maxDate:0 });
  });
</script>