
<style type="text/css">
  .table th ,   .table td , .table div{
    padding: 3px;
    text-align: left;
  } 
  #scroll-id {
    width: 600px;
  }
  @media print{
    .noprint {display:none !important; }
  }
</style>

<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Expenses List (<?php echo $this->poAndSite['po_no']; ?> - <?php echo $this->poAndSite['site_id']; ?>)
          <div class="pull-right">
            <a href="/expense" class="btn btn-success">View Site Expense</a>
          </div></h3>
        </div>
        <!--exportSiteExpenseDetailsAction-->
        <a href="/expense/export-site-expense-details/po-number/<?php echo $this->po_number; ?>/site-id/<?php echo $this->site_id; ?>" class="btn btn-info"  type="submit"   title="file-excel" style="margin-bottom: 5px;float:right;margin-right: 15px;"><i class="glyphicon glyphicon-circle-arrow-down" ></i></a> 
        <a href="/expense/export-site-expense-row-wise-details/po-number/<?php echo $this->po_number; ?>/site-id/<?php echo $this->site_id; ?>" class="btn btn-info"  type="submit"   title="row-wise-file-excel" style="margin-bottom: 5px;float:right;margin-right: 15px;"><i class="glyphicon glyphicon-circle-arrow-down" ></i></a> 
        <div class="panel panel-body">
          <div class="table-responsive" id="user-list">
            <table class="display" width="100%" id="siteExpenseDetailsTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Company</th>
                  <th>Transfer Date</th>
                  <th>Transfer Amount</th>
                  <th>Spent Amount</th>
                  <th>C&F Amount</th>
                  <th>Transefer Type</th>
                  <th>Transfer To</th>
                  <th>Bank Account</th>
                  <th>Payment Mode</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <?php 
                if($this->siteExpenseDetails){ 
                  $i = 0;
                  foreach($this->siteExpenseDetails as $siteExpense){ ?>
                    <tr id="row_<?php echo $siteExpense['id']; ?>">
                      <td><?php echo $i+1;?>.</td>
                      <td><?php echo $siteExpense['company']; ?></td>
                      <td><?php if($siteExpense['transfer_date'] == '0000-00-00') {
                        echo '00/00/0000';
                      } else {
                        echo date('d/m/Y', strtotime($siteExpense['transfer_date']));
                      } ?></td>
                      <td><b><a href="javascript:void(0)" title="View Details" onclick="showDetailedExpenses(<?php echo $siteExpense['id']; ?>)"><?php echo $siteExpense['amount']; ?></a></b></td>
                      <td><span style="color:#337ab7;" ><b><?php echo number_format((float)$siteExpense['totalBalance'], 2, '.', '') ; ?></b></span></td>
					  <td>
                      <?php if($siteExpense['amount']-$siteExpense['totalBalance'] > 0) { ?>
                      <span style="color:red;" ><b><?php echo $siteExpense['amount']-$siteExpense['totalBalance']; ?></b></span>
                      <?php } else if($siteExpense['amount']-$siteExpense['totalBalance'] < 0){ ?>
                        <span style="color:green;" ><b><?php echo $siteExpense['amount']-$siteExpense['totalBalance']; ?></b></span>
                      <?php } else if($siteExpense['amount']-$siteExpense['totalBalance'] == 0){ ?>
                      <span style="color:#337ab7;" ><b><?php echo $siteExpense['amount']-$siteExpense['totalBalance']; ?></b></span>
                      <?php }?>
                      </td>
                      <td><?php echo ucwords(strtolower($siteExpense['allocation_type'])); ?></td>
                      <td><?php echo $siteExpense['transfer_to_name']; ?></td>
                      <td><?php echo $siteExpense['bank_name']; ?><br><?php echo $siteExpense['bank_account_number']; ?></td>
                      <td><?php echo $siteExpense['payment_mode']; ?></td>
                      <td>
                         
                          <?php if (($this->role_type == 1 && $this->role == 1) || ($this->role_type == 1 && $this->role == 3)){ ?>
                           <a href="javascript:void(0)" title="Delete Expense" onclick="deleteExpense(<?php echo $siteExpense['id']; ?>,'site_expense')"><i class="fa fa-trash" style="color: red;"></i></a> 
                        <?php } ?>
                         
                      </td>
                    </tr>
                    <?php  $i++; } } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      </div>

      <script>
        $(document).ready(function() {
          $("#siteExpenseDetailsTable").DataTable();
        });
        function showDetailedExpenses(expense_id) {
          $.ajax({
            url: '/expense/get-expense-details',
            type: 'POST',
            data: {expenseId:expense_id},
            success:function(data){
              $('#myModal').html(data);
              $('#myModal').modal('toggle');
            }
          });
        }
        function deleteExpense(expense_id, type) {
          if (expense_id == '') {
            swal({
              title : "ID Not Found!",
              text  : "Please try again after refreshing the page.",
              icon  : "error"
            });
            return false;
          } else {
            swal({
              title : "Are you sure?",
              text  : "Do you want to delete clicked expense?",
              icon  : "warning",
              buttons : [true, "Yes, Delete"],
              dangerMode : true
            }).then(function(isConfirm){
              if (!isConfirm) {
                return false;
              } else {
               $("#loading-bg").show();
               $.ajax({
                url: '/expense/delete-expense',
                type: 'POST',
                data: {expense_id: expense_id, type:type},
                success:function(data){
                  $("#loading-bg").hide();
                  console.log(data);
                  var data = JSON.parse(data);
                  if (data.flag) {
                    swal({
                      title : data.title,
                      text  : data.message,
                      icon  : 'success'
                    }).then(function(){
                      $("#row_"+expense_id).remove();
                        // window.location.reload();
                      });
                  } else {
                    swal({
                      title : data.title,
                      text  : data.message,
                      icon  : 'error'
                    });
                  }
                }
              });
             }
           }); 
          }
        }
      </script>

