<?php
$site_data = $this->result_main_array_site;
$office_data = $this->result_main_array_office;
?>

<style type="text/css">
#scroll-id-two {
  min-height: 200px;
}
@media print{
  .noprint {display:none !important; }
}
</style>

<div class="row">
  <div class="col-md-9"></div>
  <div class="col-md-1">
    <button style="float:right;" type="button" class="btn btn-warning"  onclick="CallPrint('divchallan');">Print <i class="fa fa-print"></i></button> 
  </div>
  <div class="col-md-2">
    <a href="javascript:void(0)" style="float:left;" class="btn btn-success" onclick="exportTable2()">Export To Excel</a> 
  </div>
</div>

<br/>

<div id="scroll-id-two">

  <div id="divchallan" style="width:100%; height:auto;color:black;">
    <div role="tabpanel">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <button type="button" class="btn btn-success" aria-controls="home" role="tab" data-toggle="tab">Site Expenses</button>
        </li><br/><br/>
        <li role="presentation">
          <button type="button" class="btn btn-success" aria-controls="home" role="tab" data-toggle="tab">Office Expenses</button>
        </li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
         <table class="table table-bordered table2excel2" border="1">
           <thead>
            <h5 align="center">TOTAL SITE EXPENSES LIST</h5>
            <tr>
              <th style=" white-space:nowrap;">#</th>
              <th style=" white-space:nowrap;">PO</th>
              <th style=" white-space:nowrap;">Site Id</th>
              <th style=" white-space:nowrap;">Amount</th>
              <th style=" white-space:nowrap;">Transfer Date</th>
              <th style=" white-space:nowrap;">Transferred For</th>
              <th style=" white-space:nowrap;">Transferred To</th>
              <th style=" white-space:nowrap;">Remark</th>
              <th style=" white-space:nowrap; " class="noprint">Attachment</th>
            </tr>
          </thead>
          <?php 
          $i=0; 
          foreach($site_data as $key){ ?>
            <tr>
              <td style=" white-space:nowrap;"><?php echo $i+1;?>.</td>
              <td style=" white-space:nowrap;"><?php echo $key['po_no']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key['site_id']; ?></td> 
              <td style=" white-space:nowrap;"><?php echo $key['amount']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key['transfer_date']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key['transfer_for']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key['transfered_to']; ?></td>
              <td style=" min-width:250px;"><?php echo $key['remark']; ?></td>
              <td style=" white-space:nowrap;" class="noprint">
                <?php if($key['attachment']==''){ echo "-"; } else { ?>
                 <a href="<?php echo $key['attachment']; ?>" download>
                  <i class="fa fa-download"></i></a>
                <?php } ?>
              </td>
            </tr>
            <?php $i++; } ?>          
          </table>

        </div>
        <div role="tabpanel" class="tab-pane" id="tab">

          <table class="table table-bordered table2excel2" border="1">
           <thead>
            <h5 align="center">TOTAL OFFICE EXPENSES LIST</h5>
            <tr>
              <th style=" white-space:nowrap;">#</th>
              <th style=" white-space:nowrap;">Amount</th>
              <th style=" white-space:nowrap;">Transfer Date</th>
              <th style=" white-space:nowrap;">Transferred For</th>
              <th style=" white-space:nowrap;">Transferred To</th>
              <th style=" white-space:nowrap;">Remark</th>
              <th style=" white-space:nowrap; " class="noprint">Attachment</th>
            </tr>
          </thead>
          <?php 
          $i=0; 
          foreach($office_data as $key1){ ?>
            <tr>
              <td style=" white-space:nowrap;"><?php echo $i+1;?>.</td>
              <td style=" white-space:nowrap;"><?php echo $key1['amount']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key1['transfer_date']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key1['transfer_for']; ?></td>
              <td style=" white-space:nowrap;"><?php echo $key1['transfered_to']; ?></td>
              <td style=" min-width:250px;"><?php echo $key1['remark']; ?></td>
              <td style=" white-space:nowrap;" class="noprint">
                <?php if($key1['attachment']==''){ echo "-"; } else { ?>
                 <a href="<?php echo $key['attachment']; ?>" download>
                  <i class="fa fa-download"></i></a>
                <?php } ?>
              </td>
            </tr>
            <?php $i++; } ?>          
          </table>
        </div>
      </div>
    </div>
  </div>
</div>