<?php 
$customer_tower_code = array('Indus Towers Limited'=>'cust-i', 'Bharti Airtel Limited'=> 'cust-b' );
$customer_call_type_code = array('BD'=>'call-b', 'PM'=>'call-p');
$customer_product_type_code = array('AC'=>'product-a','PIU'=>'product-p');

?>
<!DOCTYPE html>
<html>
  <head>
    <title>Customer Map</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px	
      }
	       #legend {
        font-family: Arial, sans-serif;
        background: #fff;
        padding: 10px;
        margin: 10px;
        border: 1px solid #ededed;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js"></script>    <script src="/gmap/load-geo-json?customer=<?php if($this->params['customer']!=''){ echo $this->params['customer']; } ?>&circle=<?php if($this->params['circle']!=''){ echo $this->params['circle']; } ?>&call_type=<?php if($this->params['call_type']!=''){ echo $this->params['call_type']; } ?>&product_type=<?php if($this->params['product_type']!=''){ echo $this->params['product_type']; } ?>" type="text/javascript"></script>
    <script>
var map;
var title_content;
<?php if($this->params['clustered']=='1'){ ?>
var showCluster = true;

<?php }else{ ?>
var showCluster = false;
<?php } ?>
function initialize() {
  // Create a simple map.
  map = new google.maps.Map(document.getElementById('map-canvas'), {
  });
var markerBounds = new google.maps.LatLngBounds();
var markers = [];
for (var i = 0; i < data.site_count; ++i) {
		var title_content = "";
var myLatlng = new google.maps.LatLng(data.site_list[i].lat,data.site_list[i].long);
    markerBounds.extend(myLatlng);
if(showCluster){
var marker = new google.maps.Marker({
    position: myLatlng,
	icon: data.site_list[i].icon,
	optimized: false
});
}else{
var marker = new google.maps.Marker({
    position: myLatlng,
	icon: data.site_list[i].icon,
	optimized: false,
	map:map
});
	
}
	title_content = "<div><div><strong>Customer:</strong>"+data.site_list[i].cust_name+"</div>"+
	"<div><strong>Site Id:</strong>"+data.site_list[i].site_id+"</div>"+
	"<div><strong>Call Type:</strong>"+data.site_list[i].call_type+"</div>"+
	"<div><strong>Product:</strong>"+data.site_list[i].product_type+"</div>"+
	"<div><strong>Call Log No:</strong>"+data.site_list[i].call_log_no+"</div></div>";
  google.maps.event.addListener(marker, 'click', function() {
 infowindow = new google.maps.InfoWindow({
    content: title_content
  });
    infowindow.open(map, this);
  });
// To add the marker to the map, call setMap();
markers.push(marker);
}
map.fitBounds(markerBounds);

if(showCluster){
	var markerCluster = new MarkerClusterer(map, markers,{
          gridSize: 5
        });
}else{
//markers.setMap(map);	
	}
var legend = document.getElementById('legend');	
map.controls[google.maps.ControlPosition.RIGHT_TOP].push(legend);	
  // Load a GeoJSON from the same server as our demo.
  //map.data.loadGeoJson('http://apps.acme.in:9030/gmap/load-geo-json?user=<?php //echo $this->user; ?>');
/*  var featureStyle = {
    strokeColor: 'green',
    strokeWeight: 5
  }

  map.data.setStyle(featureStyle);
*/
<?php foreach($this->users as $single_job){ 
if($single_job['current_latitude'] !='' && $single_job['current_longitude'] !=''){ 
?>
var myLatlng = new google.maps.LatLng(<?php echo $single_job['current_latitude']; ?>,<?php echo $single_job['current_longitude']; ?>);

var marker = new google.maps.Marker({
    position: myLatlng,
    title:"<?php echo $single_job['StaffName'].' ('.$single_job['StaffCode'].')'; ?>",
	icon: 'http://apps.acme.in:9030/images/map-icons/current-loc.png',

});
  google.maps.event.addListener(marker, 'click', function() {
	infowindow = new google.maps.InfoWindow({
    content: "<div><div><strong>Staff Name:</strong><?php echo $single_job['StaffName']; ?></div>"+
	"<div><strong>Staff Code:</strong><?php echo $single_job['StaffCode']; ?></div></div>"	
	
  });	  
    infowindow.open(map, this);
  });

marker.setMap(map);
<?php }} ?>

}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
 
<div id="map-canvas"></div>
<div id="legend"><a target="_blank" href="/gmap/customer?customer=<?php if($this->params['customer']!=''){ echo $this->params['customer']; } ?>&circle=<?php if($this->params['circle']!=''){ echo $this->params['circle']; } ?>&call_type=<?php if($this->params['call_type']!=''){ echo $this->params['call_type']; } ?>&product_type=<?php if($this->params['product_type']!=''){ echo $this->params['product_type']; } ?>&clustered=<?php if($this->params['clustered']!=''){ echo $this->params['clustered']; } ?>">Full Map</a></div>
  </body>
</html>

