<html>
<head>
<style>
ul li{
list-style: outside none none;	
	}
ul{
padding:0 0 0 10px;
}	
</style>
</head>
<body>

<table style="width:100%">
<tr>
<th style="text-align:left">
Customer
</th>
<th  style="text-align:left">
Call Type
</th>
<th style="text-align:left">
Product
</th>
</tr>
<tr>
<td>
<ul>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-i.gif" /> Indus Towers Limited
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-b.gif" /> Bharti Airtel Limited
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-o.gif" /> Others
</li>
</ul>
</td>
<td>
<ul>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-i.gif" /> BD
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-b.gif" /> PM
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-o.gif" /> Others
</li>
</ul>
</td>
<td>
<ul>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-i.gif" /> AC
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-b.gif" /> PIU
</li>
<li>
<img src="http://apps.acme.in:9030/images/map-icons/cust-o.gif" /> Others
</li>
</ul>
</td>



</tr>
</table>
</body>
</html>