<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">
<script src="/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />
<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>
 <!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
 <script type="text/javascript">
$(function(){
	$('#legend-help').click( function() {
			//var sData = $('#user-track-form').serialize(); 
				//var data = $.trim(sData);
				$.fancybox({ 
							'padding'          : 10, 
							'autoScale'        : false, 
							'transitionIn'     : 'fade', 
							'transitionOut'    : 'fade', 
							'title'            : this.title, 
 
							'href'             : '/gmap/legend-help', 
							'type'             : 'iframe' 
						}); 
				return false; 
			
	}); 
	}); 
</script>	
<style>
ul.breadcrumb-top li{
	 display:inline-block;
	 position:relative;
	 margin:1em 0;
}
ul.breadcrumb-top{
	 float:right;
	 width:50%;	
	}
</style>
<div class="content">
<form id="user-track-form" method="post" action="/gmap/customer" target="iframex">
  <div class="header">
    <h1 class="page-title" style="float:left;width:20%">Site Tracking</h1>
    <ul class="breadcrumb-top">
    <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
    <li><a href="/gmap/track">Tracking</a> <span class="divider">/</span></li>
	<li class="active">Site Track</li>
    <li> &nbsp;&nbsp;&nbsp;<input type="checkbox" name="clustered" value="1"> Show Group</li>
    <li>&nbsp;&nbsp;&nbsp;&nbsp;<a id='legend-help' href="javascript:void(0);"> <i class="icon-cog"></i> Legends help</a></li>
  </ul>
  </div>
  <ul class="breadcrumb" style="margin:0;padding:0;">
    <li>
          <fieldset>
          
            <div>
                <div  style="margin-top:7px">
               
                <select name="customer" id="customer"  class="input-large-reports_page" style="width:19%;">
				   <option value="">Customer</option>
				  <?php
				  foreach($this->customerList as $k)
				  {
					  
				  ?>
				  <option value="<?php echo $k['Customer_Name']?>"><?php echo $k['Customer_Name']?></option>
				  <?php
				   }
				  ?>
                  </select> 
                <select name="circle" id="circle"  class="input-large-reports_page" style="width:19% !important;">
				   <option value="">Circle</option>
				  <?php
				  foreach($this->circleList as $k)
				  {
					  
				  ?>
				  <option value="<?php echo $k['CircleCode']?>"><?php echo $k['CircleName']?> [<?php echo $k['CircleCode']?>]</option>
				  <?php
				  }
				  ?>
                  </select>
                <select name="call_type" id="call_type"  class="input-large-reports_page" style="width:19% !important;">
				   <option value="">CallType</option>
				  <?php
				  foreach($this->callTypeList as $k)
				  {
					  
				  ?>
				  <option value="<?php echo $k; ?>"><?php echo $k; ?></option>
				  <?php
				  } 
				  ?>
                  </select>
                <select name="product_type" id="product_type"  class="input-large-reports_page" style="width:19% !important;">
				  <option value="">Product</option>
				  <?php
				  foreach($this->productTypeList as $k)
				  {
					  
				  ?>
				  <option value="<?php echo $k['DescrID']?>"><?php echo $k['Descr']?> [<?php echo $k['ComplaintDescrGroup']?>]</option>
				  <?php
				   }
				  ?>
                  </select>
                
                <button style="width:19%" type="submit" class="btn btn-primary" name="DistanceGenerate" value="Generate">Track</button>
                </div>
            	<div class="clear"></div>
            </div>



          </fieldset>
        </li>
  </ul>
</form>
      <div class="row-fluid" style="margin-top:10px;">
     <iframe name='iframex' width="100%" height="800" frameborder="0"></iframe> 
    </div>
    
</div>
