<link rel="stylesheet" href="/css/datepicker/jquery.ui.all.css">
<script src="/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/js/jquery.timepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jquery.timepicker.css" />
<script type="text/javascript" src="/lib2/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/lib2/bootstrap-datepicker.css" />
<script src="/js/jquery.ui.core.js"></script>
<script src="/js/jquery.ui.widget.js"></script>
<script src="/js/jquery.ui.datepicker.js"></script>
 <!-- fancybox start here -->
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
 <script type="text/javascript">
$(function(){
	$('#legend-help').click( function() {
			//var sData = $('#user-track-form').serialize(); 
				//var data = $.trim(sData);
				$.fancybox({ 
							'padding'          : 10, 
							'autoScale'        : false, 
							'transitionIn'     : 'fade', 
							'transitionOut'    : 'fade', 
							'title'            : this.title, 
 
							'href'             : '/gmap/legend-help', 
							'type'             : 'iframe' 
						}); 
				return false; 
			
	}); 
$( "#circle" ).change(function(e) {

// alert($( "#circle" ).val());    
$.get( "/reports/get-cluster-by-circle", { circle_id: $( "#circle" ).val() }, "json" )
.done(function( data ) {
//alert( "Data Loaded: " + data );
  select = document.getElementById('cluster');
    select.options.length = 0;
    options = data.options; // Or whatever source information you're working with
    for (index = 0; index < options.length; ++index) {
      option = options[index];
      select.options.add(new Option(option.text, option.value));
    }
	
});

});

$( "#cluster" ).change(function(e) {

// alert($( "#circle" ).val());    
$.get( "/gmap/get-user-by-cluster", { cluster_id: $( "#cluster" ).val() }, "json" )
.done(function( data ) {
//alert( "Data Loaded: " + data );
  select = document.getElementById('field_user');
    select.options.length = 0;
    options = data.options; // Or whatever source information you're working with
    for (index = 0; index < options.length; ++index) {
      option = options[index];
      select.options.add(new Option(option.text, option.value));
    }
	
});

});	
	}); 
</script>	
<style>
ul.breadcrumb-top li{
	 display:inline-block;
	 position:relative;
	 margin:1em 0;
}
ul.breadcrumb-top{
	 float:right;
	 width:50%;	
	}
</style>
	

<div class="content">
  <div class="header">
    <h1 class="page-title" style="float:left;width:20%">User Tracking</h1>
    <ul class="breadcrumb-top">
    <li><a href="/dashboard">Home</a> <span class="divider">/</span></li>
    <li><a href="/gmap/track">Tracking</a> <span class="divider">/</span></li>
	<li class="active">Track User</li>
    <li>&nbsp;&nbsp;&nbsp;&nbsp;<a id='legend-help' href="javascript:void(0);"> <i class="icon-cog"></i> Legends help</a></li>
  </ul>
  </div>

  <ul class="breadcrumb" style="margin:0;padding:0;">
    <li style="width:100%">
    <div  style="margin-top:7px">

    <form id="user-track-form" method="post" action="/gmap/index" target="iframex">
          <fieldset>
          
<div class="frmRow">
&nbsp;&nbsp; <input type="text" name="user_staff_code" class="input-small" id="user_id" placeholder="Staff Code"> OR 

<select name="circle" id="circle"  class="input-large-reports_page" style="width:19%;">
				   <option value="">Select Circle</option>
				  <?php
				  foreach($this->circle as $k)
				  {
					  if(in_array($k['CircleCode'],$this->current_user_circle)){
				  ?>
				  <option value="<?php echo $k['CircleCode']?>"><?php echo $k['CircleName']?> [<?php echo $k['CircleCode']?>]</option>
				  <?php
				  } }
				  ?>
                  </select>
<select name="cluster" id="cluster"  class="input-large-reports_page" style="width:19%;">
<option value="-1">Select Cluster</option>     
</select>
<select name="user" id="field_user"  class="input-large-reports_page" style="width:19%;">
<option value="-1">Staff Code</option>     
</select>
<button type="submit" class="btn btn-primary" name="submit" value="submit" style="width:19%;">Track User</button>

<div class="clear"></div>
            </div>

          </fieldset>
        </form>
             
                   
    </div>
    </li>
    </ul>
  <div class="container-fluid" style="padding-top:162px;">
	

    <div class="row-fluid" style="margin-top:10px;">
     <iframe name='iframex' width="100%" height="800" frameborder="0"></iframe> 
    </div>
    
  </div>
</div>
