 <script type="text/javascript" src="/js/jquery.min.js"></script>
 <script>
     $(document).ready(function() {
        $("#user_type").select2();
        $("#user").select2();
    });
     function validateVal()
     {
        if(document.getElementById('user').value=='')
        {
            alert('Please select user');    
            document.getElementById("user").focus();
            return false;
        }
    };

    function getUserList(user_type){
        //alert($( "#project" ).val());    
        $.get( "/gmap/get-user-list", { user_type: $( "#user_type" ).val() }, "json" )
        .done(function( data ) {
            // alert('hihiihi'); 
        //alert( "Data Loaded: " + data );
        select = document.getElementById('user');

            // Clear the old options
            select.options.length = 0;

            // Load the new options
            options = data.options; // Or whatever source information you're working with
            for (index = 0; index < options.length; ++index) {
              option = options[index];
              select.options.add(new Option(option.text, option.value));
          }
          
      });
    }
</script>
<div class="">
    <!-- Content Header (Page header) -->

       <!--  <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i> Site Allocation List Data</h4>
                </div>
            </div>
        </div> -->
        <br clear="all">
        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <div class="alert_data">
                            <?php echo $message ?>.
                        </div>
                    <?php endforeach ?>
                </div>
            <?php endif ?>
            
            
            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                       <div class="card-header card-info text-white">
                        <p style="float: left; margin: 0px; color: #fff;">Track User
                        </p>
                    </div>
                    
                    <div class="card-block" style="height: 900px;">
                        <form name="search" id="search" method="post" action="/gmap/index" target="iframex" onsubmit="return validateVal();">
                            <div class="row basic_tables">
                                <div class="p-12 col-12">
                                    <div class="form-group row">
                                        <div class="col-lg-2 m-t-10">
                                            <select name="user_type" id="user_type" onchange="getUserList(this.value)" class="form-control" tabindex="-1" >
                                                <option value="">-Select User Type-</option>
                                                <option value="vendor">Vendor</option>
                                                <option value="staff">Staff</option>
                                            </select>
                                        </div> 
                                        <div class="col-lg-2 m-t-10">
                                            <select name="user" id="user" class="form-control">
                                                <option value="">-Select User-</option>

                                            </select>
                                        </div> 
                                        <div class="col-lg-2 m-t-10">
                                            <input type="text" name="dates" id="date" value="<?php echo date('d/m/Y');?>" placeholder="DueDate" data-date-format="dd/mm/yyyy" name="date" class="form-control  datepick" >
                                        </div> 
                                        <div class="col-lg-1">
                                          <div class="col-12 m-t-10">
                                              <button type="submit" style="float: right;" name="submit" class="btn btn-responsive layout_btn_prevent btn-primary" id="load" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Create Mapping"><span class="ladda-label">Track</span><span class="ladda-spinner"></span></button>
                                          </div>
                                      </div>

                                  </div>
                              </div>
                          </div>
                      </form>
                      <div class="row basic_tables">
                        <div class="col-12">
                            <div class="table-responsive mt-0" id="my-siteallocation" style="padding:0px !important;">
                               <iframe name='iframex' width="100%" height="800" frameborder="0"></iframe>   
                               
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
   <!-- /.content -->
</div>
</div>

