<?php
    $params = $this->params;
    $getAdminRecord = $this->getAdminRecord;
?>
<script type="text/javascript">
    function validateUser(){ 
        if(document.getElementById("name").value==""){
            alert("Please Enter Name.");
            document.getElementById("name").focus();
            return false;
        }

        // if(document.getElementById("email").value==""){
        //     alert("Please Enter Email.");
        //     document.getElementById("email").focus();
        //     return false;
        // }
        
        if(document.getElementById("oldPassword").value!=""){
            if(document.getElementById("newPassword").value==""){
            alert("Please Enter New Password.");
            document.getElementById("newPassword").focus();
            return false;
            }

            if(document.getElementById("confirmPassword").value==""){
            alert("Please Enter Confirm Password.");
            document.getElementById("confirmPassword").focus();
            return false;
            }

            if(document.getElementById("newPassword").value!=document.getElementById("confirmPassword").value){
            alert("Password do not match, please enter valid password");
            document.getElementById("confirmPassword").focus();
            return false;
            }
        }
    }         
</script>
<div class="right-aside view-port-height">
<!-- Content Header (Page header) -->
        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i>  My Profile</h4>
                </div>
              
            </div>
        </div>

        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
            <div class="alert alert-success alert-dismissable">
            <?php foreach ($this->messages as $message): ?>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
            <?php endforeach ?>
            </div>
            <?php endif ?>
            <?php if($this->errorMessage) { ?>
            <br clear="all">
            <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php  echo $this->errorMessage;   ?>                                             
            </div>
            <?php } ?>
            <div class="row">
                <div class="col-12">
               
                   <div class="card  profile2_aboutme">
                   <div class="card-header card-primary text-white">
                                   <p style="float: left; margin: 0px;">Update Profile</p> <a href="/admin/my-profile"  style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">My  Profile</a>
                                    </div>
                                <div class="card-block ">
                                    
                                    <div class="row m-t-10">
                                        <div class="col-lg-12">
                                        <form name="changePassword" method="post" onsubmit="return validateUser();"  action="/admin/edit-profile"  >
                                        <input type="hidden" value="<?php  echo $getAdminRecord['id']; ?>" name="id" >
                                           <div class="form-group row">
                                        <div class="col-lg-6">
                                            <label for="first_name1" class="col-form-label">
                                                Name *
                                            </label>
                                            <div class="input-group">
                                                <input type="text" name="name" id="name" placeholder="Name" value="<?php echo $getAdminRecord['name'];?>" class="form-control">
                                            </div>
                                        </div>
                                         <div class="col-lg-6">
                                           <!-- <label for="first_name1" class="col-form-label">
                                                Email
                                            </label>
                                            <div class="input-group">
                                                <input type="text" class="form-control " id="first_name1" name="user1" placeholder="First name">
                                            </div>-->
                                        </div> 
                                        
                                        <div class="col-lg-6">
                                            <label for="first_name1" class="col-form-label">
                                                Old Password
                                            </label>
                                            <div class="input-group">
                                                <input type="password" name="oldPassword" id="oldPassword"  placeholder="Old Password" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <label for="first_name1" class="col-form-label">
                                                New Password
                                            </label>
                                            <div class="input-group">
                                                <input type="password" value="" class="form-control" name="newPassword" id="newPassword" placeholder="New Password">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <label for="first_name1" class="col-form-label">
                                                Confirm Password
                                            </label>
                                            <div class="input-group">
                                                <input type="password" value="" class="form-control" name="confirmPassword" id="confirmPassword" placeholder="Confirm Password">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-12">
                                            <button type="submit" name="submit" class="btn btn-responsive layout_btn_prevent btn-primary">Update</button>
                                        </div>
                                    </div>
                                    </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                </div>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>