    <?php $form = $this->form;?>
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6">
                <?php if($this->errorMessage) { ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px !important;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php  echo $this->errorMessage;   ?>   
                </div>
                <?php } if ($this->messages): ?>
                <?php foreach ($this->messages as $message): 
                if($message == 'error'){
                ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>Invalid Data
                </div>
                <?php }else{ ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
                </div>
                <?php } ?>
                <?php endforeach ?>
                <?php endif ?>
            <div class="login_box p-3">
            <div class="row m-t-20">
                <div class="col-lg-12 text-center">
                    <img src="/img/logo.png" class="img-fluid" alt="logo" />
                    <h5 class="text-white m-t-20">Forgot Password</h5></div>
                </div>

            <div class="m-t-15">
                <form action="/admin/forgotpassword" id="tryitForm" method="post" autocomplete="off">
                    <div class="form-group ">
                            <div class="input-group m-t-15">

                                <input type="text" name="email" class="form-control" id="email" placeholder="Email id" required>
                            </div>
                        </div>

                    <div class="row">
                            <div class="col-7 m-t-15 ">
                               <!--  <a href="login.html" class="forgottxt_clr text-white"><i class="fa fa-external-link"></i> Sign in</a> -->
                            </div>
                            <div class="col-5 m-t-15 text-right">
                               <a href="/admin" class="forgottxt_clr text-white"><i class="fa fa-external-link"></i> Sign in</a>
                            </div>
                        </div>
                   <div class="text-center login_bottom m-t-20 pb-3 ">
                            <button type="submit" class="btn btn-outline-white btn-block b_r_20 m-t-10  m-r-20">SUBMIT</button>
                    </div>

                </form>
            </div>

                <!-- <div class="row">
                        <div class="text-center col-lg-12 m-t    border-left:0;-20">
                            <h5 class="text-white">--Or--</h5>
                        </div>
                        <div class="col-lg-12 text-center mb-3">
                            <a href="#" class="btn login_fb btn-block">Sign in with <i class="ti-facebook"></i></a>
                            <a href="#" class="btn login_google btn-block">Sign in with <i class="ti-google"></i></a>

                        </div>
                </div> -->
            </div>
        </div>
    </div>