<?php $form = $this->form;?>
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6">
                <?php if($this->errorMessage) { ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px !important;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <?php  echo $this->errorMessage;   ?>   
                </div>
                <?php } if ($this->messages): ?>
                <?php foreach ($this->messages as $message): 
                if($message == 'error'){
                ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>Invalid Data
                </div>
                <?php }else{ ?>
                <br clear="all"><br clear="all">
                <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
                </div>
                <?php } ?>
                <?php endforeach ?>
                <?php endif ?>
            <div class="login_box p-3">
            <div class="row m-t-20">
                <div class="col-lg-12 text-center">
                    <img src="https://companies.naukri.com/aerial-dev/wp-content/uploads/sites/26483/2018/08/logo-web.jpg" class="img-fluid" alt="logo" />
                    <h5 class="text-white m-t-20">Login</h5></div>
                </div>

            <div class="m-t-15">
                <form action="/admin" id="tryitForm" method="post" autocomplete="off">
                    <div class="form-group ">
                        <div class="input-group ">
                            <span class="input-group-addon">
                                <i class="ti-user"></i>
                            </span>
                            <input type="email" name="email" class="form-control" id="email" placeholder="Email Address" required>
                        </div>
                    </div>
                    <div class="form-group ">
                    <div class="input-group m-t-15">
                            <span class="input-group-addon">
                                <i class="ti-lock"></i>
                            </span>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password"  required>
                    </div>
                    </div>

                   <!--  <div class="row m-t-15">
                        <div class="col-12">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input form-control">
                                <span class="custom-control-indicator"></span>
                                <a class="custom-control-description text-white">Keep me logged in</a>
                            </label>
                        </div>
                    </div> -->
                    <div class="text-center login_bottom">
                        <button type="submit" class="btn btn-success btn-block b_r_20 m-t-10 m-r-20">LOG IN</button>
                    </div>
                    <div class="row">
                        <div class="col-5 m-t-15 ">
                            <!-- <a href="" class="text-white">Forgot password ?</a> -->
                        </div>
                        <div class="col-7 m-t-15 text-right">
                            <!-- <a href="/admin/forgotpassword" class="text-white">Forgot password ?</a>
                            <a href="" class="forgottxt_clr text-white"><i class="fa fa-external-link"></i> Sign up</a> -->
                        </div>

                    </div>

                </form>
            </div>

                <!-- <div class="row">
                        <div class="text-center col-lg-12 m-t    border-left:0;-20">
                            <h5 class="text-white">--Or--</h5>
                        </div>
                        <div class="col-lg-12 text-center mb-3">
                            <a href="#" class="btn login_fb btn-block">Sign in with <i class="ti-facebook"></i></a>
                            <a href="#" class="btn login_google btn-block">Sign in with <i class="ti-google"></i></a>

                        </div>
                </div> -->
            </div>
        </div>
    </div>