<script type="text/javascript">
    function validateUser(){ 
            if(document.getElementById("newPassword").value==""){
            alert("Please Enter New Password.");
            document.getElementById("newPassword").focus();
            return false;
            }

            if(document.getElementById("confirmPassword").value==""){
            alert("Please Enter Confirm Password.");
            document.getElementById("confirmPassword").focus();
            return false;
            }

            if(document.getElementById("newPassword").value!=document.getElementById("confirmPassword").value){
            alert("Password do not match, please enter valid password");
            document.getElementById("confirmPassword").focus();
            return false;
            }

            if(document.getElementById("confirmotp").value ==""){
                alert("Enter OTP");
                document.getElementById("confirmotp").focus();
                return false;
            }
    }         
</script>
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6">
               <?php if($this->errorMessage) { ?>
                <br clear="all">
                    <div class="alert alert-danger alert-dismissable" style="margin-bottom: 0px !important;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <?php  echo $this->errorMessage;   ?>                                               
                    </div>
                    <?php } ?>
                    <?php if ($this->messages): ?>
                    <br clear="all">
                    <div class="alert alert-success alert-dismissable">
                    <?php foreach ($this->messages as $message): ?>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
                    <?php endforeach ?>
                    </div>
                    <?php endif ?>
            <div class="login_box p-3">
            <div class="row m-t-20">
                <div class="col-lg-12 text-center">
                    <img src="/img/logo.png" class="img-fluid" alt="logo" />
                    <h5 class="text-white m-t-20">Reset your password</h5></div>
                </div>

            <div class="m-t-15">
                <form action="/admin/reset-password/token/<?php echo $this->params['token'];?>" id="tryitForm" method="post" autocomplete="off">
                <input type="hidden" name="token" value="<?php echo $this->params['token'];?>">
                    <div class="form-group ">
                        <div class="input-group ">
                            <span class="input-group-addon">
                                <i class="ti-lock"></i>
                            </span>
                            <input type="password" name="newPassword" class="form-control" id="newPassword" placeholder="New Password" required>
                        </div>
                    </div>
                    <div class="form-group ">
                    <div class="input-group m-t-15">
                            <span class="input-group-addon">
                                <i class="ti-lock"></i>
                            </span>
                        <input type="password" name="confirmPassword" class="form-control" id="confirmPassword" placeholder="Confirm Password"  required>
                    </div>
                    </div>
                    <div class="form-group ">
                    <div class="input-group m-t-15">
                            <span class="input-group-addon">
                                <i class="ti-lock"></i>
                            </span>
                        <input type="text" name="confirmotp" class="form-control" id="confirmotp" placeholder="OTP"  required>
                    </div>
                    </div>

                   <!--  <div class="row m-t-15">
                        <div class="col-12">
                            <label class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input form-control">
                                <span class="custom-control-indicator"></span>
                                <a class="custom-control-description text-white">Keep me logged in</a>
                            </label>
                        </div>
                    </div> -->
                    <div class="text-center login_bottom">
                        <button type="submit" class="btn btn-success btn-block b_r_20 m-t-10 m-r-20">Update</button>
                    </div>

                </form>
            </div>

                <!-- <div class="row">
                        <div class="text-center col-lg-12 m-t    border-left:0;-20">
                            <h5 class="text-white">--Or--</h5>
                        </div>
                        <div class="col-lg-12 text-center mb-3">
                            <a href="#" class="btn login_fb btn-block">Sign in with <i class="ti-facebook"></i></a>
                            <a href="#" class="btn login_google btn-block">Sign in with <i class="ti-google"></i></a>

                        </div>
                </div> -->
            </div>
        </div>
    </div>