   <?php 
   $auth = Zend_Auth::getInstance();					
   $authStorage = $auth->getStorage();
 //echo "<pre>"; print_r($authStorage->read()); die;
   $name = $authStorage->read()->name;
   $lastLogin = $this->currdate = date("Y-m-d H:i:s",strtotime('+330 minutes'));  
   $front = Zend_Controller_Front::getInstance();
   $params= $front->getRequest()->getParams();
   $controller = $front->getRequest()->getControllerName(); 
   $action = $front->getRequest()->getActionName();
   $loginId = $authStorage->read()->id;
   $role = $authStorage->read()->role;
   $profile_image = $authStorage->read()->profile_path ?: '/img/user.jpeg';
   ?>

   <?php if(empty($authStorage->read()->id) && empty($authStorage->read()->role)) { ?>
   <?php } else  { ?>

      <!-- header-starts -->
      <div class="sticky-header header-section ">
         <div class="header-left">
            <!--toggle button start-->
            <button id="showLeftPush"><i class="fa fa-bars"></i></button>
            <!--toggle button end-->
            <div class="profile_details_left"><!-- notifications of menu start --> 
               <ul class="nofitications-dropdown">
                  <li class="dropdown head-dpdn">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">4</span></a>
                     <ul class="dropdown-menu">
                        <!-- <li>
                           <div class="notification_bottom">
                              <a href="#">See all messages</a>
                           </div> 
                        </li> -->
                     </ul>
                  </li>
                  <li class="dropdown head-dpdn">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">4</span></a>
                     <ul class="dropdown-menu">
                        <!-- <li>
                           <div class="notification_bottom">
                              <a href="#">See all notifications</a>
                           </div> 
                        </li> -->
                     </ul>
                  </li> 
                  <li class="dropdown head-dpdn">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1">8</span></a>
                     <ul class="dropdown-menu">
                        <!-- <li>
                           <div class="notification_header">
                              <h3>You have 8 pending task</h3>
                           </div>
                        </li>
                        <li><a href="#">
                           <div class="task-info">
                              <span class="task-desc">Database update</span><span class="percentage">40%</span>
                              <div class="clearfix"></div>  
                           </div>
                           <div class="progress progress-striped active">
                              <div class="bar yellow" style="width:40%;"></div>
                           </div>
                        </a></li> -->
                      <!--   <li>
                           <div class="notification_bottom">
                              <a href="#">See all pending tasks</a>
                           </div> 
                        </li> -->
                     </ul>
                  </li> 
               </ul>
               <div class="clearfix"> </div>
            </div>
            <!--notification menu end -->
            <div class="clearfix"> </div>
         </div>
         <div class="header-right">


            <!--search-box-->
            <!-- <div class="search-box">
               <form class="input">
                  <input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
                  <label class="input__label" for="input-31">
                     <svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
                        <path d="m0,0l404,0l0,77l-404,0l0,-77z"/>
                     </svg>
                  </label>
               </form>
            </div> -->
            <!--//end-search-box-->

            <div class="profile_details">    
               <ul>
                  <li class="dropdown profile_details_drop">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">  
                        
                           <?php if(!empty($authStorage->read()->profile_path)) { ?>
                                <span class="prfil-img">
                                    <img src="<?php echo $authStorage->read()->profile_path; ?>" alt="" height="50px" width="50px">
                                </span>
                            <?php } else { ?>
                                <span class="prfil-img">
                                    <img src="/img/user-img.png" alt="" height="50px" width="50px">
                                </span>
                            <?php } ?>
                           <div class="user-name">
                              <p><?php echo $name; ?></p>
                              <!-- <span>Administrator</span> -->
                           </div>
                           <i class="fa fa-angle-down lnr"></i>
                           <i class="fa fa-angle-up lnr"></i>
                           <div class="clearfix"></div>  
                        </div>   
                     </a>
                     <ul class="dropdown-menu drp-mnu"> 
                        <!--<li> <a href="#"><i class="fa fa-user"></i> My Profile</a> </li>  -->
                        <li> <a href="/home/logout"><i class="fa fa-sign-out"></i> Logout</a> </li>
                     </ul>
                  </li>
               </ul>
            </div>
            <div class="clearfix"> </div>          
         </div>
         <div class="clearfix"> </div> 
      </div>
      <!-- //header-ends -->

   <?php } ?>


