<?php 
$auth               = Zend_Auth::getInstance();
$authStorage        = $auth->getStorage();
$this->role_type    = $authStorage->read()->role_type;
$front = Zend_Controller_Front::getInstance();
$controller = $front->getRequest()->getControllerName(); 
$action = $front->getRequest()->getActionName(); 
?>
<!DOCTYPE HTML>
<html>
<head>
    <title>Genstree AI LLP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Glance Design Dashboard Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
    SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- JQuery UI CSS -->
    <link href="/assets/css/jquery-ui.css" rel='stylesheet' type='text/css' />
    <!-- JQuery DataTables CSS -->
    <link href="/assets/css/jquery.dataTables.min.css" rel='stylesheet' type='text/css' />
    <link href="/assets/css/fixedColumns.dataTables.min.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="/assets/css/buttons.dataTables.min.css">

    <!-- Custom CSS -->
    <link href="/assets/css/style.css" rel='stylesheet' type='text/css' />

    <!-- font-awesome icons CSS -->
    <link href="/assets/css/font-awesome.css" rel="stylesheet"> 
    <!-- //font-awesome icons CSS-->
    <!-- Sweet Alert CSS -->
    <link href="/assets/css/sweetalert.css" rel="stylesheet"> 
    <!-- //font-awesome icons CSS-->
    <!-- Select2 CSS -->
    <link rel="stylesheet" href="/assets/css/select2.min.css">
    <!-- Select2 CSS-->

    <!-- side nav css file -->
    <link href='/assets/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
    <!-- //side nav css file -->
    <!-- Favicon Icon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- // Favicon Icon -->
    <!-- js-->
    <script src="/assets/js/jquery-2.2.4.min.js"></script>
    <script src="/assets/js/modernizr.custom.js"></script>

    <!--webfonts-->
    <link href="/assets/fonts/fonts-googleapis" rel="stylesheet">
    <!--//webfonts--> 
    <style>
        #chartdiv {
          width: 100%;
          height: 295px;
      }
      #loading-bg {
        background: #44444473;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        margin: 0px auto;
        z-index: 9999;
        position: fixed;
    }
    #loading {
        background: url('/img/loader_gif.gif') no-repeat center;
        background-size: 250px 300px;
        position: absolute;
        top: 0;
        left: 0;
        margin: 0px auto;
        width: 100%;
        height: 100%;
        z-index: 9999;
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
    }
    .sub_active {
        background-color: #6F6358 !important;

    }
    .sub_active > a {
        color: white !important;
    }
    .sub_active > a:hover {
        background-color: #357971 !important;
    }
</style>
<!--pie-chart --><!-- index page sales reviews visitors pie chart -->
<script src="/assets/js/pie-chart.js" type="text/javascript"></script>
<!-- //pie-chart --><!-- index page sales reviews visitors pie chart -->

<!-- requried-jsfiles-for owl -->
<link href="/assets/css/owl.carousel.css" rel="stylesheet">
<script src="/assets/js/owl.carousel.js"></script>
<!-- //requried-jsfiles-for owl -->
</head> 
<body class="cbp-spmenu-push">
    <div id="loading-bg" style="display: none;">
        <div id="loading"></div>
    </div>
    <div class="main-content">
        <?php echo $this->render("header.phtml"); ?>
        <?php echo $this->render("navigation.phtml"); ?>
        <div class="card">
        <?php echo $this->layout()->content; ?>
        </div>
        <?php echo $this->render("footer.phtml"); ?>
    </div>

    <!-- JQuery UI JS -->
    <script src="/assets/js/jquery-ui.js"></script>
    <!-- SweetAlert JS -->
    <script src="/assets/js/sweetalert.min.js"></script>
    <!-- Data Table JS -->
    <!-- Select2 JS -->
    <script src="/assets/js/select2.min.js"></script>
    <!-- Select2 JS -->
    <script src="/assets/js/jquery.dataTables.js"></script>
    <script src="/assets/js/dataTables.fixedColumns.min.js"></script>
    <script src="/assets/js/dataTables.buttons.min.js"></script>
    <script src="/assets/js/jszip.min.js"></script>
    <script src="/assets/js/pdfmake.min.js"></script>
    <script src="/assets/js/vfs_fonts.js"></script>
    <script src="/assets/js/buttons.html5.min.js"></script>
    <!-- chart -->
    <script src="/assets/js/Chart.js"></script>
    <!-- Metis Menu -->
    <script src="/assets/js/metisMenu.min.js"></script>
    <script src="/assets/js/custom.js"></script>
    <link href="/assets/css/custom.css" rel="stylesheet">
    <!--//Metis Menu -->
    <!-- new added graphs chart js-->

    <script src="/assets/js/Chart.bundle.js"></script>
    <script src="/assets/js/utils.js"></script>


    <!-- Classie --><!-- for toggle left push menu script -->
    <script src="/assets/js/classie.js"></script>
    <script>
     var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
     showLeftPush = document.getElementById( 'showLeftPush' ),
     body = document.body;

     showLeftPush.onclick = function() {
      classie.toggle( this, 'active' );
      classie.toggle( body, 'cbp-spmenu-push-toright' );
      classie.toggle( menuLeft, 'cbp-spmenu-open' );
      disableOther( 'showLeftPush' );
  };


  function disableOther( button ) {
      if( button !== 'showLeftPush' ) {
       classie.toggle( showLeftPush, 'disabled' );
   }
}
</script>
<!-- //Classie --><!-- //for toggle left push menu script -->

<!--scrolling js-->
<script src="/assets/js/jquery.nicescroll.js"></script>
<script src="/assets/js/scripts.js"></script>
<!--//scrolling js-->

<!-- side nav js -->
<script src='/assets/js/SidebarNav.min.js' type='text/javascript'></script>
<script>
 $('.sidebar-menu').SidebarNav()
</script>
<!-- //side nav js -->

<!-- for index page weekly sales java script -->
<script src="/assets/js/SimpleChart.js"></script>



<!-- Bootstrap Core JavaScript -->
<script src="/assets/js/bootstrap.js"> </script>
<!-- //Bootstrap Core JavaScript -->

</body>
</html>