<?php
$getalldepartment = $this->getalldepartment;
$getRoletype = $this->getRoletype;
$getdepartment = $this->getalldepartment;
//print_r($getdepartment);
$params = $this->params;
$getUserRecord = $this->getUserRecord;
?>
  <script type="text/javascript" src="/js/jquery.min.js"></script>
  <script type="text/javascript">
     $(document).ready(function() {
                  $("#chosen2").select2();
                  $("#chossen2").select2();
                  $("#chosssen2").select2();
                  $("#chossssen2").select2();firm
                  $("#company").select2();
                  $("#firm").select2();
                  $("#v_status").select2();

                  var counter = 0;
                  $(".datepick").datepicker({ dateFormat: "dd MM yy" });
                  

                  $("#addrow").on("click", function () {
                      counter = $('#myTable tr').length - 2;
                      var newRow = $("<tr>");
                      var cols = "";
                      var length = $('#myTable tr').length;
                      cols += ' <td><input name="m_name[]" maxlength="100" placeholder="Title..." class="form-control "  type="text" required="" style="width: 110px;"></td>';
                      cols += '<td><select name="assign_to[]" class="form-control" id="chossen2'+length+'" style="width: 110px;" required=""><option value="">Select</option><?php foreach($getdepartment as $user){ ?><option value="<?php echo $user['id'];?>"><?php echo $user['department'];?></option><?php }?></select></td>';
                      cols += '<td><input name="experience[]" maxlength="100" placeholder="Title..." class="form-control "  type="text" required="" style="width: 110px;"></td>';
                       cols += '<td><input name="due_date[]" readonly="" placeholder="Due Date..." id="date" value="<?php echo date('d/m/Y')?>" class="form-control  datepick" data-date-format="dd/mm/yyyy" style="width: 110px;" name="date[]" type="text" required="" /></td>';
                      
                      cols += '<td style="padding:0.75rem"><button  name="action" type="delete" class=" btn btn-danger waves-effect waves-light ibtnDel"><i class="ti-trash"></i></button></td>';
                      newRow.append(cols);
                      //console.log (cols);
                      if (counter == 20) $('#addrow').attr('disabled', true).prop('value', "Done");
                      $("table.task-list").append(newRow);
                      counter++;
                      
                      $('#date', newRow).each(function(i) {
                          var newID = 'date[]' + counter;
                          $(this).attr('id', newID);
                      $(".datepick").datepicker({ dateFormat: "dd MM yy" });
                  });
                      $("#chosen2"+length).select2();
                      $("#chossen2"+length).select2();
                      $("#chosssen2"+length).select2();
                      $("#chossssen2"+length).select2();
                  });

                  $("table.task-list").on("click", ".ibtnDel", function (event) {
                      $(this).closest("tr").remove();
                      counter -= 1;
                      $('#addrow').attr('disabled', false).prop('value', "New Task");
                      $(".datepick").datepicker({ dateFormat: "dd MM yy" });
                    
                  });
      });  

      
  </script>
<script type="text/javascript">
  function validateUser(){
    if(document.getElementById("name").value==""){
      alert("Please Enter Name.");
      document.getElementById("name").focus();
      return false;
    }
    // if(document.getElementById("email").value==""){
    //     alert("Please Enter Email.");
    //     document.getElementById("email").focus();
    //     return false;
    // }
    if(document.getElementById("email").value==""){
      alert("Please Enter Email.");
      document.getElementById("email").focus();
      return false;
    }
    if(document.getElementById("mobile").value==""){
      alert("Please Enter Mobile Number.");
      document.getElementById("mobile").focus();
      return false;
    }
    
    if(document.getElementById("address").value==""){
      alert("Please Enter your address.");
      document.getElementById("address").focus();
      return false;
    }
    
    

    if(document.getElementById("firm").value==""){
      alert("Please Enter Constitution of Firm ");
      document.getElementById("firm").focus();
      return false;
    }
    if(document.getElementById("company").value==""){
      alert("Please select Nature of Company.");
      document.getElementById("company").focus();
      return false;
    }
    if(document.getElementById("gst").value==""){
      alert("Please select Vendor GST Number .");
      document.getElementById("gst").focus();
      return false;
    }
    if(document.getElementById("v_status").value==""){
      alert("Please select Vendor Status.");
      document.getElementById("v_status").focus();
      return false;
    }
  }
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $("#role_type").change(function(e) {
      //alert("hi");
      //alert($( "#project" ).val());    
      $.get( "/user/get-all-role", {
        role_type_id: $( "#role_type" ).val() }
            , "json" )
        .done(function( data ) {
        //alert(data);
        // alert('hihiihi'); 
        //alert( "Data Loaded: " + data );
        select = document.getElementById('role');
        // Clear the old options
        select.options.length = 0;
        // Load the new options
        options = data.options;
        // Or whatever source information you're working with
        for (index = 0; index < options.length; ++index) 
        {
          option = options[index];
          select.options.add(new Option(option.text, option.value));
        }
      }
             );
    }
                          );
  }
                   );
</script>
<div class="right-aside view-port-height">
  <!-- Content Header (Page header) -->
  <div class="content-header container-fluid bg-white">
    <div class="row">
      <div class="col-sm-4">
        <h4>
          <i class="ti-user">
          </i> Create New Vendor 
        </h4>
      </div>
    </div>
  </div>
  <!-- Main content -->
  <div class="content">
    <?php if ($this->messages): ?>
    <div class="alert alert-success alert-dismissable">
      <?php foreach ($this->messages as $message): ?>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
      </button>
      <?php echo $message ?>
      <?php endforeach ?>
    </div>
    <?php endif ?>
    <?php if($this->errorMessage) { ?>
    <br clear="all">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
      </button>
      <?php  echo $this->errorMessage;   ?>
    </div>
    <?php } ?>
    <div class="row">
      <div class="col-12">
        <div class="card  profile2_aboutme">
          <div class="card-header card-primary text-white">
            <p style="float: left; margin: 0px;">Create Vendor
            </p>
            <a href="/vendor"  style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">View All Vendors
            </a>
          </div>
          <div class="card-block">
            <div class="row m-t-10">
              <div class="col-lg-12">
                <form name="changePassword" method="post" onsubmit="return validateUser();"  action="/vendor/create-vendor">
                  <div class="form-group row">
                    <div class="col-lg-3">
                      <label for="first_name1" class="col-form-label">
                        Vendor Name *
                      </label>
                      <div class="input-group">
                        <input type="text" name="name" id="name" placeholder="Name" value="" class="form-control">
                      </div>
                    </div>
                    <div class="col-lg-3">
                      <label for="first_name1" class="col-form-label">
                        Email
                      </label>
                      <div class="input-group">
                        <input type="email" class="form-control " id="email" name="email" placeholder="email">
                      </div>
                    </div>
                    <div class="col-lg-3">
                      <label for="mobile" class="col-form-label">
                        Mobile *
                      </label>
                      <div class="input-group">
                        <input type="text" name="mobile" id="mobile" placeholder="Mobile" value="" class="form-control">
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="telephone" class="col-form-label">
                        Telephone No *
                      </label>
                      <div class="input-group">
                        <input type="text" name="telephone" id="telephone" placeholder="telephone" value="" class="form-control">
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="address" class="col-form-label">
                        Address *
                      </label>
                      <div class="input-group">
                        <textarea name="address" id="address" placeholder="address" value="" class="form-control"></textarea>
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="firm" class="col-form-label">
                        Constitution of Firm *
                      </label>
                      <div class="input-group">
                        <select name="firm" id="firm"  style="width: 300px;"  value="" class="form-control">
                            <option value="">---Select Firm---</option>
                            <option value="Manufacturer">Manufacturer</option>
                            <option value="Agent">Agent</option>
                            <option value="Dealer">Dealer</option>
                            <option value="Proprietary">Proprietary</option>
                        </select>
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="company" class="col-form-label">
                        Nature of Company *
                      </label>
                      <div class="input-group">
                        <select name="company" id="company" style="width: 300px;"  value="" class="form-control">
                            <option value="">---Select Nature of Company---</option>
                            <option value="Small">Small</option>
                            <option value="Medium">Medium</option>
                            <option value="Large">Large</option>
                        </select>
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="vendor gst" class="col-form-label">
                        Vendor GST No. *
                      </label>
                      <div class="input-group">
                        <input type="text" name="gst" id="gst" placeholder="Vendor GST Number" value="" class="form-control">
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="vendor Status" class="col-form-label">
                        Vendor Status *
                      </label>
                      <div class="input-group">
                        <select name="v_status" style="width: 300px;" id="v_status"  value="" class="form-control">
                            <option value="">---Select Vendor Status---</option>
                            <option value="Idle">Idle</option>
                            <option value="Busy">Busy</option>
                            <option value="Blacklisted">Blacklisted</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div>
                    <table  class="table table-striped task-list" id="myTable">
                  <h3 class="text-center">ManPower Details</h3>
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Department</th>
                                        <th>Experience</th>
                                        <th>Date Of Joining</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                     
                                                <td>
                                                  <input name="m_name[]" maxlength="100" placeholder="Title..." class="form-control "  type="text" required="" style="width: 110px;">
                                                </td>
                                                <td>
                                                  <select name="assign_to[]" class="form-control" id="chossen2" style="width: 110px;" required="">
                                                        <option value="">Select</option>
                                                        <?php foreach($getdepartment as $user){ ?>
                                                        <option value="<?php echo $user['id'];?>"><?php echo $user['department'];?></option>
                                                        <?php }?>
                                                  </select>
                                                </td>
                                                <td>
                                                  <input name="experience[]" maxlength="100" placeholder="Title..." class="form-control "  type="text" required="" style="width: 110px;">
                                                </td>
                                                <td><input name="due_date[]" readonly="" placeholder="Due Date..." id="date" value="<?php echo date('d/m/Y')?>" class="form-control  datepick" data-date-format="dd/mm/yyyy" style="width: 110px;" name="date[]" type="text" required="" />

                                                </td>
                                    </tr>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                    <td colspan="9" style="text-align: left;"><input type="button" id="addrow" class="btn btn-primary" value="New Task"></td>
                                    </tr>
                                    </tfoot>
                  </table>
                  </div>

                  <div class="form-group row">
                    <div class="col-12">
                      <button type="submit" name="submit" class="btn btn-responsive layout_btn_prevent btn-info pull-right">Save
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.content -->
</div>
</div>
