<?php
$getalldepartment = $this->getalldepartment;
$getRoletype = $this->getRoletype;
$getdepartment = $this->getalldepartment;
$deployment_data = $this->deployment_data;

//print_r($deployment_data);exit;
$params = $this->params;
$deployment_data = $this->deployment_data;
// echo "<pre>";
// print_r($deployment_data);exit;

$getUserRecord = $this->getUserRecord;
?>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript">
 $(document).ready(function() {
  $("#firm").select2();
                  //$("#user").select2();
                  $("#company").select2();
                  $("#v_status").select2();
                })
              </script>

              <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
              </script>
              <script type="text/javascript">
                
              </script>
              <div class="view-port-height">
                <!-- Content Header (Page header) -->
                <div class="content-header container-fluid bg-white">
                  <div class="row">
                    <div class="col-sm-4">
                      <h4>
                        <i class="ti-pencil-alt">
                        </i> Edit Deployement Data 
                      </h4>
                    </div>
                  </div>
                </div>
                <!-- Main content -->
                <div class="content">
                 <?php if($this->messages) { ?>
                  <br clear="all">
                  <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                    </button>
                    <?php  echo $this->messages;   ?>
                  </div>
                <?php } ?>
                <?php if($this->errorMessage) { ?>
                  <br clear="all">
                  <div class="alert alert-danger alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                    </button>
                    <?php  echo $this->errorMessage;   ?>
                  </div>
                <?php } ?>
                <div class="row">
                  <div class="col-12">
                    <div class="card  profile2_aboutme">
                      <div class="card-header card-info text-white">
                        <p style="float: left; margin: 0px; color: #fff;">Edit Deployement Data
                        </p>
                        <a href="/import"  style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">View Deployement Data
                        </a>
                      </div>
                      <div class="card-block">
                        <div class="row m-t-10">
                          <div class="col-lg-12">
                            <form name="changePassword" method="post" onsubmit="return validateUser();"  action="">
                              <div class="form-group row">
                                <div class="col-lg-3">
                                  <label for="SO" class="col-form-label">
                                    SO *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="SO" id="SO" placeholder="" value="<?php echo $deployment_data['so'] ?>" class="form-control">
                                    <input type="hidden" name="d_id" value="<?php echo $deployment_data['id'] ?>">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="opco_name" class="col-form-label">
                                    Opco Name *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="opco_name" id="opco_name" placeholder="Name" value="<?php echo $deployment_data['opco_name'] ?>" class="form-control">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="sr_type_opco" class="col-form-label">
                                    SR Type Opco *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="sr_type_opco" id="sr_type_opco" placeholder="" value="<?php echo $deployment_data['sr_type_opco'] ?>" class="form-control">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="po" class="col-form-label">
                                    PO *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="po" id="po" placeholder="" value="<?php echo $deployment_data['po'] ?>" class="form-control">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="infratel_id" class="col-form-label">
                                    Infratel Id *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="infratel_id" id="infratel_id" placeholder="" value="<?php echo $deployment_data['infratel_id'] ?>" class="form-control">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="district" class="col-form-label">
                                    District *
                                  </label>
                                  <div class="input-group">
                                    <input type="text" name="district" id="district" placeholder="" value="<?php echo $deployment_data['district'] ?>" class="form-control">
                                  </div>
                                </div>

                                <div class="col-lg-3">
                                  <label for="zone" class="col-form-label">
                                   Zone *
                                 </label>
                                 <div class="input-group">
                                  <input type="text" name="zone" id="zone" placeholder="" value="<?php echo $deployment_data['zone'] ?>" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="col-lg-3">
                                <label for="cluster" class="col-form-label">
                                  Cluster *
                                </label>
                                <div class="input-group">
                                  <input type="text" name="cluster" id="cluster" placeholder="" value="<?php echo $deployment_data['cluster'] ?>" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="col-lg-3">
                                <label for="technical_site_id" class="col-form-label">
                                  Technical Site Id *
                                </label>
                                <div class="input-group">
                                  <input type="text" name="technical_site_id" id="technical_site_id" placeholder="" value="<?php echo $deployment_data['technical_site_id'] ?>" class="form-control">
                                  
                                </div>
                              </div>

                              <div class="col-lg-3">
                                <label for="item" class="col-form-label">
                                  Item *
                                </label>
                                <div class="input-group">
                                  <input type="text" name="item" id="item" placeholder="" value="<?php echo $deployment_data['item'] ?>" class="form-control">
                                  
                                </div>
                              </div>
                              <div class="col-lg-3">
                                <label for="category" class="col-form-label">
                                  Category *
                                </label>
                                <div class="input-group">
                                  <input type="text" name="category" id="category" placeholder="" value="<?php echo $deployment_data['category'] ?>" class="form-control">
                                </div>
                              </div>

                              <div class="col-lg-3">
                                <label for="item_des" class="col-form-label">
                                  Item Description *
                                </label>
                                <div class="input-group">
                                  <textarea type="text" name="item_des" id="item_des" placeholder=""  class="form-control"><?php echo $deployment_data['item_des'] ?></textarea>
                                </div>
                              </div>



                            </div>
                            <div class="form-group row">
                              <div class="col-12">
                                <button type="submit" name="submit" class="btn btn-responsive layout_btn_prevent btn-info pull-right">Update
                                </button>
                              </div>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.content -->
          </div>
        </div>
