<?php
$getalldepartment = $this->getalldepartment;
$getRoletype = $this->getRoletype;
$getdepartment = $this->getalldepartment;
//print_r($getdepartment);
$params = $this->params;
$getUserRecord = $this->getUserRecord;
?>

<script type="text/javascript">
  function getPage(page, status,po,site_id){
    if(status == 'deployment'){
      //alert(po+"--"+site_id);
      var url   = '/import/deployment-list/page/'+page+'/po/'+po+'/site_id/'+site_id;
      var id    = 'deployment-list';
    }else if(status == 'matrix'){
      var url   = '/import/matrixs-list/page/'+page;
      var id    = 'matrix-list';
    }else if(status == 'location'){
      var url   = '/import/location-list/page/'+page;
      var id    = 'location-list';
    }
    
    $("#"+id).html('<div class="loading">Loading&#8230;</div>');
    $.ajax({
      url: url,
      context: document.body,
      success: function(responseText) {
        $("#"+id).html(responseText);
        $("#"+id).find("script").each(function(i) {
          eval($(this).text());
        });
      }
    });
  };
  
</script>

<div class="right-aside view-port-height">
  <!-- Content Header (Page header) -->
  <div class="content-header container-fluid bg-white">
    <div class="row">
      <div class="col-sm-4">
        <h4>
          <i class="ti-user">
          </i> Import Excel Sheet 
        </h4>
      </div>
    </div>
  </div>
  <!-- Main content -->
  <div class="content">
    <?php if ($this->messages): ?>
      <div class="alert alert-success alert-dismissable">
        
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
        </button>
        <?php echo $this->messages ?>
      </div>
    <?php endif ?>
    <?php if($this->errorMessage) { ?>
      <br clear="all">
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
        </button>
        <?php  echo $this->errorMessage;   ?>
      </div>
    <?php } ?>
    <div class="row">
      <div class="col-12">
        <div class="card  profile2_aboutme">
          <div class="card-header card-info text-white">
            <p style="float: left; margin: 0px; color: #fff;"> Import Excel Sheet
            </p>
            <a href="/excel/location.xlsx" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px;">
              <i class="fa fa-file-excel-o"></i> Location Sheet
            </a>
            <a href="/excel/matrix.xls" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px;">
              <i class="fa fa-file-excel-o"></i> Matrix Sheet
            </a>
            <a href="/excel/deployment.xlsx" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px;">
              <i class="fa fa-file-excel-o"></i> Deployment Sheet 
            </a>
            
          </div>
          <div class="card-block">
            <div class="row">
              <div class="col-lg-12">
                <form name="changePassword" method="post"   action="/import"  enctype="multipart/form-data">
                  <div class="form-group card-block row">

                    <div class="col-lg-3">
                      <label for="type" class="col-form-label">
                        Type Of Sheet *
                      </label>
                      <div class="input-group">
                        <select name="type_of_sheet" id="type_of_sheet" style="height: 35px;"  value="" class="form-control chosen-select">
                          <option value="">---Select Type Of Data---</option>
                          <option value="Deployment">Deployment Sheet</option>
                          <option value="Matrix">Matrix Sheet</option>
                          <option value="Height">Location Sheet</option>
                        </select>
                      </div>
                    </div>

                    <div class="col-lg-3">
                      <label for="upload" class="col-form-label">
                        Upload Excel File *
                      </label>
                      <div class="input-group">
                        <input  type="file" name="importxl" id="importxl" placeholder="" value="" class="form-control" required="required">
                      </div>

                    </div>

                    <div class="col-lg-3">
                      
                      <div class="input-group">
                        <input style="margin-top: 39px"  type="submit" value="Import" class=" btn btn-primary">
                      </div>

                    </div>

                    
                  </div>

                  
                </form>


                <div class="col-xl-12 col-12">
                  <div class="card real_charts">
                    <div class="card-block pt-2">
                      <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                          <a class="nav-link active text-center" href="#Deployment_section" role="tab" data-toggle="tab"> Deployment Sheet </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-center" href="#Matrix_section" role="tab" data-toggle="tab">Matrix Sheet</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-center" href="#Height_section" role="tab" data-toggle="tab">Location</a>
                        </li>
                      </ul>
                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade show active" id="Deployment_section">
                          <form name="search-deployement" method="post" id="filter" style="margin-top:1%">
                            <fieldset>
                              <legend>Search:</legend>
                              <div class="form-group row">
                                <div class="col-lg-2 col-md-2">
                                 
                                  <div class="input-group">
                                    <input  type="text" name="srch_po" id="srch_po" placeholder=" PO" value="<?php echo $params['srch_po'] ?>" class=" form-control" onkeyup="getPage('<?php echo $this->previous; ?>', 'deployment',this.form.srch_po.value,this.form.srch_siteid.value);">
                                  </div>
                                </div>
                                <div class="col-lg-2 col-md-2">
                                 
                                  <div class="input-group">
                                    <input  type="text" name="srch_siteid" id="srch_siteid" onkeyup="getPage('<?php echo $this->previous; ?>', 'deployment',this.form.srch_po.value,this.form.srch_siteid.value,);" placeholder=" Site Id"  value=""  class=" form-control">
                                  </div>
                                </div>
                                <div class="col-1" style="display: none">
                                  <div class="input-group ">
                                    <input  style="padding: 5px;" type="submit" value="Search" class=" btn btn-primary form-control">
                                  </div>
                                </div>
                              </div>
                            </fieldset>
                            
                          </form>
                          <div class="table-responsive mt-1" id="deployment-list">
                            <a class="btn btn-primary pull-right" href="/import/add-deployement">Add  New Deployement</a>
                            <!-- START PAGINATION -->
                            <?php 
                            $record = $this->paginator; 
                            $totalrec = $this->totalrec;
                            if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'deployment-pagination.phtml'); } ?>  
                            <!-- END PAGINATION -->
                            <table class="table table-striped">
                              <thead>
                                <tr>
                                  <th>#</th>
                                  <th>Action</th>
                                  <th>PO Number</th>
                                  <th nowrap>Created Date</th>
                                  <th nowrap>SO Number</th>
                                  <th nowrap>Site ID</th>
                                  
                                  <th nowrap>Infratel Id</th>
                                  <th>Location</th>
                                  <th>Work Type</th>
                                  
                                </tr>
                              </thead>
                              <tbody>
                                <?php 
                                if($totalrec){ 
                                  $totalnum = $this->totalnum?$this->totalnum:1;
                                  $istart = ($totalnum-1) * 10;
                                  $i=$istart;
                                  foreach($record as $deploy)
                                    { ?>
                                      <tr>
                                        <td><?php echo $i+1;?>.</td>
                                        <td><a href="/import/edit-deployement/id/<?php echo $deploy['id']; ?>"><i class="ti-pencil-alt"></i></a></td>
                                        <td nowrap><?php echo $deploy['po']; ?></td>
                                        <td nowrap><?php echo $deploy['po_date']; ?></td>
                                        <td nowrap><?php echo $deploy['so_no']; ?></td>
                                        <td nowrap><?php echo $deploy['site_id']; ?></td>
                                        
                                        <td nowrap><?php echo $deploy['infratel_id']; ?></td>
                                        <td nowrap><?php echo $deploy['location']; ?></td>
                                        <td nowrap><?php echo $deploy['work_type']; ?></td>
                                                <!-- <td nowrap><?php echo $deploy['cluster']; ?></td>
                                                <td nowrap><?php echo $deploy['technical_site_id']; ?></td>
                                                <td nowrap><?php echo $deploy['item']; ?></td>
                                                <td nowrap><?php echo $deploy['category']; ?></td>
                                                <td nowrap><?php echo $deploy['item_des']; ?></td> -->
                                              </tr>
                                              <?php  $i++;} } else{  ?>
                                                <tr><td colspan="14"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                              <?php  } ?>
                                            </tbody>
                                          </table>
                                          
                                          <!-- START PAGINATION -->
                                          <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'deployment-pagination.phtml'); } ?>  
                                          <!-- END PAGINATION -->
                                          
                                        </div> 
                                      </div>
                                      <div role="tabpanel" class="tab-pane fade px-3" id="Matrix_section">
                                        <div class="table-responsive mt-1" id="matrix-list">
                                          <!-- START PAGINATION -->
                                          <?php 
                                          $record = $this->paginator_matrix; 
                                          $totalrec = $this->totalrec_matrix;
                                          if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_matrix, 'Sliding', 'matrix-pagination.phtml'); } ?>  
                                          <!-- END PAGINATION -->
                                          <table class="table table-striped">
                                            <thead>
                                              <tr>
                                                <th>#</th>
                                                <th>Site Id</th>
                                                <th>Infratel Site ID</th>
                                                <th>Zone</th>
                                                <th>ZDM</th>
                                                <th>Contact</th>
                                                <th>Cluster</th>
                                                <th>Cluster Incharge</th>
                                                <th>Cluster Contact No. </th>
                                                <th>ZOM</th>
                                                <th>ZOM Contact</th>
                                                <th>Technician Name</th>
                                                <th>Technician Contact No.</th>
                                                
                                              </tr>
                                            </thead>
                                            <tbody>
                                              <?php 
                                              if($totalrec){ 
                                                $totalnum = $this->totalnum?$this->totalnum:1;
                                                $istart = ($totalnum-1) * 10;
                                                $i=$istart;
                                                foreach($record as $matrix)
                                                  { ?>
                                                    <tr>
                                                      <td><?php echo $i+1;?>.</td>
                                                      <td><?php echo $matrix['site_id']; ?></td>
                                                      <td><?php echo $matrix['infratel_site_id']; ?></td>
                                                      <td><?php echo $matrix['zone']; ?></td>
                                                      <td><?php echo $matrix['ZDM']; ?></td>
                                                      <td><?php echo $matrix['ZDM_mobile']; ?></td>
                                                      <td><?php echo $matrix['cluster']; ?></td>
                                                      <td><?php echo $matrix['cluster_incharge']; ?></td>
                                                      <td><?php echo $matrix['cluster_mobile']; ?></td>
                                                      <td><?php echo $matrix['ZOM']; ?></td>
                                                      <td><?php echo $matrix['ZOM_mobile']; ?></td>
                                                      <td><?php echo $matrix['tech_name']; ?></td>
                                                      <td><?php echo $matrix['tech_mobile']; ?></td>
                                                      
                                                    </tr>
                                                    <?php  $i++;} } else{  ?>
                                                      <tr><td colspan="9"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                                    <?php  } ?>
                                                  </tbody>
                                                </table>
                                                
                                                <!-- START PAGINATION -->
                                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_matrix, 'Sliding', 'matrix-pagination.phtml'); } ?>  
                                                <!-- END PAGINATION -->
                                                
                                              </div> 
                                            </div>
                                            <div role="tabpanel" class="tab-pane fade px-3" id="Height_section">
                                              <div class="table-responsive mt-1" id="location-list">
                                                <!-- START PAGINATION -->
                                                <?php 
                                                $record = $this->paginator_location; 
                                                $totalrec = $this->totalrec_location; 
                                                if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_location, 'Sliding', 'location-pagination.phtml'); } ?>  
                                                <!-- END PAGINATION -->
                                                <table class="table table-striped">
                                                  <thead>
                                                    <tr>
                                                      <th>#</th>
                                                      <th>Infratel Id</th>
                                                      <th>Latitude</th>
                                                      <th>Longitude</th>
                                                    </tr>
                                                  </thead>
                                                  <tbody>
                                                    <?php 
                                                    if($totalrec){ 
                                                      $totalnum = $this->totalnum?$this->totalnum:1;
                                                      $istart = ($totalnum-1) * 10;
                                                      $i=$istart;
                                                      foreach($record as $matrix)
                                                        { ?>
                                                          <tr>
                                                            <td><?php echo $i+1;?>.</td>
                                                            <td><?php echo $matrix['infratel_site_id']; ?></td>
                                                            <td><?php echo $matrix['latitude']; ?></td>
                                                            <td><?php echo $matrix['longitude']; ?></td>
                                                          </tr>
                                                          <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="4"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                                          <?php  } ?>
                                                        </tbody>
                                                      </table>
                                                      
                                                      <!-- START PAGINATION -->
                                                      <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_location, 'Sliding', 'location-pagination.phtml'); } ?>  
                                                      <!-- END PAGINATION -->
                                                      
                                                    </div> 
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>







                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- /.content -->
                          </div>
                        </div>
