<!-- START PAGINATION -->
                                <?php 
                                            $record = $this->paginator_location; 
                                            $totalrec = $this->totalrec_location; 
                                            if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_location, 'Sliding', 'location-pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->
                                        <table class="table table-striped">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Infratel Id</th>
                                                <th>Latitude</th>
                                                <th>Longitude</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10;
                                            $i=$istart;
                                            foreach($record as $matrix)
                                            { ?>
                                            <tr>
                                                <td><?php echo $i+1;?>.</td>
                                                <td><?php echo $matrix['infratel_site_id']; ?></td>
                                                <td><?php echo $matrix['latitude']; ?></td>
                                                <td><?php echo $matrix['longitude']; ?></td>
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="4"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                                
                                <!-- START PAGINATION -->
                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_location, 'Sliding', 'location-pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->