
                                       <!-- START PAGINATION -->
                                <?php 
                                            $record = $this->paginator_matrix; 
                                            $totalrec = $this->totalrec_matrix;
                                             if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_matrix, 'Sliding', 'matrix-pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->
                                        <table class="table table-striped">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Site Id</th>
                                                <th>Infratel Site ID</th>
                                                <th>Cluster</th>
                                                <th>Cluster Incharge</th>
                                                <th>Cluseter Contact No. </th>
                                                <th>Technician Name</th>
                                                <th>Technician Contact No.</th>
                                                <th>Zone</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10;
                                            $i=$istart;
                                            foreach($record as $matrix)
                                            { ?>
                                            <tr>
                                                <td><?php echo $i+1;?>.</td>
                                                <td><?php echo $matrix['site_id']; ?></td>
                                                <td><?php echo $matrix['infratel_site_id']; ?></td>
                                                <td><?php echo $matrix['cluster']; ?></td>
                                                <td><?php echo $matrix['cluster_incharge']; ?></td>
                                                <td><?php echo $matrix['cluster_mobile']; ?></td>
                                                <td><?php echo $matrix['tech_name']; ?></td>
                                                <td><?php echo $matrix['tech_mobile']; ?></td>
                                                <td><?php echo $matrix['zone']; ?></td>
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="9"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                                
                                <!-- START PAGINATION -->
                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator_matrix, 'Sliding', 'matrix-pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->
                             
                                    