
<style>
  .mainDiv {
    background-color: #DCF2FE;
    border-radius: 5px;
  }
  form {
    padding: 5px;
  }
  #mandatory {
    color: red;
    font-size: 16px;
  }
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h3>Add Location</h3>
          </div>

        </div>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <a href="/sitemap/index"  target="blank" style="float: right;"> <h4>View Site map</h4></a>   
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-19 mainDiv">

        <form action="/master/add-location" method="POST" class="form-inline" role="form" onsubmit="return validateInputData()">
          <div class="row">
            <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
            </div>
          </div>
          <br clear="all">
          <div class="row">
            <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label for="stateFor">Site id <span id="mandatory">*</span> :</label>
              <input type="numeric" class="form-control" name="site_id" id="site_id" placeholder="Enter State For" >
            </div>
            <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label for="stateFor">Site Name  <span id="mandatory">*</span> :</label>
              <input type="text" class="form-control" name="site_Name" id="site_Name" placeholder="Enter State For" >
            </div>
            <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label for="stateFor">Latitude <span id="mandatory">*</span> :</label>
              <input type="text" class="form-control" name="latitude" id="latitude" placeholder="Enter State For" >
            </div>
          </div>
          <br clear="all">
          <div class="row">
            <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <label for="stateFor">Longitude <span id="mandatory">*</span> :</label>
              <input type="text" class="form-control" name="longitude" id="longitude" placeholder="Enter State For" >
            </div>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
</div>


<!-- <script type="text/javascript">
 function validateInputData(){ 
  if($("#stateFor").val() == ""){
    swal({
      title : "State Name Missing !",
      text : "Please Enter State Name.",
      icon : "error"
    }).then(function(){
      $("#stateFor").focus();
    });
    return false;
  }
}
</script> -->
