
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
  .mainDiv {
    background-color: #DCF2FE;
    border-radius: 5px;
  }
  form {
    padding: 5px;
  }
  #mandatory {
    color: red;
    font-size: 16px;
  }
</style>

<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->params): ?>
      <?php if ($this->params['error']) { ?>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
        </div>
      <?php } ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h3>Add Company Vendor</h3>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a href="/master/company-vendor-list" class="btn btn-success pull-right">Company Vendor List</a>
          </div>
        </div>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
          <form id="companyVendorForm">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
              </div>
            </div>
            <br clear="all">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="company_vendor_name">Company Vendor Name <span id="mandatory">*</span></label>
                <input type="text" class="form-control" name="company_vendor_name" id="company_vendor_name" placeholder="Enter Company Vendor Name" oninput="this.value = this.value.replace(/[^A-Z a-z 0-9]/g, '');">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="proprietor_name">Proprietor Name</label>
                <input type="text" class="form-control" name="proprietor_name" id="proprietor_name" placeholder="Enter Proprietor Name" oninput="this.value = this.value.replace(/[^A-Z a-z]/g, '');">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="contact_person_name">Contact Person Name <span id="mandatory">*</span></label>
                <input type="text" class="form-control" name="contact_person_name" id="contact_person_name" placeholder="Enter Contact Person Name" oninput="this.value = this.value.replace(/[^a-z A-Z]/g, '');">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="contact_number">Contact Number <span id="mandatory">*</span></label>
                <input type="text" class="form-control" name="contact_number" id="contact_number" placeholder="Enter Contact Number" maxlength="10" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
              </div>
            </div>
            <br clear="all">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="gst_number">GST Number </label>
                <input type="text" class="form-control" name="gst_number" id="gst_number" placeholder="Enter GST Number">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="pan_number">PAN Number <span id="mandatory">*</span></label>
                <input type="text" class="form-control" name="pan_number" id="pan_number" placeholder="Enter PAN Number">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <label for="company_address">Address </label>
                <textarea class="form-control" name="company_address" id="company_address" placeholder="Company Address"></textarea>
              </div>
            </div>
            <br clear="all">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button type="button" class="btn btn-success pull-right" id="saveCompanyVendor">Save</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
 $(document).ready(function() {
  $("#department").select2();
  $("#role_type").select2();
  $("#role").select2();
  $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
  $("#saveCompanyVendor").click(function() {
    var company_name        = $("#company_vendor_name").val();
    var contact_person_name = $("#contact_person_name").val();
    var contact_number      = $("#contact_number").val();
    var pan_number          = $("#pan_number").val();
    if (company_name == "") {
      swal({
        title : "Conpany Name Missing!",
        text  : "Please enter company name.",
        icon  : "error"
      }).then(function(){
        $("#company_vendor_name").focus();
      });
      return false;
    } else if (contact_person_name == "") {
      swal({
        title : "Contact Person Missing!",
        text  : "Please enter contact person name.",
        icon  : "error"
      }).then(function(){
        $("#contact_person_name").focus();
      });
      return false;
    } else if (contact_number == "") {
      swal({
        title : "Contact Number Missing!",
        text  : "Please enter contact number.",
        icon  : "error"
      }).then(function(){
        $("#contact_number").focus();
      });
      return false;
    } else if (pan_number == "") {
      swal({
        title : "PAN Number Missing!",
        text  : "Please enter PAN number.",
        icon  : "error"
      }).then(function(){
        $("#pan_number").focus();
      });
      return false;
    } else {
      $("#loading-bg").show();
      $.ajax({
        url: '/master/save-company-vendor',
        type: 'POST',
        data: $("#companyVendorForm").serialize(),
        success:function(data){
          $("#loading-bg").hide();
          var data = JSON.parse(data);
          console.log(data);
          if (!data.flag) {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "error"
            });
          } else {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "success"
            }).then(function(){
              window.location.href = '/master/company-vendor-list';
            });
          }
        }
      });
    }
  });
  $("#removeImage").click(function(event) {
    event.preventDefault();
    $("#selectedFile").attr('src', '#');
    $("#profile_pic").val("");
    $("#removeImage").hide();
  });
});

 
 function showImage(inputFile) {
  if (inputFile.files && inputFile.files[0]) {
    var readFile = new FileReader();
    readFile.onload = function(e){
      $("#selectedFile")
      .attr('src', e.target.result)
      .width(80)
      .height(60);
    };
    readFile.readAsDataURL(inputFile.files[0]);
    $("#removeImage").show();
  }
}
</script>