<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
.mainDiv {
  background-color: #DCF2FE;
  border-radius: 5px;
}
form {
  padding: 5px;
}
#mandatory {
  color: red;
  font-size: 16px;
}
.formRow {
  padding: 10px !important;
}
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h3>Add Expense Type</h3>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a href="/master/transfer-for" class="btn btn-success pull-right">View Expense Type</a>
          </div>
        </div>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
          <form action="/master/add-transfer-for" method="POST" class="form-inline" role="form" onsubmit="return validateInputData()">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
              </div>
            </div>
            <br clear="all">
            <div class="row formRow">
              <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <label for="expenseType">Expense Type <span id="mandatory">*</span> :</label>
                <select name="expenseType" id="expenseType" class="form-control">
                  <option value="">Select Expense Type</option>
                  <option value="Site Expenses">Site Expenses</option>
                  <option value="Office Expenses">Office Expenses</option>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-5">
                <label for="transferFor">Expense For <span id="mandatory">*</span> :</label>
                <input type="text" class="form-control" name="transferFor" id="transferFor" placeholder="Enter Expense For" style="width: 250px">
              </div>
              <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function() {
    $("#expenseType").select2();
  });
  function validateInputData(){
    if ($("#expenseType").val() == "") {
      swal({
        title : "Expense Type Missing !",
        text : "Please Select Expense Type.",
        icon : "error"
      }).then(function(){
        $("#expenseType").focus();
      });
      return false;
    } else if($("#transferFor").val() == ""){
      swal({
        title : "Expense For Missing !",
        text : "Please Enter Expense For.",
        icon : "error"
      }).then(function(){
        $("#transferFor").focus();
      });
      return false;
    }
  }
</script>
