
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>




    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Bank Accounts
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addBankAccountModal">Add Bank Account</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="bank-list">
            <table class="display" width="100%" id="bankAccountTable">
             <thead>
              <th>#</th>
              <th>Bank Name</th>
              <th>Bank Account #</th>
              <th>Bank Branch</th>
              <th>Bank IFSC</th>
              <th>Account Holder Name</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->bank_accounts){
                $i = 1;
                foreach ($this->bank_accounts as $bank_account) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $bank_account['bank_name']; ?></td>
                  <td><?php echo $bank_account['bank_account_number']; ?></td>
                  <td><?php echo $bank_account['bank_branch']; ?></td>
                  <td><?php echo $bank_account['bank_ifsc_code']; ?></td>
                  <td><?php echo $bank_account['account_holder_name']; ?></td>
                  <td>
                    <a href="javascript:void(0)" title="Edit Bank Account" onclick="editBankAccountModal(<?php echo $bank_account['id']; ?>)"><i class="fa fa-pencil" style="color: #1DAA29;"></i></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" onclick="deleteBankAccount('<?php echo $bank_account['id'];?>')" title="Delete Bank Account"><span class="fa fa-trash" style="color: red;"></span></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Bank Modal : Start -->
  <div class="modal fade" id="addBankAccountModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add Bank Account</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <form action="/master/add-bank-account" method="POST" role="form">
              <div class="form-group">
                <label for="">Bank Name</label>
                <select name="bank_name" id="bank_name" class="form-control" required>
                  <option>Select Bank</option>
                  <?php foreach ($this->bankNameMasterList as $bank) { ?>
                    <option value="<?php echo $bank['bank_name']; ?>"><?php echo $bank['bank_name']; ?></option>
                  <?php } ?>
                </select>
              </div>

              <div class="form-group">
                <label for="">Bank Account number</label>
                <input type="text" name="bank_account_number" id="bank_account_number" class="form-control" required>
              </div>

              <div class="form-group">
                <label for="">Bank Branch</label>
                <input type="text" name="bank_branch" id="bank_branch" class="form-control" required>
              </div>

              <div class="form-group">
                <label for="">Bank IFSC</label>
                <input type="text" name="bank_ifsc_code" id="bank_ifsc_code" class="form-control" required>
              </div>

              <div class="form-group">
                <label for="">Account Holder Name</label>
                <input type="text" name="account_holder_name" id="account_holder_name" class="form-control" required>
              </div>



              <button type="submit" class="btn btn-primary">Submit</button>

            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add Bank Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editBankAccountModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#bankAccountTable").DataTable();
      $(".select2").select2();
    });
    function deleteBankAccount(id) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete clicked Bank Account?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url: '/master/delete-bank-account/id/'+id,
            type: 'GET',
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : "Deleted",
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/bank-accounts");
                });
              } else {
                swal({
                  title : "Failed !",
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    function editBankAccountModal(id) {
      if (id == "") {
        swal({
          title : "Bank ID Missing!",
          text  : "Please try after refresh the page once.",
          icon  : "error"
        });
      } else {
        $.ajax({
          url: '/master/get-bank-account',
          type: 'POST',
          data: {bank_id: id},
          success:function(data){
            $("#editBankAccountModal").html(data);
            $("#editBankAccountModal").modal("toggle");
          }
        });

      }
    }
  </script>

