
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>




    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Bank List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addBankModal">Add Bank Name</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="bank-list">
            <table class="display" width="100%" id="bankListTable">
             <thead>
              <th>#</th>
              <th>Bank Name</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->bankNameMasterList){
                $i = 1;
                foreach ($this->bankNameMasterList as $bank) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $bank['bank_name']; ?></td>
                  <td>
                    <a href="javascript:void(0)" title="Edit Bank Name" onclick="editBankNameModal(<?php echo $bank['id']; ?>)"><i class="fa fa-pencil" style="color: #1DAA29;"></i></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" onclick="deleteBank('<?php echo $bank['id'];?>')" title="Delete Bank Name"><span class="fa fa-trash" style="color: red;"></span></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Bank Modal : Start -->
  <div class="modal fade" id="addBankModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add Bank Name</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <form action="/master/add-bank-name" method="POST" class="form-inline" role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <label for="bank_name">Bank Name :</label>
                <input type="text" class="form-control" name="bank_name" id="bank_name" placeholder="Enter Bank Name">
              </div>
              <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add Bank Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editBankModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#bankListTable").DataTable();
    });
    function deleteBank(id) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete clicked bank name?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url: '/master/delete-bank-name/id/'+id,
            type: 'GET',
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : "Deleted",
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/bank-list");
                });
              } else {
                swal({
                  title : "Failed !",
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    function editBankNameModal(id) {
      if (id == "") {
        swal({
          title : "Bank ID Missing!",
          text  : "Please try after refresh the page once.",
          icon  : "error"
        });
      } else {
        $.ajax({
          url: '/master/get-bank-name',
          type: 'POST',
          data: {bank_id: id},
          success:function(data){
            $("#editBankModal").html(data);
            $("#editBankModal").modal("toggle");
          }
        });
        
      }
    }
  </script>

