<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>

		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Client(s) List
					<div class="pull-right">
						<a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addClientModal">Add Client</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="client_list">
						<table class="display" width="100%" id="clientListTable">
							<thead>
								<th>#</th>
								<th style="white-space: nowrap;">State Name</th>
								<th style="white-space: nowrap;">Client Name</th>
								<th style="white-space: nowrap;">Contact Number</th>
								<th>Address</th>
								<th style="white-space: nowrap;">GST Number</th>
								<th style="white-space: nowrap;">Status</th>
								<th style="white-space: nowrap;">Action</th>
							</thead>
							<tbody>
								<?php if($this->clients){
									$i = 1;
									foreach ($this->clients as $client) { ?>
										<tr>
											<td><?php echo $i; ?></td>
											<td style="white-space: nowrap;"><?php echo $client['state_name']; ?></td>
											<td style="white-space: nowrap;"><?php echo ucwords(strtolower($client['client_name'])); ?></td>
											<td style="white-space: nowrap;"><?php echo $client['client_contact_number']; ?></td>
											<td><?php echo ucwords(strtolower($client['client_billing_address'])); ?></td>
											<td style="white-space: nowrap;"><?php echo $client['client_gst']; ?></td>
											<td style="white-space: nowrap;"><?php echo $client['is_active'] == 1 ? "Active":"Inactive"; ?></td>
											<td style="white-space: nowrap;">
												<?php if ($client['is_active'] == "1") { ?>
													<a href="javascript:void(0)" onclick="editDeactivateActivateDeleteClient(<?php echo $client['id']; ?>,'deactivate')" title="Deactivate Client"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
												<?php } else { ?>
													<a href="javascript:void(0)" title="Activate Client" onclick="editDeactivateActivateDeleteClient(<?php echo $client['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
													&nbsp;&nbsp;
													<a href="javascript:void(0)" onclick="editDeactivateActivateDeleteClient(<?php echo $client['id']; ?>,'delete')" title="Delete Client"><span class="fa fa-trash" style="color: red;"></span></a>
												<?php } ?>
											</td>
										</tr>
										<?php $i++; } } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Add Bank Modal : Start -->
			<div class="modal fade" id="addClientModal">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3 class="modal-title">Add Client Name</h3>
						</div>
						<div class="modal-body">
							<div class="row">
								<form role="form" id="addClientForm">
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="state_id">State Name :</label>
										<select class="form-control select2" name="state_id" id="state_id" style="width: 100%;">
											<option value="">Select State</option>
											<?php foreach ($this->stateList as $state): ?>
												<option value="<?php echo $state['id']; ?>"><?php echo $state['state_name']; ?></option>
											<?php endforeach ?>
										</select>
									</div>
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="client_name">Client Name :</label>
										<input type="text" class="form-control" name="client_name" id="client_name" placeholder="Enter Client Name">
									</div>
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="contact_number">Contact Number :</label>
										<input type="text" class="form-control" name="contact_number" id="contact_number" placeholder="Enter Client Contact Number" oninput="this.value = this.value.replace(/[^0-9]/g,'')" maxlength="10">
									</div>
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="client_gst">GST Number :</label>
										<input type="text" class="form-control upperCase" name="client_gst" id="client_gst" placeholder="Enter Client GST Number" oninput="this.value = this.value.replace(/[^a-zA-Z0-9]/g,'')" maxlength="15">
									</div>
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="client_billing_address">Billing Address :</label>
										<textarea type="text" class="form-control" name="client_billing_address" id="client_billing_address" placeholder="Enter Client Billing Address"></textarea><br>
										<span>Check if shipping address is same <input type="checkbox" id="copyDataToShipping" onchange="copyBillingToShipping()"></span>
									</div>
									<div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
										<label for="client_shipping_address">Shipping Address :</label>
										<textarea type="text" class="form-control" name="client_shipping_address" id="client_shipping_address" placeholder="Enter Client Shipping Address"></textarea>
									</div>
									<div class="clearfix"></div>
									<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
										<input type="submit" class="btn btn-primary pull-right" id="saveClientName" value="Save">
									</div>
								</form>
							</div>
						</div>
						<div class="modal-footer"></div>
					</div>
				</div>
			</div>
			<!-- Add Bank Modal : End -->

			<!-- Edit Bank Modal : Start -->
			<div class="modal fade" id="editBankModal"></div>
			<!-- Edit Bank Modal : End -->

			<script type="text/javascript">
				$(document).ready(function() {
					$("#clientListTable").DataTable();
					$(".select2").select2();
					$(".upperCase").on('input', function(event) {
						event.preventDefault();
						$(this).val(function(_, val){
							return val.toUpperCase();
						})
					});
					$('#saveClientName').click(function(event) {
						event.preventDefault();
						var state_name = $("#state_id").val();
						var client_name = $("#client_name").val();
						var client_gst = $("#client_gst").val();
						var client_billing_address = $("#client_billing_address").val();
						var client_shipping_address = $("#client_shipping_address").val();
						if (state_name == "") {
							swal({
								title : "State Name Missing!",
								text  : "Please select state name.",
								icon  : "error"
							}).then(function(){
								$("#state_id").select2('open');
							});
							return false;
						} else if (client_name == "") {
							swal({
								title : "Client Name Missing!",
								text  : "Please enter client name.",
								icon  : "error"
							}).then(function(){
								$("#client_name").focus();
							});
							return false;
						} else if (client_gst == "") {
							swal({
								title : "Client GST Missing!",
								text  : "Please enter client GST.",
								icon  : "error"
							}).then(function(){
								$("#client_gst").focus();
							});
							return false;
						} else if (client_gst.length > 15 || client_gst.length < 15) {
							swal({
								title : "Invalid GST Number!",
								text  : "Please enter valid GST number.",
								icon  : "error"
							}).then(function(){
								$("#client_gst").focus();
							});
							return false;
						} else if (client_billing_address == "") {
							swal({
								title : "Billing Address Missing!",
								text  : "Please enter client billing address.",
								icon  : "error"
							}).then(function(){
								$("#client_billing_address").focus();
							});
							return false;
						} else if (client_shipping_address == "") {
							swal({
								title : "Shipping Address Missing!",
								text  : "Please enter client shipping address.",
								icon  : "error"
							}).then(function(){
								$("#client_shipping_address").focus();
							});
							return false;
						} else {
							$("#addClientModal").modal('toggle');
							$("#loading-bg").show();
							$.ajax({
								url: '/master/add-client-name',
								type: 'POST',
								data: $("#addClientForm").serialize(),
								success:function(data){
									var data = JSON.parse(data);
									console.log(data);
									$("#loading-bg").hide();
									if (data.flag) {
										swal({
											title : data.title,
											text  : data.message,
											icon  : "success"
										}).then(function(){
											location.reload("/master/client-list");
										});
									} else {
										swal({
											title : data.title,
											text  : data.message,
											icon  : "error"
										}).then(function(){
											$("#addClientModal").modal('toggle');
											return false;
										});
									}
								}
							});
						}
					});
				});
				function copyBillingToShipping() {
					if ($("#copyDataToShipping").prop('checked') === true) {
						$("#client_shipping_address").val($("#client_billing_address").val());
						$("#client_shipping_address").attr('readonly', true);
					} else {
						$("#client_shipping_address").val('');
						$("#client_shipping_address").attr('readonly', false);
					}
				}
				function editDeactivateActivateDeleteClient(id, type) {
					swal({
						title : "Are you sure?",
						text  : "Do you want to "+type+" clicked client?",
						icon  : "warning",
						buttons : [true, "Yes, "+type],
						dangerMode : true
					}).then(function(isConfirm){
						if (!isConfirm) {
							return false;
						} else {
							$("#loading-bg").show();
							$.ajax({
								url  : '/master/activate-deactivate-delete-client',
								type : 'POST',
								data : {type:type, client_id:id},
								success:function(data){
									var data = JSON.parse(data);
									$("#loading-bg").hide();
									if (data.flag) {
										swal({
											title : data.title,
											text  : data.message,
											icon  : "success",
										}).then(function(){
											location.reload("/master/client-list");
										});
									} else {
										swal({
											title : data.title,
											text  : data.message,
											icon  : "error"
										});           
									}
								}
							});
						}
					});
				}
			</script>

