
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>




    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Debit Account List
          <div class="pull-right">
            <a  href="javascript:void(0)"  id="company-details" data-toggle="modal" data-target="#con-close-modal" class="btn btn-success" onclick="addHoliday('<?php echo $bank['id']; ?>');" title="Add Details">Add Debit Account </a></div></h3>
          </div>
          <div class="panel panel-body">
            <div class="table-responsive" id="bank-list">
              <table class="display" width="100%" id="bankListTable">
               <thead>
                <th>#</th>
                <th>Debit Account Name</th>
                <th>Action</th>
              </thead>
              <tbody>
                <?php if($this->debit_data){
                  $i = 1;
                  foreach ($this->debit_data as $bank) { ?>
                   <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $bank['debit_account']; ?></td>
                    <td>
                      <a  href="javascript:void(0)" style="text-decoration:underline;"  id="company-details" data-toggle="modal" data-target="#con-close-modal" class="iframe" onclick="addHoliday('<?php echo $bank['id']; ?>');" title="view Details"><i class="fa fa-pencil"></i></a>
                      <a  href="javascript:void(0)" style="text-decoration:underline;" onclick="deleteHoliday('<?php echo $bank['id']; ?>');" id=""><i class="fa fa-trash"></i></a>
                    </td>
                  </tr>
                  <?php $i++; } } ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="custom-width-modalLabel" aria-hidden="true" style="display: none;">
      <div class="modal-dialog" style="max-height:85%;  margin-top: 50px; margin-bottom:50px; width: 60%">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 class="modal-title" id="custom-width-modalLabel">Debit Account Details</h3>
          </div>
          <div class="modal-body">

          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

    <script type="text/javascript">
      $(document).ready(function() {
        $("#bankListTable").DataTable();
      });
      function addHoliday(id){
        $.ajax({
          url: "/master/add-debit-account/id/"+id,
          context: document.body,
          success: function(responseText) {
            $(".modal-body").html(responseText);
            $(".modal-body").find("script").each(function(i) {
              eval($(this).text());

            });
          }
        });
      }
      function deleteHoliday(id) {
        swal({
          title : "Are you sure?",
          text  : "Do you want to delete clicked debit account?",
          icon  : "warning",
          buttons : [true, "Yes, Delete"],
          dangerMode : true
        }).then(function(isConfirm){
          if (!isConfirm) {
            return false;
          } else {
            $.ajax({
              url: '/master/delete-debit-account/id/'+id,
              type: 'GET',
              success:function(data){
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : "Deleted",
                    text  : data.message,
                    icon  : "success",
                  }).then(function(){
                    location.reload("/master/debit_account");
                  });
                } else {
                  swal({
                    title : "Failed !",
                    text  : data.message,
                    icon  : "error"
                  });           
                }
              }
            });

          }
        });
      }
    </script>

