<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
.select2.select2-container {
    width: 100% !important;
}
.mainDiv {
  background-color: #DCF2FE;
  border-radius: 5px;
}
form {
  padding: 5px;
}
#mandatory {
  color: red;
  font-size: 16px;
}
.table-bordered {
    border: 2px solid #1b1a1a !important;
}
.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
    border: 1px solid #1b1a1a !important;
}
</style>

<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
        </div>
    <?php } else if ($message['error']) { ?>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
    </div>
<?php } ?>
<?php endforeach ?>
<?php endif ?>
<div class="panel panel-primary">
  <div class="panel panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3>Edit Product</h3>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <a href="/master/product-list" class="btn btn-success pull-right">View Products</a>
    </div>
</div>
</div>
<div class="panel panel-body">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
        <form action="/master/edit-product/product-id/<?php echo md5($this->productDetails['id']); ?>" method="POST" onsubmit="return validateInputData()">
            <div class="row">
                <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <label for="product_category">Product Type <span id="mandatory">*</span></label>
                    <select name="product_category" id="product_category">
                        <option value="">Select Product Type</option>
                        <?php foreach ($this->productType as $productType): ?>
                            <option value="<?php echo $productType['id']; ?>"<?php echo $productType['id'] == $this->productDetails['product_type_id']?"selected":""; ?>><?php echo $productType['product_type_name']; ?></option>
                        <?php endforeach ?>
                    </select>    
                </div>
                <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <label for="product_name">Product Name <span id="mandatory">*</span></label>
                    <input type="text" class="form-control" name="product_name" id="product_name" placeholder="Enter Product Name" value="<?php echo $this->productDetails['product_name']; ?>">
                </div>
                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <label for="product_unit">Product Unit <span id="mandatory">*</span></label>
                    <select name="product_unit" id="product_unit">
                        <option value="">Select Product Unit</option>
                        <?php foreach ($this->productUnit as $productUnit): ?>
                            <option value="<?php echo $productUnit['unit_name']; ?>"<?php echo $productUnit['unit_name'] == $this->productDetails['unit']?"selected":""; ?>><?php echo $productUnit['unit_name']; ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <br clear="all">
            <div class="row">
                <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
                    <label for="price">Product Price/Unit <span id="mandatory">*</span></label>
                    <input type="text" class="form-control" name="price" id="price" placeholder="Enter Product Price" value="<?php echo $this->productDetails['price']; ?>" oninput="this.value = this.value.replace(/[^0-9.]/g, '');">
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding: 10px">
                    <button type="submit" class="btn btn-success pull-right">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
</div>

<script>
    $(document).ready(function() {
        $("#product_category").select2();
        $("#product_unit").select2();
    }); 
    function validateInputData() {
        var productType     = $("#product_category").val();
        var productName     = $("#product_name").val();
        var productUnit     = $("#product_unit").val();
        var productPrice    = $("#price").val();
        if (productType == "") {
            swal({
                title : "Product Type Missing !",
                text  : "Please Select Product Type",
                icon  : "error"
            }).then(function() {
                $("#product_category").focus();
            });
            return false;
        } else if (productName == "") {
            swal({
                title : "Product Name Missing !",
                text  : "Please Enter Product Name",
                icon  : "error"
            }).then(function() {
                $("#product_name").focus();
            });
            return false;
        } else if (productUnit == "") {
            swal({
                title : "Product Unit Missing !",
                text  : "Please Select Product Unit",
                icon  : "error"
            }).then(function() {
                $("#product_unit").focus();
            });
            return false;
        } else if (productPrice == "") {
            swal({
                title : "Product Price Missing !",
                text  : "Please Enter Product Price",
                icon  : "error"
            }).then(function() {
                $("#price").focus();
            });
            return false;
        }
    }
</script>