
<style>
.mainDiv {
  background-color: #DCF2FE;
  border-radius: 5px;
}
form {
  padding: 5px;
}
#mandatory {
  color: red;
  font-size: 16px;
}
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if (isset($this->params)): ?>
      <?php if (isset($this->params['success'])){ ?>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Success !</strong>&nbsp; <?php echo $this->params["success"]; ?>
        </div>
      <?php } else if (isset($this->params['error'])) { ?>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
        </div>
      <?php } ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h3>Edit Annual Turnover</h3>
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <a href="/master/annual-turnover-master" class="btn btn-success pull-right">Annual Turnover List</a>
          </div>
        </div>
      </div>
      <div class="panel panel-body">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
          <form action="/master/edit-annual-turnover-master/annual-turnover-master-id/<?php echo md5($this->annualTurnoverDetails['id']); ?>" method="POST" class="form-inline" role="form" onsubmit="return validateInputData()">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Field is mandatory.</span>
              </div>
            </div>
            <br clear="all">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <label for="annual_turnover">Annual Turnover Master <span id="mandatory">*</span> :</label>
                <input type="text" class="form-control" name="annual_turnover" id="annual_turnover" placeholder="Enter Annual Turnover Master" oninput="this.value = this.value.replace(/[^A-Za-z0-9-/. ]/g, '');" style="width: 50%;" value="<?php echo $this->annualTurnoverDetails['annual_turnover']; ?>">
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <button type="submit" class="btn btn-success">Update</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
 function validateInputData(){ 
  if($("#annual_turnover").val() == ""){
    swal({
      title : "Annual Turnover Missing !",
      text  : "Please Enter Annual Turnover Master.",
      icon  : "error"
    }).then(function(){
      $("#annual_turnover").focus();
    });
    return false;
  }
}
</script>
