<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Employee Roles List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addEmployeeRoleModal">Add Employee Role</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="employee Roles-list">
            <table class="display" width="100%" id="employeeRolesListTable">
             <thead>
              <th>#</th>
              <th>Role Type</th>
              <th>Role Name</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->employeeRolesList){
                $i = 1;
                foreach ($this->employeeRolesList as $employeeRole) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $employeeRole['role_type_name']; ?></td>
                  <td><?php echo $employeeRole['role']; ?></td>
                  <td><?php echo $employeeRole['status']? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($employeeRole['status'] == "1"){ ?>
                      <a href="javascript:void(0)" title="Edit Role" onclick="activateDeactivateDeleteRole(<?php echo $employeeRole['id']; ?>,'edit')"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="activateDeactivateDeleteRole(<?php echo $employeeRole['id'];?>,'deactivate')" title="Deactivate Role"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Role" onclick="activateDeactivateDeleteRole(<?php echo $employeeRole['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #0050C7;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="activateDeactivateDeleteRole(<?php echo $employeeRole['id'];?>,'delete')" title="Delete Role"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addEmployeeRoleModal">
    <div class="modal-dialog" style="width: 60%;">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add New Role</h4>
        </div>
        <div class="modal-body">
          <div class="row">
           <form action="/master/add-employee-role-name" method="POST" class="form-inline" role="form">
            <div class="row">
              <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-5">
                <label for="role_type_id">Role Type :</label>
                <select class="form-control" name="role_type_id" id="role_type_id" style="width: 230px;">
                  <option value="">Please Select</option>
                  <?php foreach ($this->roleTypeList as $roleTypeList): ?>
                    <option value="<?php echo $roleTypeList['id']; ?>"><?php echo $roleTypeList['role_type']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-5">
                <label for="role">Role Name :</label>
                <input type="text" class="form-control" name="role" id="role" placeholder="Enter Role Name" style="width: 230px;">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-2 col-lg-2">
                <input type="submit" class="btn btn-primary" value="Save">
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>
<!-- Add State Modal : End -->

<!-- Edit Bank Modal : Start -->
<div class="modal fade" id="editRoleFormModal"></div>
<!-- Edit Bank Modal : End -->

<script type="text/javascript">
  $(document).ready(function() {
    $("#employeeRolesListTable").DataTable();
    $("#role_type_id").select2();
  });
  function activateDeactivateDeleteRole(id, value) {
    if (value == "edit") {
      $.ajax({
        url: '/master/get-employee-role-name',
        type: 'POST',
        data: {role_id: id},
        success:function(data){
          $("#editRoleFormModal").html(data);
          $("#editRoleFormModal").modal("toggle");
        }
      });
    } else {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+value+" clicked role?",
        icon  : "warning",
        buttons : [true, "Yes, "+value],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url: '/master/activate-deactivate-delete-employee-role-name/id/'+id+'/type/'+value,
            type: 'GET',
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/employee-roles-list");
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
  }
  function editEmployeeRoleModal(id) {
    if (id == "") {
      swal({
        title : "State ID Missing!",
        text  : "Please try after refresh the page once.",
        icon  : "error"
      });
    } else {


    }
  }
</script>

