
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Expense Type
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addExpenseTypeModal">Add Expense Type</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="state-list">
            <table class="display" width="100%" id="stateListTable">
             <thead>
              <th>#</th>
              <th>Expense Type</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->expenseTypeList){
                $i = 1;
                foreach ($this->expenseTypeList as $expenseType) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $expenseType['expense_type']; ?></td>
                  <td><?php echo $expenseType['status'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($expenseType['status'] == "1") { ?>
                      <a href="javascript:void(0)" title="Edit Expense Type" onclick="editDeactivateActivateDeleteExpenseType(<?php echo $expenseType['id']; ?>,'edit')"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="editDeactivateActivateDeleteExpenseType(<?php echo $expenseType['id']; ?>,'deactivate')" title="Deactivate Expense Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Expense Type" onclick="editDeactivateActivateDeleteExpenseType(<?php echo $expenseType['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="editDeactivateActivateDeleteExpenseType(<?php echo $expenseType['id']; ?>,'delete')" title="Delete Expense Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addExpenseTypeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add Expense Type</h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <form class="form-inline" role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <label for="expenseType">Expense Type :</label>
                <input type="text" class="form-control" name="expenseType" id="expenseType" placeholder="Enter Expense Type">
              </div>
              <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="saveExpenseTypeButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#stateListTable").DataTable();
      $("#saveExpenseTypeButton").click(function(event) {
        event.preventDefault();
        var expenseType = $("#expenseType").val();
        if (expenseType == "") {
          swal({
            title : "Expense Type Missing!",
            text  : "Please enter expense type.",
            icon  : "error",
          });
        } else {
          $("#addExpenseTypeModal").modal("toggle");
          $.ajax({
            url: '/master/add-expense-type',
            type: 'POST',
            data: {expenseType: expenseType},
            success:function(data){
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : "Saved Successfully",
                  text  : data.message,
                  icon  : "success"
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : "Error",
                  text  : data.message,
                  icon  : "error"
                }).then(function(){
                  $("#addExpenseTypeModal").modal("toggle");
                });
              }
            }
          });
        }
      });
    });
    function editDeactivateActivateDeleteExpenseType(id, type) {
      if (type == "edit") {
        $.ajax({
          url: '/master/get-expense-type',
          type: 'POST',
          data: {expense_type_id: id},
          success:function (data) {
            $("#editExpenseTypeModal").html(data);
            $("#editExpenseTypeModal").modal("toggle");
          }
        });
      } else {
        swal({
          title : "Are you sure?",
          text  : "Do you want to "+type+" clicked expense type?",
          icon  : "warning",
          buttons : [true, "Yes, "+type],
          dangerMode : true
        }).then(function(isConfirm){
          if (!isConfirm) {
            return false;
          } else {
            $.ajax({
              url  : '/master/deactivate-activate-delete-expense-type',
              type : 'POST',
              data : {type:type, expense_type_id:id},
              success:function(data){
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "success",
                  }).then(function(){
                    location.reload("/master/expense-type");
                  });
                } else {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "error"
                  });           
                }
              }
            });

          }
        });
      }
    }
    function submitUpdateExpenseTypeForm(id) {
      var expenseType = $("#updateExpenseType").val();
      if (expenseType == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please enter expense type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-type',
          type: 'POST',
          data: {expenseType: expenseType, expense_type_id:id},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

