<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Expense In Type
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addExpenseInTypeModal">Add Expense In Type</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="expenseInTypeListTable">
             <thead>
              <th>#</th>
              <th>Expense Type</th>
              <th>Expense In</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->expenseInTypeList){
                $i = 1;
                foreach ($this->expenseInTypeList as $expenseInType) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $expenseInType['expense_type']; ?></td>
                  <td><?php echo $expenseInType['expense_in_type']; ?></td>
                  <td><?php echo $expenseInType['status'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($expenseInType['status'] == "1") { ?>
                      <a href="javascript:void(0)" title="Edit Expense Type" onclick="editDeactivateActivateDeleteExpenseInType(<?php echo $expenseInType['id']; ?>,'edit')"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="editDeactivateActivateDeleteExpenseInType(<?php echo $expenseInType['id']; ?>,'deactivate')" title="Deactivate Expense Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Expense Type" onclick="editDeactivateActivateDeleteExpenseInType(<?php echo $expenseInType['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="editDeactivateActivateDeleteExpenseInType(<?php echo $expenseInType['id']; ?>,'delete')" title="Delete Expense Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addExpenseInTypeModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Expense In Type</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="expenseTypeId">Expense Type :</label>
                <select name="expenseTypeId" id="expenseTypeId" class="form-control select2" style="width: 100% !important;">
                  <option value="">Please Select</option>
                  <?php foreach ($this->expenseTypeList as $expenseType): ?>
                    <option value="<?php echo $expenseType['id']; ?>"><?php echo $expenseType['expense_type']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="expenseInType">Expense In Type :</label>
                <input type="text" class="form-control" name="expenseInType" id="expenseInType" placeholder="Enter Expense Type">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="saveExpenseInTypeButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseInTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#expenseInTypeListTable").DataTable();
      $(".select2").select2();
      $("#saveExpenseInTypeButton").click(function(event) {
        event.preventDefault();
        var expenseInType = $("#expenseInType").val();
        var expenseTypeId = $("#expenseTypeId").val();
        if (expenseTypeId == "") {
          swal({
            title : "Expense Type Missing!",
            text  : "Please select expense type.",
            icon  : "error",
          });
        } else if (expenseInType == "") {
          swal({
            title : "Expense In Type Missing!",
            text  : "Please enter expense in type.",
            icon  : "error",
          });
        } else {
          $("#addExpenseInTypeModal").modal("toggle");
          $.ajax({
            url: '/master/add-expense-in-type',
            type: 'POST',
            data: {expenseTypeId: expenseTypeId, expenseInType:expenseInType},
            success:function(data){
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : "Saved Successfully",
                  text  : data.message,
                  icon  : "success"
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : "Error",
                  text  : data.message,
                  icon  : "error"
                }).then(function(){
                  $("#addExpenseInTypeModal").modal("toggle");
                });
              }
            }
          });
        }
      });
    });
    function editDeactivateActivateDeleteExpenseInType(id, type) {
      if (type == "edit") {
        $.ajax({
          url: '/master/get-expense-in-type',
          type: 'POST',
          data: {expense_in_type_id: id},
          success:function (data) {
            $("#editExpenseInTypeModal").html(data);
            $(".select2").select2();
            $("#editExpenseInTypeModal").modal("toggle");
          }
        });
      } else {
        swal({
          title : "Are you sure?",
          text  : "Do you want to "+type+" clicked expense in type?",
          icon  : "warning",
          buttons : [true, "Yes, "+type],
          dangerMode : true
        }).then(function(isConfirm){
          if (!isConfirm) {
            return false;
          } else {
            $.ajax({
              url  : '/master/deactivate-activate-delete-expense-in-type',
              type : 'POST',
              data : {type:type, expense_in_type_id:id},
              success:function(data){
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "success",
                  }).then(function(){
                    location.reload("/master/expense-type");
                  });
                } else {
                  swal({
                    title : data.title,
                    text  : data.message,
                    icon  : "error"
                  });           
                }
              }
            });

          }
        });
      }
    }
    function submitUpdateExpenseInTypeForm(id) {
      var expenseTypeId = $("#updatedExpenseTypeId").val();
      var expenseInType = $("#updatedExpenseInType").val();
      if (expenseTypeId == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please select expense type.",
          icon  : "error",
        });
      } else if (expenseInType == "") {
        swal({
          title : "Expense In Type Missing!",
          text  : "Please enter expense in type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseInTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-in-type',
          type: 'POST',
          data: {expenseInTypeId:id, expenseTypeId: expenseTypeId, expenseInType:expenseInType},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseInTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

