<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Edit Bank Name</h4>
    </div>
    <div class="modal-body">
      <form action="/master/edit-bank-account/bank-id/<?php echo md5($this->bankAccountDetails['id']); ?>" method="POST"  role="form">
       <div class="form-group">
        <label for="">Bank Name</label>
        <select name="bank_name" id="bank_name" class="form-control" required>
          <option>Select Bank</option>
          <?php foreach ($this->bankNameMasterList as $bank) { ?>
            <option value="<?php echo $bank['bank_name']; ?>" <?php echo $this->bankAccountDetails['bank_name'] == $bank['bank_name'] ? "selected":""; ?>><?php echo $bank['bank_name']; ?></option>
          <?php } ?>
        </select>
      </div>


      <div class="form-group">
        <label for="">Bank Account number</label>
        <input type="text"  name="bank_account_number" id="bank_account_number" class="form-control" value="<?php echo $this->bankAccountDetails['bank_account_number']; ?>" required>
      </div>

      <div class="form-group">
        <label for="">Bank Branch</label>
        <input type="text"  name="bank_branch" id="bank_branch" class="form-control" value="<?php echo $this->bankAccountDetails['bank_branch']; ?>" required>
      </div>

      <div class="form-group">
        <label for="">Bank IFSC</label>
        <input type="text"  name="bank_ifsc_code" id="bank_ifsc_code" class="form-control" value="<?php echo $this->bankAccountDetails['bank_ifsc_code']; ?>" required>
      </div>

      <div class="form-group">
        <label for="">Account Holder Name</label>
        <input type="text"  name="account_holder_name" id="account_holder_name" class="form-control" value="<?php echo $this->bankAccountDetails['account_holder_name']; ?>" required>
      </div>



      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  <div class="modal-footer"></div>
</div>
</div>