<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3 class="modal-title">Edit Expense In Type</h3>
    </div>
    <div class="modal-body">
      <div class="row">
        <form role="form">
          <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <label for="updatedExpenseTypeId">Expense Type :</label>
            <select name="updatedExpenseTypeId" id="updatedExpenseTypeId" class="form-control select2" style="width: 100% !important;" onchange="showUpdatedExpenseInOptions()">
              <option value="">Please Select</option>
              <?php foreach ($this->expenseTypeList as $expenseType): ?>
                <option value="<?php echo $expenseType['id']; ?>"<?php echo $expenseType['id'] == $this->expenseTransferForDetails['expense_type_id'] ? "selected":""; ?>><?php echo $expenseType['expense_type']; ?></option>
              <?php endforeach ?>
            </select>
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <label for="updatedExpenseInId">Expense In Type :</label>
            <select name="updatedExpenseInId" id="updatedExpenseInId" class="form-control select2" style="width: 100% !important;">
              <option value="">Please Select</option>
              <?php foreach ($this->expenseInTypeDetails as $expenseInType): ?>
                <option value="<?php echo $expenseInType['id']; ?>"<?php echo $expenseInType['id'] == $this->expenseTransferForDetails['expense_in_id'] ? "selected":""; ?>><?php echo $expenseInType['expense_in_type']; ?></option>
              <?php endforeach ?>
            </select>
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <label for="updatedExpenseTransferFor">Expense Transfer For :</label>
            <input type="text" class="form-control" name="updatedExpenseTransferFor" id="updatedExpenseTransferFor" placeholder="Enter Expense Transfer For" value="<?php echo $this->expenseTransferForDetails['expense_transfer_for']; ?>">
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <input type="button" class="btn btn-primary" value="Update" onclick="submitUpdateExpenseTransferForForm(<?php echo $this->expenseTransferForDetails['id']; ?>)">
          </div>
        </form>
      </div>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>