<div class="modal-dialog" style="width: 70%;">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Edit Role</h4>
    </div>
    <div class="modal-body">
      <form action="/master/edit-employee-role-name/role-id/<?php echo md5($this->employeeRoleDetails['id']); ?>" method="POST" class="form-inline" role="form">
        <div class="row">
          <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-5">
            <label for="role_type_id">Role Type :</label>
            <select class="form-control" name="role_type_id" id="role_type_id" style="width: 280px;">
              <option value="">Please Select</option>
              <?php foreach ($this->roleTypeList as $roleTypeList): ?>
                <option value="<?php echo $roleTypeList['id']; ?>"<?php echo $roleTypeList['id'] == $this->employeeRoleDetails['role_type'] ? "selected":""; ?>><?php echo $roleTypeList['role_type']; ?></option>
              <?php endforeach ?>
            </select>
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-5 col-lg-5">
            <label for="role">Role Name :</label>
            <input type="text" class="form-control" name="role" id="role" placeholder="Enter Role Name" value="<?php echo $this->employeeRoleDetails['role']; ?>" style="width: 280px;">
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-2 col-lg-2">
            <input type="submit" class="btn btn-primary" value="Update">
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>