<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Edit Role Type</h4>
    </div>
    <div class="modal-body">
      <form action="/master/edit-employee-role-type/role-type-id/<?php echo md5($this->employeeRoleTypeDetails['id']); ?>" method="POST" class="form-inline" role="form">
        <div class="row">
          <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <label for="role_type">Role Type :</label>
            <input type="text" class="form-control" name="role_type" id="role_type" placeholder="Enter Role Type" value="<?php echo $this->employeeRoleTypeDetails['role_type']; ?>" style="width: 220px;">
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-2 col-lg-2">
            <input type="submit" class="btn btn-primary" value="Update">
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>