<style>
#mandatory {
  color: red;
}
</style>
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Material Supplier(s) List For Site
          <div class="pull-right">
            <a href="javascript:void(0)" data-toggle="modal" data-target="#addMaterialSupplierModal" class="btn btn-success">Add Supplier</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="transfer-type-list">
            <table class="display" width="100%" id="transferForTypeTable">
             <thead>
              <th>#</th>
              <th>Supplier Name</th>
              <th>Supplier GST Number</th>
              <th>Supplier Contact Person</th>
              <th>Supplier Contact Number</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->materialSupplierList){
                $i = 1;
                foreach ($this->materialSupplierList as $materialSupplier) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo ucwords(strtolower($materialSupplier['supplier_name'])); ?></td>
                  <td><?php echo $materialSupplier['supplier_gst'] == NULL ? "-":$materialSupplier['supplier_gst']; ?></td>
                  <td><?php echo $materialSupplier['supplier_person_name'] == NULL ? "-":ucwords(strtolower($materialSupplier['supplier_person_name'])); ?></td>
                  <td><?php echo $materialSupplier['supplier_contact_number'] == NULL ? "-":$materialSupplier['supplier_contact_number']; ?></td>
                  <td><?php echo $materialSupplier['status'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($materialSupplier['status'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteMaterialSupplier(<?php echo $materialSupplier['id']; ?>,'deactivate')" title="Deactivate Material Supplier"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Material Supplier" onclick="deactivateActivateDeleteMaterialSupplier(<?php echo $materialSupplier['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteMaterialSupplier(<?php echo $materialSupplier['id']; ?>,'delete')" title="Delete Material Supplier"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Material Supplier Modal : Start -->
  <div class="modal fade" id="addMaterialSupplierModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Material Supplier</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form" id="addMaterialSupplierForm">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="materialSupplierName">Supplier Name <span id="mandatory">*</span></label>
                <input type="text" class="form-control" name="materialSupplierName" id="materialSupplierName" placeholder="Enter Material Supplier Name">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="materialSupplierGst">Supplier GST Number</label>
                <input type="text" class="form-control" name="materialSupplierGst" id="materialSupplierGst" placeholder="Enter Material Supplier GST Number" oninput="this.value = this.value.replace(/[^0-9a-zA-Z]/g, '');" onkeyup="this.value = this.value.toUpperCase();" data-toggle="tooltip" title="Enter Only Capital Alphabets (Upperase)">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="materialSupplierContactPerson">Supplier Contact Person</label>
                <input type="text" class="form-control" name="materialSupplierContactPerson" id="materialSupplierContactPerson" placeholder="Enter Material Supplier Contact Person">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="materialSupplierContactNumber">Supplier Contact Number</label>
                <input type="text" class="form-control" name="materialSupplierContactNumber" id="materialSupplierContactNumber" placeholder="Enter Material Supplier Name" oninput="this.value = this.value.replace(/[^0-9]/g, '');" title="Enter Numeric Value Only">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <button type="submit" class="btn btn-primary" id="submitMaterialSupplierForm">Save</button>
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  <!-- Add Material Supplier Modal : End -->
  <script>
    $(document).ready(function() {
      $("#transferForTypeTable").DataTable();
      $('#submitMaterialSupplierForm').click(function(event) {
        event.preventDefault();
        var materialSupplierName = $('#materialSupplierName').val();
        if (materialSupplierName == "") {
          swal({
            title : "Supplier Name Missing!",
            text  : 'Please enter supplier name.',
            icon  : 'error'
          }).then(function(){
            $('#materialSupplierName').focus();
            $('#materialSupplierName').css('border', 'solid 1px red');
          });
        } else {
          $("#addMaterialSupplierModal").modal('toggle');
          $.ajax({
            url: '/master/add-material-supplier',
            type: 'POST',
            data: $('#addMaterialSupplierForm').serialize(),
            success:function(data){
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : 'success'
                }).then(function(){
                  window.location.href = '/master/material-suppliers';
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : 'error'
                }).then(function(){
                  $("#addMaterialSupplierModal").modal('toggle');
                });
              }
            }
          });
        }
      });
      $('#materialSupplierName').keyup(function(event) {
        event.preventDefault();
        $('#materialSupplierName').css('border', '');
      });
    });

    function deactivateActivateDeleteMaterialSupplier(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" clicked Supplier?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url  : '/master/deactivate-activate-delete-material-supplier',
            type : 'POST',
            data : {type:type, material_supplier_id:id},
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/material-suppliers");
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });
        }
      });
    }
  </script>

