
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
        </div>
    <?php } else if ($message['error']) { ?>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
    </div>
<?php } ?>
<?php endforeach ?>
<?php endif ?>
<div class="panel panel-primary">
  <div class="panel panel-heading">
    <h3>Nature Of Work
      <div class="pull-right">
        <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" class="btn btn-success">Add Nature Of Work</a>
    </div></h3>
</div>
<div class="panel panel-body">
  <div class="table-responsive" id="state-list">
    <table class="display" width="100%" id="natureOfWorkTable">
      <thead>
        <tr>
            <strong>
                <th>#</th>
                <th>Nature Of Work</th>
                <th>Action</th>
            </strong>
        </tr>
    </thead>
    <tbody>
      <?php if($this->natrureOfWork){
        $i = 1;
        foreach ($this->natrureOfWork as $work) { ?>
           <tr>
            <td> <?php echo $i; ?></td>
            <td><?php echo $work['nature_of_work']; ?></td>
            <td>
                <a href="javascript:void(0)" onclick="deleteNatureOfWork('<?php echo $work['id'];?>')" title="Delete Work"><span class="fa fa-trash" style="color: red;"></span></a>
            </td>                                                                                         
        </tr>
        <?php $i++; } } ?>
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>

<!-- Add Nature of Work Modal : START -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title">Add Nature Of Work</h3>
            </div>
            <div class="modal-body">
                <form class="form-inline" role="form">
                    <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
                        <label class="sr-only" for="">Nature of Work</label>
                        <input style="width: 100%;" type="text" class="form-control" name="nature_of_work" id="nature_of_work" placeholder="Enter Nature of work">
                    </div>
                    <button type="submit" class="btn btn-success" id="saveNatureOfWork">Save</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<!-- Add Nature of Work Modal : END -->
<script>
    $(document).ready(function() {
        $("#natureOfWorkTable").DataTable();
        $('#saveNatureOfWork').click(function(e) {
            e.preventDefault();
            var natureOfWork = $('#nature_of_work').val();
            if (natureOfWork == "") {
                swal({
                    title : 'Nature of Work Missing!',
                    text  : 'Please enter nature of work.',
                    icon  : 'error'
                }).then(function(){
                    $('#nature_of_work').focus();
                });
            } else {
                $('#loading-bg').show();
                $('#myModal').modal('toggle');
                $.ajax({
                    url: '/master/add-nature-of-work',
                    type: 'POST',
                    data: {natureOfWork: natureOfWork},
                    success:function(data){
                        var data = JSON.parse(data);
                        console.log(data);
                        $("#loading-bg").hide();
                        if (data.flag) {
                            swal({
                                title : data.title,
                                text  : data.message,
                                icon  : 'success'
                            }).then(function(){
                                window.location.href = '/master';
                            });
                        } else {
                            swal({
                                title : data.title,
                                text  : data.message,
                                icon  : 'error'
                            }).then(function(){
                                $('#myModal').modal('toggle');
                            });
                        }
                    }
                });
                
            }
        });
    });

    function deleteNatureOfWork(id) {
        swal({
            title : "Are you sure?",
            text  : "Do you want to delete this work?",
            icon  : "warning",
            buttons : [true, "Yes, Delete"],
            dangerMode : true
        }).then(function (isConfirm) {
            if (!isConfirm) return;
            $.ajax({
                url: "/master/delete-work/id/"+id,
                context: document.body,
                success: function (data) {
                    var data = JSON.parse(data);
                    if (data.flag) {
                      swal({
                        title: "Deleted", 
                        text: data.message, 
                        icon: "success"
                    }).then(function() {
                        window.location.href="/master";
                    });
                } else {
                    swal({
                        title: "Failed !", 
                        text: data.message, 
                        icon: "error"
                    });
                } 
            }
        });
        });
    }
</script>