
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Product List
          <div class="pull-right">
            <a href="/master/add-new-product" class="btn btn-success">Add Product</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="product-list">
            <table class="display" width="100%" id="productListTable">
             <thead>
              <th>#</th>
              <th>Product Name</th>
              <th>Product Type</th>
              <th>Product Unit</th>
              <th>Price/Unit</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->productDetails){
                $i = 1;
                foreach ($this->productDetails as $product) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $product['product_name']; ?></td>
                  <td><?php echo $product['product_type_name']; ?></td>
                  <td><?php echo $product['unit']; ?></td>
                  <td><?php echo $product['price']; ?></td>
                  <td>
                    <a href="/master/edit-product/product-id/<?php echo md5($product['id']);?>" class="todoedit" title="Edit Product Type"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteProduct('<?php echo $product['id'];?>')" title="Delete Product Type"><span class="fa fa-trash" style="color: red;"></span></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function() {
      $("#productListTable").DataTable();
    });
    function deleteProduct(id) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete clicked product?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url: '/master/delete-product/id/'+id,
            type: 'GET',
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : "Deleted",
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/product-unit-list");
                });
              } else {
                swal({
                  title : "Failed !",
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
  </script>

