
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Product Type List
          <div class="pull-right">
            <a href="/master/add-product-type" class="btn btn-success">Add Product Type</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="transfer-type-list">
            <table class="display" width="100%" id="productTypeListTable">
             <thead>
              <th >#</th>
              <th>Product Type</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->productlist){
                $i = 1;
                foreach ($this->productlist as $products) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $products['product_type_name']; ?></td>
                  <td>
                    <a href="/master/edit-product-type/product-type-id/<?php echo md5($products['id']);?>" class="todoedit" title="Edit Product Type"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteProductType('<?php echo $products['id'];?>','<?php echo $products['product_type_name'];?>')" title="Delete Product Type"><span class="fa fa-trash" style="color: red;"></span></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function() {
      $("#productTypeListTable").DataTable();
    });
    function deleteProductType(id, name) {
      swal({
        title: "Are you sure?",
        text: " Do You want to delete selected product type?",
        icon: "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
          url: "/master/delete-product-type/id/"+id,
          success: function (data) {
            var data = JSON.parse(data);
            if (data.flag) {
              swal({
                title : "Deleted",
                text : data.message,
                icon : "success"
              }).then(function(){
                location.reload("/master/product-type");
              });
            } else {
              swal({
                title : "Failed !",
                text : data.message,
                icon : "error"
              });
            }
          }
        });
      });
    }
  </script>
