
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Product Brand List
          <div class="pull-right">
            <a href="/master/add-product-brand" class="btn btn-success">Add Product Brand</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="transfer-type-list">
            <table class="display" width="100%" id="productBrandListTable">
             <thead>
              <th >#</th>
              <th>Product Brand Name</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->productBrand){
                $i = 1;
                foreach ($this->productBrand as $productBrands) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $productBrands['brand_name']; ?></td>
                  <td>
                    <a href="/master/edit-product-brand/product-brand-id/<?php echo md5($productBrands['id']);?>" class="todoedit" title="Edit Product Brand Name"><span class="fa fa-pencil" style="color: #1DAA29;"></span></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteProductBrand('<?php echo $productBrands['id'];?>','<?php echo $productBrands['brand_name']; ?>')" title="Delete Product Brand Name"><span class="fa fa-trash" style="color: red;"></span></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function() {
      $("#productBrandListTable").DataTable();
    });
    function deleteProductBrand(id, name) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete "+name+" from product brand?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url: '/master/delete-product-brand/id/'+id+'/name/'+name,
            type: 'GET',
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : "Deleted",
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload("/master/product-brand-list");
                });
              } else {
                swal({
                  title : "Failed !",
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
  </script>

