
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>




		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Site Documents
					<div class="pull-right">
						<a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addSiteModal">Add Site Documents</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="document-list">
						<table class="display" width="100%" id="siteListTable">
							<thead>
								<th>#</th>
								<th>Site-Documents</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php if($this->siteDocumentMasterList){
									$i = 1;
									foreach ($this->siteDocumentMasterList as $site) { ?>
										<tr>
											<td><?php echo $i; ?></td>
											<td><?php echo $site['document_name']; ?></td>
											<td>
												<a href="javascript:void(0)" onclick="deletesite('<?php echo $site['id'];?>')" title="Delete Site Documents"><span class="fa fa-trash" style="color: red;"></span></a>
											</td>
										</tr>
										<?php $i++; } } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- Add Bank Modal : Start -->
			<div class="modal fade" id="addSiteModal">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h4 class="modal-title">Add Site-Documents</h4>
						</div>
						<div class="modal-body">
							<div class="row">
								<form action="/master/add-site-document" method="POST" class="form-inline" role="form">
									<div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
										<label for="document_name" >Site-Documents :</label>
										<input type="text" class="form-control" name="document_name" id="document_name" placeholder="Enter Site-Documents" required>
									</div>
									<div class="custom-control custom-checkbox">
										<input type="checkbox" class="custom-control-input" id="is_required" name="is_required" >

										<label class="custom-control-label" for="defaultUnchecked"> Is Required</label>
									</div><br>
									<div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
										<input type="submit" class="btn btn-primary" value="Save">
									</div>
								</form>
							</div>
						</div>
						<div class="modal-footer"></div>
					</div>
				</div>
			</div>
			<!-- Add Bank Modal : End -->

			<!-- Edit Bank Modal : Start -->
			<div class="modal fade" id="editSiteModal"></div>
			<!-- Edit Bank Modal : End -->

			<script type="text/javascript">
				$(document).ready(function() {
					$("#siteListTable").DataTable();
				});
				function deletesite(id) {
					swal({
						title : "Are you sure?",
						text  : "Do you want to delete clicked Site-Documents?",
						icon  : "warning",
						buttons : [true, "Yes, Delete"],
						dangerMode : true
					}).then(function(isConfirm){
						if (!isConfirm) {
							return false;
						} else {
							$.ajax({
								url: '/master/delete-site-document/id/'+id,
								type: 'GET',	
								success:function(data){
									var data = JSON.parse(data);
									if (data.flag) {
										swal({
											title : "Deleted",
											text  : data.message,
											icon  : "success",
										}).then(function(){
											location.reload("/master/document-list");
										});
									} else {
										swal({
											title : "Failed !",
											text  : data.message,
											icon  : "error"
										});           
									}
								}
							});

						}
					});
				}
				function editSiteDocumentModal(id) {
					if (id == "") {
						swal({
							title : "Site Document Missing!",
							text  : "Please try after refresh the page once.",
							icon  : "error"
						});
					} else {
						$.ajax({
							url: '/master/get-site-document',
							type: 'POST',
							data: {site_id: id},
							success:function(data){
								$("#editSiteModal").html(data);
								$("#editSiteModal").modal("toggle");
							}
						});

					}
				}
			</script>

