<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Site Type List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addSiteTypeModal">Add Site Type</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="siteTypeListTable">
             <thead>
              <th>#</th>
              <th>Work For</th>
              <th>Site Type</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->siteTypeList){
                $i = 1;
                foreach ($this->siteTypeList as $siteType) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $siteType['work_for']; ?></td>
                  <td><?php echo $siteType['site_type']; ?></td>
                  <td><?php echo $siteType['is_active'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($siteType['is_active'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteSiteType(<?php echo $siteType['id']; ?>,'deactivate')" title="Deactivate Work Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Work Type" onclick="deactivateActivateDeleteSiteType(<?php echo $siteType['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteSiteType(<?php echo $siteType['id']; ?>,'delete')" title="Delete Work Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addSiteTypeModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Site Type</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_for_id">Site Work For :</label>
                <select class="form-control select2" name="work_for_id" id="work_for_id" style="width: 100%;">
                  <option value="">Select Site For</option>
                  <?php foreach ($this->workForSiteOfList as $workFor): ?>
                    <option value="<?php echo $workFor['id']; ?>"><?php echo $workFor['work_for_site_of_name']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="site_type">Site Type :</label>
                <input type="text" class="form-control" name="site_type" id="site_type" placeholder="Enter site Type">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <input type="submit" class="btn btn-primary pull-right" id="saveSiteTypeButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseInTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#siteTypeListTable").DataTable();
      $(".select2").select2();
      $("#saveSiteTypeButton").click(function(event) {
        event.preventDefault();
        var work_for_id = $("#work_for_id").val();
        var work_type = $("#site_type").val();
        if (work_for_id == "") {
          swal({
            title : "Site Work For Missing!",
            text  : "Please select site work for.",
            icon  : "error",
          }).then(function(){
            $("#work_for_id").focus();
          });
        } else if (work_type == "") {
         swal({
          title : "Site Type Missing!",
          text  : "Please enter site type.",
          icon  : "error",
        }).then(function(){
          $("#site_type").focus();
        });
      } else {
        $("#addSiteTypeModal").modal("toggle");
        $("#loading-bg").show();
        $.ajax({
          url: '/master/add-site-type',
          type: 'POST',
          data: {work_type:work_type, work_for_id:work_for_id},
          success:function(data){
            $("#loading-bg").hide();
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#addSiteTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    });
    });
    function deactivateActivateDeleteSiteType(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" site type?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url  : '/master/deactivate-activate-delete-site-type',
            type : 'POST',
            data : {type:type, work_type_id:id},
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    // function submitUpdateExpenseInTypeForm(id) {
    //   var work_type_id = $("#updatedExpenseTypeId").val();
    //   var work_type = $("#updatedExpenseInType").val();
    //   if (work_type_id == "") {
    //     swal({
    //       title : "Expense Type Missing!",
    //       text  : "Please select expense type.",
    //       icon  : "error",
    //     });
    //   } else if (work_type == "") {
    //     swal({
    //       title : "Expense In Type Missing!",
    //       text  : "Please enter expense in type.",
    //       icon  : "error",
    //     });
    //   } else {
    //     $("#editExpenseInTypeModal").modal("toggle");
    //     $.ajax({
    //       url: '/master/edit-expense-in-type',
    //       type: 'POST',
    //       data: {expenseInTypeId:id, work_type_id: work_type_id, work_type:work_type},
    //       success:function(data){
    //         var data = JSON.parse(data);
    //         console.log(data);
    //         if (data.flag) {
    //           swal({
    //             title : "Updated Successfully",
    //             text  : data.message,
    //             icon  : "success"
    //           }).then(function(){
    //             location.reload();
    //           });
    //         } else {
    //           swal({
    //             title : "Error",
    //             text  : data.message,
    //             icon  : "error"
    //           }).then(function(){
    //             $("#editExpenseInTypeModal").modal("toggle");
    //           });
    //         }
    //       }
    //     });
    //   }
    // }
  </script>

