
</style>
<script type="text/javascript">
  function deleteStateFor(id) {
    swal({
      title : "Are you sure ?",
      text  : "Do you want to delete state for ?",
      icon  : "warning",
      buttons:[true, "Yes, Delete"],
      dangerMode : true
    }).then(function(isConfirm){
      if (!isConfirm) {
        return false;
      } else {
        $.ajax({
          url: '/master/delete-state-for',
          type: 'POST',
          data: {stateForId: id},
          success:function(data) {
            var data = JSON.parse(data);
            if (data.flag) {
              swal({
                title : "Success",
                text  : data.message,
                icon  : "success"
              }).then(function() {
                location.reload();
              });
            } else {
              swal({
                title : "Failed !",
                text  : data.message,
                icon  : "error"
              });
            }
          }
        });
      }
    });
  }
</script>

<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>State For
          <div class="pull-right">
            <a href="/master/add-state-for" class="btn btn-success">Add State For</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="state-list">
            <table class="display" width="100%" id="stateForTable">
              <thead>
                <tr>
                  <strong>
                    <th>#</th>
                    <th>State For</th>
                    <th >Action</th>
                  </strong>
                </tr>
              </thead>
              <tbody>
                <?php if($this->stateFor){
                  $i = 1;
                  foreach ($this->stateFor as  $state) { ?>
                   <tr>
                    <td> <?php echo $state['id']; ?></td>
                    <td><?php echo $state['state_for']; ?></td>
                    <td>
                      <a href="/master/edit-state-for/state-for-id/<?php echo md5($state['id']);?>" class="todoedit" title="Edit State For"><span class="fa fa-pencil"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteStateFor('<?php echo $state['id'];?>')" title="Delete State For"><span class="fa fa-trash" style="color: red;"></span></a>
                    </td>
                  </tr>
                  <?php $i++; } } ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      $(document).ready(function() {
        $("#stateForTable").DataTable();
      });
    </script>