
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
        </div>
    <?php } else if ($message['error']) { ?>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
    </div>
<?php } ?>
<?php endforeach ?>
<?php endif ?>
<div class="panel panel-primary">
  <div class="panel panel-heading">
    <h3>Supplier(s) List
      <div class="pull-right">
        <a href="/master/add-supplier" class="btn btn-success">Add Supplier</a>
    </div></h3>
</div>
<div class="panel panel-body">
  <div class="table-responsive" id="transfer-type-list">
    <table class="display" width="100%" id="transferForTypeTable">
       <thead>
        <th>#</th>
        <th>Supplier Name</th>
        <th>Mobile Number</th>
        <th>GST Number</th>
        <th>Action</th>
    </thead>
    <tbody>
      <?php if($this->supplierList){
        $i = 1;
        foreach ($this->supplierList as $suppliers) { ?>
           <tr>
            <td><?php echo $i; ?></td>
            <td><?php echo $suppliers['name']; ?></td>
            <td><?php echo $suppliers['contact_1']; ?></td>
            <td><?php echo $suppliers['gst_number']; ?></td>
            <td>
                <a href="/master/edit-supplier/datacode/<?php echo md5($suppliers['id']); ?>" title="Edit Supplier"><i class="fa fa-pencil" style="color: #1DAA29;"></i></a>
                &nbsp;&nbsp;
                <a href="javascript:void(0)" title="Delete Supplier" onclick="deleteSupplier(<?php echo $suppliers['id']; ?>, '<?php echo $suppliers['name']; ?>')"><i class="fa fa-trash" style="color: red;"></i></a>
            </td>
        </tr>
        <?php $i++; } } ?>
    </tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<script>
    $(document).ready(function() {
      $("#transferForTypeTable").DataTable();
  });

    function deleteSupplier(id, name) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete "+name+" from supplier list ?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
    }).then(function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
            url: "/master/delete-supplier/id/"+id+"/name/"+name,
            context: document.body,
            success: function (data) {
                console.log(data);
                var data = JSON.parse(data);
                if (data.flag) {
                  swal({
                    title: "Deleted", 
                    text: data.message, 
                    icon: "success"
                }).then(function() {
                    window.location.href="/master/supplier-list";
                });
            } else {
              swal({
                title: "Failed !", 
                text: data.message, 
                icon: "error"
            });
          } 
      }
  });
    });
}
</script>

