
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">Company's Details</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="table-responsive">
					<table width="100%" class="table table-hover">
						<tr>
							<th>Company Name :</th><td><?php echo $this->companyDetails['vendor_company_name']; ?></td>
							<th>Proprietor Name :</th><td><?php echo $this->companyDetails['proprietor_name']; ?></td>
						</tr>
						<tr>
							<th>Contact Person :</th><td><?php echo $this->companyDetails['contact_person_name']; ?></td>
							<th>Contact Number :</th><td><?php echo $this->companyDetails['contact_number']; ?></td>
						</tr>
						<tr>
							<th>PAN Number :</th><td><?php echo $this->companyDetails['pan_number']; ?></td>
							<th>GST Number :</th><td><?php echo $this->companyDetails['gst_number']; ?></td>
						</tr>
						<tr>
							<th>Company Address :</th><td colspan="3"><?php echo $this->companyDetails['company_address']; ?></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="modal-footer">
		</div>
	</div>
</div>