
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Work Handling Amount Master List
          <div class="pull-right">
            <a href="/master/add-work-handling-amount-master" class="btn btn-success">Add Work Handling Amount</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="transfer-type-list">
            <table class="display" width="100%" id="workHandlingAmountMasterTable">
             <thead>
              <th>#</th>
              <th>Work Handling Amount Master Name</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->workHandlingAmountList){
                $i = 1;
                foreach ($this->workHandlingAmountList as $workHandlingAmount) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $workHandlingAmount['work_handling_amount']; ?></td>
                  <td>
                    <a href="/master/edit-work-handling-amount-master/work-handling-amount-master-id/<?php echo md5($workHandlingAmount['id']); ?>" title="Edit Work Handling Amount"><i class="fa fa-pencil" style="color: #1DAA29;"></i></a>
                    &nbsp;&nbsp;
                    <a href="javascript:void(0)" title="Delete Work Handling Amount" onclick="deleteWorkHandlingAmountMaster(<?php echo $workHandlingAmount['id']; ?>)"><i class="fa fa-trash" style="color: red;"></i></a>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function() {
      $("#workHandlingAmountMasterTable").DataTable();
    });

    function deleteWorkHandlingAmountMaster(id) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to delete selected work handling amount master?",
        icon  : "warning",
        buttons : [true, "Yes, Delete"],
        dangerMode : true
      }).then(function (isConfirm) {
        if (!isConfirm) return;
        $.ajax({
          url: "/master/delete-work-handling-amount-master/id/"+id,
          context: document.body,
          success: function (data) {
            console.log(data);
            var data = JSON.parse(data);
            if (data.flag) {
              swal({
                title: "Deleted", 
                text: data.message, 
                icon: "success"
              }).then(function() {
                window.location.href="/master/work-handling-amount-master";
              });
            } else {
              swal({
                title: "Failed !", 
                text: data.message, 
                icon: "error"
              });
            } 
          }
        });
      });
    }
  </script>

