<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Work Description List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addWorkDescriptionModal">Add Work Description</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="workDescriptionListTable">
             <thead>
              <th>#</th>
              <th>Work Type</th>
              <th>Work Name</th>
              <th>Work Description</th>
              <th>Aging Days</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->workDescriptionList){
                $i = 1;
                foreach ($this->workDescriptionList as $workDescription) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $workDescription['site_type']; ?></td>
                  <td><?php echo $workDescription['work_name']; ?></td>
                  <td><?php echo $workDescription['work_description']; ?></td>
                  <td><?php echo $workDescription['aging_days']; ?></td>
                  <td><?php echo $workDescription['is_active'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($workDescription['is_active'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWorkDescription(<?php echo $workDescription['id']; ?>,'deactivate')" title="Deactivate Work Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Work Type" onclick="deactivateActivateDeleteWorkDescription(<?php echo $workDescription['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWorkDescription(<?php echo $workDescription['id']; ?>,'delete')" title="Delete Work Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add Work Description Modal : Start -->
  <div class="modal fade" id="addWorkDescriptionModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Work Description</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_type">Work Type:</label>
                <select name="work_type" id="work_type" class="form-control select2" style="width: 100%;" onchange="getWorkNameByWorkType()">
                  <option value="">Select Work Type</option>
                  <?php foreach ($this->workTypeList as $workType): ?>
                    <option value="<?php echo $workType['id']; ?>"><?php echo $workType['site_type']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_name">Work Name:</label>
                <select name="work_name" id="work_name" class="form-control select2" style="width: 100%;">
                  <option value="">Select Work Name</option>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_description">Work Description:</label>
                <input type="text" class="form-control" name="work_description" id="work_description" placeholder="Enter Work Description">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="aging_days">Aging Days :</label>
                <input type="text" class="form-control" name="aging_days" id="aging_days" placeholder="Enter Work Aging Days" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="saveWorkDescriptionButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add Work Description Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#workDescriptionListTable").DataTable();
      $(".select2").select2();
      $("#saveWorkDescriptionButton").click(function(event) {
        event.preventDefault();
        var work_desc = $("#work_description").val();
        var work_name = $("#work_name").val();
        var work_type = $("#work_type").val();  
        var aging     = $("#aging_days").val();
        if (work_type == "") {
          swal({
            title : "Work Type Missing!",
            text  : "Please select work type.",
            icon  : "error",
          }).then(function(){
            $('#work_type').select2('open');
          });
        } else if (work_name == "") {
          swal({
            title : "Work Name Missing!",
            text  : "Please select work name.",
            icon  : "error",
          }).then(function(){
            $('#work_name').select2('open');
          });
        } else if (work_desc == "") {
          swal({
            title : "Work Description Missing!",
            text  : "Please enter work description.",
            icon  : "error"
          }).then(function(){
            $("#work_description").focus();
          });
        } else if (aging == "") {
         swal({
          title : "Aging Days Missing!",
          text  : "Please enter work aging days.",
          icon  : "error"
        }).then(function(){
          $("#aging_days").focus();
        });
      } else {
        $("#addWorkDescriptionModal").modal("toggle");
        $("#loading-bg").show();
        $.ajax({
          url: '/master/add-work-description',
          type: 'POST',
          data: {work_type_id:work_type, work_name_id:work_name, work_description:work_desc, aging_days:aging},
          success:function(data){
            $("#loading-bg").hide();
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#addWorkDescriptionModal").modal("toggle");
              });
            }
          }
        });
      }
    });
    });
    function getWorkNameByWorkType() {
      var work_type_id = $("#work_type").val();
      if (work_type_id) {
        $("#loading-bg").show();
        $.ajax({
          url: '/master/get-work-name-list-by-work-type',
          type: 'POST',
          data: {work_type_id:work_type_id},
          success:function(data){
            $("#loading-bg").hide();
            var data = JSON.parse(data);
            if (data.flag) {
              $("#work_name").append(data.options);
            } else {
              swal({
                title : data.title,
                text  : data.message,
                icon  : "error"
              });
            }
          }
        });
      } else {
        $("#work_name").html("<option value=''>Select Work Name</option>");
      }
    }
    function deactivateActivateDeleteWorkDescription(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" work description?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url  : '/master/deactivate-activate-delete-work-description',
            type : 'POST',
            data : {type:type, work_description_id:id},
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    function submitUpdateExpenseInTypeForm(id) {
      var work_type_id = $("#updatedExpenseTypeId").val();
      var work_name = $("#updatedExpenseInType").val();
      if (work_type_id == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please select expense type.",
          icon  : "error",
        });
      } else if (work_name == "") {
        swal({
          title : "Expense In Type Missing!",
          text  : "Please enter expense in type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseInTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-in-type',
          type: 'POST',
          data: {expenseInTypeId:id, work_type_id: work_type_id, work_name:work_name},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseInTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

