<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Work List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addWorkModal">Add Work</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="workListTable">
             <thead>
              <th>#</th>
              <th>Site Of</th>
              <th>Site Type</th>
              <th>Work</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->workList){
                $i = 1;
                foreach ($this->workList as $work) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $work['work_for_site_of_name']; ?></td>
                  <td><?php echo $work['site_type']; ?></td>
                  <td><?php echo $work['work_name']; ?></td>
                  <td><?php echo $work['is_active'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($work['is_active'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWork(<?php echo $work['id']; ?>,'deactivate')" title="Deactivate Work Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Work Type" onclick="deactivateActivateDeleteWork(<?php echo $work['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWork(<?php echo $work['id']; ?>,'delete')" title="Delete Work Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addWorkModal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Work</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form">
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_for_id">Site Work For :</label>
                <select name="work_for_id" id="work_for_id" class="form-control select2" style="width: 100%;" onchange="getSiteTypeList()">
                  <option value="">Select Work Type</option>
                  <?php foreach ($this->workForSiteOfList as $workFor): ?>
                    <option value="<?php echo $workFor['id']; ?>"><?php echo $workFor['work_for_site_of_name']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_type">Site Type:</label>
                <select name="work_type" id="work_type" class="form-control select2" style="width: 100%;">
                  <option value="">Select Site Type</option>
                  <?php foreach ($this->workTypeList as $workType): ?>
                    <option value="<?php echo $workType['id']; ?>"><?php echo $workType['work_type']; ?></option>
                  <?php endforeach ?>
                </select>
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <label for="work_name">Work :</label>
                <input type="text" class="form-control" name="work_name" id="work_name" placeholder="Enter Work Name">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="saveWorkButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseInTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#workListTable").DataTable();
      $(".select2").select2();
      $("#saveWorkButton").click(function(event) {
        event.preventDefault();
        var work_for_id = $("#work_for_id").val();
        var work_name   = $("#work_name").val();
        var work_type   = $("#work_type").val();  
        if (work_for_id == "") {
          swal({
            title : "Site For Missing!",
            text  : "Please select site work type.",
            icon  : "error",
          }).then(function(){
            $('#work_for_id').select2('open');
          });
        } else if (work_type == "") {
          swal({
            title : "Work Type Missing!",
            text  : "Please select work type.",
            icon  : "error",
          }).then(function(){
            $('#work_type').select2('open');
          });
        } else if (work_name == "") {
          swal({
            title : "Work Name Missing!",
            text  : "Please enter work name.",
            icon  : "error",
          }).then(function(){
            $("#work_name").focus();
          });
        } else {
          $("#addWorkModal").modal("toggle");
          $("#loading-bg").show();
          $.ajax({
            url: '/master/add-work',
            type: 'POST',
            data: {work_name:work_name, work_type_id:work_type, work_for_id:work_for_id},
            success:function(data){
              $("#loading-bg").hide();
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success"
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                }).then(function(){
                  $("#addWorkModal").modal("toggle");
                });
              }
            }
          });
        }
      });
    });
    function getSiteTypeList() {
      var work_for_id = $("#work_for_id").val();
      if (work_for_id == "") {
        swal({
          title : "Work For Missing!",
          text  : "Please select site work for.",
          icon  : "error"
        }).then(function(){
          $("#work_for_id").focus();
        });
      } else {
        $("#loading-bg").show();
        $.ajax({
          url: '/master/get-work-type-by-site-type',
          type: 'POST',
          data: {work_for_id:work_for_id},
          success:function(data){
           $("#loading-bg").hide();
           var data = JSON.parse(data);
           if (data.flag) {
            $("#work_type").html(data.options);
          } else {
            swal({
              title : data.title,
              text  : data.message,
              icon  : "error"
            });
          }
        }
      });
      }
    }
    function deactivateActivateDeleteWork(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" work?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url  : '/master/deactivate-activate-delete-work',
            type : 'POST',
            data : {type:type, work_name_id:id},
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    function submitUpdateExpenseInTypeForm(id) {
      var work_type_id = $("#updatedExpenseTypeId").val();
      var work_name = $("#updatedExpenseInType").val();
      if (work_type_id == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please select expense type.",
          icon  : "error",
        });
      } else if (work_name == "") {
        swal({
          title : "Expense In Type Missing!",
          text  : "Please enter expense in type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseInTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-in-type',
          type: 'POST',
          data: {expenseInTypeId:id, work_type_id: work_type_id, work_name:work_name},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseInTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

