<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
  <div class="main-page">
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Work Type List
          <div class="pull-right">
            <a href="javascript:void(0)" class="btn btn-success" data-toggle="modal" data-target="#addWorkTypeModal">Add Work Type</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive">
            <table class="display" width="100%" id="workTypeListTable">
             <thead>
              <th>#</th>
              <th>Work Type</th>
              <th>Status</th>
              <th>Action</th>
            </thead>
            <tbody>
              <?php if($this->workTypeList){
                $i = 1;
                foreach ($this->workTypeList as $workType) { ?>
                 <tr>
                  <td><?php echo $i; ?></td>
                  <td><?php echo $workType['work_type']; ?></td>
                  <td><?php echo $workType['is_active'] == "1" ? "Active":"Deactive"; ?></td>
                  <td>
                    <?php if ($workType['is_active'] == "1") { ?>
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWorkType(<?php echo $workType['id']; ?>,'deactivate')" title="Deactivate Work Type"><span class="fa fa-ban" style="color: #D66F00;"></span></a>
                    <?php } else { ?>
                      <a href="javascript:void(0)" title="Activate Work Type" onclick="deactivateActivateDeleteWorkType(<?php echo $workType['id']; ?>,'activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a>
                      &nbsp;&nbsp;
                      <a href="javascript:void(0)" onclick="deactivateActivateDeleteWorkType(<?php echo $workType['id']; ?>,'delete')" title="Delete Work Type"><span class="fa fa-trash" style="color: red;"></span></a>
                    <?php } ?>
                  </td>
                </tr>
                <?php $i++; } } ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Add State Modal : Start -->
  <div class="modal fade" id="addWorkTypeModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title">Add Work Type</h3>
        </div>
        <div class="modal-body">
          <div class="row">
            <form role="form" class="form-inline">
              <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <label for="work_type">Work Type :</label>
                <input type="text" class="form-control" name="work_type" id="work_type" placeholder="Enter Work Type" style="width: 70%;">
              </div>
              <div class="form-group col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" id="saveWorkTypeButton" value="Save">
              </div>
            </form>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    </div>
  </div>
  <!-- Add State Modal : End -->

  <!-- Edit Bank Modal : Start -->
  <div class="modal fade" id="editExpenseInTypeModal"></div>
  <!-- Edit Bank Modal : End -->

  <script type="text/javascript">
    $(document).ready(function() {
      $("#workTypeListTable").DataTable();
      $(".select2").select2();
      $("#saveWorkTypeButton").click(function(event) {
        event.preventDefault();
        var work_type = $("#work_type").val();
        if (work_type == "") {
          swal({
            title : "Work Type Missing!",
            text  : "Please enter work type.",
            icon  : "error",
          }).then(function(){
            $("#work_type").focus();
          });
        } else {
          $("#addWorkTypeModal").modal("toggle");
          $("#loading-bg").show();
          $.ajax({
            url: '/master/add-work-type',
            type: 'POST',
            data: {work_type:work_type},
            success:function(data){
              $("#loading-bg").hide();
              var data = JSON.parse(data);
              console.log(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success"
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                }).then(function(){
                  $("#addWorkTypeModal").modal("toggle");
                });
              }
            }
          });
        }
      });
    });
    function deactivateActivateDeleteWorkType(id, type) {
      swal({
        title : "Are you sure?",
        text  : "Do you want to "+type+" work type?",
        icon  : "warning",
        buttons : [true, "Yes, "+type],
        dangerMode : true
      }).then(function(isConfirm){
        if (!isConfirm) {
          return false;
        } else {
          $.ajax({
            url  : '/master/deactivate-activate-delete-work-type',
            type : 'POST',
            data : {type:type, work_type_id:id},
            success:function(data){
              var data = JSON.parse(data);
              if (data.flag) {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "success",
                }).then(function(){
                  location.reload();
                });
              } else {
                swal({
                  title : data.title,
                  text  : data.message,
                  icon  : "error"
                });           
              }
            }
          });

        }
      });
    }
    function submitUpdateExpenseInTypeForm(id) {
      var work_type_id = $("#updatedExpenseTypeId").val();
      var work_type = $("#updatedExpenseInType").val();
      if (work_type_id == "") {
        swal({
          title : "Expense Type Missing!",
          text  : "Please select expense type.",
          icon  : "error",
        });
      } else if (work_type == "") {
        swal({
          title : "Expense In Type Missing!",
          text  : "Please enter expense in type.",
          icon  : "error",
        });
      } else {
        $("#editExpenseInTypeModal").modal("toggle");
        $.ajax({
          url: '/master/edit-expense-in-type',
          type: 'POST',
          data: {expenseInTypeId:id, work_type_id: work_type_id, work_type:work_type},
          success:function(data){
            var data = JSON.parse(data);
            console.log(data);
            if (data.flag) {
              swal({
                title : "Updated Successfully",
                text  : data.message,
                icon  : "success"
              }).then(function(){
                location.reload();
              });
            } else {
              swal({
                title : "Error",
                text  : data.message,
                icon  : "error"
              }).then(function(){
                $("#editExpenseInTypeModal").modal("toggle");
              });
            }
          }
        });
      }
    }
  </script>

