<?php
 $attendance_report=$this->attendance_report;
 $attendance_report = $this->paginator; 
 $totalrec = $this->totalrec;
  //$params = $this->params;
?>

<div class=" view-port-height">
<!-- Content Header (Page header) -->

        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i> Attendance Report</h4>
                </div>
            </div>
        </div>
        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <div class="alert_data">
                <?php echo $message ?>.
                </div>
                <?php endforeach ?>
                </div>
            <?php endif ?>
        

            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                       <p style="float: left; margin: 3px;">Attendance Report </p> 
                           <a href="/task/attendance-report" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px">Export Attendance Record
                           </a>
                    </div>
                                    
                        <div class="card-block">
                            <div class="row basic_tables">
                                <div class="col-12">
                                    <div class="table-responsive mt-0" id="attendance_report">
                                         <div id="leftpag">
                                <!-- START PAGINATION -->
                             
                                <!-- END PAGINATION -->
                                </div>
                                        <table  class="table table-striped">
                                            <thead>
                                            <tr>
                                                <strong>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >#</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">User ID</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8"" nowrap="">User Type</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Contact No.</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Start Day Datetime</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Start Day Latitude</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day  Longitude</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day Datetime</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day Latitude</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day  Longitude</th>
                                                <!-- <th style="text-align:center!important; font-weight: bold; color:#007bb8" nowrap=""  >status</th> -->
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Created</th>
                                                <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Updated</th>

                                                </strong>
                                            </tr>
                                            </thead>
                                            <tbody>
                                           
                                              <?php if($totalrec){ $totalnum = $this->totalnum?$this->totalnum:1;
                                                $istart = ($totalnum-1) * 10;
                                                $i=$istart; 
                                                foreach ($attendance_report as  $user) { 

                                                   ?>
                                            <tr>
                                              <td style="text-align:left!important;" nowrap=""> <?php echo $user['id']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['user_id']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['user_type']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['contact_no']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_datetime']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_latitude']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_longitude']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_datetime']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_latitude']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_longitude']; ?></td>
                                              <!-- <td style="text-align:center!important;" nowrap=""><?php //echo $user['status']; ?></td> -->
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['created']; ?></td>
                                              <td style="text-align:left!important;" nowrap=""><?php echo $user['updated']; ?></td>                                                                                            
                                            </tr>
                                          
                                            <?php $i++; } } else{  ?>
                                    <tr><td colspan="6"><span style="color:red; font-size:10px;">No Record Found !</span></td></tr>
                                       <?php  } ?>
                                            </tbody>
                                        </table>
                           

                <div class="row">
                  <div class="col col-xs-12">
                    <ul class="pagination hidden-xs pull-right">
                      <li><?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?></li>
                      
                    </ul>
                    
                  </div>
                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- /.content -->
    </div>
</div>