<?php
    $user_list = $this->user_list;
    $record = $this->paginator; 
    $totalrec = $this->totalrec;
?>
<script type="text/javascript">
// function getPage(page){
//       var url   = '/vendor/user-list/page/'+page;
//       var id    = 'user-list';
//       $("#"+id).html('<div class="loading">Loading&#8230;</div>');
//       $.ajax({
//           url: url,
//           context: document.body,
//           success: function(responseText) {
//               $("#"+id).html(responseText);
//               $("#"+id).find("script").each(function(i) {
//                   eval($(this).text());
//               });
//           }
//       });
// };
</script>
<div class=" view-port-height">
<!-- Content Header (Page header) -->
        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i>  Vendor's Manpower List</h4>
                </div>
            </div>
        </div>

        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <div class="alert_data">
                <?php echo $message ?>.
                </div>
                <?php endforeach ?>
                </div>
            <?php endif ?>
            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                                   <p style="float: left; margin: 3px;">Vendor's ManPower Details</p> 
                                   <a href="/vendor" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px">
                                        <i class="ti-user"></i> View Vendor List
                                        </a>

                                 

                                    </div>
                        <div class="card-block">
                           
                            <div class="row basic_tables">
                                <div class="col-12 m-t-20">
                                    <div class="table-responsive mt-1" id="user-list">
                                        <table class="table table-striped">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Name</th>
                                                <th>Department</th>
                                                <th>Experience</th>
                                                <th>Date Of Joining</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10;
                                            $i=$istart;
                                            foreach($record as $user)
                                            { ?>
                                            <tr>
                                                <td><?php echo $i+1;?>.</td>
                                                <td><?php echo $user['name']; ?></td>
                                                <td><?php echo $user['dname']; ?></td>
                                                <td><?php echo $user['experience']; ?></td>
                                                <td><?php echo $user['joining_date']; ?></td>
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="7"><p style="color:red; font-size:16px;">No User Found !</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                                        <div id="leftpag">
                                <!-- START PAGINATION -->
                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->
                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.content -->
    </div>
</div>