<?php
$params = $this->params;
?>


<script type="text/javascript">
 function validateUser(){ 
  if(document.getElementById("asset_type").value==""){
    swal("Please Enter Asset Type");
    document.getElementById("asset_type").focus();
    return false;
  }
}
</script>


<div class=" view-port-height">
  <!-- Content Header (Page header) -->
  <div class="content-header container-fluid bg-white">
    <div class="row">
      <div class="col-sm-4">
        <h4><i class="ti-user"></i> Add Asset Type </h4>
      </div>
    </div>
  </div>
  <!-- Main content -->
  <div class="content">

    <?php if ($this->messages): ?>
      <div class="alert alert-success alert-dismissable">
        <?php foreach ($this->messages as $message): ?>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php echo $message ?>
        <?php endforeach ?>
      </div>
    <?php endif ?>
    <?php if($this->errorMessage) { ?>
      <br clear="all">
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><?php  echo $this->errorMessage;   ?>                                             
      </div>
    <?php } ?>


    <div class="row">
      <div class="col-12">
        <div class="card  profile2_aboutme">
          <div class="card-header card-info text-white">

            <p style="float: left; margin: 0px;"></p> <a href="/assets/assets-type/"  style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">View All Asset Type</a>
          </div>

          <div class="card-block ">
            <div class="row m-t-10">
              <div class="col-lg-12">
                <form name="form" method="post"   
                action="" onsubmit="return validateUser();" enctype="multipart/form-data">

                <div class="form-group row">
                  <div class="col-lg-5">
                    <label for="caddress" class="col-form-label">
                      Enter Type
                    </label>
                    <div class="input-group">
                      <input type="text" name="asset_type" id="asset_type"
                      placeholder="Enter Type" class="form-control" />
                    </div>
                  </div> 
                  <div class="col-lg-3" style="margin-top: 40px">
                    <button type="submit" name="submit" class="btn btn-responsive layout_btn_prevent btn-info">Save</button>
                  </div>
                </div>                                      
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.content -->
</div>
</div>

