	<?php

	$natureOfWork = $this->paginator; 
	$totalrec = $this->totalrec;

	// print_r($this->qry_assets);
	// exit();
	?>
	<style>

	.modal-header .close {
		color: #000000 !important;
	</style>
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/pages/modals.js"></script>
	<script type="text/javascript">
		function deleteSystem(id) {
			swal({
				title: "Are you sure?",
				text: "You want to Delete this ",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes, Delete this Type!",
				closeOnConfirm: false
			}, function (isConfirm) {
				if (!isConfirm) return;
				$.ajax({
					url: "/assets/delete-system/id/"+id,
					context: document.body,
					success: function () {
						swal({
							title: "Deleted", 
							text: "Deleted successfully ", 
							type: "success"
						},function() {
							window.location.href="/assets/asset-allocation";
						});
					},
					error: function (xhr, ajaxOptions, thrownError) {
						swal("Error "+status+"!","Please try again", "error");
					}
				});
			});
		};
	</script>
	<div class="content-header container-fluid bg-white">
		<div class="row">
			<div class="col-sm-4">
				<h4><i class="ti-list"></i>Listing</h4>
			</div>
		</div>
	</div>


	<div class="content">

		<?php if ($this->messages): ?>
			<div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
				<?php foreach ($this->messages as $message): ?>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<div class="alert_data">
						<?php echo $message ?>
					</div>
				<?php endforeach ?>
			</div>
		<?php endif ?>

	<!-- <div class="row">
	<div class="col-12">
	<div class="card  profile2_aboutme">
	<div class="card-header card-info text-white">
	<p style="float: left; margin: 3px; color: #fff;">System</p> 
	<a href="/assets/add-system" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px">
	<i class="ti-user"></i> Add System
	</a>
</div> -->



<div class="card-block">
	<div class="row basic_tables">
		<div class="col-12">
			<div class="table-responsive mt-0" >

				<table  class="table table-striped">
					<thead>
						<tr>
							<strong>
								<th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >#</th>
								<th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">System</th>
								<th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">Allocated by</th>
								<th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">Allocated to</th>
								<th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Released date</th>
							</strong>
						</tr>
					</thead>
					<tbody>

						<?php if($totalrec){ $totalnum = $this->totalnum?$this->totalnum:1;
							$istart = ($totalnum-1) * 10;
							$i=1; 
							foreach ($this->qry_assets as  $user) { 

								?>
								<tr>
									<td style="text-align:left!important;" nowrap=""> <?php echo $i; ?></td>
									<td style="text-align:left!important;" nowrap=""><?php echo $user['name']; ?></td>
									<td style="text-align:left!important;" nowrap=""><?php echo $user['assigned_by']; ?></td>
									<td style="text-align:left!important;" nowrap=""><?php echo $user['user_name']; ?></td>
									<td style="text-align:left!important;" nowrap=""><?php echo date('d-m-y'); ?></a></td>




	<!-- <td>
	<a href="javascript:void(0)" class="toallocate" title="Allocated List" onclick="showAssets(<?php echo $user['id'];?>)"><span class="fa fa-list"></span></a>&nbsp&nbsp
-->
<!-- <a href="/assets/edit-system/id/<?php echo $user['id'];?>" class="todoedit" title="edit"><span class="ti-pencil-alt"></span></a>&nbsp&nbsp<a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteSystem('<?php echo $user['id'];?>')" title="delete"><span class="ti-trash"></span></a> --><!-- </td>                                                                 -->                         
</tr>

<?php $i++; } } else{  ?>
	<tr><td colspan="6"><span style="color:red; font-size:10px;">No Record Found !</span></td></tr>
<?php  } ?>
</tbody>
</table>


	<!-- <div class="row">
	<div class="col col-xs-12">
	<ul class="pagination hidden-xs pull-right">
	<li><?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?></li>

	</ul>

</div> -->
</div>
</div>
</div>
</div>
</div>




</div>
</div>
</div>

</div> <!-- end of content -->

<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>

<script>


	function closeModal() {
		$("#myModal").modal("toggle");
	}
	// function showAssets(system_id){
	// $.ajax({
	// url: "/assets/system-assets/system_id/"+system_id,
	// context: document.body,
	// success: function(responseText) {
	// $("#myModal").html(responseText);
	// $("#myModal").modal("toggle");
	// }

});
}
</script>