
<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Asset Details
					<div class="pull-right">
						<a href="javascript:;" class="btn btn-success" data-toggle="modal" data-target="#addAssetModal">Add New Asset</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="state-list">
						<table class="display" width="100%" id="assetTypeListTable">
							<thead>
								<th>#</th>
								<th>Code</th>
								<th>Name</th>
								<th>Asset Type</th>
								<th>Warranty Date</th>
								<th>Status</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php if($this->assetDetails){
									$i = 1;
									foreach ($this->assetDetails as $asset) { ?>
										<tr>
											<td> <?php echo $i; ?>
										</td>
										<td><?php echo $asset['code']; ?></td>
										<td><?php echo $asset['name']; ?></td>
										<td><?php echo $asset['type']; ?></td>
										<td><?php echo date('d/m/Y',strtotime($asset['warranty_date'])); ?></td>
										<td><?php echo $asset['is_active'] ? "Active":"Deactive"; ?></td>
										<td>
											<?php if ($asset['is_active']){ ?>
												<!-- <a href="javascript:void(0)" title="Edit Asset Type" onclick="editDeactiveActiveDeleteAsset('<?php //echo md5($asset['id']); ?>','edit')"><span class="fa fa-pencil"></span></a>
													&nbsp;&nbsp; -->
												<!-- <a href="javascript:void(0)" onclick="editDeactiveActiveDeleteAsset('<?php //echo $asset['id'];?>','deactivate')" title="Deactivate Asset Type"><span class="fa fa-ban" style="color: #D66F00;"></span>
												</a> -->
											<?php } else { ?>
												<!-- <a href="javascript:void(0)" title="Activate Asset Type" onclick="editDeactiveActiveDeleteAsset('<?php //echo $asset['id']; ?>','activate')"><span class="fa fa-sign-in" style="color: #1DAA29;"></span></a> -->
												&nbsp;&nbsp;
												<!-- <a href="javascript:void(0)" onclick="editDeactiveActiveDeleteAsset('<?php //echo $asset['id'];?>','delete')" title="Delete Asset Type"><span class="fa fa-trash" style="color: red;"></span>
												</a> -->
											<?php } ?>
										</td>
									</tr>
									<?php $i++; } } ?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Add State Modal : Start -->
		<div class="modal fade" id="addAssetModal">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						<h3 class="modal-title">Add Asset</h3>
					</div>
					<div class="modal-body">
						<form id="addAssetForm" role="form">
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="asset_type">Asset Type</label>
									<select name="asset_type" id="asset_type" class="form-control select2" style="width: 100% !important;">
										<option value="">Please Select</option>
										<?php foreach ($this->assetTypeDetails as $assetType): ?>
											<option value="<?php echo $assetType['id']; ?>"><?php echo $assetType['type']; ?></option>
										<?php endforeach ?>
									</select>
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="asset_code">Asset Code</label>
									<input type="text" class="form-control" name="asset_code" id="asset_code" placeholder="Enter Asset Code">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="asset_name">Asset Name</label>
									<input type="text" class="form-control" name="asset_name" id="asset_name" placeholder="Enter Asset Name">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="warranty_date">Warranty Date</label>
									<input type="text" class="form-control datepicker" name="warranty_date" id="warranty_date" placeholder="Select Data" readonly="">
								</div>
							</div>
							<div class="row">
								<div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4 pull-right">
									<input type="button" id="submitAssetForm" class="btn btn-primary pull-right" value="Save">
								</div>
							</div>
						</form>
					</div>
					<div class="modal-footer"></div>
				</div>
			</div>
		</div>
		<!-- Add State Modal : End -->

		<!-- Edit Bank Modal : Start -->
		<div class="modal fade" id="editAssetNameModal"></div>
		<!-- Edit Bank Modal : End -->

		<script type="text/javascript">
			$(document).ready(function() {
				$("#assetTypeListTable").DataTable();
				$(".select2").select2();
				$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
				$("input[type=text]").keyup(function(event) {
					event.preventDefault();
					$("input[type=text]").css('border', '');
				});
				$("#submitAssetForm").click(function(event) {
					event.preventDefault();
					var asset_type 			= $("#asset_type").val();	
					var asset_code 			= $("#asset_code").val();	
					var asset_name 			= $("#asset_name").val();	
					// var asset_warranty_date = $("#warranty_date").val();	
					if (asset_type == "") {
						swal({
							title : "Asset Type Missing!",
							text  : "Please select asset type.",
							icon  : "error"
						}).then(function(){
							$("#asset_type").focus();
						});
						return false;
					} else if (asset_code == "") {
						swal({
							title : "Asset Code Missing!",
							text  : "Please enter asset code.",
							icon  : "error"
						}).then(function(){
							$("#asset_code").focus();
							$("#asset_code").css('border', '1px solid red');
						});
						return false;
					} else if (asset_name == "") {
						swal({
							title : "Asset Name Missing!",
							text  : "Please enter asset name.",
							icon  : "error"
						}).then(function(){
							$("#asset_name").focus();
							$("#asset_name").css('border', '1px solid red');
						});
						return false;
					} else {
						$("#addAssetModal").modal("toggle");
						$.ajax({
							url: '/assets/add-asset',
							type: 'POST',
							data: $("#addAssetForm").serialize(),
							success:function(data){
								var data = JSON.parse(data);
								if (data.flag) {
									swal({
										title : data.title,
										text  : data.message,
										icon  : 'success'
									}).then(function(){
										window.location.href = "/assets/asset";
									});
								} else {
									swal({
										title : data.title,
										text  : data.message,
										icon  : 'error'
									}).then(function(){
										$("#addAssetModal").modal("toggle");
									});
								}
							}
						});
					}
				});
			});


			function editDeactiveActiveDeleteAsset(id, type) {
				if (type == "edit") {
					$.ajax({
						url: '/assets/get-asset-name',
						type: 'POST',
						data: {asset_id: id},
						success:function(data){
							$("#editAssetNameModal").html(data);
							$("#editAssetNameModal").modal("toggle");
						}
					});
				} else {
					swal({
						title : "Are you sure?",
						text  : "Do you want to "+type+" clicked asset ?",
						icon  : "warning",
						buttons : [true, "Yes, "+type],
						dangerMode : true
					}).then(function(isConfirm){
						if (!isConfirm) {
							return false;
						} else {
							$.ajax({
								url: '/assets/active-deactive-delete-asset',
								type: 'POST',
								data:{id:id, type:type},
								success:function(data){
									var data = JSON.parse(data);
									console.log(data);
									if (data.flag) {
										swal({
											title : data.type,
											text  : data.message,
											icon  : "success",
										}).then(function(){
											location.reload("/assets/asset-list");
										});
									} else {
										swal({
											title : "Failed !",
											text  : data.message,
											icon  : "error"
										});           
									}
								}
							});

						}
					});
				}
			}
			function editAssetFormSubmit() {
				var asset_type 			= $("#edit_asset_type").val();	
				var asset_code 			= $("#edit_asset_code").val();	
				var asset_name 			= $("#edit_asset_name").val();	
				if (asset_type == "") {
					swal({
						title : "Asset Type Missing!",
						text  : "Please select asset type.",
						icon  : "error"
					}).then(function(){
						$("#edit_asset_type").focus();
					});
					return false;
				} else if (asset_code == "") {
					swal({
						title : "Asset Code Missing!",
						text  : "Please enter asset code.",
						icon  : "error"
					}).then(function(){
						$("#edit_asset_code").focus();
						$("#edit_asset_code").css('border', '1px solid red');
					});
					return false;
				} else if (asset_name == "") {
					swal({
						title : "Asset Name Missing!",
						text  : "Please enter asset name.",
						icon  : "error"
					}).then(function(){
						$("#edit_asset_name").focus();
						$("#edit_asset_name").css('border', '1px solid red');
					});
					return false;
				} else {
					$("#editAssetNameModal").modal("toggle");
					$.ajax({
						url: '/assets/edit-asset',
						type: 'POST',
						data: $("#editAssetForm").serialize(),
						success:function(data){
							var data = JSON.parse(data);
							if (data.flag) {
								swal({
									title : data.title,
									text  : data.message,
									icon  : 'success'
								}).then(function(){
									window.location.href = "/assets/asset";
								});
							} else {
								swal({
									title : data.title,
									text  : data.message,
									icon  : 'error'
								}).then(function(){
									$("#editAssetNameModal").modal("toggle");
								});
							}
						}
					});
				}
			}
			function changeAlertBorder() {
				$("input[type=text]").css('border', '');
			}
		</script>



