
<div id="page-wrapper">
	<div class="main-page">
		<?php if ($this->messages): ?>
			<?php foreach ($this->messages as $message): ?>
				<?php if ($message['success']){ ?>
					<div class="alert alert-success">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
					</div>
				<?php } else if ($message['error']) { ?>
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
					</div>
				<?php } ?>
			<?php endforeach ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Assigned System Details
					<div class="pull-right">
						<a href="/assets/assign-asset" class="btn btn-success">Assign Asset</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="table-responsive" id="state-list">
						<table class="display" width="100%" id="systemListTable">
							<thead>
								<th>#</th>
								<th>Name</th>
								<th>System Code</th>
								<th>Assigned To</th>
								<th>Assigned Date</th>
								<th>Assigned Time</th>
								<th>Return Date</th>
								<th>Return Time</th>
								<th>Status</th>
								<th>Action</th>
							</thead>
							<tbody>
								<?php if($this->assetAllocatedDetails){
									$i = 1;
									foreach ($this->assetAllocatedDetails as $allocatedAsset) { ?>
										<tr>
											<td> <?php echo $i; ?></td>
											<td><?php echo $allocatedAsset['name']; ?></td>
											<td><?php echo $allocatedAsset['code']; ?></td>
											<td><?php echo $allocatedAsset['user_name']; ?></td>
											<td> <span style="display: none;"><?php echo date('Ymd', strtotime($allocatedAsset['assign_date'])); ?></span>  <?php echo date('d-m-Y',strtotime($allocatedAsset['assign_date'])) ;?></td>
											<td><?php echo date('H:i:s',strtotime($allocatedAsset['assign_date'])) ;?></td>
											<td><?php echo is_null($allocatedAsset['return_date']) ? "":date('d-m-Y',strtotime($allocatedAsset['return_date'])); ?></td>
											<td><?php echo is_null($allocatedAsset['return_date']) ? "": date('H:i:s',strtotime($allocatedAsset['return_date'])); ?></td>
											<td><?php echo is_null($allocatedAsset['return_date']) ? "Assigned":"Returned"; ?></td>
											<td>
												<?php if(is_null($allocatedAsset['return_date'])){?>
													<a href="#" onclick="returnDevice(<?php echo $allocatedAsset['id']; ?>)"><i class="fa fa-undo"></i></a>
												<?php } ?>
												
											</td>
										</tr>
										<?php $i++; } } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- View System Assets Modal : Start -->
			<div class="modal fade" id="viewSystemAssetsModal"></div>
			<!-- View System Assets Modal : End -->

			<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>

			<script type="text/javascript">
				$(document).ready(function() {
					// $("#systemListTable").DataTable();

					var table = $('#systemListTable').DataTable();
					// table
					// .order( [ 3, 'desc' ] )
					// .draw();
					// 
					table.on( 'order.dt search.dt', function () {
						table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
							cell.innerHTML = i+1;
						} );
					} )
					.order( [ 4, 'desc' ] )
					.draw();

				});

				function viewAssignedSystemAssets(id) {
					if (id == "") {
						swal({
							title : "System ID Missing !",
							text  : "System ID Missing. Please try again after refresh the page.",
							icon  : "error"
						});
					} else {
						$.ajax({
							url: '/assets/view-system-asset-details',
							type: 'POST',
							data: {system_id: id},
							success:function (data) {
								$("#viewSystemAssetsModal").html(data);
								$("#viewSystemAssetsModal").modal('toggle');
							}
						});
					}
				}
				function deactiveActiveDeleteSystem(id, type) {
					swal({
						title : "Are you sure?",
						text  : "Do you want to "+type+" clicked system ?",
						icon  : "warning",
						buttons : [true, "Yes, "+type],
						dangerMode : true
					}).then(function(isConfirm){
						if (!isConfirm) {
							return false;
						} else {
							$.ajax({
								url: '/assets/active-deactive-delete-system',
								type: 'POST',
								data:{id:id, type:type},
								success:function(data){
									var data = JSON.parse(data);
									console.log(data);
									if (data.flag) {
										swal({
											title : data.title,
											text  : data.message,
											icon  : "success",
										}).then(function(){
											location.reload("/assets/system");
										});
									} else {
										swal({
											title : "Failed !",
											text  : data.message,
											icon  : "error"
										});           
									}
								}
							});

						}
					});
				}

				function returnDevice(id){
					$.ajax({
						url: '/assets/return-device/id/'+id,
						type: 'POST',
						success:function (data) {
							var data = JSON.parse(data);
							if (data.flag) {
								swal({
									title : data.title,
									text  : data.message,
									icon  : "success",
								}).then(function(){
									$('#assignsystem').addClass('btn btn-success');
									location.reload("/assets/system");
								}); 
							}

						}
					});
				}
				
			</script>