<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3 class="modal-title">Edit Asset Details</h3>
    </div>
    <div class="modal-body">
      <form role="form" id="editAssetForm">
        <div class="row">
          <input type="hidden" name="asset_id" value="<?php echo md5($this->assetDetails['id']); ?>">
          <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <label for="edit_asset_type">Asset Type</label>
            <select name="edit_asset_type" id="edit_asset_type" class="form-control select2" style="width: 100% !important;">
              <option value="">Please Select</option>
              <?php foreach ($this->assetTypeDetails as $assetType): ?>
                <option value="<?php echo $assetType['id']; ?>"<?php echo $assetType['id'] == $this->assetDetails['asset_type_id'] ? "selected":""; ?>><?php echo $assetType['type']; ?></option>
              <?php endforeach ?>
            </select>
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <label for="edit_asset_code">Asset Code</label>
            <input type="text" class="form-control" name="edit_asset_code" id="edit_asset_code" onkeyup="changeAlertBorder()" placeholder="Enter Asset Code" value="<?php echo $this->assetDetails['code']; ?>">
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <label for="edit_asset_name">Asset Name</label>
            <input type="text" class="form-control" name="edit_asset_name" id="edit_asset_name" onkeyup="changeAlertBorder()" placeholder="Enter Asset Name" value="<?php echo $this->assetDetails['name']; ?>">
          </div>
          <div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <label for="edit_warranty_date">Warranty Date</label>
            <input type="text" class="form-control datepicker" name="edit_warranty_date" id="edit_warranty_date" onkeyup="changeAlertBorder()" placeholder="Select Data" readonly="" value="<?php echo date('d/m/Y', strtotime($this->assetDetails['warranty_date'])); ?>">
          </div>
        </div>
        <div class="row">
          <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4 pull-right">
            <input type="button" id="submitEditAssetBtn" class="btn btn-primary pull-right" onclick="editAssetFormSubmit()" value="Update">
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $(".select2").select2();
  });
</script>