<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Edit Asset Type</h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <form action="/assets/edit-asset-type/asset-type-id/<?php echo md5($this->assetTypeDetail['id']); ?>" method="POST" class="form-inline" role="form">
          <div class="form-group col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <label for="asset_type">Asset Type Name :</label>
            <input type="text" class="form-control" name="asset_type" id="asset_type" placeholder="Enter Asset Type Name" value="<?php echo $this->assetTypeDetail['type']; ?>">
          </div>
          <div class="form-group col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <input type="submit" class="btn btn-primary" value="Update">
          </div>
        </form>
      </div>
    </div>
    <div class="modal-footer"></div>
  </div>
</div>