<?php
$user_list = $this->user_list;
$record = $this->paginator; 
$totalrec = $this->totalrec;
?>
<script type="text/javascript">
    function deleteMappedUserRole(userId) {
        swal({
            title: "Are you sure?",
            text: "You want to Delete this ",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, Delete this role mapping!",
            closeOnConfirm: false
        }, function (isConfirm) {
            if (!isConfirm) return;
            $.ajax({
                url: "/user/delete-user/id/"+userId,
                context: document.body,
                success: function () {
                  swal({
                    title: "Deleted", 
                    text: "Status has been successfully changed", 
                    type: "success"
                },function() {
                    window.location.href="/user";
                });
              },
              error: function (xhr, ajaxOptions, thrownError) {
                swal("Error "+status+"!", "Please try again", "error");
            }
        });
        });
    };
    function getPage(page){
      var url   = '/user/user-list/page/'+page;
      var id    = 'user-list';
      $("#"+id).html('<div class="loading">Loading&#8230;</div>');
      $.ajax({
          url: url,
          context: document.body,
          success: function(responseText) {
              $("#"+id).html(responseText);
              $("#"+id).find("script").each(function(i) {
                  eval($(this).text());
              });
          }
      });
  };
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
       $('th').attr("nowrap","nowrap");
       $('td').attr("nowrap","nowrap");
   //$('th').attr("class","text-center");
   //$('td').attr("class","text-center");
});
</script>
<div class="right-aside view-port-height">
    <!-- Content Header (Page header) -->
    <div class="content-header container-fluid bg-white">
        <div class="row">
            <div class="col-sm-4">
                <h4><i class="ti-user"></i>  Users List</h4>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <div class="content">
        <?php if ($this->messages): ?>
            <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                <?php foreach ($this->messages as $message): ?>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <div class="alert_data">
                        <?php echo $message ?>.
                    </div>
                <?php endforeach ?>
            </div>
        <?php endif ?>
        <div class="row">
            <div class="col-12">
                <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                       <p style="float: left; margin: 3px;">User List</p> 
                       <a href="/user/create-user" type="button" class="btn btn-success btn_lg_width m-t-10 m-r-10" style="float: right; margin-top: 0px;margin-left: 10px">
                        <i class="ti-user"></i> Create New User
                    </a>

                    

                </div>
                <div class="card-block">
                   
                    <div class="row basic_tables">
                        <div class="col-12 m-t-20">
                            <div class="table-responsive mt-1" id="user-list">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Email</th>
                                            <th>Permanent Address</th>
                                            <th>Current Address</th>
                                            <th>Birth Date</th>
                                            <th>Joining Date</th>
                                            <th>Department</th>
                                            <th>Location</th>
                                            <th>Role Type</th>
                                            <th>Role</th>
                                            <th>Profile Picture</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php 
                                        if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10;
                                            $i=$istart;
                                            foreach($record as $user)
                                                { ?>
                                                    <tr>
                                                        <td><?php echo $i+1;?>.</td>
                                                        <td><?php echo $user['name']; ?></td>
                                                        <td><?php echo $user['contact_no']; ?></td>
                                                        <td><?php echo $user['email_id']; ?></td>
                                                        <td><?php echo $user['permanent_address']; ?></td>
                                                        <td><?php echo $user['current_address']; ?></td>
                                                        <td><?php echo $user['date_of_joining']; ?></td>
                                                        <td><?php echo $user['date_of_birth']; ?></td>
                                                        <td><?php echo $user['department']; ?></td>
                                                        <td><?php echo $user['location']; ?></td>
                                                        <td><?php echo $user['role_type']; ?></td>
                                                        <td><?php echo $user['role']; ?></td>
                                                        <td><img class="img-thumbnail" height="50" width="50" src="/uploads/profile_pic/<?php echo $user['profile_path']; ?>"></td>

                                                        <td><a href="/user/edit-user-info/id/<?php echo $user['id'];?>" class="todoedit" title="delete"><span class="ti-pencil-alt"></span></a>&nbsp&nbsp<a href="javascript:void(0)" class="tododelete redcolor" onclick="deleteMappedUserRole('<?php echo $user['id'];?>')" title="delete"><span class="ti-trash"></span></a></td>
                                                    </tr>
                                                    <?php  $i++;} } else{  ?>
                                                        <tr><td colspan="7"><p style="color:red; font-size:16px;">No User Found !</p></td></tr>
                                                    <?php  } ?>
                                                </tbody>
                                            </table>
                                            <div id="leftpag">
                                                <!-- START PAGINATION -->
                                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>  
                                                <!-- END PAGINATION -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.content -->
        </div>
    </div>