
<style type="text/css">
	.table th ,   .table td , .table div{
		padding: 3px;
		text-align: left;
	} 
	#scroll-id {
		width: 600px;
	}

	.tableHeading {
		min-width: 180px;
		text-align: center;
	}
	.tableHeadingDay {
		min-width: 90px;
		text-align: center;
	}
	.tableSubHeading {
		min-width: 90px;
		text-align: center;
	}
	@media print{
		.noprint {display:none !important; }
	}
	th, td { white-space: nowrap; }
	div.dataTables_wrapper {
		margin: 0 auto;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<h3>Monthly Attendance Report
					<div class="pull-right">
						<a href="/attendance" class="btn btn-success" target="_blank">Mark Attendance</a>
					</div></h3>
				</div>
				<div class="panel panel-body">
					<div class="row">
						<form action="/attendance/employees-monthly-attendance" method="post">
							<div class="col-md-2">
								<select class="form-control" name="month" id="month">
									<option value="01" <?php echo $this->month == "01"?"selected":""; ?>>January</option>
									<option value="02" <?php echo $this->month == "02"?"selected":""; ?>>February</option>
									<option value="03" <?php echo $this->month == "03"?"selected":""; ?>>March</option>
									<option value="04" <?php echo $this->month == "04"?"selected":""; ?>>April</option>
									<option value="05" <?php echo $this->month == "05"?"selected":""; ?>>May</option>
									<option value="06" <?php echo $this->month == "06"?"selected":""; ?>>June</option>
									<option value="07" <?php echo $this->month == "07"?"selected":""; ?>>July </option>
									<option value="08" <?php echo $this->month == "08"?"selected":""; ?>>August</option>
									<option value="09" <?php echo $this->month == "09"?"selected":""; ?>>September</option>
									<option value="10" <?php echo $this->month == "10"?"selected":""; ?>>October</option>
									<option value="11" <?php echo $this->month == "11"?"selected":""; ?>>November</option>
									<option value="12" <?php echo $this->month == "12"?"selected":""; ?>>December</option>
								</select>
							</div>
							<div class="col-md-2">
								<select class="form-control" name="year" id="year">
									<?php $years = array_combine(range(date("Y"), 1910), range(date("Y"), 1910));
									foreach($years as $year) {  ?>
										<option value="<?php echo $year;?>" <?php echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>
									<?php } ?>
								</select>
							</div>
							<div class="col-md-5">
								<button type="submit" class="btn btn-primary">Show</button>
							</div>
						</form>
					</div>
					<br clear="all">
					<div class="table-responsive" id="user-list">
						<table class="display" style="width:100%" id="attendanceDetailsTable" border="1">
							<thead>
								<tr>
									<th>S.No</th>
									<th class="tableHeading">Name</th>
									<?php 
									if($this->month == date('m')){ 
										$days = date('d');
									}else{
										$days = $this->working_days;
									}
									for($i = 1; $i <= $days; $i++){ ?>
										<th class="tableHeadingDay"><?php echo $i." ".date("F", mktime(0, 0, 0, $this->month, 10)); ?></th>
									<?php } ?>
								</tr>
							</thead>
							<tbody>
								<?php if($this->userNames){ 
									$i = 0;
									foreach($this->userNames as $user){ ?>
										<tr>
											<td>
												<?php echo $i+1;?>
											</td>
											<td>
												<a href="javascript:void(0)" title="View Detailed Attendance" onclick="showEmployeeDetailedAttendance(<?php echo $user['id']; ?>, <?php echo $this->month; ?>,<?php echo $this->year; ?>)"><?php echo strtoupper($user['name']); ?></a>
											</td>
											<?php for($j = 1; $j<= $days; $j++){
												if($j < 10){
													$j = '0'.$j;
												}
												$date = $this->year.'-'.$this->month.'-'.$j; ?>
												<?php
												if(!$this->controller->checkSunday($date)){
													if($this->controller->checkAttendance($user['id'],$date)){ 
														$attendacneData = $this->controller->checkAttendance($user['id'],$date);
														echo'<td class="dataTd" style="text-align: center;">
														<span class="label label-success">'.$attendacneData['start_time'].'</span>
														&nbsp;&nbsp;&nbsp;
														<span class="label label-success">'.$attendacneData['end_time'].'</span></td>';
													} else {
														echo'<td class="dataTd" style="background-color: #B7C8C5; text-align: center;"><span class="label label-danger">A</span></td>';
													} 
												}else{ 
													echo '<td style="text-align: center; background-color: #B8832E;"><b>SUN</b></td>';
												} ?>
											<?php } ?>
										</tr>
										<?php  $i++; } } ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			</div>

			<script>
				$(document).ready(function() {
					var table = $("#attendanceDetailsTable").DataTable({
						dom: 'Bfrtip',
						buttons: [
						'excelHtml5'
						]	
					});
				});
				function showEmployeeDetailedAttendance(employee_id, month, year) {
					$('#loading-bg').show();
					$.ajax({
						url: '/attendance/view-employees-monthly-attendance-details',
						type: 'POST',
						data: {employee_id:employee_id, month:month, year:year},
						success:function (data) {
							$('#loading-bg').hide();
							$('#myModal').html(data);
							$('#myModal').modal('toggle');
						}
					});

				}
			</script>

