<?php
$record = $this->paginator; 
$totalrec = $this->totalrec;
$params = $this->params;  
$front = Zend_Controller_Front::getInstance();
$controller = $front->getRequest()->getControllerName(); 
$action = $front->getRequest()->getActionName(); 
?>

<style>

.sunday{
  color: #fff !important;
  background-color: #F9690E;
  text-align: center;
}
</style>
<div class="content-header container-fluid bg-white">
  <div class="row">
    <div class="col-sm-4">
      <h4><i class="ti-list"></i>Employee Attendance Report</h4>
    </div>
  </div>
</div>


<div class="content">

  <?php if ($this->messages): ?>
    <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
      <?php foreach ($this->messages as $message): ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="alert_data">
          <?php echo $message ?>.
        </div>
      <?php endforeach ?>
    </div>
  <?php endif ?>

  <div class="row">
    <div class="col-12">
      <div class="card  profile2_aboutme">
        <div class="card-header card-info text-white">
          <p style="float: left; margin: 3px; color: #fff;">Employee Attendance Report</p> 
        </div>



        <div class="card-block">
          <div class="row basic_tables">
            <div class="col-12">

              <form>
                <div class="col-md-4">
                  <select class="form-control" name="employee" id="employee">
                    <option value="">Select Employee</option>
                    <?php foreach ($this->employees as $employee) { ?>
                      <option value="<?php echo $employee['employee_id']; ?>" <?php echo $this->emp_id == $employee['id'] ? "selected":""; ?>><?php echo $employee['name']; ?></option>
                    <?php } ?>
                  </select>
                </div>
                <div class="col-md-2">
                  <select class="form-control" name="month" id="month">
                    <option value="01" <?php echo $this->month == "01"?"selected":""; ?>>January</option>
                    <option value="02" <?php echo $this->month == "02"?"selected":""; ?>>February</option>
                    <option value="03" <?php echo $this->month == "03"?"selected":""; ?>>March</option>
                    <option value="04" <?php echo $this->month == "04"?"selected":""; ?>>April</option>
                    <option value="05" <?php echo $this->month == "05"?"selected":""; ?>>May</option>
                    <option value="06" <?php echo $this->month == "06"?"selected":""; ?>>June</option>
                    <option value="07" <?php echo $this->month == "07"?"selected":""; ?>>July </option>
                    <option value="08" <?php echo $this->month == "08"?"selected":""; ?>>August</option>
                    <option value="09" <?php echo $this->month == "09"?"selected":""; ?>>September</option>
                    <option value="10" <?php echo $this->month == "10"?"selected":""; ?>>October</option>
                    <option value="11" <?php echo $this->month == "11"?"selected":""; ?>>November</option>
                    <option value="12" <?php echo $this->month == "12"?"selected":""; ?>>December</option>
                  </select>
                </div>
                <div class="col-md-2">
                  <select class="form-control" name="year" id="year">
                    <?php $years = array_combine(range(date("Y"), 1910), range(date("Y"), 1910));
                    foreach($years as $year){  ?> ?>
                    <option value="<?php echo $year;?>" <?php echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>
                  <?php } ?>
                </select>
              </div>
              <div class="col-md-2">
                <button type="submit" class="btn btn-primary">Show</button>
              </div>

              <div class="col-md-2">
                <a href="#" class="btn btn-primary" onclick="exportTable('attedanceTable')">Export</a>
              </div>
            </form>
            <div class="clearfix" style="padding:5px;"></div>

            <div id="attedanceTable">
              <table class="table">
                <thead>
                  <tr>

                    <th>Date</th>
                    <th>Status</th>
                    <th>In Time</th>
                    <th>Out Time</th>
                    <th>Working Hours</th>

                  </tr>
                </thead>
                <tbody>
                  <?php 
                  if(isset($params['employee']) && $params['employee'] != ""){
                    if($this->month == date('m')){ 
                      $days = date('d');
                    }else{
                      $days = $this->working_days;
                    }
                    for($j = 1; $j<= $days; $j++){
                      if($j < 10){
                        $j = '0'.$j;
                      }
                      $date = $this->year.'-'.$this->month.'-'.$j; ?>
                      <tr>
                        <td><?php echo date('d/m/y',strtotime($date)); ?></th>
                         <td class="<?php echo $this->controller->checkSunday($date) ? 'sunday':'';?>"><?php
                         if(!$this->controller->checkSunday($date)){
                          if($this->controller->checkAttendance($this->emp_id,$date)){
                            echo '<span class="label label-success">Present</span>';
                          }else{
                            echo '<span class="label label-danger">Absent</span>';
                          } 
                          ?>

                        <?php }else{ 
                          echo 'SUN'; }
                          ?>
                        </td>

                        <td class="<?php echo $this->controller->checkSunday($date) ? 'sunday':'';?>"><?php
                        if(!$this->controller->checkSunday($date)){
                          echo $this->controller->getInTime($this->emp_id,$date);
                          ?>

                        <?php }else{ 
                          echo 'SUN'; }
                          ?>
                        </td>

                        <td class="<?php echo $this->controller->checkSunday($date) ? 'sunday':'';?>"><?php
                        if(!$this->controller->checkSunday($date)){
                          echo  $this->controller->getOutTime($this->emp_id,$date);
                          ?>

                        <?php }else{ 
                          echo 'SUN'; }
                          ?>
                        </td>

                        <td class="<?php echo $this->controller->checkSunday($date) ? 'sunday':'';?>"><?php
                        if(!$this->controller->checkSunday($date)){
                          echo  $this->controller->calculateWorkingHour($this->emp_id,$date);
                          ?>

                        <?php }else{ 
                          echo 'SUN'; }
                          ?>
                        </td>

                      </tr>
                    <?php } } else{ ?>
                      <tr><td colspan="5">Select Employee</td></tr>
                    <?php } ?>
                  </tbody>
                </table>

              </div>

            </div>
          </div>
        </div>



      </div>
    </div>
  </div>

</div> <!-- end of content -->
<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>
