<?php
$attendance_report=$this->attendance_report;
$attendance_report = $this->paginator; 
$totalrec = $this->totalrec;
$params = $this->params;
 // echo "<pre>";
 // print_r($params);exit;



?>

<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/pages/modals.js"></script>
<script type="text/javascript">
  function getPage(page, status,date_fr,date_tt){
    //alert(page)
     //var date_from = $("#date_from").val();
     var  dateArr = [];
     var  dateArr1 = [];
     dateArr     = date_fr.split('/');
     var val1    = dateArr[1] + '-' + dateArr[0]  + '-' + dateArr[2];012
          //alert(val1);

          dateArr1     = date_tt.split('/');
          var val2         = dateArr1[1] + '-' + dateArr1[0]  + '-' + dateArr1[2];
    //alert(val2)
    
    
    var url   = '/report/attendence-list/page/'+page+'/date_from/'+val1+'/date_to/'+val2;
           //alert(url);
           var id    = 'attendence-list';
           
           $("#"+id).html('<div class="loading">Loading&#8230;</div>');
           $.ajax({
            url: url,
            context: document.body,
            success: function(responseText) {
              $("#"+id).html(responseText);
              $("#"+id).find("script").each(function(i) {
                eval($(this).text());
              });
            }
          });
         };
         function getPage1(page, status,date_fr,date_tt){
          var dateArr     = date_fr.split('-');
          var val1    = dateArr[0] + '-' + dateArr[1]  + '-' + dateArr[2];
          
          dateArr1     = date_tt.split('-');
          var val2         = dateArr1[0] + '-' + dateArr1[1]  + '-' + dateArr1[2];
          
          
          
          var url   = '/report/attendence-list/page/'+page+'/date_from/'+val1+'/date_to/'+val2;
          var id    = 'attendence-list';
          
          $("#"+id).html('<div class="loading">Loading&#8230;</div>');
          $.ajax({
            url: url,
            context: document.body,
            success: function(responseText) {
              $("#"+id).html(responseText);
              $("#"+id).find("script").each(function(i) {
                eval($(this).text());
              });
            }
          });
          
        };
        
      </script>
      <script type="text/javascript">
       $(document).ready(function() {
        $(".datepick").datepicker({ dateFormat: "dd MM yy" });

        
      });


       function generateExcel(){
  //alert(date_frm);
  window.location.href="/report/attendance-report/type/Generate";
}
</script>

<div class="view-port-height">
  <!-- Content Header (Page header) -->

  <div class="content-header container-fluid bg-white">
    <div class="row">
      <div class="col-sm-4">
        <h4><i class="ti-user"></i> Attendance Report</h4>
      </div>
    </div>
  </div>
  <!-- Main content -->
  <div class="content">
    <?php if ($this->messages): ?>
      <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
        <?php foreach ($this->messages as $message): ?>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <div class="alert_data">
            <?php echo $message ?>.
          </div>
        <?php endforeach ?>
      </div>
    <?php endif ?>
    

    <div class="row">
      <div class="col-12">
        <div class="card  profile2_aboutme">
         <div class="card-header card-info text-white">
           <p style="float: left; margin: 3px; color: #fff;">Attendance Report </p> 
           <a href="javascript:void(0)" onclick="generateExcel()" type="button" style="float: right; margin: 0px;" class="btn btn-success btn_lg_width m-t-10 m-r-10"> Export to Excel
           </a>
         </div>
         
         <div class="card-block">
          <div class="row" >
            <div class="col-md-12">
              <form name="changePassword" method="post" id="filter_date" action="javascript:void(0)">
                <div class="form-group row">

                  <div class="col-lg-3 col-md-3">
                    <div class="input-group">
                      <input  type="text" name="date_from" id="date_from" placeholder="Date From" value="<?php echo $params['date_from'] ?>" required="required" class="datepick form-control">
                    </div>

                  </div>

                  <div class="col-lg-3 col-md-3">
                    <div class="input-group">
                      <input  type="text" name="date_to" id="date_to" placeholder="Date To" value="<?php echo $params['date_to'] ?>" required="required" class="datepick form-control">
                    </div>

                  </div>

                  <div class="col-0.5">
                    <div class="input-group ">
                      <input  type="submit" onclick="getPage('<?php echo $this->previous; ?>', 'attendence',this.form.date_from.value,this.form.date_to.value);" value="Search" class=" btn btn-primary form-control">                 
                    </div>
                  </div>                                   
                </div>                                
              </form>
            </div>
          </div>
          <div class="card-block">
            <div class="row basic_tables">
              <div class="col-12">
                <div class="table-responsive mt-1" id="attendence-list">
                  
                  
                  <table  class="table table-striped">
                    <!-- START PAGINATION -->
                    
                    <thead>
                      <tr>
                        <strong>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >#</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">User </th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="">User Type</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Contact No.</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Start Day Datetime</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap="" >Start Day Latitude</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Start Day  Longitude</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day Datetime</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day Latitude</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >End Day  Longitude</th>
                          <!-- <th style="text-align:center!important; font-weight: bold; color:#007bb8" nowrap=""  >status</th> -->
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Created</th>
                          <th style="text-align:left!important; font-weight: bold; color:#007bb8" nowrap=""  >Working Hour</th>

                        </strong>
                      </tr>
                    </thead>
                    <tbody>
                     
                      <?php 
                      if($totalrec){ 
                        $totalnum = $this->totalnum?$this->totalnum:1;
                        $istart = ($totalnum-1) * 10;
                        $i=$istart;
                        foreach ($attendance_report as  $user) 
                        { 
                          $diff = strtotime($user['end_day_datetime']) - strtotime($user['start_day_datetime']);
                                                  //$diff_in_hrs = $diff/3600;
                          $days    = floor($diff / 86400);
                          $hours   = floor(($diff - ($days * 86400)) / 3600);
                          $minutes = floor(($diff - ($days * 86400) - ($hours * 3600))/60);
                                                  //echo $hours.'h '.$minutes.'m '.$seconds.'s<br/>';

                          ?>
                          <tr>
                            <td style="text-align:left!important;" nowrap=""> <?php echo $i; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['user_id']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['user_type']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['contact_no']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_datetime']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_latitude']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['start_day_longitude']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_datetime']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_latitude']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['end_day_longitude']; ?></td>
                            <!-- <td style="text-align:center!important;" nowrap=""><?php //echo $user['status']; ?></td> -->
                            <td style="text-align:left!important;" nowrap=""><?php echo $user['created']; ?></td>
                            <td style="text-align:left!important;" nowrap=""><?php echo $hours.'h '.$minutes.'m '; ?></td>                                                                                            
                          </tr>
                          
                          <?php  $i++;} } else{  ?>
                            <tr><td colspan="14"><p style="color:red; font-size:16px;">No Record Found !</p></td></tr>
                          <?php  } ?>
                        </tbody>
                      </table>
                      

                      <!-- START PAGINATION -->
                      <?php 
                      $record = $this->paginator; 
                      $totalrec = $this->totalrec;
                      if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'attendence-pagination.phtml'); } ?> 
                      
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>
  </div>