<?php

?>
<style>

    .modal-header .close {
        color: #000000 !important;
    </style>
    <script type="text/javascript">

        function closeModal() {
            $("#myModal").modal("toggle");
        }
        function getStockOutRecords(id) {
            $.ajax({
                url: "/report/view-stock-out/id/"+id,
                context: document.body,
                success: function(responseText) {
                    console.log(responseText);
                    $("#myModal").html(responseText);
                    $("#myModal").modal("toggle");
                }

            });
        }
    </script>

    <div id="page-wrapper">
        <div class="main-page">
            <?php if ($this->messages): ?>
                <?php foreach ($this->messages as $message): ?>
                    <?php if ($message['success']){ ?>
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
                        </div>
                    <?php } else if ($message['error']) { ?>
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
                        </div>
                    <?php } ?>
                <?php endforeach ?>
            <?php endif ?>
            <div class="panel panel-primary">
                <div class="panel panel-heading">
                    <h3>Material Stock Report
                        <div class="pull-right">
                            <a href="/material-stock/material-stock-in" class="btn btn-success">Add Stock</a>
                        </div></h3>
                    </div>
                    <div class="panel panel-body">
                        <div class="table-responsive" id="user-list">
                            <table class="display" width="100%" id="materialStockTable">
                                <thead>
                                    <th>#</th>
                                    <th>Product Type</th>
                                    <th>Product Name</th>

                                    <th>Total Quantity</th>
                                    <th>Unit</th>
                                </thead>
                                <tbody>
                                   <?php if($this->materialStocklist){ 

                                    $i = 1; 
                                    foreach($this->materialStocklist as $materialStock){   
                                        ?>
                                        <?php if( $materialStock['quantity']) {?>
                                            <tr>
                                                <td><?php echo $i; ?></td>
                                                <td><?php echo $materialStock['product_type']; ?></td>
                                                <td><?php echo $materialStock['product_name']; ?></td>
                                                <td><?php echo $materialStock['quantity']; ?></td>
                                                <td><?php echo $materialStock['unit']?></td>
                                            </tr>
                                            <?php $i++;}}}?>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                </div>

                <script>
                    $(document).ready(function() {
                        $("#materialStockTable").DataTable();
                    });
                </script>
