<?php

?>
<style>

	.modal-header .close {
		color: #000000 !important;
	</style>
	<script type="text/javascript">

		function closeModal() {
			$("#myModal").modal("toggle");
		}
		function getStockinRecords(id) {
			$.ajax({
				url: "/report/view-stockin/id/"+id,
				context: document.body,
				success: function(responseText) {
					console.log(responseText);
					$("#myModal").html(responseText);
					// $("#myModal").modal("toggle");
				}

			});
		}
	</script>

	<div id="page-wrapper">
		<div class="main-page">
			<?php if ($this->messages): ?>
				<?php foreach ($this->messages as $message): ?>
					<?php if ($message['success']){ ?>
						<div class="alert alert-success">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							<strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
						</div>
					<?php } else if ($message['error']) { ?>
						<div class="alert alert-danger">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							<strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
						</div>
					<?php } ?>
				<?php endforeach ?>
			<?php endif ?>
			<div class="panel panel-primary">
				<div class="panel panel-heading">
					<h3>Summary Report
						<div class="pull-right">
							<!-- <a href="/user/create-user" class="btn btn-success">Download</a> -->
						</div></h3>
					</div>
					<div class="panel panel-body">
					    <div class="row">
						<form action="" method="POST" role="form" >  
						<!--onsubmit="return validateForm()"-->
							<div class="col-md-2">
								<div class="form-group">
									<label for="">From date</label>
									<input type="text" class="form-control datepicker " name="from_date" id="from_date" placeholder="From Date" readonly="" value="<?php if(isset($this->from_date)){ echo $this->from_date;} ?>" >
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<label for="">To date</label>
									<input type="text" class="form-control datepicker " name="to_date" id="to_date" placeholder="To Date" readonly="" value="<?php if(isset($this->to_date)){ echo $this->to_date; } ?>">
								</div>
							</div>

							<div class="col-md-2">
								<div class="form-group">
									<button type="submit" class="btn btn-primary">Submit</button>
								</div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<a href="/expense/office-expenses" class="btn btn-info">Reset</a>
								</div>
							</div>
						</form>
						<a href="expense/export-site-expense  ?>" class="btn btn-info"  type="submit"   title="file-excel" style="margin-bottom: 5px;float:right;margin-right: 15px;"><i class="glyphicon glyphicon-circle-arrow-down" ></i></a> 
					</div>

						<div class="table-responsive" id="user-list">
							<table id="materialStockInReportTable"  class="display" width="100%">
								<thead>
									<tr>
										<th>#</th>
										<th>Month</th>
										<th>Site ID</th>
										<th>Site Name</th>
										<th>Expenses</th>
										<th>Site Start Date</th>
										<th>Invoice Amount</th>
										<!--<th>Invoice Date</th>-->
										<th>Amount Received</th>
										<!--<th>Date of Amount Received</th>-->
									</tr>
								</thead>
								<tbody>
								    <?php   
								        $monthArr = array('01'=>'January', '02'=>'February', '03'=>'March', '04'=>'April', '05'=>'May', '06'=>'June', '07'=>'July', '08'=>'August', '09'=>'September', '10'=>'October', '11'=>'November', '12'=>'December');
								    ?>
									<?php if($this->finalArr){ 
										$i = 1; 
										foreach($this->finalArr as $key=>$val){?>
											<tr>
												<td> <?php echo $i; ?></td>
												<td> <?php echo $monthArr[date("m",strtotime($val['order_date']))];
												echo " ".date("Y",strtotime($val['order_date']))?></td>
												<td><?php echo $val['site_id']; ?></td>
												<td><?php echo $val['site_name']; ?></td>
												<td><?php echo $val['expenses']; ?></td>
												<td><?php echo $val['order_date']; ?></td>
												<td><?php echo $val['invoice_amount']; ?></td>
												<td><?php echo $val['received_amount']; ?></td>
												<?php $i++; } } ?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="modal modal-success fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

					</div>
					<script>
						$(document).ready(function() {
							$("#materialStockInReportTable").DataTable();
							
							$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
						});
					</script>