<?php
    $record = $this->paginator; 
    $totalrec = $this->totalrec;
    $params = $this->params;
    //print_r($this->params);exit;
    function dateConverter1($var)
    {
        if ($var!="")
        {
          $date = explode('-', $var);
          $final_date = $date['1'].'/'.$date['0'].'/'.$date['2'];
          return $final_date;
        }
    }
?>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/pages/modals.js"></script>

  <script type="text/javascript">
     $(document).ready(function() {
                  $(".datepick").datepicker({ dateFormat: "dd MM yy" });

                 
      });


      </script>
<script type="text/javascript">
  function getSearch(date_from,date_to,page)
  {
      //var date_from = $("#date_from").val();
      var dateArr     = date_from.split('/');
      var val1         = dateArr[1] + '-' + dateArr[0]  + '-' + dateArr[2];
      //alert(val1);

      //var date_to = $("#date_to").val();
      var dateArr1     = date_to.split('/');
      var val2        = dateArr1[1] + '-' + dateArr1[0]  + '-' + dateArr1[2];
    document.search.action="/report/task-report/date_fr/"+val1+"/date_tt/"+val2;  
    document.search.submit();  
  }

  function generateExcel()
  {
    window.location.href="/report/task-report/type/Generate";
  }
</script>
<div class=" view-port-height">
<!-- Content Header (Page header) -->

        <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i> Assigned Site Report</h4>
                </div>
            </div>
        </div>
        <!-- Main content -->
        <div class="content">
            <?php if ($this->messages): ?>
                <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                    <?php foreach ($this->messages as $message): ?>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <div class="alert_data">
                <?php echo $message ?>.
                </div>
                <?php endforeach ?>
                </div>
            <?php endif ?>
        

            <div class="row">
                <div class="col-12">
                    <div class="card  profile2_aboutme">
                   <div class="card-header card-info text-white">
                       <p style="float: left; margin: 3px;">Assigned Site Report</p> 
                           <a href="javascript:void(0)" onclick="generateExcel()" type="button" style="float: right; margin: 0px;" class="btn btn-success btn_lg_width m-t-10 m-r-10"> Export to Excel
                           </a>
                    </div>
                      <div class="card-block">
                          <div class="row" >
                              <div class="col-md-12">
                                <form name="search" method="post" id="filter_date">
                                  <div class="form-group row">

                                    <div class="col-lg-3 col-md-3">
                                      <div class="input-group">
                                        <input  type="text" name="date-from" id="date_from" placeholder="Date From" value="<?php echo dateConverter1($params['date_fr']) ?>" readonly class="datepick form-control" required="required">
                                      </div>

                                    </div>

                                    <div class="col-lg-3 col-md-3">
                                      <div class="input-group">
                                        <input  type="text" name="date-to" id="date_to" placeholder="Date To"  value="<?php echo dateConverter1($params['date_tt']) ?>" readonly class="datepick form-control" required="required">
                                      </div>

                                    </div>

                                    <div class="col-0.5">
                                      <div class="input-group ">
                                        <input  onclick="getSearch(this.form.date_from.value,this.form.date_to.value)" type="submit" value="Search" class=" btn btn-primary form-control">
                                      </div>

                                    </div>

                                    
                                  </div>



                                 
                                </form>
                              </div>
                            </div>
                            <div class="row basic_tables">
                                <div class="col-12">
                                    <div class="table-responsive mt-0" id="my-siteallocation" style="padding:0px !important;">
                                         <div id="leftpag" style="float: right !important;">
                                </div>

                                        <table  class="table table-striped">
                                            <thead>
                                            <tr>
                                                <strong>
                                                <th>#</th>
                                                <th style="text-align:left!important;">PO</th>
                                                <th style="text-align:left!important;" nowrap>Site Id</th>
                                                 <th style="text-align:left!important;" nowrap>Assigned Date</th>
                                                <th style="text-align:left!important;">Status</th>
                                                <th style="text-align:left!important;">Zone</th>
                                                <th style="text-align:left!important;" nowrap>Cluster</th>
                                                <th style="text-align:left!important;" nowrap>Technician Name</th>
                                                <th style="text-align:left!important;" nowrap>Technician Mobile No.</th>
                                                <th style="text-align:left!important;" nowrap>Allocated User</th>
                                              
                                               
                                                </strong>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if($totalrec){ 
                                            $totalnum = $this->totalnum?$this->totalnum:1;
                                            $istart = ($totalnum-1) * 10+1;
                                            $i=$istart;
                                            foreach($record as $user)
                                            { ?>
                                            <tr>
                                                <td ><?php echo $i;?>.</td>
                                                
                                                <td style="text-align:left!important;"><?php echo $user['po_no']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['site_id']; ?></td>
                                                <td style="text-align:left!important;"><?php echo date('d/m/Y', strtotime($user['created'])); ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['status_name']; ?></td>
                                                <!-- <td style="text-align:left!important;"><?php echo $user['infratel_id']; ?></td> -->
                                                <td style="text-align:left!important;"><?php echo $user['zone']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['cluster']; ?></td>
                                               
                                                <!-- <td style="text-align:left!important;"><?php echo $user['cluster_mobile']; ?></td> -->
                                                <td style="text-align:left!important;"><?php echo $user['tech_name']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['tech_mobile'];?></td>


                                                <!-- <td style="text-align:left!important;"><?php if($user['resource_allocator'] == 'Vendor') { echo $user['vendor']; }else{ echo $user['allocate_user'];}?></td> -->

                                                <td style="text-align:left!important;"><?php echo $user['supervisor']; ?></td>

                                               <!--  <td style="text-align:left!important;"><?php echo date('d/m/Y', strtotime($user['due_date'])); ?></td> -->
                                              
                                                
                                                
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="7"><p style="color:red; font-size:16px;">No Task Found !</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                                        <div id="leftpag">
                                <!-- START PAGINATION -->
                                <?php if($totalrec > $this->perPage) { echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); } ?>  
                                <!-- END PAGINATION -->
                                </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- /.content -->
    </div>
</div>