<?php
$params = $this->params;
$reason = $this->companies;
// echo '<pre>';print_r( $this->companies);exit;

?>
<div class="row">
	<form action="/company/add-company/id/<?php echo $reason['id']?>" method="POST" onsubmit="return Validate();">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<div class="col-md-5">
					<div class="form-group">
						<label>Company Name:</label>
						<input type="text" name="name" class="form-control" id="name" value="<?php echo $this->companies['name']?>">
					</div>
				</div>
				<div class="col-md-5">
					<div class="form-group">
						<label>Address :</label>
						<textarea name="address" class="form-control" id="address" ><?php echo $this->companies['address']?></textarea>
					</div>
				</div>
			</div>
			<br clear="all">
			<div class="row" id="reason">
				<div class="col-md-5">
					<div class="form-group">
						<label>Email:</label>
						<input type="text" name="email" id="email" class="form-control" value="<?php echo $this->companies['email']?>">
					</div>
				</div>
				<div class="col-md-5">
					<div class="form-group">
						<label>Mobile Number :</label>
						<input type="text" name="mobile_number" class="form-control" id="mobile_number" value="<?php echo $this->companies['mobile_number']?>">
					</div>
				</div>
				<div class="col-md-5">
					<div class="form-group">
						<label>Company Alias :</label>
						<input type="text" name="company_alias" class="form-control" id="company_alias" value="<?php echo $reason['company_alias']?>">
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
					<div class="input-group">
						<button class="btn btn-primary">Submit</button>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">
	function Validate() {
		if($('#name').val() == ""){
			swal('Error','Please enter the name','error');
			return false;
		}else if($('#address').val() == ""){
			swal('Error','Please enter the address','error');
			return false;
		}else if($('#email').val() == ""){
			swal('Error','Please enter the email','error');
			return false;
		}else if($('#mobile_number').val() == ""){
			swal('Error','Please enter the mobile  number','error');
			return false;
		}else if($('#company_alias').val() == ""){
			swal('Error','Please enter the company alias','error');
			return false;
		}else{
			return true;
		}
	}
</script>