 
<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
          </div>
        <?php } else if ($message['error']) { ?>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
          </div>
        <?php } ?>
      <?php endforeach ?>
    <?php endif ?>
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>Import Companies

          <div class="pull-right">
            <a  href="javascript:void(0)"  id="company-details" data-toggle="modal" data-target="#con-close-modal" class="btn btn-success" onclick="addHoliday('<?php echo $company['id']; ?>');" title="add Details"><i class="fa fa-plus"></i>Add New Company</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="user-list">
            <table class="display" width="100%" id="companyTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Company</th>
                  <th>Address</th>
                  <th>Email</th>
                  <th>Mobile Number</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <?php if($this->companies){ 
                  $i = 1;
                  foreach($this->companies as $company) { ?>
                    <tr>
                      <td><?php echo $i;?>.</td>
                      <td><?php echo $company['name']; ?></td>
                      <td><?php echo $company['address']; ?></td>
                      <td><?php echo $company['email']; ?></td>
                      <td><?php echo $company['mobile_number']; ?></td>
                      <td>
                        <a  href="javascript:void(0)" style="text-decoration:underline;"  id="company-details" data-toggle="modal" data-target="#con-close-modal" class="iframe" onclick="addHoliday('<?php echo $company['id']; ?>');" title="view Details"><i class="fa fa-pencil"></i></a>
                        <a  href="javascript:void(0)" style="text-decoration:underline;" onclick="deleteHoliday('<?php echo $company['id']; ?>');" id=""><i class="fa fa-trash"></i></a>
                      </td>
                    </tr>
                    <?php  $i++; } } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="custom-width-modalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="max-height:85%;  margin-top: 50px; margin-bottom:50px; width: 60%">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h3 class="modal-title" id="custom-width-modalLabel">Company Details</h3>
            </div>
            <div class="modal-body">

            </div>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->

      <script>
        $(document).ready(function() {
          $("#companyTable").DataTable();
        });
        function addHoliday(id){
          $.ajax({
            url: "/company/add-company/id/"+id,
            context: document.body,
            success: function(responseText) {
              $(".modal-body").html(responseText);
              $(".modal-body").find("script").each(function(i) {
                eval($(this).text());
              });
            }
          });
        }
        
        function deleteHoliday(id) {
          swal({
            title : "Are you sure?",
            text  : "Do you want to delete clicked company",
            icon  : "warning",
            buttons : [true, "Yes, Delete"],
            dangerMode : true
          }).then(function(isConfirm){
            if (!isConfirm) {
              return false;
            } else {
              $.ajax({
                url: "/company/delete-company/id/" + id,
                type: 'GET',
                success:function(data){
                  var data = JSON.parse(data);
                  if (data.flag) {
                    swal({
                      title : "Deleted",
                      text  : data.message,
                      icon  : "success",
                    }).then(function(){
                      location.reload("/company/company-details");
                    });
                  } else {
                    swal({
                      title : "Failed !",
                      text  : data.message,
                      icon  : "error"
                    });           
                  }
                }
              });

            }
          });
        }
      </script>

