 
<div id="page-wrapper">
  <div class="main-page">
    <div class="panel panel-primary">
      <div class="panel panel-heading">
        <h3>
          <div class="pull-right">
            <a href="" class="btn btn-success">Add New Company</a>
          </div></h3>
        </div>
        <div class="panel panel-body">
          <div class="table-responsive" id="user-list">
            <table class="display" width="100%" id="poDetailsTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Company</th>
                  <th>Address</th>
                  <th>Email</th>
                  <th>Mobile Number</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <script>
   
  </script>

