<?php if($this->planData){
    //if($this->activity == 'Material Delivery' || $this->activity == 'Overall'){ $per = '%';}
    ?>
<script type="text/javascript">
            AmCharts.makeChart("chartdiv",
                {
                    "type": "serial",
                    "categoryField": "month",
                    "startDuration": 1,
                    "categoryAxis": {
                        "gridPosition": "start"
                    },
                    "chartCursor": {
                        "enabled": true
                    },
                    "export": {
                        "enabled": true
                    },
                    "trendLines": [],
                    "graphs": [
                        {
                            "balloonText": "[[value]]%",
                            "bullet": "round",
                            "id": "AmGraph-1",
                            "title": "Plan",
                            "valueField": "plan"
                        },
                        {
                            "balloonText": "[[value]]%",
                            "bullet": "round",
                            "id": "AmGraph-2",
                            "title": "CUP-1",
                            "valueField": "cup1"
                        },
                        {
                            "balloonText": "[[value]]%",
                            "bullet": "round",
                            "id": "AmGraph-3",
                            "title": "CUP-2",
                            "valueField": "cup2"
                        },
                        {
                            "balloonText": "[[value]]%",
                            "bullet": "round",
                            "id": "AmGraph-4",
                            "title": "CUP-3",
                            "valueField": "cup3"
                        },
                        {
                            "balloonText": "[[value]]%",
                            "bullet": "round",
                            "id": "AmGraph-5",
                            "title": "Actual",
                            "valueField": "actual"
                        }
                    ],
                    "guides": [],
                    "valueAxes": [
                        {
                            "id": "ValueAxis-1",
                            "title": "S-curve in percentage(%)"
                        }
                    ],
                    "allLabels": [],
                    "balloon": {},
                    "legend": {
                        "enabled": true,
                        "useGraphSettings": true
                    },
                    "titles": [
                        {
                            "id": "Title-1",
                            "size": 15,
                            "text": "<?php echo $this->activity; ?>"
                        }
                    ],
                    "dataProvider": [
                    <?php $i=0; foreach ($this->getScurveData as $key => $value) { 
                        $planArray = $i.'plan';
                        $planArray = array();

                        $catch_up_plan_1Array = $i.'catch_up_plan_1';
                        $catch_up_plan_1Array = array();

                        $catch_up_plan_2Array = $i.'catch_up_plan_2';
                        $catch_up_plan_2Array = array();

                        $catch_up_plan_3Array = $i.'catch_up_plan_3';
                        $catch_up_plan_3Array = array();

                        $sumArray = $i.'sum';
                        $sumArray = array();

                        if($i == 0){
                            array_push($planArray, $value['plan']);
                            array_push($catch_up_plan_1Array, $value['cup1']);
                            array_push($catch_up_plan_2Array, $value['cup2']);
                            array_push($catch_up_plan_3Array, $value['cup3']);
                            array_push($sumArray, $value['sum']);
                        }else{
                            for ($j=0; $j< $i+1; $j++) { 
                                array_push($planArray, $this->getScurveData[$j]['plan']);
                                array_push($catch_up_plan_1Array, $this->getScurveData[$j]['cup1']);
                                array_push($catch_up_plan_2Array, $this->getScurveData[$j]['cup2']);
                                array_push($catch_up_plan_3Array, $this->getScurveData[$j]['cup3']);
                                array_push($sumArray, $this->getScurveData[$j]['sum']);
                            }
                        }
                        

                        ?>
                        {
                            "month": "<?php echo $value['month'];?>",
                            "plan": "<?php if(array_sum($planArray)>100){ echo '100';}else{echo @ceil(array_sum($planArray));}?>",
                            "cup1": "<?php if(array_sum($catch_up_plan_1Array)>100){ echo '100';}else{echo @ceil(array_sum($catch_up_plan_1Array));}?>",
                            "cup2": "<?php if(array_sum($catch_up_plan_2Array)>100){ echo '100';}else{echo @ceil(array_sum($catch_up_plan_2Array));}?>",
                            "cup3": "<?php if(array_sum($catch_up_plan_3Array)>100){ echo '100';}else{echo @ceil(array_sum($catch_up_plan_3Array));}?>",
                            "actual": "<?php if(array_sum($sumArray)>100){ echo '100';}else{echo @ceil(array_sum($sumArray));}?>"
                        },
                        <?php $i++;}?>
                    ]
                }
            );
        </script>
       <script type="text/javascript">
            // AmCharts.makeChart("monthly",
            //     {
            //         "type": "serial",
            //         "categoryField": "month",
            //         "angle": 30,
            //         "depth3D": 30,
            //         "startDuration": 1,
            //         "categoryAxis": {
            //             "gridPosition": "start"
            //         },
            //         "chartCursor": {
            //             "enabled": true,
            //             "fileName":'s-curve'
            //         },
            //         "export": {
            //             "enabled": true
            //         },
            //         "trendLines": [],
            //         "graphs": [
            //             {
            //                 "balloonText": "[[value]]<?php echo $per;?>",
            //                 "fillAlphas": 1,
            //                 "id": "AmGraph-1",
            //                 "title": "Plan",
            //                 "type": "column",
            //                 "valueField": "plan"
            //             },
            //             {
            //                 "balloonText": "[[value]]<?php echo $per;?>",
            //                 "fillAlphas": 1,
            //                 "id": "AmGraph-2",
            //                 "title": "CUP-1",
            //                 "type": "column",
            //                 "valueField": "cup1"
            //             },
            //             {
            //                 "balloonText": "[[value]]<?php echo $per;?>",
            //                 "fillAlphas": 1,
            //                 "id": "AmGraph-3",
            //                 "title": "CUP-2",
            //                 "type": "column",
            //                 "valueField": "cup2"
            //             },
            //             {
            //                 "balloonText": "[[value]]<?php echo $per;?>",
            //                 "fillAlphas": 1,
            //                 "id": "AmGraph-4",
            //                 "title": "CUP-3",
            //                 "type": "column",
            //                 "valueField": "cup3"
            //             },
            //             {
            //                 "balloonText": "[[value]]<?php echo $per;?>",
            //                 "fillAlphas": 1,
            //                 "id": "AmGraph-5",
            //                 "title": "Actual",
            //                 "type": "column",
            //                 "valueField": "actual"
            //             }
            //         ],
            //         "guides": [],
            //         "valueAxes": [
            //             {
            //                 "id": "ValueAxis-1",
            //                 "title": "S-curve in counts"
            //             }
            //         ],
            //         "allLabels": [],
            //         "balloon": {},
            //         "legend": {
            //             "enabled": true,
            //             "useGraphSettings": true
            //         },
            //         "titles": [
            //             {
            //                 "id": "Title-1",
            //                 "size": 15,
            //                 "text": ""
            //             }
            //         ],
            //         "dataProvider": [
            //         <?php $i=0; foreach ($this->getScurveMonthlyGraphData as $key => $value) { ?>
            //             {
            //                 "plan": "<?php echo @number_format($value['plan'],2);?>",
            //                 <?php if($value['cup1']){ ?>
            //                 "cup1": "<?php echo @number_format($value['cup1'],2);?>",
            //                 <?php  } if($value['cup2']){?>
            //                 "cup2": "<?php echo @number_format($value['cup2'],2);?>",
            //                  <?php  } if($value['cup3']){?>
            //                 "cup3": "<?php echo @number_format($value['cup3'],2);?>",
            //                  <?php  }?>
            //                 "actual": "<?php echo @number_format($value['sum'],2);?>",
            //                 "month": "<?php echo $value['month'];?>"
            //             },
            //         <?php }?>
                    
            //         ]
            //     }
            // );
        </script>
<div id="chartdiv" style="height:350px; "></div>
<!-- <div id="monthly" style="height:350px; "></div> -->
<?php }else{ ?>
    <br clear="all"><br clear="all">
    <div class="alert alert-danger" role="alert" id="alert">
    <button type="button" class="close" data-dismiss="alert"></button>
    No Record found...
    </div>
<?php   } ?>