<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>
<style>
.select2.select2-container {
    width: 100% !important;
}
.mainDiv {
  background-color: #DCF2FE;
  border-radius: 5px;
}
form {
  padding: 5px;
}
#mandatory {
  color: red;
  font-size: 16px;
}
.table-bordered {
    border: 2px solid #1b1a1a !important;
}
.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
    border: 1px solid #1b1a1a !important;
}
</style>

<div id="page-wrapper">
  <div class="main-page">
    <?php if ($this->messages): ?>
      <?php foreach ($this->messages as $message): ?>
        <?php if ($message['success']){ ?>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success !</strong>&nbsp; <?php echo $message["success"]; ?>
        </div>
    <?php } else if ($message['error']) { ?>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Error !</strong>&nbsp; <?php echo $message["error"]; ?>
    </div>
<?php } ?>
<?php endforeach ?>
<?php endif ?>
<div class="panel panel-primary">
  <div class="panel panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h3>Add New Product</h3>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <a href="#" class="btn btn-success pull-right">View Products</a>
    </div>
</div>
</div>
<div class="panel panel-body">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
        <form action="/material-stock/add-new-product" method="post">
            <div class="row" style="overflow: auto; padding: 8px 15px;">
                <table class="table table-bordered" id="newProductTable">
                    <thead>
                        <th>Product Type</th>
                        <th>Product Name</th>
                        <th>Unit</th>
                        <th>Price (INR)</th>
                        <th>Action</th>
                    </thead>
                    <tbody>
                        <tr id="row_1">
                            <td width="20%">
                                <select name="product_category[]" id="product_category_1" class="form-control">
                                    <option value="">Select Product Category</option>
                                    <?php foreach ($this->productType as $productTypeList) {?>
                                        <option value="<?php echo $productTypeList['id']; ?>"><?php echo $productTypeList['product_type_name']; ?></option><?php } ?>
                                    </select>
                                </td>
                                <td width="40%">
                                    <input type="text" class="form-control" name="product_name[]" id="product_name_1" required="">
                                </td>
                                <td width="18%">
                                    <select name="unit[]" id="unit_1" class="form-control">
                                        <option value="">Select product unit</option>
                                        <?php foreach ($this->unit as $brands) {?>
                                            <option value="<?php echo $brands['unit_name']; ?>"><?php echo $brands['unit_name']; ?></option><?php } ?>
                                        </select>
                                    </td>
                                    <td width="12%">
                                        <input type="text" class="form-control" name="price[]" id="price_1" required="" size="4">
                                    </td>
                                    <td width="10%"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <br clear="all">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Product</button>
                        </div>
                    </div>
                    <br clear="all">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                          <button type="submit" class="btn btn-success pull-right">Save</button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
  </div>
</div>
</div>

<script>
    $(document).ready(function() {
        $("#product_category_1").select2();
        $("#brand_1").select2();
        $("#unit_1").select2();
    }); 

    function addMoreRow() {
        var row_count = $('#newProductTable tr').length;
        if (row_count <= 10) {

            var html_content = `<tr id="row_`+row_count+`">
            <td>
            <select name="product_category[]" id="product_category_`+row_count+`" class="form-control">
            <option value="">Select Product Category</option>
            <?php foreach ($this->productType as $productTypeList) {?>
                <option value="<?php echo $productTypeList['id']; ?>"><?php echo $productTypeList['product_type_name']; ?></option><?php } ?>
                </select>
                </td>
                <td>
                <input type="text" class="form-control" name="product_name[]" id="product_name_`+row_count+`" required="">
                </td>
                <td>
                <select name="unit[]" id="unit_`+row_count+`" class="form-control">
                <option value="">Select product unit</option>
                <?php foreach ($this->unit as $brands) {?>
                    <option value="<?php echo $brands['unit_name']; ?>"><?php echo $brands['unit_name']; ?></option><?php } ?>
                    </select>
                    </td>
                    <td>
                    <input type="text" class="form-control" name="price[]" id="price_`+row_count+`" required="" size="4">
                    </td>
                    <td><a href="javascript:void(0)" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color:red;"></i></a></td>
                    </tr>`;
                    $("#newProductTable").append(html_content);   
                    $("#product_category_"+row_count).select2();
                    $("#brand_"+row_count).select2();
                    $("#unit_"+row_count).select2();   
                } else {
                    swal('Access Denide','Only 10 rows are allowed.','info');
                    $("#addRow").attr('disabled', 'disabled');
                }
            }
            function deleteRow(count) {
             $("#row_"+count).remove();
             $("#addRow").removeAttr("disabled");
         } 

           // function validateData() {
           //     var product_type = $()
           // }
       </script>