<link rel="stylesheet" href="/assets/css/select2.min.css">
<script src="/assets/js/select2.min.js"></script>

<style>
	.select2.select2-container {
		width: 100% !important;
	}
	.error_box{
		border: 1px solid red;
		border-radius: 5px;
	}
	.mainDiv {
		background-color: #DCF2FE;
		border-radius: 5px;
		padding: 10px 15px 10px 15px;
	}
	form {
		padding: 5px;
	}
	#mandatory {
		color: red;
		font-size: 18px;
	}
	.siteExpenseDiv {
		display: block;
		border: 5px solid #b0d5ea;
		border-radius: 5px;
		padding: 10px 10px 10px 10px;
	}
	.table-bordered {
		border: 2px solid #1b1a1a !important;
	}
	.table-bordered > thead > tr > th, .table-bordered > tbody > tr, .table-bordered > tbody > tr > td {
		border: 1px solid #1b1a1a !important;
	}
</style>

<div id="page-wrapper">
	<div class="main-page">
		<?php if (isset($this->params)): ?>
			<?php if (isset($this->params['error'])) { ?>
				<div class="alert alert-danger">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error !</strong>&nbsp; <?php echo $this->params["error"]; ?>
				</div>
			<?php } ?>
		<?php endif ?>
		<div class="panel panel-primary">
			<div class="panel panel-heading">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<h3>Allocate New Site</h3>
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
						<a href="/siteallocation" class="btn btn-success pull-right">View Allocated Sites</a>
					</div>
				</div>
			</div>
			<div class="panel panel-body">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 mainDiv">
					<form action="/siteallocation/allocate-site" method="POST" onsubmit="return validateInputData()">
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<span style="font-weight: bold; font-size: 16px; color: #D60019;">*&nbsp;Fields are mandatory.</span>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="state_id">State <span id="mandatory">*</span></label>
								<select name="state_id" id="state_id" class="form-control select2" onchange="getClientMasterList()">
									<option value="">Select State</option>
									<?php foreach ($this->stateList as $state): ?>
										<option value="<?php echo $state['id']; ?>"<?php if(isset($this->params['state_id'])) { echo $this->params['state_id'] == $state['id']?"selected":"";} ?>><?php echo $state['state_name']; ?></option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="client_id">Client Name<span id="mandatory">*</span> :</label>
								<select class="form-control select2" name="client_id" id="client_id" onchange="getPoList()">
									<option value="">Select Client</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="poNumber">PO Number <span id="mandatory">*</span></label>
								<select name="poNumber" id="poNumber" class="form-control select2" onchange="getSitesByPoNumberForAllocation()">
									<option value="">Select PO Number</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="siteId">Site ID<span id="mandatory">*</span></label>
								<select name="siteId" id="siteId" class="form-control select2" onchange="getSiteTechnicalDetails()">
									<option value="">Select Site ID</option>
								</select>
							</div>
							<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="po_date">PO Date</label>
								<input type="text" class="form-control" name="po_date" id="po_date" readonly="">
							</div>
							<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
								<label for="site_completion_date">Site Completion Date (Tentative)<span id="mandatory">*</span></label>
								<input type="text" class="form-control datepicker" name="site_completion_date" id="site_completion_date" readonly="">
							</div>
						</div>
						<br clear="all">
						<div class="siteExpenseDiv">
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<h2 align="center" style="text-decoration: underline;">Site Details</h2>
								</div>
							</div>
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="infratel_id">Infratel ID</label>
									<input type="text" class="form-control" name="infratel_id" id="infratel_id" readonly="">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="zone">Zone</label>
									<input type="text" class="form-control" readonly name="zone" id="zone">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="location">Location</label>
									<input type="text" class="form-control" readonly name="location" id="location">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="cluster">Cluster</label>
									<input type="text" class="form-control" readonly name="cluster" id="cluster">
								</div>
							</div>
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="cluster_incharge">Cluster Incharge</label>
									<input type="text" class="form-control" readonly name="cluster_incharge" id="cluster_incharge">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="cluster_mobile">Cluster Mobile Number</label>
									<input type="text" class="form-control" readonly name="cluster_mobile" id="cluster_mobile">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="technician_name">Technician Name</label>
									<input type="text" class="form-control" readonly name="technician_name" id="technician_name">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="technician_mobile">Technician Mobile Number</label>
									<input type="text" class="form-control" readonly name="technician_mobile" id="technician_mobile">
								</div>
							</div>
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="site_latitude">Site Latitude</label>
									<input type="text" class="form-control" readonly name="site_latitude" id="site_latitude">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="site_longitude">Site Longitude</label>
									<input type="text" class="form-control" readonly name="site_longitude" id="site_longitude">
								</div>
								<div class="form-group col-xs-12 col-sm-12 col-md-3 col-lg-3">
									<label for="work_type">Work Type</label>
									<input type="text" class="form-control" readonly name="work_type" id="work_type">
								</div>
							</div>
							<div class="row">
								<div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<h2 align="center" style="text-decoration: underline;">Nature Of Work & Resource Allocation</h2>
								</div>
							</div>

							<div class="row" id="workAllocationDiv" style="overflow: auto; padding: 8px 15px;">
								<table class="table table-bordered" id="workAllocationTable">
									<thead>
										<th>Nature Of Work</th>
										<!-- <th>Work Aging</th> -->
										<th>Allocate Resource Type</th>
										<th>Vendor Name</th>
										<th>Supervisor Name</th>
										<th>Due Date</th>
										<th>Action</th>
									</thead>
									<tbody>
										<tr id="row_1">
											<td>
												<select name="nature_of_work[]" id="nature_of_work_1" class="form-control mandatory select2">
													<option value="">Please Select</option>
													<?php foreach ($this->natureOfWork as $natureOfWork): ?>
														<option value="<?php echo $natureOfWork['id']; ?>"<?php if(isset($this->params['natureOfWork'])) { echo $this->params['nature_of_work'] == $natureOfWork['id']?"selected":"";} ?>><?php echo $natureOfWork['nature_of_work']; ?></option>
													<?php endforeach ?>
												</select>
												<span id="" class="error" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
											</td>
											<td>
												<select name="resource_type[]" id="resource_type_1" class="form-control mandatory select2" onchange="showDetailsToAllocateSite(1)">
													<option value="">Please Select</option>
													<option value="Staff">Staff</option>
													<option value="Vendor">Vendor</option>
													<option value="Direct">Direct</option>
												</select>
												<span id="" class="error" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
											</td>
											<td id="vendorNameTd_1">
												<select name="vendor_id[]" id="vendor_id_1" class="form-control select2" onchange="getVendorSupervisorList(1)">
													<option value="">Please Select</option>
												</select>
											</td>
											<td>
												<select name="supervisor_id[]" id="supervisor_id_1" class="form-control mandatory select2">
													<option value="">Please Select</option>
												</select>
												<span id="" class="error" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
											</td>
											<td>
												<input type="text" class="form-control datepicker" name="completion_date[]" id="completion_date_1" readonly="" value="<?php echo date('d/m/Y'); ?>">
											</td>
											<td></td>
										</tr>
									</tbody>
								</table>
								<div class="row">
									<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
										<button type="button" name="addRow" class="btn btn-responsive layout_btn_prevent btn-success" onclick="addMoreRow();">Add More Row</button>
									</div>
								</div>
							</div>

						</div>
						<br clear="all">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 pull-right">
								<button type="submit" class="btn btn-success" style="float: right;">Allocate Site</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true});
	}); 
	function getSitesByPoNumberForAllocation() {
		var po_number = $("#poNumber").val();
		if (po_number != "") {
			$("#loading-bg").show();
			$.ajax({
				url: '/siteallocation/get-sites-by-po-number-for-allocation',
				type: 'POST',
				data: {po_number: po_number},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					var option = "<option value=''>Select Site ID</option>";
					if (data.flag) {
						$.each(data.sites, function(index, site_id) {
							option += "<option value='"+site_id.site_id+"'>"+site_id.site_id+"</option>";
						});
					} else {
						option += "<option>"+data.message+"</option>";
					}
					$("#siteId").html(option);
					$("#po_date").val(data.po_date);
				}
			});
		} else {
			swal({
				title : "PO Number Missing!",
				text  : "Please select PO number first.",
				icon  : "error"
			}).then(function(){
				$("#siteId").html("<option>Select Site ID</option>");
				$("#po_date").val('');
				$("#infratel_id").val('');
				$("#zone").val('');
				$("#location").val('');
				$("#cluster").val('');
				$("#cluster_incharge").val('');
				$("#cluster_mobile").val('');
				$("#technician_name").val('');
				$("#technician_mobile").val('');
				$("#site_latitude").val('');
				$("#site_longitude").val('');
				$("#work_type").val('');
			});
		}
	}
	function getSiteTechnicalDetails() {
		var site_id = $("#siteId").val();
		if (site_id != "") {
			$("#loading-bg").show();
			$.ajax({
				url: '/siteallocation/get-site-matrix-details',
				type: 'POST',
				data: {site_id: site_id},
				success:function (data) {
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					if (data.flag) {
						var site_data = data.site_data;
						$("#infratel_id").val(site_data.infratel_id);
						$("#zone").val(site_data.zone);
						$("#location").val(site_data.location);
						$("#cluster").val(site_data.cluster);
						$("#cluster_incharge").val(site_data.cluster_incharge);
						$("#cluster_mobile").val(site_data.cluster_mobile);
						$("#technician_name").val(site_data.tech_name);
						$("#technician_mobile").val(site_data.tech_mobile);
						$("#site_latitude").val(site_data.latitude);
						$("#site_longitude").val(site_data.longitude);
						$("#work_type").val(site_data.work_type);
					} else {

					}
				}
			});
		} else {
			$("#infratel_id").val('');
			$("#zone").val('');
			$("#location").val('');
			$("#cluster").val('');
			$("#cluster_incharge").val('');
			$("#cluster_mobile").val('');
			$("#technician_name").val('');
			$("#technician_mobile").val('');
			$("#site_latitude").val('');
			$("#site_longitude").val('');
			$("#work_type").val('');
		}
	}
	function showDetailsToAllocateSite(row) {
		var resourceType = $("#resource_type_"+row).val();
		if (resourceType == "Staff" || resourceType == "Direct") {
			$.ajax({
				url: '/user/get-supervisor-list',
				type: 'GET',
				success:function (data) {
					var data = JSON.parse(data);
					console.log(data);
					if (data.flag) {
						$("#supervisor_id_"+row).html(data.supervisor_list);
						$("#vendorNameTd_"+row).html('<input type="text" class="form-control" name="vendor_id[]" id="blankTd_'+row+'" />');
						$("#blankTd_"+row).attr('readonly', true);
						$("#blankTd_"+row).val('');
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
					}
				}

			});
		} else if (resourceType == "Vendor") {
			$.ajax({
				url: '/vendor/get-vendor-list',
				type: 'GET',
				success:function (data) {
					var data = JSON.parse(data);
					console.log(data);
					if (data.flag) {
						$("#vendorNameTd_"+row).html('<select name="vendor_id[]" id="vendor_id_'+row+'" class="form-control select2" onchange="getVendorSupervisorList('+row+')">');
						$("#vendor_id_"+row).html(data.vendor_list);
						$(".select2").select2();
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
					}
				}
			});
			
		} else {
			$("#supervisor_id_"+row).html('<option value="">Please Select</option>');
		}
	}
	function getVendorSupervisorList(row) {
		var vendor_id = $("#vendor_id_"+row).val();
		if (vendor_id != "") {
			$.ajax({
				url: '/vendor/get-vendor-supervisor-list-by-vendor-id',
				type: 'POST',
				data: {vendor_id: vendor_id},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					if (data.flag) {
						$("#supervisor_id_"+row).html(data.supervisor_list);
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
					}
				}
			});
		} else {
			swal({
				title : "Vendor Name Missing!",
				text  : "Please select vendor name from vendor list.",
				icon  : "error"
			}).then(function(){
				$("#supervisor_id_"+row).html('<option value="">Please Select</option>');
			});
		}
	}
	function addMoreRow() {
		var row_count = $('#workAllocationTable tr').length;
		var html_content = `<tr id="row_`+row_count+`">
		<td>
		<select name="nature_of_work[]" id="nature_of_work_`+row_count+`" class="form-control mandatory select2">
		<option value="">Please Select</option>
		<?php foreach ($this->natureOfWork as $natureOfWork): ?>
			<option value="<?php echo $natureOfWork['id']; ?>"<?php if(isset($this->params['natureOfWork'])) { echo $this->params['nature_of_work'] == $natureOfWork['id']?"selected":"";} ?>><?php echo $natureOfWork['nature_of_work']; ?></option>
		<?php endforeach ?>
		</select>
		<span id="" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
		</td>
		<td>
		<select name="resource_type[]" id="resource_type_`+row_count+`" class="form-control mandatory select2" onchange="showDetailsToAllocateSite(`+row_count+`)">
		<option value="">Please Select</option>
		<option value="Staff">Staff</option>
		<option value="Vendor">Vendor</option>
		<option value="Direct">Direct</option>
		</select>
		<span id="" class="error" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
		</td>
		<td id="vendorNameTd_`+row_count+`">
		<select name="vendor_id[]" id="vendor_id_`+row_count+`" class="form-control select2" onchange="getVendorSupervisorList(`+row_count+`)">
		<option value="">Please Select</option>
		</select>
		</td>
		<td>
		<select name="supervisor_id[]" id="supervisor_id_`+row_count+`" class="form-control mandatory select2">
		<option value="">Please Select</option>
		</select>
		<span id="" class="error" style=" display: none; color: red; font-weight: bold;"><i class="fa fa-exclamation-circle error" style="color: red;"></i>&nbsp;Please Select</span>
		</td>
		<td>
		<input type="text" class="form-control datepicker" name="completion_date[]" id="completion_date_`+row_count+`" readonly="" value="<?php echo date('d/m/Y'); ?>">
		</td>
		<td><a href="javascript:void(0)" onclick="deleteRow(`+row_count+`)"><i class="fa fa-trash fa-2x" style="color:red;"></i></a></td>
		</tr>`;
		$("#workAllocationTable").append(html_content);
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true }); 
	} 
	function deleteRow(count) {
		$("#row_"+count).remove();
	} 
	function getClientMasterList() {
		var state_id = $("#state_id").val();
		if (state_id == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
			$("#client_id").empty();
			$("#client_id").append('<option value="">Select Client</option>');
			return false;
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/master/get-client-details',
				type: 'POST',
				data: {state_id: state_id},
				success:function(data){
					var data = JSON.parse(data);
					$("#loading-bg").hide();
					console.log(data);
					if (data.flag) {
						$("#client_id").empty();  
						$("#client_id").append('<option value="">Select Client</option>');  
						$.each(data.clientDetails, function(index, val) {
							$("#client_id").append('<option value="'+val.id+'">'+val.client_name+'</option>');  
						});
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						$("#client_id").empty();  
						$("#client_id").append('<option value="">Select Client</option>');  
					}
				}
			});
		}
	}
	function getPoList() {
		var state_id = $("#state_id").val();
		var client_id = $("#client_id").val();
		if (state_id == "") {
			swal({
				title : "State Missing!",
				text  : "Please select state name.",
				icon  : "error"
			}).then(function(){
				$("#state_id").select2('open');
			});
			return false;
		} else if (client_id == "") {
			swal({
				title : "Client Missing!",
				text  : "Please select client name.",
				icon  : "error"
			}).then(function(){
				$("#client_id").select2('open');
			});
			return false;
		} else {
			$("#loading-bg").show();
			$.ajax({
				url: '/manage-po-site/get-po-list-by-state-and-client',
				type: 'POST',
				data: {state_id: state_id, client_id: client_id},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					if (data.flag) {
						$("#poNumber").empty();
						$("#poNumber").append("<option value=''>Select PO Number</option>");
						$("#poNumber").append(data.poList);
					} else {
						swal({
							title : data.title,
							text  : data.message,
							icon  : "error"
						});
						return false;
					}
				}
			});
		}
	}
	function validateInputData() {
		var poNumber     = $("#poNumber").val();
		var siteId       = $("#siteId").val();
		var siteCompletion = $("#site_completion_date").val();
		if (poNumber == "") {
			swal({
				title : "PO Number Missing!",
				text  : "Please select PO Number.",
				icon  : "error"
			}).then(function(){
				$("#poNumber").focus();
			});
			return false;
		} else if (siteId == "") {
			swal({
				title : "Site ID Missing!",
				text  : "Please select site ID.",
				icon  : "error"
			}).then(function(){
				$("#siteId").focus();
			});
			return false;
		} else if (siteCompletion == "") {
			swal({
				title : "Completion Date Missing!",
				text  : "Please select site completion date.",
				icon  : "error"
			}).then(function(){
				$("#site_completion_date").focus();
			});
			return false;
		} else {
			$('.mandatory').each(function(e) {
				if ($(this).val() == "") {
					$(this).siblings(".select2-container").addClass('error_box');
				} else {
					$(this).siblings(".select2-container").removeClass('error_box');
				}
				return false;
			});
		}
	}
</script>