<div class="col-lg-3" style="float:left;">
  <label for="first_name1" class="col-form-label">
    Infratel Id *
  </label>
  <div class="input-group">
    <input type="text" name="infratel_id" id="infratel_id" readonly="" style="background-color:#ECEEEF;" placeholder="Infratel Id" value="<?php echo $this->martix_data['infratel_site_id'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="telephone" class="col-form-label">
    Location *
  </label>
  <div class="input-group">
    <input type="text" name="district" id="district" readonly="" style="background-color:#ECEEEF;" placeholder="District" value="<?php echo $this->district['location'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="address" class="col-form-label">
    Zone *
  </label>
  <div class="input-group">
    <input type="text" name="zone" id="zone" readonly="" style="background-color:#ECEEEF;" placeholder="District" value="<?php echo $this->martix_data['zone'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="address" class="col-form-label">
    Cluster *
  </label>
  <div class="input-group">
    <input type="text" name="cluster" id="cluster" readonly="" style="background-color:#ECEEEF;" placeholder="District" value="<?php echo $this->martix_data['cluster'];?>" class="form-control">
  </div>
</div>


<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Cluster Incharge. *
  </label>
  <div class="input-group">
    <input type="text" name="cluster_incharge" readonly="" style="background-color:#ECEEEF;" id="cluster_incharge" placeholder="Cluster Incharge" value="<?php echo $this->martix_data['cluster_incharge'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Cluster Phone No. *
  </label>
  <div class="input-group">
    <input type="text" name="cluster_mobile" readonly="" style="background-color:#ECEEEF;" id="cluster_mobile" placeholder="Cluster Mobile No." value="<?php echo $this->martix_data['cluster_mobile'];?>" class="form-control">
  </div>
</div>
<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Technician Name  *
  </label>
  <div class="input-group">
    <input type="text" name="tech_name" readonly="" style="background-color:#ECEEEF;" id="tech_name" placeholder="Technician Name" value="<?php echo $this->martix_data['tech_name'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Technician Phone No.  *
  </label>
  <div class="input-group">
    <input type="text" name="tech_mobile" readonly="" style="background-color:#ECEEEF;" id="tech_mobile" placeholder="Technician Phone No." value="<?php echo $this->martix_data['tech_mobile'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Latitude.  *
  </label>
  <div class="input-group">
    <input type="text" name="latitude" readonly="" style="background-color:#ECEEEF;" id="latitude" placeholder="Latitude" value="<?php echo $this->cooridnate['latitude'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-3" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Longitude.  *
  </label>
  <div class="input-group">
    <input type="text" name="longitude" readonly="" style="background-color:#ECEEEF;" id="longitude" placeholder="Longitude" value="<?php echo $this->cooridnate['longitude'];?>" class="form-control">
  </div>
</div>

<div class="col-lg-6" style="float:left;">
  <label for="vendor gst" class="col-form-label">
    Work Type  *
  </label>
  <div class="input-group">
    <textarea name="item_desc" id="item_desc" readonly=""  style="background-color:#ECEEEF;" placeholder="Item Description" class="form-control"><?php echo $this->district['work_type'];?></textarea>
  </div>
</div>