<?php
$params             = $this->params;
$site               = $this->site;  
?>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD67PS69UkNREHH5pkb1E-zCy7iWKSNgE4&libraries=geometry"></script>
<div class="">
  <!-- Content Header (Page header) -->

       <!--  <div class="content-header container-fluid bg-white">
            <div class="row">
                <div class="col-sm-4">
                    <h4><i class="ti-user"></i> Site Allocation List Data</h4>
                </div>
            </div>
          </div> -->
          <br clear="all">
          <!-- Main content -->
          <div class="content">
            <?php if ($this->messages): ?>
              <div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
                <?php foreach ($this->messages as $message): ?>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <div class="alert_data">
                    <?php echo $message ?>.
                  </div>
                <?php endforeach ?>
              </div>
            <?php endif ?>
            

            <div class="row">
              <div class="col-12">
                <div class="card  profile2_aboutme">
                 <div class="card-header card-info text-white">
                  <p style="float: left; margin: 0px; color: #fff;">Site Location
                  </p>
                  <a href="/siteallocation" style="float: right; margin: 0px;" class="btn btn-success btn_width m-t-10 m-r-10">View All Site Allocation
                  </a>
                </div>
                
                <div class="card-block" style="<?php if($site['latitude']!=''){ ?>height: 550px;<?php }?> ">
                  <div class="row basic_tables">
                    <div class="col-12">
                      <div class="table-responsive mt-0" id="my-siteallocation" style="padding:0px !important;">
                        <?php
                        if($site['latitude']!=''){
                          ?>
                          <div id="map" style="width: 98%; height: 500px; position: absolute !important;"></div>
                          <script type="text/javascript">
                            var locations = [
                            ['Infratel Site Id : <strong><?php echo ucwords($site['infratel_site_id']);?></strong><br/>Technical Site Id : <strong><?php echo ucwords($this->site_details['site_id']);?></strong><br/>Technician Name : <strong><?php echo ucwords($this->site_details['tech_name']);?></strong><br/>Technician Mobile No. : <strong><?php echo $this->site_details['tech_mobile'];?></strong><br/>', <?php echo $site['latitude'];?>, <?php echo $site['longitude'];?>, 4],       
                            ];
                                       // Enable the visual refresh
                                       google.maps.visualRefresh = true;
                                       var map = new google.maps.Map(document.getElementById('map'), {
                                         zoom: 18,
                                         center: new google.maps.LatLng(<?php echo $site['latitude'];?>, <?php echo $site['longitude'];?>),
                                         mapTypeId: google.maps.MapTypeId.ROADMAP
                                       });
                                       
                                       var infowindow = new google.maps.InfoWindow();
                                       var marker, i;

                                       var icon = {
                                        url: '/img/tower/tower.png'
                                      }

                                      for (i = 0; i < locations.length; i++) { 
                                       //alert(locations[i][1]);
                                             //alert(locations[i][2]); 
                                             

                                             marker = new google.maps.Marker({
                                               position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                                               map: map,
                                               icon: icon
                                             });
                                             
                                             google.maps.event.addListener(marker, 'click', (function(marker, i) {
                                               return function() {
                                                 infowindow.setContent(locations[i][0]);
                                                 infowindow.open(map, marker);
                                               }
                                             })(marker, i));
                                           }
                                         </script>
                                       <?php }else{ ?>
                                        <div class="alert alert-danger alert-dismissible fade show m-t-10" role="alert">
                                          <div class="alert_data">
                                            No Record Found...
                                          </div>
                                        </div>
                                      <?php  } ?>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- /.content -->
                      </div>
                    </div>

