
<div class="modal-dialog modal-lg">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3 class="modal-title">Allocated Site Details</h3>
		</div>
		<div class="modal-body">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
					<label for="">PO Number</label>
					<input type="text" class="form-control" value="<?php echo $this->allocatedSite['po_no']; ?>" readonly>	
				</div>
				<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
					<label for="">PO Date</label>
					<input type="text" class="form-control" value="<?php echo date('d/m/Y',strtotime($this->allocatedSite['po_date'])); ?>" readonly>	
				</div>
				<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
					<label for="">Site Id</label>
					<input type="text" class="form-control" value="<?php echo $this->allocatedSite['site_id']; ?>" readonly>	
				</div>
				<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
					<label for="">Site Completion Date</label>
					<input type="text" class="form-control" value="<?php echo date('d/m/Y',strtotime($this->allocatedSite['due_date']));  ?>" readonly>	
				</div>
			</div>
			<div class="row">
				<div class="table-responsive">
					<table class="table table-bordered" style="width: 100%;">
						<thead>
							<tr>
								<th>Nature of Work</th>
								<th>Allocated Resource</th>
								<th>Vendor Name</th>
								<th>Supervisor Name</th>
								<th>Due Date</th>
							</tr>
						</thead>
						<tbody>
							<?php if ($this->allocatedSiteDetails): ?>
								<?php foreach ($this->allocatedSiteDetails as $allocatedSite): ?>
									<tr>
										<td>
											<?php echo $allocatedSite['nature_of_work']; ?>
										</td>
										<td>
											<?php echo $allocatedSite['allocation_type']; ?>
										</td>
										<td>
											<?php if ($allocatedSite['vendor_id']) { 
												echo $allocatedSite['vendor_name']; 
											} else { 
												echo "-"; 
											} ?>
										</td>
										<td>
											<?php if ($allocatedSite['vendor_id']) {
												echo $allocatedSite['vendor_contact_name'];
											} else { 
												echo $allocatedSite['supervisor_name']; 
											} ?>
										</td>
										<td><?php echo date('d/m/Y', strtotime($allocatedSite['work_completion_date']));  ?></td>
									</tr>
								<?php endforeach ?>
							<?php endif ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="modal-footer">

		</div>
	</div>
</div>
