<?php 
$record = $this->allocated_site_list;
// print_r($record);exit;

?>

<table  class="table table-striped">
    <thead>
        <tr>
            <strong>
                <th>#</th>
                <th style="text-align:left!important;">PO</th>
                <th style="text-align:left!important;" nowrap>Site Id</th>
                <th style="text-align:left!important;" nowrap>Assigned Date</th>
                <th style="text-align:left!important;">Zone</th>
                <th style="text-align:left!important;" nowrap>Cluster</th>
                <th style="text-align:left!important;" nowrap>Allocated To</th>
                <th style="text-align:left!important;">Due Date</th>
                <th style="text-align:left!important;" nowrap>Allocated By</th>
                <th style="text-align:left!important;">Status</th>
            </strong>
        </tr>
    </thead>
    <tbody>
        <?php 
        if($record){ 
            $i=1;
            foreach($record as $user)
                { ?>
                    <tr>
                        <td ><?php echo $i;?>.</td>

                        <td style="text-align:left!important;"><?php echo $user['po_no']; ?></td>
                        <td style="text-align:left!important;"><?php echo $user['site_id']; ?></td>
                        <td style="text-align:left!important;"><?php echo date('d/m/Y', strtotime($user['created'])); ?></td>
                        
                        <td style="text-align:left!important;"><?php echo $user['zone']; ?></td>
                        <td style="text-align:left!important;"><?php echo $user['cluster']; ?></td>

                        <td style="text-align:left!important;"><?php echo $user['allocated_to']; ?></td>
                        <td style="text-align:left!important;"><?php echo $user['due_date'];?></td>

                        <td style="text-align:left!important;"><?php echo $user['allocated_by']; ?></td>


                        <td style="text-align:left!important;"><?php echo $user['status_name']; ?></td>


                    </tr>
                    <?php  $i++;} } else{  ?>
                        <tr><td colspan="16"><p style="color:red; font-size:16px;">No Data Found !</p></td></tr>
                    <?php  } ?>
                </tbody>
            </table>


