
                        <div class="modal-dialog modal-lg modal-content" style="max-width: 70%;">
                            <div class="modal-header bg-primary">
                
                            <button type="button" class="close text-white" id="test" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h5 class="modal-title text-white" id="exampleModalLabel3"><?php echo "Completed Allocated Site Data";?></h5>
                            </div>
                            <div class="modal-body" style="text-align: center; max-height:450px; overflow:auto;">
                                <table  class="table table-striped">
                                            <thead>
                                            <tr>
                                                <strong>
                                                <th>#</th>
                                                <th style="text-align:left!important;">PO</th>
                                                <th style="text-align:left!important;" nowrap>Site Id</th>
                                                <th style="text-align:left!important;" nowrap>Assigned Date</th>
                                                <th style="text-align:left!important;">Zone</th>
                                                <th style="text-align:left!important;" nowrap>Cluster</th>
                                                <th style="text-align:left!important;" nowrap>Technician Name</th>
                                                <th style="text-align:left!important;" nowrap>Technician Mobile No.</th>
                                                <th style="text-align:left!important;" nowrap>Allocated User</th>
                                              
                                               
                                                </strong>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            if($this->completed_allocate_site_list){ 
                                            $i=1;
                                            foreach($this->completed_allocate_site_list as $user)
                                            { ?>
                                            <tr>
                                                <td ><?php echo $i;?>.</td>
                                                
                                                <td style="text-align:left!important;"><?php echo $user['po_no']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['site_id']; ?></td>
                                                <td style="text-align:left!important;"><?php echo date('d/m/Y', strtotime($user['created'])); ?></td>
                                                <!-- <td style="text-align:left!important;"><?php echo $user['infratel_id']; ?></td> -->
                                                <td style="text-align:left!important;"><?php echo $user['zone']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['cluster']; ?></td>
                                               
                                                <!-- <td style="text-align:left!important;"><?php echo $user['cluster_mobile']; ?></td> -->
                                                <td style="text-align:left!important;"><?php echo $user['tech_name']; ?></td>
                                                <td style="text-align:left!important;"><?php echo $user['tech_mobile'];?></td>


                                                <!-- <td style="text-align:left!important;"><?php if($user['resource_allocator'] == 'Vendor') { echo $user['vendor']; }else{ echo $user['allocate_user'];}?></td> -->

                                                <td style="text-align:left!important;"><?php echo $user['supervisor']; ?></td>

                                               <!--  <td style="text-align:left!important;"><?php echo date('d/m/Y', strtotime($user['due_date'])); ?></td> -->
                                              
                                                
                                                
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                                            <tr><td colspan="16"><p style="color:red; font-size:16px;">No Data Found !</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                            </div>
                           
                        </div>

               