<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/pages/modals.js"></script>
<style type="text/css">
  .nav
  { 
    background-color: #9370DB;
  }
  .nav li a{
    color: white;
  }
  .nav li a:hover {
    border: none;
    color: white;
  }
  .table
  {
    max-height: 300px;
    overflow-y: scroll;
    display:block;

  }
</style>
<div id="page-wrapper">
  <div class="main-page">
    <div class="col-lg-12">
      <div class="panel panel-heading" style="background: linear-gradient(to bottom, #ccff33 0%, #99cc00 100%);">
        <div class="row">
          <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
            <h3>Expenses</h3>
          </div>
          <form action="" method="post">
            <div class="col-lg-3 col-md-3 col-sm-9 col-xs-3">
              <div class="col-xs-9 col-sm-9 col-md-9">
                <input type="text" class="form-control datepicker" value="<?php echo date('d/m/Y',strtotime($this->date)); ?>" name="date" id="date" placeholder="Select Date" readonly="">
              </div>
              <div class="col-xs-3 col-sm-3 col-md-3">
                <button type="submit" class="btn btn-primary" href="" name="show" id="show">Show</button>
              </div>
            </div>
          </form>
        </div>
      </div>

      <div class="col-lg-6"><br>
        <div class="widget-header">
          <h4 align="center"><b>Site Expense</b>
          </h4><br>
          <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
          <div class="card" id="siteexpence"></div>
        </div>

      </div>
      <div class="col-lg-6"><br>
        <div class="widget-header">
          <h4 align="center"><b>Office Expense</b>
          </h4><br>
          <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
          <div class="card" id="officediv"></div>
        </div>
      </div>
    </div>
    <br clear="all">
    <br clear="all">

    <div class="col-lg-12">

      <div class="panel panel-heading" style="background: linear-gradient(to bottom, #ccff33 0%, #99cc00 100%);">
        <div class="row">
          <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
            <h3>Recents</h3>
          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="widget-header">


          <div class="widget-toolbar no-border">
            <ul class="nav nav-tabs" id="recent-tab" >
              <li class="active">
                <a data-toggle="tab" href="#po">PO</a>
              </li>

              <li>
                <a data-toggle="tab" href="#po_sites">PO Sites</a>
              </li>

              <li>
                <a data-toggle="tab" href="#stock_in">Stock In</a>
              </li>
              <li>
                <a data-toggle="tab" href="#stock_out">Stock Out</a>
              </li>
            </ul>
            <div class="tab-content" style="font-size:15px">
              <div class="tab-pane fade in active" id="po">
                <table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
                  <?php foreach($this->po_sites_data as $data){
                    echo "<tr>
                    <td>
                    <div style='border:1px solid black;border-radius:20px;'>
                    <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                    </td>
                    <td>
                    <p>The PO is added with PO Number <b>".$data['po_no']." </b> on Date <b>".date('d/m/Y',strtotime($data['created_at']))."</b>  at location situated in <b> ".$data['operating_unit'] ."</b> of client <b>".$data['client_name']."</b></p>
                    <td>
                    </tr>";
                  }?>
                  <tr>
                    <td colspan="2" align="center">
                      <div class="center">
                        <i class="ace-icon fa fa-users fa-2x green middle"></i>
                        <a href="/manage-po-site/po-details" class="btn btn-sm btn-white btn-info">
                          See all PO Details &nbsp;
                          <i class="ace-icon fa fa-arrow-right"></i>
                        </a>
                      </div>
                    </td>
                  </tr>
                </table>
              </div>
              <div class="tab-pane fade" id="po_sites">

                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-bordered table-striped mb-0" width="50%" height="400" style="overflow-y: scroll; " >
                      <?php foreach($this->po_sites_data as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>The PO is added with PO Number <b>".$data['po_no']." </b> on Date <b>".date('d/m/Y',strtotime($data['created_at']))."</b>  at location situated in <b> ".$data['operating_unit'] ."</b> of client <b>".$data['client_name']."</b></p>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/manage-po-site/po-details" class="btn btn-sm btn-white btn-info">
                              See all PO Site Details &nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="stock_in">

                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-hover" width="50%" style="overflow-y: scroll;">
                      <?php foreach($this->stock_in_details as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>
                        The stocks have been arrived at <b>".$data['stock_in_date']."</b> of product <b>".$data['product_name']."</b> from brand <b>".$data['brand_name']."</b> supplied by <b>".$data['supplier_name']."</b> of quantity <b>".$data['brand_name']."".$data['unit']."</b> and the product type is <b>".$data['product_type_name']."</b>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/report/material-stock-in-report" class="btn btn-sm btn-white btn-info">
                              See all Stocks In Deatils &nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="stock_out">
                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
                      <?php foreach($this->stock_out_details as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>
                        The stocks are out  at <b>".$data['stock_out_date']."</b> of product <b>".$data['product_name']."</b> from brand <b>".$data['brand_name']."</b> allocated to <b>".$data['allocated_by']."</b> of quantity <b>".$data['brand_name']."".$data['unit']."</b> and the product type is <b>".$data['product_type_name']."</b>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/report/material-stock-out-report" class="btn btn-sm btn-white btn-info">
                              See all Stocks Out Details&nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="widget-header">


          <div class="widget-toolbar no-border">
            <ul class="nav nav-tabs" id="recent-tab" >
              <li class="active">
                <a data-toggle="tab" href="#officeExpense">Office Expense</a>
              </li>

              <li>
                <a data-toggle="tab" href="#SiteExpense">Site Expense</a>
              </li>

              <li>
                <a data-toggle="tab" href="#Invoices">Invoices</a>
              </li>
              <li>
                <a data-toggle="tab" href="#Funds">Funds</a>
              </li>
            </ul>
            <div class="tab-content" style="font-size:15px">
              <div class="tab-pane fade in active" id="officeExpense">
                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
                      <?php foreach($this->officeExpense as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>The Office expense of company <b>".$data['company']."</b> of amount <b>".$data['amount']."</b> which is transfered to <b>".$data['payee']."</b> from bank <b>".$data['bank_name']."</b> and account number is <b>".$data['bank_account_number']."</b> and the payment mode was <b>".$data['payment_mode']." </b> on date ".$data['tra']."
                        </p>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/expense/office-expenses" class="btn btn-sm btn-white btn-info">
                              See all Office expense &nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="SiteExpense">

                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-bordered table-striped mb-0" width="50%" height="400" style="overflow-y: scroll; " >
                      <?php foreach($this->siteExpense as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>The Site expense of company <b>".$data['company']."</b> of amount <b>".$data['amount']."</b> which is transfered to <b>".$data['transfer_to_name']."</b> from bank <b>".$data['bank_name']."</b> and account number is <b>".$data['bank_account_number']."</b> and the payment mode was <b>".$data['payment_mode']."</b>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/expense" class="btn btn-sm btn-white btn-info">
                              See all Site Expense Details &nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="Invoices">

                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-hover" width="50%" style="overflow-y: scroll;">
                      <?php foreach($this->invoiceReports as $data){
                        echo "<tr>
                        <td>
                        <div style='border:1px solid black;border-radius:20px;'>
                        <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                        </td>
                        <td>
                        <p>
                        THe invoice has been generate at <b>".date('d/m/Y',strtotime($data['invoice_date']))."</b> against PO <b>".$data['po_no']."</b> of  Site <b>".$data['site_id']."</b> for client <b>".$data['client_name']."</b> in state <b>".$data['state_name']."</b> because <b>".$data['invoice_remark']."</b>
                        <td>
                        </tr>";
                      }?>
                      <tr>
                        <td colspan="2" align="center">
                          <div class="center">
                            <i class="ace-icon fa fa-users fa-2x green middle"></i>
                            <a href="/invoice/invoice-report" class="btn btn-sm btn-white btn-info">
                              See all Invoice Deatils &nbsp;
                              <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                          </div>
                        </td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <div class="tab-pane fade" id="Funds">

                <div class="comments ace-scroll" style="position: relative;">
                  <div class="itemdiv commentdiv">
                    <table class="table table-hover" width="50%" style="overflow-y: scroll;">
                     <?php foreach($this->fundData as $data){
                      echo "<tr>
                      <td>
                      <div style='border:1px solid black;border-radius:20px;'>
                      <img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
                      </td>
                      <td>
                      <p>The Fund transfered to company <b>".$data['company']."</b> of amount <b>".$data['amount']."</b> which is transfered to <b>".$data['transfer_name']."</b> from bank <b>".$data['bank_name']."</b> and account number is <b>".$data['bank_account_number']."</b> and the payment mode was <b>".$data['payment_mode']."</b>
                      <td>
                      </tr>";
                    }?>
                    <tr>
                      <td colspan="2" align="center">
                        <div class="center">
                          <i class="ace-icon fa fa-users fa-2x green middle"></i>
                          <a href="/expense/fund-transfer-reports" class="btn btn-sm btn-white btn-info">
                            See all Fund Deatils &nbsp;
                            <i class="ace-icon fa fa-arrow-right"></i>
                          </a>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  </div>
  <br clear="all">
</div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".select2").select2();
    $(".datepicker").datepicker({ dateFormat: "dd/mm/yy", changeYear:true, changeMonth:true });
    $('#show').click(function() {
      var date = $('#date').val();
      // alert(date);
      // $('#loading-bg').show();
      // $.ajax({
      //   url: "/home/daily-update-dashboard/date/"+date,
      //   context: document.body,
      //   success: function() {
      //     $('#loading-bg').hide();
      //   }
      // });
    })
  });
</script>
<script>
  am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("siteexpence", am4charts.XYChart3D);

// Add data
chart.data = [
<?php foreach ($this->yearlySiteExpense as $site_expense) { ?>
  {
    "country": "<?php echo $site_expense[2]; ?>",
    "visits": <?php echo $site_expense[1];?>
  },
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#FFFFFF");

columnTemplate.adapter.add("fill", function(fill, target) {
  return chart.colors.getIndex(target.dataItem.index);
})

columnTemplate.adapter.add("stroke", function(stroke, target) {
  return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineY.strokeOpacity = 0;

}); // end am4core.ready()
</script>
<script>
  am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("officediv", am4charts.XYChart3D);

chart.data = [
<?php foreach ($this->yearlyOfficeExpense as $office_expense) { ?>
  {
    "country": "<?php echo $office_expense[2]; ?>",
    "visits": <?php echo $office_expense[1];?>
  },
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#FFFFFF");

columnTemplate.adapter.add("fill", function(fill, target) {
  return chart.colors.getIndex(target.dataItem.index);
})

columnTemplate.adapter.add("stroke", function(stroke, target) {
  return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineY.strokeOpacity = 0;

}); // end am4core.ready()
</script>

