<!-- <script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/pages/modals.js"></script> -->

<script>
	am4core.ready(function() {


// Create axes

      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        // var data = google.visualization.arrayToDataTable([
        //   ['Year', 'Sales', 'Expenses', 'Profit', 'Loss'],
        //   ['<?php echo $this->year?>', 1000, 400, 200, 100]
        // ]);
        var data = google.visualization.arrayToDataTable([
          ['PO(SiteID)', 'Invoice', 'Site Expenses', 'Profit Or Loss','Received Amount'],
          ['<?php echo $this->poNumber; ?>(<?php echo $this->siteId; ?>)',<?php echo  $this->PiData['total']; ?>,<?php echo  $this->seData['expense_amount']; ?>,<?php echo  $this->PlData; ?>,<?php echo  $this->PiData['total_received_amount']; ?>]
        ]);

        var options = {
        //   chart: {
        //     title: 'Company Performance',
        //     subtitle: 'Sales, Expenses, and Profit: 2014-2017',
        //   },
          bars: 'vertical',
          vAxis: {format: 'decimal'},
          height: 500,
          width: 700,
          colors: ['#1b9e77', '#d95f02', '#7570b3', '#0066ff']
        };

        var chart = new google.charts.Bar(document.getElementById('po-site'));

        chart.draw(data, google.charts.Bar.convertOptions(options));

        var btns = document.getElementById('btn-group');

        btns.onclick = function (e) {

          if (e.target.tagName === 'BUTTON') {
            options.vAxis.format = e.target.id === 'none' ? '' : e.target.id;
            chart.draw(data, google.charts.Bar.convertOptions(options));
          }
        }
      }
	});
</script>