
                        <div class="modal-dialog modal-lg modal-content" style="max-width: 70%;">
                            <div class="modal-header bg-primary">
                
                            <button type="button" class="close text-white" id="test" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h5 class="modal-title text-white" id="exampleModalLabel3"><?php echo "Total Site Data";?></h5>
                            </div>
                            <div class="modal-body" style="text-align: center; max-height:450px; overflow:auto;">
                                <table class="table table-striped" id="list_table">
                                <style>
                                    th{
                                        text-align: center;
                                    }
                                </style>
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>SO</th>
                                                <th nowrap>Created Date</th>
                                                <th nowrap>OPCO Name</th>
                                                <th>PO</th>
                                                <th nowrap>Infratel Id</th>
                                                <th>District</th>
                                                <th>Zone</th>
                                                <th>Cluster</th>
                                                <th nowrap>Site ID</th>
                                                <th>Item</th>
                                                <th>Category</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php 
                                            $i=1;
                                            if($this->site_list){
                                            foreach($this->site_list as $deploy)
                                            { ?>
                                            <tr>
                                                <td><?php echo $i;?>.</td>
                                                <td nowrap><?php echo $deploy['so']; ?></td>
                                                <td nowrap><?php echo $deploy['created_date']; ?></td>
                                                <td nowrap><?php echo $deploy['opco_name']; ?></td>
                                                <td nowrap><?php echo $deploy['po']; ?></td>
                                                <td nowrap><?php echo $deploy['infratel_id']; ?></td>
                                                <td nowrap><?php echo $deploy['district']; ?></td>
                                                <td nowrap><?php echo $deploy['zone']; ?></td>
                                                <td nowrap><?php echo $deploy['cluster']; ?></td>
                                                <td nowrap><?php echo $deploy['technical_site_id']; ?></td>
                                                <td nowrap><?php echo $deploy['item']; ?></td>
                                                <td nowrap><?php echo $deploy['category']; ?></td>
                                            </tr>
                                            <?php  $i++;} } else{  ?>
                                            <tr><td colspan="12"><p style="color:red; font-size:16px;">No  Site Data Found!</p></td></tr>
                                                <?php  } ?>
                                            </tbody>
                                        </table>
                            </div>
                           
                        </div>

               