<?php 
$getTotalSite = $this->getTotalSite;
$getTotalAllocatedSite = $this->getTotalAllocatedSite;
$getpendingSite = $this->getpendingSite;
$getcompletedSite = $this->getcompletedSite;
?>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/pages/modals.js"></script>
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script src="/vendors/amcharts/amcharts.js"></script>
<script src="/vendors/amcharts/pie.js"></script>
<script src="/vendors/amcharts/themes/light.js"></script>
<script src="/vendors/amcharts/serial.js" type="text/javascript"></script>
<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<!-- Chart code -->
<!-- Resources -->
<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<style>
	#chartmatdiv1 {
		width: 100%;
		height: 300px;
	}
	#chartmatdiv2{
		width: 100%;
		height: 300px;
	}
	#chartdiv {
		width  : 100%;
		height  : 338px;
		font-size : 11px;
	}			
	#monthlytasks{
		width   : 100%;
		height    : 338px;
		font-size : 11px;
	}
	
	#siteexpence {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	#officediv {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	#invoice {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	#po {
		width: 100%;
		height: 338px;
		font-size : 11px;
	}
	.table
	{
		max-height: 300px;
		overflow-y: scroll;
		display:block;

	}
</style>

<!-- Resources -->

<script>
	$(document).ready(function() {
		$(".select2").select2();
		$(".datepicker").datepicker({ dateFormat: "yy-mm-dd", changeYear:true, changeMonth:true});
	}); 
	$(document).ready(function(){
	// 	setInterval(function(){ 
	// 		var x = Math.floor((Math.random() * 12) + 1);
	// 		if(x<10){x='0'+x;}
	// 		var d = new Date().getFullYear();
	// 		var year = $('#yearhome').val();
	// 		if(year){
	// 			d = year;
	// 		}
	// 		$.ajax({
	// 			url: "/home/get-data-invoice/month/"+x+"/year/"+d,
	// 			context: document.body,
	// 			success: function(responseText) {
	// 				$('#loading-bg').hide();
	// 				$('#invoice').html(responseText);	
	// 				$('#month').val(x);	
	// 				$('#year').val(d);	
	// 			}
	// 		});
	// 		$.ajax({
	// 			url: "/home/get-data-po/month/"+x+"/year/"+d,
	// 			context: document.body,
	// 			success: function(responseText) {
	// 				$('#loading-bg').hide();
	// 				$('#po').html(responseText);
	// 				$('#month1').val(x);	
	// 				$('#year1').val(d);	

	// 			}
	// 		});
	// 	}, 9000);		
		
	// })
	
		$('#submit').click(function() {
			var month = $('#month').val();
			var year = $('#year').val();
			$('#loading-bg').show();
			$.ajax({
				url: "/home/get-data-invoice/month/"+month+"/year/"+year,
				context: document.body,
				success: function(responseText) {
					$('#loading-bg').hide();
					$('#invoice').html(responseText);	
				}
			});
		})
		$('#submit1').click(function() {
			var month1 = $('#month1').val();
			var year1 = $('#year1').val();
			$('#loading-bg').show();
			$.ajax({
				url: "/home/get-data-po/month/"+month1+"/year/"+year1,
				context: document.body,
				success: function(responseText) {
					$('#loading-bg').hide();
					$('#po').html(responseText);	
				}
			});
		})
		
			$('#submit2').click(function() {
			    
			var poNumber = $('#poNumber').val();
			var siteId = $('#siteId').val();
		//	alert(poNumber+" "+siteId);
			$('#loading-bg').show();
			$.ajax({
				url: "/home/get-data-po-site/poNumber/"+poNumber+"/siteId/"+siteId,
				context: document.body,
				success: function(responseText) {
				    //console.log(responseText+"test");
					$('#loading-bg').hide();
					$('#po-site').html(responseText);	
				}
			});
		})

	});


	function getDataByYear(){
		var year = $('#yearhome').val();
		$.ajax({
			url: "/home/year/"+year,
			context: document.body,
			success: function(responseText) {
				
			}
		});
	}
	function totalsite(type) {
		$.ajax({
			url: "/home/get-totalsite/type/"+type,
			context: document.body,
			success: function(responseText) {
				$("#basic_modal2").html(responseText);
				$("#basic_modal2").find("script").each(function(i) {
					eval($(this).text());
				});
			}
		});
	};
	function getallocatedata(type) {
		$("#modal_title").text("TOTAL ALLOCATED SITES");
        //alert(type);
        $.ajax({
        	url: "/home/allocated-site/type/"+type,
        	context: document.body,
        	success: function(responseText) {
        		$("#modal_body").html(responseText);
        		$("#modal_body").find("script").each(function(i) {
        			eval($(this).text());
        		});
        	}
        });
    };
    function pendingallocatedata(type) {
    	$("#modal_title").text("TOTAL PENDING ALLOCATED SITES");
    	// alert(type);
    	$.ajax({
    		url: "/home/pending-allocation-site/type/"+type,
    		context: document.body,
    		success: function(responseText) {
    			$("#basic_modal2").html(responseText);
    			$("#basic_modal2").find("script").each(function(i) {
    				eval($(this).text());
    			});
    		}
    	});
    };
    function completedAllocatedata(type) {
        //alert(type);
        $.ajax({
        	url: "/home/completed-allocation-site/type/"+type,
        	context: document.body,
        	success: function(responseText) {
        		$("#basic_modal2").html(responseText);
        		$("#basic_modal2").find("script").each(function(i) {
        			eval($(this).text());
        		});
        	}
        });
    };
    
    function getSitesByPoNumberForAllocation() {
		var po_number = $("#poNumber").val();
		if (po_number != "") {
			$("#loading-bg").show();
			$.ajax({
				url: '/home/get-sites-by-po-number-for-allocation',
				type: 'POST',
				data: {po_number: po_number},
				success:function(data){
					var data = JSON.parse(data);
					console.log(data);
					$("#loading-bg").hide();
					var option = "<option value=''>Select Site ID</option>";
					if (data.flag) {
						$.each(data.sites, function(index, site_id) {
							option += "<option value='"+site_id.site_id+"'>"+site_id.site_id+"</option>";
						});
					} else {
						option += "<option>"+data.message+"</option>";
					}
					$("#siteId").html(option);
					$("#po_date").val(data.po_date);
				}
			});
		} else {
			swal({
				title : "PO Number Missing!",
				text  : "Please select PO number first.",
				icon  : "error"
			}).then(function(){
				$("#siteId").html("<option>Select Site ID</option>");
				$("#po_date").val('');
				$("#infratel_id").val('');
				$("#zone").val('');
				$("#location").val('');
				$("#cluster").val('');
				$("#cluster_incharge").val('');
				$("#cluster_mobile").val('');
				$("#technician_name").val('');
				$("#technician_mobile").val('');
				$("#site_latitude").val('');
				$("#site_longitude").val('');
				$("#work_type").val('');
			});
		}
	}
</script>
<?php $mdata = json_encode($this->getmaterialData);?>
<!-- Chart code -->
<script>
	am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("chartmatdiv1", am4charts.PieChart);
var mdata = <?php echo  $mdata ;?>;
// Add data
chart.data = mdata;
console.log(chart.data);
// Add and configure Series
var pieSeries = chart.series.push(new am4charts.PieSeries());
pieSeries.dataFields.value = "quantity";
pieSeries.dataFields.category = "product_name";
pieSeries.slices.template.stroke = am4core.color("#fff");
pieSeries.slices.template.strokeWidth = 2;
pieSeries.slices.template.strokeOpacity = 1;

// This creates initial animation
pieSeries.hiddenState.properties.opacity = 1;
pieSeries.hiddenState.properties.endAngle = -90;
pieSeries.hiddenState.properties.startAngle = -90;

}); // end am4core.ready()
</script>



<!-- Chart code -->
<script>
	am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("siteexpence", am4charts.XYChart3D);

// Add data
chart.data = [
<?php foreach ($this->yearlySiteExpense as $site_expense) { ?>
	{
		"country": "<?php echo $site_expense[0]; ?>",
		"visits": <?php echo $site_expense[1];?>
	},
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";
//valueAxis.numberFormatter.numberFormat = "#,##";


// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#FFFFFF");

columnTemplate.adapter.add("fill", function(fill, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

columnTemplate.adapter.add("stroke", function(stroke, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineY.strokeOpacity = 0;

}); // end am4core.ready()
</script>
<!-- Resources -->

<!-- Chart code -->
<script>
	am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// Create chart instance
var chart = am4core.create("officediv", am4charts.XYChart3D);
chart.data = [
<?php foreach ($this->yearlyOfficeExpense as $office_expense) { ?>
	{
		"country": "<?php echo $office_expense[0]; ?>",
		"visits": <?php echo $office_expense[1];?>
	},
<?php }?>
];

// Create axes
let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
categoryAxis.dataFields.category = "country";
categoryAxis.renderer.labels.template.rotation = 270;
categoryAxis.renderer.labels.template.hideOversized = false;
categoryAxis.renderer.minGridDistance = 20;
categoryAxis.renderer.labels.template.horizontalCenter = "right";
categoryAxis.renderer.labels.template.verticalCenter = "middle";
categoryAxis.tooltip.label.rotation = 270;
categoryAxis.tooltip.label.horizontalCenter = "right";
categoryAxis.tooltip.label.verticalCenter = "middle";

let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
valueAxis.title.text = "Amount";
valueAxis.title.fontWeight = "bold";

// Create series
var series = chart.series.push(new am4charts.ColumnSeries3D());
series.dataFields.valueY = "visits";
series.dataFields.categoryX = "country";
series.name = "Visits";
series.tooltipText = "{categoryX}: [bold]{valueY}[/]";
series.columns.template.fillOpacity = .8;

var columnTemplate = series.columns.template;
columnTemplate.strokeWidth = 2;
columnTemplate.strokeOpacity = 1;
columnTemplate.stroke = am4core.color("#FFFFFF");

columnTemplate.adapter.add("fill", function(fill, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

columnTemplate.adapter.add("stroke", function(stroke, target) {
	return chart.colors.getIndex(target.dataItem.index);
})

chart.cursor = new am4charts.XYCursor();
chart.cursor.lineX.strokeOpacity = 0;
chart.cursor.lineY.strokeOpacity = 0;

}); // end am4core.ready()
</script>
<div id="page-wrapper">
	<div class="main-page">
		<!-- Main content -->
		<?php if ($this->messages): ?>
			<div class="alert alert-success alert-dismissible fade show m-t-10" role="alert">
				<?php foreach ($this->messages as $message): ?>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<div class="alert_data">
						<?php echo $message ?>.
					</div>
				<?php endforeach ?>
			</div>
		<?php endif ?>
	<!--	<div class="row">-->
	<!--	    <form action="" method="POST" role="form">-->
	<!--	    <div class="col-md-3">-->
	<!--		<select class="form-control" name="yearhome" id="yearhome" onchange="getDataByYear();">-->
	<!--		    <option value="">Select</option>-->
	<!--			<?php //$years = array_combine(range(date("Y"), 1995), range(date("Y"), 1995));-->
	//	foreach($years as $year) {  ?>
					<!--<option value="<?php //echo $year;?>" <?php //echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>-->
	<!--				<option value="<?php echo $year;?>"><?php //echo $year;?></option>-->
	<!--			<?php //} ?>-->
	<!--		</select>-->
	<!--		</div>-->
	<!--        <div class="col-md-3">-->
	<!--		<select class="form-control" name="monthhome" id="monthhome">-->
				<!--<option value="04" <?php //echo $this->month == '04' ?"selected":""; ?>>APR</option>-->
				<!--<option value="05" <?php //echo $this->month == '05' ?"selected":""; ?>>MAY</option>-->
				<!--<option value="06" <?php //echo $this->month == '06' ?"selected":""; ?>>JUN</option>-->
				<!--<option value="07" <?php //echo $this->month == '07' ?"selected":""; ?>>JUL</option>-->
				<!--<option value="08" <?php //echo $this->month == '08' ?"selected":""; ?>>AUG</option>-->
				<!--<option value="09" <?php //echo $this->month == '09' ?"selected":""; ?>>SEP</option>-->
				<!--<option value="10" <?php //echo $this->month == '10' ?"selected":""; ?>>OCT</option>-->
				<!--<option value="11" <?php //echo $this->month == '11' ?"selected":""; ?>>NOV</option>-->
				<!--<option value="12" <?php //echo $this->month == '12' ?"selected":""; ?>>DEC</option>-->
				<!--<option value="01" <?php //echo $this->month == '01' ?"selected":""; ?>>JAN</option>-->
				<!--<option value="02" <?php //echo $this->month == '02' ?"selected":""; ?>>FEB</option>-->
				<!--<option value="03" <?php //echo $this->month == '03' ?"selected":""; ?>>MAR</option>-->
	<!--			<option value="">Select</option>-->
	<!--			<option value="04" >APR</option>-->
	<!--			<option value="05" >MAY</option>-->
	<!--			<option value="06" >JUN</option>-->
	<!--			<option value="07" >JUL</option>-->
	<!--			<option value="08" >AUG</option>-->
	<!--			<option value="09" >SEP</option>-->
	<!--			<option value="10" >OCT</option>-->
	<!--			<option value="11" >NOV</option>-->
	<!--			<option value="12" >DEC</option>-->
	<!--			<option value="01" >JAN</option>-->
	<!--			<option value="02" >FEB</option>-->
	<!--			<option value="03" >MAR</option>-->
	<!--		</select>-->
	<!--	</div>-->
	<!--        <div class="col-md-3">-->
	<!--<select class="form-control select2" name="site_type" id="site_type">-->
	<!--    <option value="">Select Site Type</option>-->
	<!--	<option value="RTT">RTT</option>-->
	<!--	<option value="GBT">GBT</option>-->
	<!--	<option value="Upgrade ">Upgrade</option>-->
	<!--</select>-->
	<!--	</div>-->
	<!--        <div class="col-md-2">-->
	<!--		<div class="form-group">-->
	<!--		<button type="submit" class="btn btn-primary" style="margin-top: 0px;">Filter</button>-->
	<!--		</div>-->
	<!--	</div>-->
	<!--        </form>-->
	<!--	</div>-->
	<div class="row">
		<form action="" method="POST" role="form" >  
		<!--onsubmit="return validateForm()"-->
			<div class="col-md-2">
				<div class="form-group">
					<label for="">From date</label>
					<input type="text" class="form-control datepicker " name="from_date" id="from_date" placeholder="From Date" readonly="" value="" >
				</div>
			</div>
			<div class="col-md-2">
				<div class="form-group">
					<label for="">To date</label>
					<input type="text" class="form-control datepicker " name="to_date" id="to_date" placeholder="To Date" readonly="" value="">
				</div>
			</div>
	        <div class="col-md-3">
	        <div class="form-group">
	            <label for="">Site Type</label>
            	<select class="form-control select2" name="site_type" id="site_type">
            	    <option value="">Select Site Type</option>
            		<option value="RTT">RTT</option>
            		<option value="GBT">GBT</option>
            		<option value="Upgrade ">Upgrade</option>
            	</select>
    		</div>
    		</div>
			<div class="col-md-2" >
				<div class="form-group">
					<button type="submit" class="btn btn-primary" style="margin-bottom:-50px;">Submit</button>
				</div>
			</div>
			<div class="col-md-2">
				<div class="form-group">
					<a href="/home" class="btn btn-info" style="margin-bottom:-50px;">Reset</a>
				</div>
			</div>
		</form>
	</div>
		<br>
		<div class="col_3">
			<div class="col-md-3 widget widget1">
				<div class="r3_counter_box">
					<i class="pull-left fa fa-building-o icon-rounded" style="color: blue;"></i>
					<div class="stats">
						<h5><strong><?php echo $this->getTotalSite['totalsite']?></strong></h5>
						<span>Total Sites</span>
					</div>
				</div>
			</div>
			<div class="col-md-3 widget widget1">
				<div class="r3_counter_box">
					<i class="pull-left fa fa-exclamation-circle user1 icon-rounded"></i>
					<div class="stats">
						<h5><strong><?php echo $this->getpendingSite['pendingsite']?></strong></h5>
						<span>Pending Sites</span>
					</div>
				</div>
			</div>
			<div class="col-md-3 widget widget1">
				<div class="r3_counter_box">
					<i class="pull-left fa fa-briefcase user2 icon-rounded"></i>
					<div class="stats">
						<h5><strong><?php echo $this->getTotalAllocatedSite['allocatedsite']?></strong></h5>
						<span>Allocated Sites</span>
					</div>
				</div>
			</div>
			<div class="col-md-3 widget widget1">
				<div class="r3_counter_box">
					<i class="pull-left fa fa-tasks dollar1 icon-rounded"></i>
					<div class="stats">
						<h5><strong><?php echo $this->getpendingSite['pendingsite']?></strong></h5>
						<span>In Progress</span>
					</div>
				</div>
			</div>
			<div class="col-md-3 widget">
				<div class="r3_counter_box">
					<i class="pull-left fa fa-thumbs-up dollar2 icon-rounded"></i>
					<div class="stats">
						<h5><strong><?php echo $this->getcompletedSite['completedsite']?></strong></h5>
						<span>Completed Sites</span>
					</div>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<?php if($this->role == 1){?>
			<div class="r3_counter_box">
				<a href="/home/daily-update-dashboard"><i class="pull-right fa fa-tasks  icon-rounded"></i></a>
			</div>
		<?php }?>
		<br clear="all">
	</div>
		
	<div class="col-lg-12">
		<div class="col-lg-6"><br>
			<div class="widget-header">
				<h4 align="center"><b>Site Expense</b>
				</h4><br>
				<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
				<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
				<div class="card" id="siteexpence"></div>
			</div>
		</div>
		<div class="col-lg-6"><br>
			<div class="widget-header">
				<h4 align="center"><b>Office Expense</b>
				</h4><br>
				<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
				<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
				<div class="card" id="officediv"></div>
			</div>
		</div>
	</div>

<div class="col-lg-12 text-center"><br><br>
		
		<div class="col-lg-12"><br>
			<div class="widget-header ">
				<h4 align="center"><b>PO & Site Wise Profit Loss Statement</b>
				</h4><br>
				<div class="row">
					<div class="col-md-4">
						<select class="form-control select2" name="poNumber" id="poNumber" onchange="getSitesByPoNumberForAllocation()">
							<option value="" >Select</option>
							<?php if($this->allocatedSites){ 
                             foreach($this->allocatedSites as $allocatedSite) { ?>
							<option value="<?php echo $allocatedSite['po_no']; ?>"><?php echo $allocatedSite['po_no']; ?></option>
							<?php } } ?>
						</select>
					</div>
					<div class="col-md-3">
						<!--<select class="form-control" name="year" id="year2">-->
						<select name="siteId" id="siteId" class="form-control select2">
									<option value="">Select Site ID</option>
								</select>
						<!--</select>-->
					</div>
					<div class="col-md-5">
						<button type="submit" class="btn btn-primary" id="submit2">Show</button>
					</div>
				</div><br/><br/>
				<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
				<!--<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>-->
				<div class="card" id="po-site"></div>
				<br/>
                <div id="btn-group">
                  <button class="button button-blue" id="none">No Format</button>
                  <button class="button button-blue" id="scientific">Scientific Notation</button>
                  <button class="button button-blue" id="decimal">Decimal</button>
                  <button class="button button-blue" id="short">Short</button>
                </div>
			</div>



		</div>
	</div>
	
	<div class="col-lg-12"><br><br>
		
		<div class="col-lg-6"><br>
			<div class="widget-header">
				<h4 align="center"><b>Invoice Data</b>
				</h4><br>
				<div class="row">
					<div class="col-md-4">
						<select class="form-control" name="month" id="month">
							<option value="01" <?php echo $this->month == "01"?"selected":""; ?>>January</option>
							<option value="02" <?php echo $this->month == "02"?"selected":""; ?>>February</option>
							<option value="03" <?php echo $this->month == "03"?"selected":""; ?>>March</option>
							<option value="04" <?php echo $this->month == "04"?"selected":""; ?>>April</option>
							<option value="05" <?php echo $this->month == "05"?"selected":""; ?>>May</option>
							<option value="06" <?php echo $this->month == "06"?"selected":""; ?>>June</option>
							<option value="07" <?php echo $this->month == "07"?"selected":""; ?>>July </option>
							<option value="08" <?php echo $this->month == "08"?"selected":""; ?>>August</option>
							<option value="09" <?php echo $this->month == "09"?"selected":""; ?>>September</option>
							<option value="10" <?php echo $this->month == "10"?"selected":""; ?>>October</option>
							<option value="11" <?php echo $this->month == "11"?"selected":""; ?>>November</option>
							<option value="12" <?php echo $this->month == "12"?"selected":""; ?>>December</option>
						</select>
					</div>
					<div class="col-md-3">
						<select class="form-control" name="year" id="year">
							<?php $years = array_combine(range(date("Y"), 1910), range(date("Y"), 1910));
							foreach($years as $year) {  ?>
								<option value="<?php echo $year;?>" <?php echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>
							<?php } ?>
						</select>
					</div>
					<div class="col-md-5">
						<button type="submit" class="btn btn-primary" id="submit">Show</button>
					</div>
				</div>
				<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
				<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
				<div class="card" id="invoice"></div>
			</div>



		</div>
		<div class="col-lg-6"><br>
			<div class="widget-header">
				<h4 align="center"><b>Po Amounts</b>
				</h4><br>
				<div class="row">

					<div class="col-md-4">
						<select class="form-control" name="month" id="month1">
							<option value="01" <?php echo $this->month == "01"?"selected":""; ?>>January</option>
							<option value="02" <?php echo $this->month == "02"?"selected":""; ?>>February</option>
							<option value="03" <?php echo $this->month == "03"?"selected":""; ?>>March</option>
							<option value="04" <?php echo $this->month == "04"?"selected":""; ?>>April</option>
							<option value="05" <?php echo $this->month == "05"?"selected":""; ?>>May</option>
							<option value="06" <?php echo $this->month == "06"?"selected":""; ?>>June</option>
							<option value="07" <?php echo $this->month == "07"?"selected":""; ?>>July </option>
							<option value="08" <?php echo $this->month == "08"?"selected":""; ?>>August</option>
							<option value="09" <?php echo $this->month == "09"?"selected":""; ?>>September</option>
							<option value="10" <?php echo $this->month == "10"?"selected":""; ?>>October</option>
							<option value="11" <?php echo $this->month == "11"?"selected":""; ?>>November</option>
							<option value="12" <?php echo $this->month == "12"?"selected":""; ?>>December</option>
						</select>
					</div>
					<div class="col-md-3">
						<select class="form-control" name="year1" id="year1">
							<?php $years = array_combine(range(date("Y"), 1910), range(date("Y"), 1910));
							foreach($years as $year) {  ?>
								<option value="<?php echo $year;?>" <?php echo $this->year == $year ?"selected":""; ?>><?php echo $year;?></option>
							<?php } ?>
						</select>
					</div>
					<div class="col-md-5">
						<button type="submit" class="btn btn-primary" id="submit1">Show</button>
					</div>
					
				</div>
				<!-- <div id="chartContainer" style="height: 370px; width: 100%;"></div> -->
				<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
				<div class="card" id="po"></div>
			</div>
		</div>
	</div>

	<br clear="all">
	<div class="row">
		<div><h4 align="center">
			<br clear="all">
			<br clear="all">
			<b>Material Stock</b>
		</h4></div>
		<br clear="all">
		<br clear="all">

		<div class="col-lg-12">
			<div class="card" id="chartmatdiv1"></div>
		</div>
	</div>
	<br clear="all">
	<div class="col-lg-6">
		<div class="widget-header">
			<h4 align="center"><b>RECENT</b>
			</h4><br>

			<div class="widget-toolbar no-border">
				<ul class="nav nav-tabs" id="recent-tab" >
					<li class="active">
						<a data-toggle="tab" href="#po">PO</a>
					</li>

					<li>
						<a data-toggle="tab" href="#po_sites">PO Sites</a>
					</li>

					<li>
						<a data-toggle="tab" href="#stock_in">Stock In</a>
					</li>
					<li>
						<a data-toggle="tab" href="#stock_out">Stock Out</a>
					</li>
				</ul>
				<div class="tab-content" style="font-size:15px">
					<div class="tab-pane fade in active" id="po">
						<table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
							<?php foreach($this->po_sites_data as $data){
								echo "<tr>
								<td>
								<div style='border:1px solid black;border-radius:20px;'>
								<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
								</td>
								<td>
								<p>The PO is added with PO Number <b>".$data['po_no']." </b> on Date <b>".$data['created_at']."</b>  at location situated in <b> ".$data['operating_unit'] ."</b> of client <b>".$data['client_name']."</b></p>
								<td>
								</tr>";
							}?>
							<tr>
								<td colspan="2" align="center">
									<div class="center">
										<i class="ace-icon fa fa-users fa-2x green middle"></i>
										<a href="/manage-po-site/po-details" class="btn btn-sm btn-white btn-info">
											See all PO Details &nbsp;
											<i class="ace-icon fa fa-arrow-right"></i>
										</a>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="tab-pane fade" id="po_sites">

						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-bordered table-striped mb-0" width="50%" height="400" style="overflow-y: scroll; " >
									<?php foreach($this->po_sites_data as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>The PO is added with PO Number <b>".$data['po_no']." </b> on Date <b>".$data['created_at']."</b>  at location situated in <b> ".$data['operating_unit'] ."</b> of client <b>".$data['client_name']."</b></p>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/manage-po-site/po-details" class="btn btn-sm btn-white btn-info">
													See all PO Site Details &nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="stock_in">

						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-hover" width="50%" style="overflow-y: scroll;">
									<?php foreach($this->stock_in_details as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>
										The stocks have been arrived at <b>".$data['created_at']."</b> of product <b>".$data['product_name']."</b> from brand <b>".$data['brand_name']."</b> supplied by <b>".$data['supplier_name']."</b> of quantity <b>".$data['brand_name']."".$data['unit']."</b> and the product type is <b>".$data['product_type_name']."</b>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/report/material-stock-in-report" class="btn btn-sm btn-white btn-info">
													See all Stocks In Deatils &nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="stock_out">
						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
									<?php foreach($this->stock_out_details as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>
										The stocks are out  at <b>".$data['stock_out_date']."</b> of product <b>".$data['product_name']."</b> from brand <b>".$data['brand_name']."</b> allocated to <b>".$data['allocated_by']."</b> of quantity <b>".$data['brand_name']."".$data['unit']."</b> and the product type is <b>".$data['product_type_name']."</b>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/report/material-stock-out-report" class="btn btn-sm btn-white btn-info">
													See all Stocks Out Details&nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="widget-header">
			<h4 align="center"><b>RECENT</b>
			</h4><br>

			<div class="widget-toolbar no-border">
				<ul class="nav nav-tabs" id="recent-tab" >
					<li class="active">
						<a data-toggle="tab" href="#officeExpense">Office Expense</a>
					</li>

					<li>
						<a data-toggle="tab" href="#SiteExpense">Site Expense</a>
					</li>

					<li>
						<a data-toggle="tab" href="#Invoices">Invoices</a>
					</li>

				</ul>
				<div class="tab-content" style="font-size:15px">
					<div class="tab-pane fade in active" id="officeExpense">
						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-bordered table-striped mb-0" width="50%" style="overflow-y: scroll;">
									<?php foreach($this->officeExpense as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>The Office expense of company <b>".$data['company']."</b> of amount <b>".$data['amount']."</b> which is transfered to <b>".$data['payee']."</b> from bank <b>".$data['bank_name']."</b> and account number is <b>".$data['bank_account_number']."</b> and the payment mode was <b>".$data['payment_mode']."</b>
										</p>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/expense/office-expenses" class="btn btn-sm btn-white btn-info">
													See all Office expense &nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="SiteExpense">

						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-bordered table-striped mb-0" width="50%" height="400" style="overflow-y: scroll; " >
									<?php foreach($this->siteExpense as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>The Site expense of company <b>".$data['company']."</b> of amount <b>".$data['amount']."</b> which is transfered to <b>".$data['transfer_to_name']."</b> from bank <b>".$data['bank_name']."</b> and account number is <b>".$data['bank_account_number']."</b> and the payment mode was <b>".$data['payment_mode']."</b>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/expense" class="btn btn-sm btn-white btn-info">
													See all Site Expense Details &nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
					<div class="tab-pane fade" id="Invoices">

						<div class="comments ace-scroll" style="position: relative;">
							<div class="itemdiv commentdiv">
								<table class="table table-hover" width="50%" style="overflow-y: scroll;">
									<?php foreach($this->invoiceReports as $data){
										echo "<tr>
										<td>
										<div style='border:1px solid black;border-radius:20px;'>
										<img src='\assets\images\ower.png' style='height:50px;width:50px;'></div>
										</td>
										<td>
										<p>
										THe invoice has been generate at <b>".$data['invoice_date']."</b> against PO <b>".$data['po_no']."</b> of  Site <b>".$data['site_id']."</b> for client <b>".$data['client_name']."</b> in state <b>".$data['state_name']."</b> because <b>".$data['remark']."</b>
										<td>
										</tr>";
									}?>
									<tr>
										<td colspan="2" align="center">
											<div class="center">
												<i class="ace-icon fa fa-users fa-2x green middle"></i>
												<a href="/invoice/invoice-reportt" class="btn btn-sm btn-white btn-info">
													See all Invoice Deatils &nbsp;
													<i class="ace-icon fa fa-arrow-right"></i>
												</a>
											</div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>
	<br clear="all">

</div>
</div>


<div class="modal fade" id="basic_modal2">
	<div class="modal-dialog modal-lg animated rollIn" style="max-width: 80%; max-height: 500px;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="modal_title"></h4>
			</div>
			<div class="modal-body" id="modal_body" style="height: 300px; overflow-y: scroll;">

			</div>
			<div class="modal-footer">
				<button type="button" class="
				btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>



